[general]
verbose=5
output=../out/croissant.out

[jsonld]
extension=jld
ontology=cr:https://mlcommons.org/croissant/
verify=
version=1.1

[ontology]
cr=1.12
schema=28.0

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/json-ld/croissant

[nits]
nids=

[html]
version=2024/10/01
