[general]
verbose=info
output=../out/simple.out
class=

[css]
verify=
extension=css
version=3
no-external=

[html]
version=2024/07/01

[link]
check=

[nits]
nids=

[ontology]
dpv=2

[site]
domain=example.edu
extension=html
extension=xhtml
index=index.html
root=../toast/other/simple

[spell]
no-check=true
