#!/bin/sh
#

./ssc -f ../toast/aria/1-0/aria.conf
./ssc -f ../toast/aria/1-1/aria.conf
./ssc -f ../toast/aria/1-2/aria.conf
./ssc -f ../toast/aria/1-3/aria.conf
./ssc -f ../toast/aria/dp/aria.conf
./ssc -f ../toast/aria/graphics/aria.conf
./ssc -f ../toast/aria/html/aria.conf
./ssc -f ../toast/conf/html/conf.conf
./ssc -f ../toast/conf/httpd/httpd.conf
./ssc -f ../toast/conf/xhtml/conf.conf
./ssc -f ../toast/coop/corrupt/corrupt.conf
./ssc -f ../toast/coop/corrupt/corrupt1.conf
./ssc -f ../toast/coop/corrupt/corrupt2.conf
./ssc -f ../toast/coop/corrupt/corrupt512.conf
./ssc -f ../toast/coop/corrupt/corruptaria.conf
./ssc -f ../toast/coop/css/css.conf
./ssc -f ../toast/coop/schema-abc/abc.conf
./ssc -f ../toast/coop/oct21/living.conf
./ssc -f ../toast/csp/1/csp.conf
./ssc -f ../toast/csp/2/csp.conf
./ssc -f ../toast/csp/3/csp.conf
./ssc -f ../toast/css/1/css.conf
./ssc -f ../toast/css/2.0/css.conf
./ssc -f ../toast/css/2.1/css.conf
./ssc -f ../toast/css/2.2/css.conf
./ssc -f ../toast/css/3-adjust/css.conf
./ssc -f ../toast/css/3-anchor-positioning/css.conf
./ssc -f ../toast/css/4-anchor-positioning/css.conf
./ssc -f ../toast/css/3-animation/css.conf
./ssc -f ../toast/css/4-animation/css.conf
./ssc -f ../toast/css/3-background/css.conf
./ssc -f ../toast/css/4-background/css.conf
./ssc -f ../toast/css/4-border/css.conf
./ssc -f ../toast/css/3-box-model/css.conf
./ssc -f ../toast/css/4-box-model/css.conf
./ssc -f ../toast/css/3-box-sizing/css.conf
./ssc -f ../toast/css/4-box-sizing/css.conf
./ssc -f ../toast/css/3-cascade/css.conf
./ssc -f ../toast/css/4-cascade/css.conf
./ssc -f ../toast/css/5-cascade/css.conf
./ssc -f ../toast/css/6-cascade/css.conf
./ssc -f ../toast/css/3-colour/css.conf
./ssc -f ../toast/css/4-colour/css.conf
./ssc -f ../toast/css/5-colour/css.conf
./ssc -f ../toast/css/6-colour/css.conf
./ssc -f ../toast/css/3-compositing/css.conf
./ssc -f ../toast/css/4-compositing/css.conf
./ssc -f ../toast/css/3-contain/css.conf
./ssc -f ../toast/css/4-contain/css.conf
./ssc -f ../toast/css/5-contain/css.conf
./ssc -f ../toast/css/3-content/css.conf
./ssc -f ../toast/css/3-cr/css.conf
./ssc -f ../toast/css/4-cr/css.conf
./ssc -f ../toast/css/5-cr/css.conf
./ssc -f ../toast/css/3-cs/css.conf
./ssc -f ../toast/css/3-cssom/css.conf
./ssc -f ../toast/css/3-device/css.conf
./ssc -f ../toast/css/3-display/css.conf
./ssc -f ../toast/css/4-display/css.conf
./ssc -f ../toast/css/3-ease/css.conf
./ssc -f ../toast/css/4-ease/css.conf
./ssc -f ../toast/css/3-egg/css.conf
./ssc -f ../toast/css/3-exclude/css.conf
./ssc -f ../toast/css/3-extensions/css.conf
./ssc -f ../toast/css/3-fbl/css.conf
./ssc -f ../toast/css/3-fcs/css.conf
./ssc -f ../toast/css/3-fcs-2/css.conf
./ssc -f ../toast/css/3-fill/css.conf
./ssc -f ../toast/css/3-filter/css.conf
./ssc -f ../toast/css/4-filter/css.conf
./ssc -f ../toast/css/3-float/css.conf
./ssc -f ../toast/css/3-font/css.conf
./ssc -f ../toast/css/4-font/css.conf
./ssc -f ../toast/css/5-font/css.conf
./ssc -f ../toast/css/4-frag/css.conf
./ssc -f ../toast/css/3-gap/css.conf
./ssc -f ../toast/css/3-grid/css.conf
./ssc -f ../toast/css/4-grid/css.conf
./ssc -f ../toast/css/5-grid/css.conf
./ssc -f ../toast/css/3-hdr/css.conf
./ssc -f ../toast/css/3-highlight/css.conf
./ssc -f ../toast/css/3-image/css.conf
./ssc -f ../toast/css/4-image/css.conf
./ssc -f ../toast/css/5-image/css.conf
./ssc -f ../toast/css/3-img-anim/css.conf
./ssc -f ../toast/css/3-inline/css.conf
./ssc -f ../toast/css/3-linkparam/css.conf
./ssc -f ../toast/css/3-list/css.conf
./ssc -f ../toast/css/3-logic/css.conf
./ssc -f ../toast/css/3-masking/css.conf
./ssc -f ../toast/css/3-mc/css.conf
./ssc -f ../toast/css/3-media/css.conf
./ssc -f ../toast/css/4-media/css.conf
./ssc -f ../toast/css/5-media/css.conf
./ssc -f ../toast/css/3-motion/css.conf
./ssc -f ../toast/css/3-multicolumn/css.conf
./ssc -f ../toast/css/4-multicolumn/css.conf
./ssc -f ../toast/css/3-nes/css.conf
./ssc -f ../toast/css/3-nesting/css.conf
./ssc -f ../toast/css/3-ns/css.conf
./ssc -f ../toast/css/3-overflow/css.conf
./ssc -f ../toast/css/4-overflow/css.conf
./ssc -f ../toast/css/5-overflow/css.conf
./ssc -f ../toast/css/3-overscroll/css.conf
./ssc -f ../toast/css/3-page/css.conf
./ssc -f ../toast/css/4-page/css.conf
./ssc -f ../toast/css/3-pagetemp/css.conf
./ssc -f ../toast/css/3-paint-api/css.conf
./ssc -f ../toast/css/3-position/css.conf
./ssc -f ../toast/css/3-present/css.conf
./ssc -f ../toast/css/4-pseudo/css.conf
./ssc -f ../toast/css/3-region/css.conf
./ssc -f ../toast/css/3-rhythm/css.conf
./ssc -f ../toast/css/3-round/css.conf
./ssc -f ../toast/css/3-route/css.conf
./ssc -f ../toast/css/3-ruby/css.conf
./ssc -f ../toast/css/3-scope/css.conf
./ssc -f ../toast/css/3-scrollbar/css.conf
./ssc -f ../toast/css/3-sda/css.conf
./ssc -f ../toast/css/3-sel/css.conf
./ssc -f ../toast/css/4-sel/css.conf
./ssc -f ../toast/css/5-sel/css.conf
./ssc -f ../toast/css/3-shadow/css.conf
./ssc -f ../toast/css/3-shape/css.conf
./ssc -f ../toast/css/3-snap/css.conf
./ssc -f ../toast/css/4-snap/css.conf
./ssc -f ../toast/css/3-spatial/css.conf
./ssc -f ../toast/css/3-speech/css.conf
./ssc -f ../toast/css/3-style/css.conf
./ssc -f ../toast/css/3-syntax/css.conf
./ssc -f ../toast/css/3-table/css.conf
./ssc -f ../toast/css/3-text/css.conf
./ssc -f ../toast/css/4-text/css.conf
./ssc -f ../toast/css/3-textdec/css.conf
./ssc -f ../toast/css/4-textdec/css.conf
./ssc -f ../toast/css/3-transform/css.conf
./ssc -f ../toast/css/4-transform/css.conf
./ssc -f ../toast/css/3-transition/css.conf
./ssc -f ../toast/css/4-transition/css.conf
./ssc -f ../toast/css/3-ui/css.conf
./ssc -f ../toast/css/4-ui/css.conf
./ssc -f ../toast/css/3-value/css.conf
./ssc -f ../toast/css/4-value/css.conf
./ssc -f ../toast/css/3-view/css.conf
./ssc -f ../toast/css/4-view/css.conf
./ssc -f ../toast/css/3-wc/css.conf
./ssc -f ../toast/css/3-writing/css.conf
./ssc -f ../toast/css/4-writing/css.conf
./ssc -f ../toast/css/accessibility/css.conf
./ssc -f ../toast/css/ae/css.conf
./ssc -f ../toast/css/custom/css.conf
./ssc -f ../toast/css/deprecated/css.conf
./ssc -f ../toast/css/marquee/css.conf
./ssc -f ../toast/css/print/css.conf
./ssc -f ../toast/css/profile/css.conf
./ssc -f ../toast/css/reader/css.conf
./ssc -f ../toast/css/simple/css.conf
./ssc -f ../toast/css/songlight/css.conf
./ssc -f ../toast/external/1kb.lejtzen.dev/ext.conf
./ssc -f ../toast/external/cleberg.net/ext.conf
./ssc -f ../toast/external/rdf/ext.conf
./ssc -f ../toast/external/rss/ext.conf
./ssc -f ../toast/external/ukarim.com/ext.conf
./ssc -f ../toast/external/vik.tf/ext.conf
./ssc -f ../toast/external/w3-sheets/ext.conf
./ssc -f ../toast/HTML/1.0/html1.conf
./ssc -f ../toast/HTML/2.0/html2.conf
./ssc -f ../toast/HTML/3.0/html3.conf
./ssc -f ../toast/HTML/3.2/html32.conf
./ssc -f ../toast/HTML/4.00/html4.conf
./ssc -f ../toast/HTML/4.01/html4.conf
./ssc -f ../toast/HTML/5.0/html5.conf
./ssc -f ../toast/HTML/5.1/html5.conf
./ssc -f ../toast/HTML/5.2/html5.conf
./ssc -f ../toast/HTML/5.3/html5.conf
./ssc -f ../toast/HTML/5.4/html5.conf
./ssc -f ../toast/HTML/minimal/minimal.conf
./ssc -f ../toast/HTML/Plus/plus.conf
./ssc -f ../toast/HTML/tags/tags.conf
./ssc -f ../toast/HTML/wx/wx.conf
./ssc -f ../toast/json-ld/1.0/jsonld.conf
./ssc -f ../toast/json-ld/adms/jsonld.conf
./ssc -f ../toast/json-ld/as/jsonld.conf
./ssc -f ../toast/json-ld/certification/jsonld.conf
./ssc -f ../toast/json-ld/croissant/jsonld.conf
./ssc -f ../toast/json-ld/schemaorg/jsonld.conf
./ssc -f ../toast/link/external/link.conf
./ssc -f ../toast/link/link/link.conf
./ssc -f ../toast/living/jul07/living.conf
./ssc -f ../toast/living/jan08/living.conf
./ssc -f ../toast/living/jul08/living.conf
./ssc -f ../toast/living/jan09/living.conf
./ssc -f ../toast/living/jul09/living.conf
./ssc -f ../toast/living/jan10/living.conf
./ssc -f ../toast/living/jul10/living.conf
./ssc -f ../toast/living/jan11/living.conf
./ssc -f ../toast/living/jul11/living.conf
./ssc -f ../toast/living/jan12/living.conf
./ssc -f ../toast/living/jul12/living.conf
./ssc -f ../toast/living/jan13/living.conf
./ssc -f ../toast/living/jul13/living.conf
./ssc -f ../toast/living/jan14/living.conf
./ssc -f ../toast/living/jul14/living.conf
./ssc -f ../toast/living/jan15/living.conf
./ssc -f ../toast/living/jul15/living.conf
./ssc -f ../toast/living/jan16/living.conf
./ssc -f ../toast/living/jul16/living.conf
./ssc -f ../toast/living/jan17/living.conf
./ssc -f ../toast/living/jul17/living.conf
./ssc -f ../toast/living/jan18/living.conf
./ssc -f ../toast/living/jul18/living.conf
./ssc -f ../toast/living/jan19/living.conf
./ssc -f ../toast/living/jul19/living.conf
./ssc -f ../toast/living/jan20/living.conf
./ssc -f ../toast/living/jul20/living.conf
./ssc -f ../toast/living/jan21/living.conf
./ssc -f ../toast/living/apr21/living.conf
./ssc -f ../toast/living/jul21/living.conf
./ssc -f ../toast/living/oct21/living.conf
./ssc -f ../toast/living/jan22/living.conf
./ssc -f ../toast/living/apr22/living.conf
./ssc -f ../toast/living/jul22/living.conf
./ssc -f ../toast/living/oct22/living.conf
./ssc -f ../toast/living/jan23/living.conf
./ssc -f ../toast/living/apr23/living.conf
./ssc -f ../toast/living/jul23/living.conf
./ssc -f ../toast/living/oct23/living.conf
./ssc -f ../toast/living/jan24/living.conf
./ssc -f ../toast/living/apr24/living.conf
./ssc -f ../toast/living/jul24/living.conf
./ssc -f ../toast/living/oct24/living.conf
./ssc -f ../toast/living/jan25/living.conf
./ssc -f ../toast/living/apr25/living.conf
./ssc -f ../toast/living/jul25/living.conf
./ssc -f ../toast/living/oct25/living.conf
./ssc -f ../toast/living/jan26/living.conf
./ssc -f ../toast/living/apr26/living.conf
./ssc -f ../toast/living/jul26/living.conf
./ssc -f ../toast/math/1/math.conf
./ssc -f ../toast/math/2/math.conf
./ssc -f ../toast/math/3/math.conf
./ssc -f ../toast/math/4/math.conf
./ssc -f ../toast/math/4-core/math.conf
./ssc -f ../toast/mdn/active/mdn.conf
./ssc -f ../toast/mdn/align/mdn.conf
./ssc -f ../toast/mdn/anchor/mdn.conf
./ssc -f ../toast/mdn/animation/mdn.conf
./ssc -f ../toast/mdn/at/mdn.conf
./ssc -f ../toast/mdn/attribute/mdn.conf
./ssc -f ../toast/mdn/background/mdn.conf
./ssc -f ../toast/mdn/border/mdn.conf
./ssc -f ../toast/mdn/box/mdn.conf
./ssc -f ../toast/mdn/break/mdn.conf
./ssc -f ../toast/mdn/caret/mdn.conf
./ssc -f ../toast/mdn/clip/mdn.conf
./ssc -f ../toast/mdn/colour/mdn.conf
./ssc -f ../toast/mdn/column/mdn.conf
./ssc -f ../toast/mdn/combinator/mdn.conf
./ssc -f ../toast/mdn/contain/mdn.conf
./ssc -f ../toast/mdn/container/mdn.conf
./ssc -f ../toast/mdn/corner/mdn.conf
./ssc -f ../toast/mdn/counter/mdn.conf
./ssc -f ../toast/mdn/element/mdn.conf
./ssc -f ../toast/mdn/fill/mdn.conf
./ssc -f ../toast/mdn/first/mdn.conf
./ssc -f ../toast/mdn/flex/mdn.conf
./ssc -f ../toast/mdn/focus/mdn.conf
./ssc -f ../toast/mdn/font/mdn.conf
./ssc -f ../toast/mdn/function/mdn.conf
./ssc -f ../toast/mdn/grid/mdn.conf
./ssc -f ../toast/mdn/image/mdn.conf
./ssc -f ../toast/mdn/inset/mdn.conf
./ssc -f ../toast/mdn/interest/mdn.conf
./ssc -f ../toast/mdn/justify/mdn.conf
./ssc -f ../toast/mdn/layout/mdn.conf
./ssc -f ../toast/mdn/line/mdn.conf
./ssc -f ../toast/mdn/list/mdn.conf
./ssc -f ../toast/mdn/margin/mdn.conf
./ssc -f ../toast/mdn/marker/mdn.conf
./ssc -f ../toast/mdn/mask/mdn.conf
./ssc -f ../toast/mdn/math/mdn.conf
./ssc -f ../toast/mdn/max/mdn.conf
./ssc -f ../toast/mdn/meta/mdn.conf
./ssc -f ../toast/mdn/min/mdn.conf
./ssc -f ../toast/mdn/moz-property/mdn.conf
./ssc -f ../toast/mdn/moz-pseudo-class/mdn.conf
./ssc -f ../toast/mdn/moz-pseudo-element/mdn.conf
./ssc -f ../toast/mdn/nth/mdn.conf
./ssc -f ../toast/mdn/object/mdn.conf
./ssc -f ../toast/mdn/offset/mdn.conf
./ssc -f ../toast/mdn/outline/mdn.conf
./ssc -f ../toast/mdn/overflow/mdn.conf
./ssc -f ../toast/mdn/overscroll/mdn.conf
./ssc -f ../toast/mdn/page/mdn.conf
./ssc -f ../toast/mdn/place/mdn.conf
./ssc -f ../toast/mdn/position/mdn.conf
./ssc -f ../toast/mdn/property/mdn.conf
./ssc -f ../toast/mdn/pseudo-class/mdn.conf
./ssc -f ../toast/mdn/pseudo-element/mdn.conf
./ssc -f ../toast/mdn/rel/mdn.conf
./ssc -f ../toast/mdn/ruby/mdn.conf
./ssc -f ../toast/mdn/scroll-property/mdn.conf
./ssc -f ../toast/mdn/scroll-pseudo-element/mdn.conf
./ssc -f ../toast/mdn/scrollbar/mdn.conf
./ssc -f ../toast/mdn/selector/mdn.conf
./ssc -f ../toast/mdn/shape/mdn.conf
./ssc -f ../toast/mdn/stroke/mdn.conf
./ssc -f ../toast/mdn/target/mdn.conf
./ssc -f ../toast/mdn/text/mdn.conf
./ssc -f ../toast/mdn/transform/mdn.conf
./ssc -f ../toast/mdn/transition/mdn.conf
./ssc -f ../toast/mdn/type/mdn.conf
./ssc -f ../toast/mdn/types/mdn.conf
./ssc -f ../toast/mdn/value/mdn.conf
./ssc -f ../toast/mdn/view-property/mdn.conf
./ssc -f ../toast/mdn/view-pseudo-element/mdn.conf
./ssc -f ../toast/mdn/webkit-property/mdn.conf
./ssc -f ../toast/mdn/webkit-pseudo-element/mdn.conf
./ssc -f ../toast/microdata/12/schema.conf
./ssc -f ../toast/microdata/addendum/add.conf
./ssc -f ../toast/microdata/basic/basic.conf
./ssc -f ../toast/microdata/dpv1/dpv1.conf
./ssc -f ../toast/microdata/dpv2/dpv2.conf
./ssc -f ../toast/microdata/export/export.conf
./ssc -f ../toast/microdata/link/link.conf
./ssc -f ../toast/microdata/microformats/mf.conf
./ssc -f ../toast/microdata/schema-abc/abc.conf
./ssc -f ../toast/microdata/schema-defg/defg.conf
./ssc -f ../toast/microdata/schema-hijkl/hijkl.conf
./ssc -f ../toast/microdata/schema-mno/mno.conf
./ssc -f ../toast/microdata/schema-pqrs/pqrs.conf
./ssc -f ../toast/microdata/schema-tuv/tuv.conf
./ssc -f ../toast/microdata/schema-wxyz/wxyz.conf
./ssc -f ../toast/microformats/mf1/mf1.conf
./ssc -f ../toast/microformats/mf2/mf2.conf
./ssc -f ../toast/microformats/rel/rel.conf
./ssc -f ../toast/other/abbr/abbr.conf
./ssc -f ../toast/other/ads/ads.conf
./ssc -f ../toast/other/base/base.conf
./ssc -f ../toast/other/characters/chars.conf
./ssc -f ../toast/other/clacks/clacks.conf
./ssc -f ../toast/other/CSS/css.conf
./ssc -f ../toast/other/dfn/dfn.conf
./ssc -f ../toast/other/dump/dump.conf
./ssc -f ../toast/other/efficient/efficient.conf
./ssc -f ../toast/other/efficient/inefficient.conf
./ssc -f ../toast/other/efficient/original.conf
./ssc -f ../toast/other/ie/ie.conf
./ssc -f ../toast/other/ignore/ignore.conf
./ssc -f ../toast/other/img/img.conf
./ssc -f ../toast/other/incorrectness/incorrectness.conf
./ssc -f ../toast/other/lists/lists.conf
./ssc -f ../toast/other/live/live.conf
./ssc -f ../toast/other/nits/nits.conf
./ssc -f ../toast/other/parsing/parsing.conf
./ssc -f ../toast/other/pattern/pattern.conf
./ssc -f ../toast/other/permissions/permissions.conf
./ssc -f ../toast/other/required/required.conf
./ssc -f ../toast/other/robotic/robotic.conf
./ssc -f ../toast/other/ruby/ruby.conf
./ssc -f ../toast/other/safari/safari.conf
./ssc -f ../toast/other/security/security.conf
./ssc -f ../toast/other/simple/simple.conf
./ssc -f ../toast/other/silenced/silenced.conf
./ssc -f ../toast/other/ssi/ssi.conf
./ssc -f ../toast/other/vtt/vtt.conf
./ssc -f ../toast/RDF/1.0/rdf.conf
./ssc -f ../toast/RDF/1.1/rdf.conf
./ssc -f ../toast/RDF/pointer/rdf.conf
./ssc -f ../toast/RDF/prism-1.0/rdf.conf
./ssc -f ../toast/RDF/prism-1.1/rdf.conf
./ssc -f ../toast/RDF/prism-1.2/rdf.conf
./ssc -f ../toast/RDF/prism-1.3/rdf.conf
./ssc -f ../toast/RDF/prism-2.0/rdf.conf
./ssc -f ../toast/RDF/prism-2.1/rdf.conf
./ssc -f ../toast/RDF/prism-3.0/rdf.conf
./ssc -f ../toast/RDF/prism-3.1/rdf.conf
./ssc -f ../toast/RDFa/1.1.3/rdfa.conf
./ssc -f ../toast/RDFa/cc/rdfa.conf
./ssc -f ../toast/RDFa/dc/rdfa.conf
./ssc -f ../toast/RDFa/foaf/rdfa.conf
./ssc -f ../toast/RDFa/gr/rdfa.conf
./ssc -f ../toast/RDFa/grddl/rdfa.conf
./ssc -f ../toast/RDFa/imported/rdfa.conf
./ssc -f ../toast/RDFa/lrdw/rdfa.conf
./ssc -f ../toast/RDFa/ontology/rdfa.conf
./ssc -f ../toast/RDFa/role/rdfa.conf
./ssc -f ../toast/RDFa/rs/rdfa.conf
./ssc -f ../toast/RDFa/sioc/rdfa.conf
./ssc -f ../toast/RDFa/vcard/rdfa.conf
./ssc -f ../toast/RDFa/vcard-2/rdfa.conf
./ssc -f ../toast/RDFa/vcard-3/rdfa.conf
./ssc -f ../toast/RDFa/vcard-4/rdfa.conf
./ssc -f ../toast/RDFa/xsd/rdfa.conf
./ssc -f ../toast/rss/0.91/rss.conf
./ssc -f ../toast/rss/0.92/rss.conf
./ssc -f ../toast/rss/2.0/rss.conf
./ssc -f ../toast/rss/cc/cc.conf
./ssc -f ../toast/rss/media/media.conf
./ssc -f ../toast/rss/trackback/trackback.conf
./ssc -f ../toast/shadow/comment/comment.conf
./ssc -f ../toast/shadow/copy/copy.conf
./ssc -f ../toast/shadow/copydiff/copydiff.conf
./ssc -f ../toast/shadow/copyover/copyover.conf
./ssc -f ../toast/shadow/css/css.conf
./ssc -f ../toast/shadow/dedu/dedu.conf
./ssc -f ../toast/shadow/dedudiff/dedudiff.conf
./ssc -f ../toast/shadow/deduover/deduover.conf
./ssc -f ../toast/shadow/delete/delete.conf
./ssc -f ../toast/shadow/hard/hard.conf
./ssc -f ../toast/shadow/pages/pages.conf
./ssc -f ../toast/shadow/soft/soft.conf
./ssc -f ../toast/shadow/softover/softover.conf
./ssc -f ../toast/shadow/ssi/ssi.conf
./ssc -f ../toast/shadow/update/update.conf
./ssc -f ../toast/signing/sign/sign.conf
./ssc -f ../toast/signing/verify/verify.conf
./ssc -f ../toast/signing/sign-pw/sign-pw.conf
./ssc -f ../toast/signing/verify-pw/verify-pw.conf
./ssc -f ../toast/snippet/conf/snippet.conf
./ssc -f ../toast/snippet/kiwi/snippet.conf
./ssc -f ../toast/spell/case/spell.conf
./ssc -f ../toast/spell/noicu/spell.conf
./ssc -f ../toast/spell/spell/spell.conf
./ssc -f ../toast/stats/CSS/stats.conf
./ssc -f ../toast/stats/CSS-6/stats.conf
./ssc -f ../toast/stats/CSS-6/stats-annotation.conf
./ssc -f ../toast/stats/CSS-6/stats-character-variant.conf
./ssc -f ../toast/stats/CSS-6/stats-content-name.conf
./ssc -f ../toast/stats/CSS-6/stats-counter-style.conf
./ssc -f ../toast/stats/CSS-6/stats-css-property.conf
./ssc -f ../toast/stats/CSS-6/stats-custom-media.conf
./ssc -f ../toast/stats/CSS-6/stats-custom-property.conf
./ssc -f ../toast/stats/CSS-6/stats-font.conf
./ssc -f ../toast/stats/CSS-6/stats-font-family.conf
./ssc -f ../toast/stats/CSS-6/stats-function.conf
./ssc -f ../toast/stats/CSS-6/stats-highlight.conf
./ssc -f ../toast/stats/CSS-6/stats-historical-form.conf
./ssc -f ../toast/stats/CSS-6/stats-keyframe.conf
./ssc -f ../toast/stats/CSS-6/stats-layer.conf
./ssc -f ../toast/stats/CSS-6/stats-ornament.conf
./ssc -f ../toast/stats/CSS-6/stats-page-name.conf
./ssc -f ../toast/stats/CSS-6/stats-palette.conf
./ssc -f ../toast/stats/CSS-6/stats-param.conf
./ssc -f ../toast/stats/CSS-6/stats-region.conf
./ssc -f ../toast/stats/CSS-6/stats-scroll-anim.conf
./ssc -f ../toast/stats/CSS-6/stats-statement.conf
./ssc -f ../toast/stats/CSS-6/stats-styleset.conf
./ssc -f ../toast/stats/CSS-6/stats-stylistic.conf
./ssc -f ../toast/stats/CSS-6/stats-swash.conf
./ssc -f ../toast/stats/CSS-6/stats-view.conf
./ssc -f ../toast/stats/detail/stats.conf
./ssc -f ../toast/stats/detail/stats-abbreviation.conf
./ssc -f ../toast/stats/detail/stats-category.conf
./ssc -f ../toast/stats/detail/stats-class.conf
./ssc -f ../toast/stats/detail/stats-definition.conf
./ssc -f ../toast/stats/detail/stats-element.conf
./ssc -f ../toast/stats/detail/stats-file.conf
./ssc -f ../toast/stats/detail/stats-id.conf
./ssc -f ../toast/stats/detail/stats-meta.conf
./ssc -f ../toast/stats/detail/stats-name-value.conf
./ssc -f ../toast/stats/detail/stats-ontology.conf
./ssc -f ../toast/stats/detail/stats-reference.conf
./ssc -f ../toast/stats/detail/stats-version.conf
./ssc -f ../toast/stats/single/stats.conf
./ssc -f ../toast/stats/summary/stats.conf
./ssc -f ../toast/SVG/1.0/svg.conf
./ssc -f ../toast/SVG/1.1/svg.conf
./ssc -f ../toast/SVG/1.2/svg.conf
./ssc -f ../toast/SVG/1.2-full/svg.conf
./ssc -f ../toast/SVG/2.0/svg.conf
./ssc -f ../toast/SVG/2.1/svg.conf
./ssc -f ../toast/type/atom/atom.conf
./ssc -f ../toast/type/colour/colour.conf
./ssc -f ../toast/type/custom/custom.conf
./ssc -f ../toast/type/httpequiv/httpequiv.conf
./ssc -f ../toast/type/lang/lang.conf
./ssc -f ../toast/type/metaname/metaname.conf
./ssc -f ../toast/type/mimetype/mimetype.conf
./ssc -f ../toast/type/rel/rel.conf
./ssc -f ../toast/type/rfc6570/rfc6570.conf
./ssc -f ../toast/type/rsl/rsl.conf
./ssc -f ../toast/type/sgml/sgml.conf
./ssc -f ../toast/type/url/url.conf
./ssc -f ../toast/w3/3663/w3.conf
./ssc -f ../toast/w3/12458/w3.conf
./ssc -f ../toast/w3/acefh/w3.conf
./ssc -f ../toast/w3/bogus/w3.conf
./ssc -f ../toast/w3/cag-1/w3.conf
./ssc -f ../toast/w3/cag-2/w3.conf
./ssc -f ../toast/w3/charset/w3.conf
./ssc -f ../toast/w3/html20/w3.conf
./ssc -f ../toast/w3/html40/w3.conf
./ssc -f ../toast/w3/html401/w3.conf
./ssc -f ../toast/w3/html5/w3.conf
./ssc -f ../toast/w3/imnop/w3.conf
./ssc -f ../toast/w3/mathml/w3.conf
./ssc -f ../toast/w3/rddl/w3.conf
./ssc -f ../toast/w3/rstuw/w3.conf
./ssc -f ../toast/w3/sgml/w3.conf
./ssc -f ../toast/w3/smil/w3.conf
./ssc -f ../toast/w3/svg/w3.conf
./ssc -f ../toast/w3/text/w3.conf
./ssc -f ../toast/w3/xhtml/w3.conf
./ssc -f ../toast/w3/xml/w3.conf
./ssc -f ../toast/webapps/jan05/webapps.conf
./ssc -f ../toast/webapps/jul05/webapps.conf
./ssc -f ../toast/webapps/jan06/webapps.conf
./ssc -f ../toast/webapps/jul06/webapps.conf
./ssc -f ../toast/webapps/jan07/webapps.conf
./ssc -f ../toast/XHTML/1.0/xhtml1.conf
./ssc -f ../toast/XHTML/1.1/xhtml11.conf
./ssc -f ../toast/XHTML/2.0/xhtml2.conf
./ssc -f ../toast/XHTML/5.0/xhtml5.conf
./ssc -f ../toast/output/bespoke/output.conf
./ssc -f ../toast/output/html/output.conf
./ssc -f ../toast/output/out/output.conf
./ssc -f ../toast/output/stylesheet/output.conf
./ssc -f ../toast/output/test/output.conf
./ssc -f ../toast/output/text/output.conf
./ssc -f ../toast/output/xhtml/output.conf
