ssc.exe -f ../toast/conf/html/conf.conf
ssc.exe -f ../toast/conf/xhtml/conf.conf
ssc.exe -f ../toast/coop/corrupt/corrupt.conf
ssc.exe -f ../toast/coop/corrupt/corrupt2.conf
ssc.exe -f ../toast/coop/corrupt/corrupt512.conf
ssc.exe -f ../toast/coop/oct21/living.conf
ssc.exe -f ../toast/coop/schema-abc/abc.conf
ssc.exe -f ../toast/csp/1/csp.conf
ssc.exe -f ../toast/csp/2/csp.conf
ssc.exe -f ../toast/csp/3/csp.conf
ssc.exe -f ../toast/css/1/css.conf
ssc.exe -f ../toast/css/2.0/css.conf
ssc.exe -f ../toast/css/2.1/css.conf
ssc.exe -f ../toast/css/2.2/css.conf
ssc.exe -f ../toast/css/3-ns/css.conf
ssc.exe -f ../toast/css/3-sel/css.conf
ssc.exe -f ../toast/css/3-style/css.conf
ssc.exe -f ../toast/css/accessibility/css.conf
ssc.exe -f ../toast/css/songlight/css.conf
ssc.exe -f ../toast/HTML/1.0/html1.conf
ssc.exe -f ../toast/HTML/2.0/html2.conf
ssc.exe -f ../toast/HTML/3.0/html3.conf
ssc.exe -f ../toast/HTML/3.2/html32.conf
ssc.exe -f ../toast/HTML/4.00/html4.conf
ssc.exe -f ../toast/HTML/4.01/html4.conf
ssc.exe -f ../toast/HTML/5.0/html5.conf
ssc.exe -f ../toast/HTML/5.1/html5.conf
ssc.exe -f ../toast/HTML/5.2/html5.conf
ssc.exe -f ../toast/HTML/5.3/html5.conf
ssc.exe -f ../toast/HTML/5.4/html5.conf
ssc.exe -f ../toast/HTML/minimal/minimal.conf
ssc.exe -f ../toast/HTML/Plus/plus.conf
ssc.exe -f ../toast/HTML/tags/tags.conf
ssc.exe -f ../toast/link/external/link.conf
ssc.exe -f ../toast/link/link/link.conf
ssc.exe -f ../toast/json-ld/as/jsonld.conf
ssc.exe -f ../toast/json-ld/schemaorg/jsonld.conf
ssc.exe -f ../toast/living/jul07/living.conf
ssc.exe -f ../toast/living/jan08/living.conf
ssc.exe -f ../toast/living/jul08/living.conf
ssc.exe -f ../toast/living/jan09/living.conf
ssc.exe -f ../toast/living/jul09/living.conf
ssc.exe -f ../toast/living/jan10/living.conf
ssc.exe -f ../toast/living/jul10/living.conf
ssc.exe -f ../toast/living/jan11/living.conf
ssc.exe -f ../toast/living/jul11/living.conf
ssc.exe -f ../toast/living/jan12/living.conf
ssc.exe -f ../toast/living/jul12/living.conf
ssc.exe -f ../toast/living/jan13/living.conf
ssc.exe -f ../toast/living/jul13/living.conf
ssc.exe -f ../toast/living/jan14/living.conf
ssc.exe -f ../toast/living/jul14/living.conf
ssc.exe -f ../toast/living/jan15/living.conf
ssc.exe -f ../toast/living/jul15/living.conf
ssc.exe -f ../toast/living/jan16/living.conf
ssc.exe -f ../toast/living/jul16/living.conf
ssc.exe -f ../toast/living/jan17/living.conf
ssc.exe -f ../toast/living/jul17/living.conf
ssc.exe -f ../toast/living/jan18/living.conf
ssc.exe -f ../toast/living/jul18/living.conf
ssc.exe -f ../toast/living/jan19/living.conf
ssc.exe -f ../toast/living/jul19/living.conf
ssc.exe -f ../toast/living/jan20/living.conf
ssc.exe -f ../toast/living/jul20/living.conf
ssc.exe -f ../toast/living/jan21/living.conf
ssc.exe -f ../toast/living/apr21/living.conf
ssc.exe -f ../toast/living/jul21/living.conf
ssc.exe -f ../toast/living/oct21/living.conf
ssc.exe -f ../toast/living/jan22/living.conf
ssc.exe -f ../toast/living/apr22/living.conf
ssc.exe -f ../toast/living/jul22/living.conf
ssc.exe -f ../toast/living/oct22/living.conf
ssc.exe -f ../toast/math/1/math.conf
ssc.exe -f ../toast/math/2/math.conf
ssc.exe -f ../toast/math/3/math.conf
ssc.exe -f ../toast/math/4-20/math.conf
ssc.exe -f ../toast/math/4-22/math.conf
ssc.exe -f ../toast/microdata/12/schema.conf
ssc.exe -f ../toast/microdata/addendum/add.conf
ssc.exe -f ../toast/microdata/basic/basic.conf
ssc.exe -f ../toast/microdata/export/export.conf
ssc.exe -f ../toast/microdata/microformats/mf.conf
ssc.exe -f ../toast/microdata/schema-abc/abc.conf
ssc.exe -f ../toast/microdata/schema-defg/defg.conf
ssc.exe -f ../toast/microdata/schema-hijkl/hijkl.conf
ssc.exe -f ../toast/microdata/schema-mno/mno.conf
ssc.exe -f ../toast/microdata/schema-pqrs/pqrs.conf
ssc.exe -f ../toast/microdata/schema-tuv/tuv.conf
ssc.exe -f ../toast/microdata/schema-wxyz/wxyz.conf
ssc.exe -f ../toast/microformats/mf1/mf1.conf
ssc.exe -f ../toast/microformats/mf2/mf2.conf
ssc.exe -f ../toast/microformats/rel/rel.conf
ssc.exe -f ../toast/other/abbr/abbr.conf
ssc.exe -f ../toast/other/aria/aria.conf
ssc.exe -f ../toast/other/base/base.conf
ssc.exe -f ../toast/other/blob/blob.conf
ssc.exe -f ../toast/other/characters/chars.conf
ssc.exe -f ../toast/other/CSS/css.conf
ssc.exe -f ../toast/other/dfn/dfn.conf
ssc.exe -f ../toast/other/dump/dump.conf
ssc.exe -f ../toast/other/ignore/ignore.conf
ssc.exe -f ../toast/other/incorrectness/incorrectness.conf
ssc.exe -f ../toast/other/nits/nits.conf
ssc.exe -f ../toast/other/parsing/parsing.conf
ssc.exe -f ../toast/other/pattern/pattern.conf
ssc.exe -f ../toast/other/simple/simple.conf
ssc.exe -f ../toast/other/ssi/ssi.conf
ssc.exe -f ../toast/RDFa/1.1.3/rdfa.conf
ssc.exe -f ../toast/RDFa/cc/rdfa.conf
ssc.exe -f ../toast/RDFa/dc/rdfa.conf
ssc.exe -f ../toast/RDFa/foaf/rdfa.conf
ssc.exe -f ../toast/RDFa/gr/rdfa.conf
ssc.exe -f ../toast/RDFa/grddl/rdfa.conf
ssc.exe -f ../toast/RDFa/imported/rdfa.conf
ssc.exe -f ../toast/RDFa/lrdw/rdfa.conf
ssc.exe -f ../toast/RDFa/role/rdfa.conf
ssc.exe -f ../toast/RDFa/rs/rdfa.conf
ssc.exe -f ../toast/RDFa/schema/rdfa.conf
ssc.exe -f ../toast/RDFa/sioc/rdfa.conf
ssc.exe -f ../toast/RDFa/vcard/rdfa.conf
ssc.exe -f ../toast/RDFa/vcard-2/rdfa.conf
ssc.exe -f ../toast/RDFa/vcard-3/rdfa.conf
ssc.exe -f ../toast/RDFa/vcard-4/rdfa.conf
ssc.exe -f ../toast/RDFa/xsd/rdfa.conf
ssc.exe -f ../toast/shadow/comment/comment.conf
ssc.exe -f ../toast/shadow/copy/copy.conf
ssc.exe -f ../toast/shadow/copydiff/copydiff.conf
ssc.exe -f ../toast/shadow/copyover/copyover.conf
ssc.exe -f ../toast/shadow/dedu/dedu.conf
ssc.exe -f ../toast/shadow/dedudiff/dedudiff.conf
ssc.exe -f ../toast/shadow/deduover/deduover.conf
ssc.exe -f ../toast/shadow/delete/delete.conf
ssc.exe -f ../toast/shadow/hard/hard.conf
ssc.exe -f ../toast/shadow/pages/pages.conf
ssc.exe -f ../toast/shadow/soft/soft.conf
ssc.exe -f ../toast/shadow/softover/softover.conf
ssc.exe -f ../toast/shadow/ssi/ssi.conf
ssc.exe -f ../toast/shadow/update/update.conf
ssc.exe -f ../toast/snippet/conf/snippet.conf
ssc.exe -f ../toast/snippet/kiwi/snippet.conf
ssc.exe -f ../toast/spell/case/spell.conf
ssc.exe -f ../toast/spell/noicu/spell.conf
ssc.exe -f ../toast/spell/spell/spell.conf
ssc.exe -f ../toast/stats/detail/stats.conf
ssc.exe -f ../toast/stats/single/stats.conf
ssc.exe -f ../toast/stats/summary/stats.conf
ssc.exe -f ../toast/SVG/1.0/svg.conf
ssc.exe -f ../toast/SVG/1.1/svg.conf
ssc.exe -f ../toast/SVG/1.2/svg.conf
ssc.exe -f ../toast/SVG/1.2-full/svg.conf
ssc.exe -f ../toast/SVG/2.0/svg.conf
ssc.exe -f ../toast/SVG/2.1/svg.conf
ssc.exe -f ../toast/type/colour/colour.conf
ssc.exe -f ../toast/type/custom/custom.conf
ssc.exe -f ../toast/type/httpequiv/httpequiv.conf
ssc.exe -f ../toast/type/lang/lang.conf
ssc.exe -f ../toast/type/metaname/metaname.conf
ssc.exe -f ../toast/type/mimetype/mimetype.conf
ssc.exe -f ../toast/type/sgml/sgml.conf
ssc.exe -f ../toast/type/url/url.conf
ssc.exe -f ../toast/w3/3663/w3.conf
ssc.exe -f ../toast/w3/12458/w3.conf
ssc.exe -f ../toast/w3/acefhw3.conf
ssc.exe -f ../toast/w3/bogus/w3.conf
ssc.exe -f ../toast/w3/charset/w3.conf
ssc.exe -f ../toast/w3/html20/w3.conf
ssc.exe -f ../toast/w3/html40/w3.conf
ssc.exe -f ../toast/w3/html401/w3.conf
ssc.exe -f ../toast/w3/html5/w3.conf
ssc.exe -f ../toast/w3/imnop/w3.conf
ssc.exe -f ../toast/w3/mathml/w3.conf
ssc.exe -f ../toast/w3/rddl/w3.conf
ssc.exe -f ../toast/w3/rstuw/w3.conf
ssc.exe -f ../toast/w3/sgml/w3.conf
ssc.exe -f ../toast/w3/smil/w3.conf
ssc.exe -f ../toast/w3/svg/w3.conf
ssc.exe -f ../toast/w3/text/w3.conf
ssc.exe -f ../toast/w3/xhtml/w3.conf
ssc.exe -f ../toast/w3/xml/w3.conf
ssc.exe -f ../toast/webapps/jan05/webapps.conf
ssc.exe -f ../toast/webapps/jul05/webapps.conf
ssc.exe -f ../toast/webapps/jan06/webapps.conf
ssc.exe -f ../toast/webapps/jul06/webapps.conf
ssc.exe -f ../toast/webapps/jan07/webapps.conf
ssc.exe -f ../toast/XHTML/1.0/xhtml1.conf
ssc.exe -f ../toast/XHTML/1.1/xhtml11.conf
ssc.exe -f ../toast/XHTML/2.0/xhtml2.conf
ssc.exe -f ../toast/output/html/output.conf
ssc.exe -f ../toast/output/out/output.conf
ssc.exe -f ../toast/output/test/output.conf
ssc.exe -f ../toast/output/text/output.conf
ssc.exe -f ../toast/output/xhtml/output.conf
