ssc.exe -T --nits.spec -o ../out/confhtml.tst -f ../toast/conf/html/conf.conf
ssc.exe -T --nits.spec -o ../out/confxhtml.tst -f ../toast/conf/xhtml/conf.conf
ssc.exe -T --nits.spec -o ../out/coopcorrupt.tst -f ../toast/coop/corrupt/corrupt.conf
ssc.exe -T --nits.spec -o ../out/coopcorrupt2.tst -f ../toast/coop/corrupt/corrupt2.conf
ssc.exe -T --nits.spec -o ../out/coopcorrupt512.tst -f ../toast/coop/corrupt/corrupt512.conf
ssc.exe -T --nits.spec -o ../out/coopliving.tst -f ../toast/coop/oct21/living.conf
ssc.exe -T --nits.spec -o ../out/coopabc.tst -f ../toast/coop/schema-abc/abc.conf
ssc.exe -T --nits.spec -o ../out/1csp.tst -f ../toast/csp/1/csp.conf
ssc.exe -T --nits.spec -o ../out/2csp.tst -f ../toast/csp/2/csp.conf
ssc.exe -T --nits.spec -o ../out/3csp.tst -f ../toast/csp/3/csp.conf
ssc.exe -T --nits.spec -o ../out/1css.tst -f ../toast/csp/1/css.conf
ssc.exe -T --nits.spec -o ../out/20css.tst -f ../toast/css/2.0/css.conf
ssc.exe -T --nits.spec -o ../out/21css.tst -f ../toast/css/2.1/css.conf
ssc.exe -T --nits.spec -o ../out/22css.tst -f ../toast/css/2.2/css.conf
ssc.exe -T --nits.spec -o ../out/3animation.tst -f ../toast/css/3-animation/css.conf
ssc.exe -T --nits.spec -o ../out/4animation.tst -f ../toast/css/4-animation/css.conf
ssc.exe -T --nits.spec -o ../out/3background.tst -f ../toast/css/3-background/css.conf
ssc.exe -T --nits.spec -o ../out/3bm.tst -f ../toast/css/3-box-model/css.conf
ssc.exe -T --nits.spec -o ../out/4bm.tst -f ../toast/css/4-box-model/css.conf
ssc.exe -T --nits.spec -o ../out/3bsz.tst -f ../toast/css/3-box-sizing/css.conf
ssc.exe -T --nits.spec -o ../out/3cascade.tst -f ../toast/css/3-cascade/css.conf
ssc.exe -T --nits.spec -o ../out/4cascade.tst -f ../toast/css/4-cascade/css.conf
ssc.exe -T --nits.spec -o ../out/5cascade.tst -f ../toast/css/5-cascade/css.conf
ssc.exe -T --nits.spec -o ../out/6cascade.tst -f ../toast/css/6-cascade/css.conf
ssc.exe -T --nits.spec -o ../out/3colour.tst -f ../toast/css/3-colour/css.conf
ssc.exe -T --nits.spec -o ../out/4colour.tst -f ../toast/css/4-colour/css.conf
ssc.exe -T --nits.spec -o ../out/5colour.tst -f ../toast/css/5-colour/css.conf
ssc.exe -T --nits.spec -o ../out/3comp.tst -f ../toast/css/3-compositing/css.conf
ssc.exe -T --nits.spec -o ../out/3cr.tst -f ../toast/css/3-cr/css.conf
ssc.exe -T --nits.spec -o ../out/3cs.tst -f ../toast/css/3-cs/css.conf
ssc.exe -T --nits.spec -o ../out/3display.tst -f ../toast/css/3-display/css.conf
ssc.exe -T --nits.spec -o ../out/3fbl.tst -f ../toast/css/3-fbl/css.conf
ssc.exe -T --nits.spec -o ../out/3font.tst -f ../toast/css/3-font/css.conf
ssc.exe -T --nits.spec -o ../out/4font.tst -f ../toast/css/4-font/css.conf
ssc.exe -T --nits.spec -o ../out/5font.tst -f ../toast/css/5-font/css.conf
ssc.exe -T --nits.spec -o ../out/4frag.tst -f ../toast/css/4-frag/css.conf
ssc.exe -T --nits.spec -o ../out/3grid.tst -f ../toast/css/3-grid/css.conf
ssc.exe -T --nits.spec -o ../out/4grid.tst -f ../toast/css/4-grid/css.conf
ssc.exe -T --nits.spec -o ../out/3image.tst -f ../toast/css/3-image/css.conf
ssc.exe -T --nits.spec -o ../out/3masking.tst -f ../toast/css/3-masking/css.conf
ssc.exe -T --nits.spec -o ../out/3mc.tst -f ../toast/css/3-mc/css.conf
ssc.exe -T --nits.spec -o ../out/3media.tst -f ../toast/css/3-media/css.conf
ssc.exe -T --nits.spec -o ../out/4media.tst -f ../toast/css/4-media/css.conf
ssc.exe -T --nits.spec -o ../out/5media.tst -f ../toast/css/5-media/css.conf
ssc.exe -T --nits.spec -o ../out/3ns.tst -f ../toast/css/3-ns/css.conf
ssc.exe -T --nits.spec -o ../out/3overflow.tst -f ../toast/css/3-overflow/css.conf
ssc.exe -T --nits.spec -o ../out/3position.tst -f ../toast/css/3-position/css.conf
ssc.exe -T --nits.spec -o ../out/3sel.tst -f ../toast/css/3-sel/css.conf
ssc.exe -T --nits.spec -o ../out/4sel.tst -f ../toast/css/4-sel/css.conf
ssc.exe -T --nits.spec -o ../out/3shape.tst -f ../toast/css/3-shape/css.conf
ssc.exe -T --nits.spec -o ../out/3style.tst -f ../toast/css/3-style/css.conf
ssc.exe -T --nits.spec -o ../out/3speech.tst -f ../toast/css/3-peech/css.conf
ssc.exe -T --nits.spec -o ../out/3syntax.tst -f ../toast/css/3-syntax/css.conf
ssc.exe -T --nits.spec -o ../out/3table.tst -f ../toast/css/3-able/css.conf
ssc.exe -T --nits.spec -o ../out/3textdec.tst -f ../toast/css/3-textdec/css.conf
ssc.exe -T --nits.spec -o ../out/4textdec.tst -f ../toast/css/4-textdec/css.conf
ssc.exe -T --nits.spec -o ../out/3transform.tst -f ../toast/css/3-transform/css.conf
ssc.exe -T --nits.spec -o ../out/4transform.tst -f ../toast/css/4-transform/css.conf
ssc.exe -T --nits.spec -o ../out/3transition.tst -f ../toast/css/3-transition/css.conf
ssc.exe -T --nits.spec -o ../out/3ui.tst -f ../toast/css/3-ui/css.conf
ssc.exe -T --nits.spec -o ../out/4ui.tst -f ../toast/css/4-ui/css.conf
ssc.exe -T --nits.spec -o ../out/3value.tst -f ../toast/css/3-value/css.conf
ssc.exe -T --nits.spec -o ../out/4value.tst -f ../toast/css/4-value/css.conf
ssc.exe -T --nits.spec -o ../out/3wc.tst -f ../toast/css/3-wc/css.conf
ssc.exe -T --nits.spec -o ../out/3writing.tst -f ../toast/css/3-writing/css.conf
ssc.exe -T --nits.spec -o ../out/4writing.tst -f ../toast/css/4-writing/css.conf
ssc.exe -T --nits.spec -o ../out/accessibility.tst -f ../toast/css/accessibility/css.conf
ssc.exe -T --nits.spec -o ../out/cssae.tst -f ../toast/css/ae/css.conf
ssc.exe -T --nits.spec -o ../out/csscustom.tst -f ../toast/css/custom/css.conf
ssc.exe -T --nits.spec -o ../out/cssdeprecated.tst -f ../toast/css/deprecated/css.conf
ssc.exe -T --nits.spec -o ../out/cssease.tst -f ../toast/css/ease/css.conf
ssc.exe -T --nits.spec -o ../out/cssprofile.tst -f ../toast/css/profile/css.conf
ssc.exe -T --nits.spec -o ../out/csssimple.tst -f ../toast/css/simple/css.conf
ssc.exe -T --nits.spec -o ../out/songlight.tst -f ../toast/css/songlight/css.conf
ssc.exe -T --nits.spec -o ../out/1.0html1.tst -f ../toast/HTML/1.0/html1.conf
ssc.exe -T --nits.spec -o ../out/2.0html2.tst -f ../toast/HTML/2.0/html2.conf
ssc.exe -T --nits.spec -o ../out/3.0html3.tst -f ../toast/HTML/3.0/html3.conf
ssc.exe -T --nits.spec -o ../out/3.2html32.tst -f ../toast/HTML/3.2/html32.conf
ssc.exe -T --nits.spec -o ../out/4.00html4.tst -f ../toast/HTML/4.00/html4.conf
ssc.exe -T --nits.spec -o ../out/4.01html4.tst -f ../toast/HTML/4.01/html4.conf
ssc.exe -T --nits.spec -o ../out/5.0html5.tst -f ../toast/HTML/5.0/html5.conf
ssc.exe -T --nits.spec -o ../out/5.1html5.tst -f ../toast/HTML/5.1/html5.conf
ssc.exe -T --nits.spec -o ../out/5.2html5.tst -f ../toast/HTML/5.2/html5.conf
ssc.exe -T --nits.spec -o ../out/5.3html5.tst -f ../toast/HTML/5.3/html5.conf
ssc.exe -T --nits.spec -o ../out/5.4html5.tst -f ../toast/HTML/5.4/html5.conf
ssc.exe -T --nits.spec -o ../out/minimalminimal.tst -f ../toast/HTML/minimal/minimal.conf
ssc.exe -T --nits.spec -o ../out/Plusplus.tst -f ../toast/HTML/Plus/plus.conf
ssc.exe -T --nits.spec -o ../out/tagstags.tst -f ../toast/HTML/tags/tags.conf
ssc.exe -T --nits.spec -o ../out/jas.tst -f ../toast/json-ld/as/jsonld.conf
ssc.exe -T --nits.spec -o ../out/jschemaorg.tst -f ../toast/json-ld/schemaorg/jsonld.conf
ssc.exe -T --nits.spec -o ../out/exlink.tst -f ../toast/link/external/link.conf
ssc.exe -T --nits.spec -o ../out/linklink.tst -f ../toast/link/link/link.conf
ssc.exe -T --nits.spec -o ../out/jul07living.tst -f ../toast/living/jul07/living.conf
ssc.exe -T --nits.spec -o ../out/jan08living.tst -f ../toast/living/jan08/living.conf
ssc.exe -T --nits.spec -o ../out/jul08living.tst -f ../toast/living/jul08/living.conf
ssc.exe -T --nits.spec -o ../out/jan09living.tst -f ../toast/living/jan09/living.conf
ssc.exe -T --nits.spec -o ../out/jul09living.tst -f ../toast/living/jul09/living.conf
ssc.exe -T --nits.spec -o ../out/jan10living.tst -f ../toast/living/jan10/living.conf
ssc.exe -T --nits.spec -o ../out/jul10living.tst -f ../toast/living/jul10/living.conf
ssc.exe -T --nits.spec -o ../out/jan11living.tst -f ../toast/living/jan11/living.conf
ssc.exe -T --nits.spec -o ../out/jul11living.tst -f ../toast/living/jul11/living.conf
ssc.exe -T --nits.spec -o ../out/jan12living.tst -f ../toast/living/jan12/living.conf
ssc.exe -T --nits.spec -o ../out/jul12living.tst -f ../toast/living/jul12/living.conf
ssc.exe -T --nits.spec -o ../out/jan13living.tst -f ../toast/living/jan13/living.conf
ssc.exe -T --nits.spec -o ../out/jul13living.tst -f ../toast/living/jul13/living.conf
ssc.exe -T --nits.spec -o ../out/jan14living.tst -f ../toast/living/jan14/living.conf
ssc.exe -T --nits.spec -o ../out/jul14living.tst -f ../toast/living/jul14/living.conf
ssc.exe -T --nits.spec -o ../out/jan15living.tst -f ../toast/living/jan15/living.conf
ssc.exe -T --nits.spec -o ../out/jul15living.tst -f ../toast/living/jul15/living.conf
ssc.exe -T --nits.spec -o ../out/jan16living.tst -f ../toast/living/jan16/living.conf
ssc.exe -T --nits.spec -o ../out/jul16living.tst -f ../toast/living/jul16/living.conf
ssc.exe -T --nits.spec -o ../out/jan17living.tst -f ../toast/living/jan17/living.conf
ssc.exe -T --nits.spec -o ../out/jul17living.tst -f ../toast/living/jul17/living.conf
ssc.exe -T --nits.spec -o ../out/jan18living.tst -f ../toast/living/jan18/living.conf
ssc.exe -T --nits.spec -o ../out/jul18living.tst -f ../toast/living/jul18/living.conf
ssc.exe -T --nits.spec -o ../out/jan19living.tst -f ../toast/living/jan19/living.conf
ssc.exe -T --nits.spec -o ../out/jul19living.tst -f ../toast/living/jul19/living.conf
ssc.exe -T --nits.spec -o ../out/jan20living.tst -f ../toast/living/jan20/living.conf
ssc.exe -T --nits.spec -o ../out/jul20living.tst -f ../toast/living/jul20/living.conf
ssc.exe -T --nits.spec -o ../out/jan21living.tst -f ../toast/living/jan21/living.conf
ssc.exe -T --nits.spec -o ../out/apr21living.tst -f ../toast/living/apr21/living.conf
ssc.exe -T --nits.spec -o ../out/jul21living.tst -f ../toast/living/jul21/living.conf
ssc.exe -T --nits.spec -o ../out/oct21living.tst -f ../toast/living/oct21/living.conf
ssc.exe -T --nits.spec -o ../out/jan22living.tst -f ../toast/living/jan22/living.conf
ssc.exe -T --nits.spec -o ../out/apr22living.tst -f ../toast/living/apr22/living.conf
ssc.exe -T --nits.spec -o ../out/jul22living.tst -f ../toast/living/jul22/living.conf
ssc.exe -T --nits.spec -o ../out/oct22living.tst -f ../toast/living/oct22/living.conf
ssc.exe -T --nits.spec -o ../out/jan23living.tst -f ../toast/living/jan23/living.conf
ssc.exe -T --nits.spec -o ../out/apr23living.tst -f ../toast/living/apr23/living.conf
ssc.exe -T --nits.spec -o ../out/jul23living.tst -f ../toast/living/jul23/living.conf
ssc.exe -T --nits.spec -o ../out/oct23living.tst -f ../toast/living/oct23/living.conf
ssc.exe -T --nits.spec -o ../out/1math.tst -f ../toast/math/1/math.conf
ssc.exe -T --nits.spec -o ../out/2math.tst -f ../toast/math/2/math.conf
ssc.exe -T --nits.spec -o ../out/3math.tst -f ../toast/math/3/math.conf
ssc.exe -T --nits.spec -o ../out/420math.tst -f ../toast/math/4-20/math.conf
ssc.exe -T --nits.spec -o ../out/422math.tst -f ../toast/math/4-22/math.conf
ssc.exe -T --nits.spec -o ../out/12schema.tst -f ../toast/microdata/12/schema.conf
ssc.exe -T --nits.spec -o ../out/addendumadd.tst -f ../toast/microdata/addendum/add.conf
ssc.exe -T --nits.spec -o ../out/basicbasic.tst -f ../toast/microdata/basic/basic.conf
ssc.exe -T --nits.spec -o ../out/exportexport.tst -f ../toast/microdata/export/export.conf
ssc.exe -T --nits.spec -o ../out/microdatamf.tst -f ../toast/microdata/microformats/mf.conf
ssc.exe -T --nits.spec -o ../out/schema-abcabc.tst -f ../toast/microdata/schema-abc/abc.conf
ssc.exe -T --nits.spec -o ../out/schema-defgdefg.tst -f ../toast/microdata/schema-defg/defg.conf
ssc.exe -T --nits.spec -o ../out/schema-hijklhijkl.tst -f ../toast/microdata/schema-hijkl/hijkl.conf
ssc.exe -T --nits.spec -o ../out/schema-mnomno.tst -f ../toast/microdata/schema-mno/mno.conf
ssc.exe -T --nits.spec -o ../out/schema-pqrspqrs.tst -f ../toast/microdata/schema-pqrs/pqrs.conf
ssc.exe -T --nits.spec -o ../out/schema-tuvtuv.tst -f ../toast/microdata/schema-tuv/tuv.conf
ssc.exe -T --nits.spec -o ../out/schema-wxyzwxyz.tst -f ../toast/microdata/schema-wxyz/wxyz.conf
ssc.exe -T --nits.spec -o ../out/mf1mf1.tst -f ../toast/microformats/mf1/mf1.conf
ssc.exe -T --nits.spec -o ../out/mf2mf2.tst -f ../toast/microformats/mf2/mf2.conf
ssc.exe -T --nits.spec -o ../out/relrel.tst -f ../toast/microformats/rel/rel.conf
ssc.exe -T --nits.spec -o ../out/abbrabbr.tst -f ../toast/other/abbr/abbr.conf
ssc.exe -T --nits.spec -o ../out/ariaaria.tst -f ../toast/other/aria/aria.conf
ssc.exe -T --nits.spec -o ../out/basebase.tst -f ../toast/other/base/base.conf
ssc.exe -T --nits.spec -o ../out/blobblob.tst -f ../toast/other/blob/blob.conf
ssc.exe -T --nits.spec -o ../out/charchars.tst -f ../toast/other/characters/chars.conf
ssc.exe -T --nits.spec -o ../out/clacksclacks.tst -f ../toast/other/clacks/clacks.conf
ssc.exe -T --nits.spec -o ../out/CSScss.tst -f ../toast/other/CSS/css.conf
ssc.exe -T --nits.spec -o ../out/dfndfn.tst -f ../toast/other/dfn/dfn.conf
ssc.exe -T --nits.spec -o ../out/dumpdump.tst -f ../toast/other/dump/dump.conf
ssc.exe -T --nits.spec -o ../out/ignoreignore.tst -f ../toast/other/ignore/ignore.conf
ssc.exe -T --nits.spec -o ../out/ieie.tst -f ../toast/other/ie/ie.conf
ssc.exe -T --nits.spec -o ../out/incorrectnessincorrectness.tst -f ../toast/other/incorrectness/incorrectness.conf
ssc.exe -T --nits.spec -o ../out/nitsnits.tst -f ../toast/other/nits/nits.conf
ssc.exe -T --nits.spec -o ../out/parsingparsing.tst -f ../toast/other/parsing/parsing.conf
ssc.exe -T --nits.spec -o ../out/patternpattern.tst -f ../toast/other/pattern/pattern.conf
ssc.exe -T --nits.spec -o ../out/safarisafari.tst -f ../toast/other/safari/safari.conf
ssc.exe -T --nits.spec -o ../out/simplesimple.tst -f ../toast/other/simple/simple.conf
ssc.exe -T --nits.spec -o ../out/ssissi.tst -f ../toast/other/ssi/ssi.conf
ssc.exe -T --nits.spec -o ../out/RDFa113.tst -f ../toast/RDFa/1.1.3/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFacc.tst -f ../toast/RDFa/cc/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFadc.tst -f ../toast/RDFa/dc/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFafoaf.tst -f ../toast/RDFa/foaf/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFagr.tst -f ../toast/RDFa/gr/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFagrddl.tst -f ../toast/RDFa/grddl/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFaimported.tst -f ../toast/RDFa/imported/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFalrdw.tst -f ../toast/RDFa/lrdw/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFarole.tst -f ../toast/RDFa/role/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFars.tst -f ../toast/RDFa/rs/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFaschema.tst -f ../toast/RDFa/schema/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFasioc.tst -f ../toast/RDFa/sioc/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFavcard1.tst -f ../toast/RDFa/vcard/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFavcard2.tst -f ../toast/RDFa/vcard-2/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFavcard3.tst -f ../toast/RDFa/vcard-3/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFavcard4.tst -f ../toast/RDFa/vcard-4/rdfa.conf
ssc.exe -T --nits.spec -o ../out/RDFaxsd.tst -f ../toast/RDFa/xsd/rdfa.conf
ssc.exe -T --nits.spec -o ../out/commentcomment.tst -f ../toast/shadow/comment/comment.conf
ssc.exe -T --nits.spec -o ../out/copycopy.tst -f ../toast/shadow/copy/copy.conf
ssc.exe -T --nits.spec -o ../out/copydiffcopydiff.tst -f ../toast/shadow/copydiff/copydiff.conf
ssc.exe -T --nits.spec -o ../out/copyovercopyover.tst -f ../toast/shadow/copyover/copyover.conf
ssc.exe -T --nits.spec -o ../out/dedudedu.tst -f ../toast/shadow/dedu/dedu.conf
ssc.exe -T --nits.spec -o ../out/dedudiffdedudiff.tst -f ../toast/shadow/dedudiff/dedudiff.conf
ssc.exe -T --nits.spec -o ../out/deduoverdeduover.tst -f ../toast/shadow/deduover/deduover.conf
ssc.exe -T --nits.spec -o ../out/deletedelete.tst -f ../toast/shadow/delete/delete.conf
ssc.exe -T --nits.spec -o ../out/hardhard.tst -f ../toast/shadow/hard/hard.conf
ssc.exe -T --nits.spec -o ../out/pagespages.tst -f ../toast/shadow/pages/pages.conf
ssc.exe -T --nits.spec -o ../out/softsoft.tst -f ../toast/shadow/soft/soft.conf
ssc.exe -T --nits.spec -o ../out/softoversoftover.tst -f ../toast/shadow/softover/softover.conf
ssc.exe -T --nits.spec -o ../out/ssishssi.tst -f ../toast/shadow/ssi/ssi.conf
ssc.exe -T --nits.spec -o ../out/case.tst -f ../toast/spell/case/spell.conf
ssc.exe -T --nits.spec -o ../out/noicu.tst -f ../toast/spell/noicu/spell.conf
ssc.exe -T --nits.spec -o ../out/spell.tst -f ../toast/spell/spell/spell.conf
ssc.exe -T --nits.spec -o ../out/updateupdate.tst -f ../toast/shadow/update/update.conf
ssc.exe -T --nits.spec -o ../out/snippetconf.tst -f ../toast/snippet/conf/snippet.conf
ssc.exe -T --nits.spec -o ../out/snippetkiwi.tst -f ../toast/snippet/kiwi/snippet.conf
ssc.exe -T --nits.spec -o ../out/detailstats.tst -f ../toast/stats/detail/stats.conf
ssc.exe -T --nits.spec -o ../out/singlestats.tst -f ../toast/stats/single/stats.conf
ssc.exe -T --nits.spec -o ../out/summarystats.tst -f ../toast/stats/summary/stats.conf
ssc.exe -T --nits.spec -o ../out/1.0svg.tst -f ../toast/SVG/1.0/svg.conf
ssc.exe -T --nits.spec -o ../out/1.1svg.tst -f ../toast/SVG/1.1/svg.conf
ssc.exe -T --nits.spec -o ../out/1.2svg.tst -f ../toast/SVG/1.2/svg.conf
ssc.exe -T --nits.spec -o ../out/1.2-fullsvg.tst -f ../toast/SVG/1.2-full/svg.conf
ssc.exe -T --nits.spec -o ../out/2.0svg.tst -f ../toast/SVG/2.0/svg.conf
ssc.exe -T --nits.spec -o ../out/2.1svg.tst -f ../toast/SVG/2.1/svg.conf
ssc.exe -T --nits.spec -o ../out/colourcolour.tst -f ../toast/type/colour/colour.conf
ssc.exe -T --nits.spec -o ../out/customcustom.tst -f ../toast/type/custom/custom.conf
ssc.exe -T --nits.spec -o ../out/httpequivhttpequiv.tst -f ../toast/type/httpequiv/httpequiv.conf
ssc.exe -T --nits.spec -o ../out/langlang.tst -f ../toast/type/lang/lang.conf
ssc.exe -T --nits.spec -o ../out/metanamemetaname.tst -f ../toast/type/metaname/metaname.conf
ssc.exe -T --nits.spec -o ../out/mimetypemimetype.tst -f ../toast/type/mimetype/mimetype.conf
ssc.exe -T --nits.spec -o ../out/sgmlsgml.tst -f ../toast/type/sgml/sgml.conf
ssc.exe -T --nits.spec -o ../out/urlurl.tst -f ../toast/type/url/url.conf
ssc.exe -T --nits.spec -o ../out/w3-3663.tst -f ../toast/w3/3663/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-12458.tst -f ../toast/w3/12458/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-acefh.tst -f ../toast/w3/acefh/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-bogus.tst -f ../toast/w3/bogus/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-charset.tst -f ../toast/w3/charset/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-html20.tst -f ../toast/w3/html20/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-html40.tst -f ../toast/w3/html40/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-html401.tst -f ../toast/w3/html401/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-html5.tst -f ../toast/w3/html5/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-imnop.tst -f ../toast/w3/imnop/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-mathml.tst -f ../toast/w3/mathml/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-rddl.tst -f ../toast/w3/rddl/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-rstuw.tst -f ../toast/w3/rstuw/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-sgml.tst -f ../toast/w3/sgml/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-smil.tst -f ../toast/w3/smil/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-svg.tst -f ../toast/w3/svg/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-text.tst -f ../toast/w3/text/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-xhtml.tst -f ../toast/w3/xhtml/w3.conf
ssc.exe -T --nits.spec -o ../out/w3-xml.tst -f ../toast/w3/xml/w3.conf
ssc.exe -T --nits.spec -o ../out/jan05webapps.tst -f ../toast/webapps/jan05/webapps.conf
ssc.exe -T --nits.spec -o ../out/jul05webapps.tst -f ../toast/webapps/jul05/webapps.conf
ssc.exe -T --nits.spec -o ../out/jan06webapps.tst -f ../toast/webapps/jan06/webapps.conf
ssc.exe -T --nits.spec -o ../out/jul06webapps.tst -f ../toast/webapps/jul06/webapps.conf
ssc.exe -T --nits.spec -o ../out/jan07webapps.tst -f ../toast/webapps/jan07/webapps.conf
ssc.exe -T --nits.spec -o ../out/1.0xhtml1.tst -f ../toast/XHTML/1.0/xhtml1.conf
ssc.exe -T --nits.spec -o ../out/1.1xhtml11.tst -f ../toast/XHTML/1.1/xhtml11.conf
ssc.exe -T --nits.spec -o ../out/2.0xhtml2.tst -f ../toast/XHTML/2.0/xhtml2.conf
ssc.exe -T --nits.spec -o ../out/outputhtml.tst -f ../toast/output/html/output.conf
ssc.exe -T --nits.spec -o ../out/outputout.tst -f ../toast/output/out/output.conf
ssc.exe -T --nits.spec -o ../out/outputtest.tst -f ../toast/output/test/output.conf
ssc.exe -T --nits.spec -o ../out/outputtext.tst -f ../toast/output/text/output.conf
ssc.exe -T --nits.spec -o ../out/outputxhtml.tst -f ../toast/output/xhtml/output.conf
