ssc.exe -T -Z -o ../out/1csp.tst -f ../toast/csp/1/csp.conf
ssc.exe -T -Z -o ../out/2csp.tst -f ../toast/csp/2/csp.conf
ssc.exe -T -Z -o ../out/3csp.tst -f ../toast/csp/3/csp.conf
ssc.exe -T -Z -o ../out/1.0html1.tst -f ../toast/HTML/1.0/html1.conf
ssc.exe -T -Z -o ../out/2.0html2.tst -f ../toast/HTML/2.0/html2.conf
ssc.exe -T -Z -o ../out/3.0html3.tst -f ../toast/HTML/3.0/html3.conf
ssc.exe -T -Z -o ../out/3.2html32.tst -f ../toast/HTML/3.2/html32.conf
ssc.exe -T -Z -o ../out/4.00html4.tst -f ../toast/HTML/4.00/html4.conf
ssc.exe -T -Z -o ../out/4.01html4.tst -f ../toast/HTML/4.01/html4.conf
ssc.exe -T -Z -o ../out/5.0html5.tst -f ../toast/HTML/5.0/html5.conf
ssc.exe -T -Z -o ../out/5.1html5.tst -f ../toast/HTML/5.1/html5.conf
ssc.exe -T -Z -o ../out/5.2html5.tst -f ../toast/HTML/5.2/html5.conf
ssc.exe -T -Z -o ../out/5.3html5.tst -f ../toast/HTML/5.3/html5.conf
ssc.exe -T -Z -o ../out/5.4html5.tst -f ../toast/HTML/5.4/html5.conf
ssc.exe -T -Z -o ../out/minimalminimal.tst -f ../toast/HTML/minimal/minimal.conf
ssc.exe -T -Z -o ../out/Plusplus.tst -f ../toast/HTML/Plus/plus.conf
ssc.exe -T -Z -o ../out/tagstags.tst -f ../toast/HTML/tags/tags.conf
ssc.exe -T -Z -o ../out/linklink.tst -f ../toast/link/link.conf
ssc.exe -T -Z -o ../out/jul07living.tst -f ../toast/living/jul07/living.conf
ssc.exe -T -Z -o ../out/jan08living.tst -f ../toast/living/jan08/living.conf
ssc.exe -T -Z -o ../out/jul08living.tst -f ../toast/living/jul08/living.conf
ssc.exe -T -Z -o ../out/jan09living.tst -f ../toast/living/jan09/living.conf
ssc.exe -T -Z -o ../out/jul09living.tst -f ../toast/living/jul09/living.conf
ssc.exe -T -Z -o ../out/jan10living.tst -f ../toast/living/jan10/living.conf
ssc.exe -T -Z -o ../out/jul10living.tst -f ../toast/living/jul10/living.conf
ssc.exe -T -Z -o ../out/jan11living.tst -f ../toast/living/jan11/living.conf
ssc.exe -T -Z -o ../out/jul11living.tst -f ../toast/living/jul11/living.conf
ssc.exe -T -Z -o ../out/jan12living.tst -f ../toast/living/jan12/living.conf
ssc.exe -T -Z -o ../out/jul12living.tst -f ../toast/living/jul12/living.conf
ssc.exe -T -Z -o ../out/jan13living.tst -f ../toast/living/jan13/living.conf
ssc.exe -T -Z -o ../out/jul13living.tst -f ../toast/living/jul13/living.conf
ssc.exe -T -Z -o ../out/jan14living.tst -f ../toast/living/jan14/living.conf
ssc.exe -T -Z -o ../out/jul14living.tst -f ../toast/living/jul14/living.conf
ssc.exe -T -Z -o ../out/jan15living.tst -f ../toast/living/jan15/living.conf
ssc.exe -T -Z -o ../out/jul15living.tst -f ../toast/living/jul15/living.conf
ssc.exe -T -Z -o ../out/jan16living.tst -f ../toast/living/jan16/living.conf
ssc.exe -T -Z -o ../out/jul16living.tst -f ../toast/living/jul16/living.conf
ssc.exe -T -Z -o ../out/jan17living.tst -f ../toast/living/jan17/living.conf
ssc.exe -T -Z -o ../out/jul17living.tst -f ../toast/living/jul17/living.conf
ssc.exe -T -Z -o ../out/jan18living.tst -f ../toast/living/jan18/living.conf
ssc.exe -T -Z -o ../out/jul18living.tst -f ../toast/living/jul18/living.conf
ssc.exe -T -Z -o ../out/jan19living.tst -f ../toast/living/jan19/living.conf
ssc.exe -T -Z -o ../out/jul19living.tst -f ../toast/living/jul19/living.conf
ssc.exe -T -Z -o ../out/jan20living.tst -f ../toast/living/jan20/living.conf
ssc.exe -T -Z -o ../out/jul20living.tst -f ../toast/living/jul20/living.conf
ssc.exe -T -Z -o ../out/jan21living.tst -f ../toast/living/jan21/living.conf
ssc.exe -T -Z -o ../out/1math.tst -f ../toast/math/1/math.conf
ssc.exe -T -Z -o ../out/2math.tst -f ../toast/math/2/math.conf
ssc.exe -T -Z -o ../out/3math.tst -f ../toast/math/3/math.conf
ssc.exe -T -Z -o ../out/12schema.tst -f ../toast/microdata/12/schema.conf
ssc.exe -T -Z -o ../out/addendumadd.tst -f ../toast/microdata/addendum/add.conf
ssc.exe -T -Z -o ../out/basicbasic.tst -f ../toast/microdata/basic/basic.conf
ssc.exe -T -Z -o ../out/exportexport.tst -f ../toast/microdata/export/export.conf
ssc.exe -T -Z -o ../out/microdatamf.tst -f ../toast/microdata/microformats/mf.conf
ssc.exe -T -Z -o ../out/schema-abcabc.tst -f ../toast/microdata/schema-abc/abc.conf
ssc.exe -T -Z -o ../out/schema-defgdefg.tst -f ../toast/microdata/schema-defg/defg.conf
ssc.exe -T -Z -o ../out/schema-hijklhijkl.tst -f ../toast/microdata/schema-hijkl/hijkl.conf
ssc.exe -T -Z -o ../out/schema-mnomno.tst -f ../toast/microdata/schema-mno/mno.conf
ssc.exe -T -Z -o ../out/schema-pqrspqrs.tst -f ../toast/microdata/schema-pqrs/pqrs.conf
ssc.exe -T -Z -o ../out/schema-tuvtuv.tst -f ../toast/microdata/schema-tuv/tuv.conf
ssc.exe -T -Z -o ../out/schema-wxyzwxyz.tst -f ../toast/microdata/schema-wxyz/wxyz.conf
ssc.exe -T -Z -o ../out/mf1mf1.tst -f ../toast/microformats/mf1/mf1.conf
ssc.exe -T -Z -o ../out/mf2mf2.tst -f ../toast/microformats/mf2/mf2.conf
ssc.exe -T -Z -o ../out/relrel.tst -f ../toast/microformats/rel/rel.conf
ssc.exe -T -Z -o ../out/abbrabbr.tst -f ../toast/other/abbr/abbr.conf
ssc.exe -T -Z -o ../out/basebase.tst -f ../toast/other/base/base.conf
ssc.exe -T -Z -o ../out/CSScss.tst -f ../toast/other/CSS/css.conf
ssc.exe -T -Z -o ../out/dfndfn.tst -f ../toast/other/dfn/dfn.conf
ssc.exe -T -Z -o ../out/ignoreignore.tst -f ../toast/other/ignore/ignore.conf
ssc.exe -T -Z -o ../out/incorrectnessincorrectness.tst -f ../toast/other/incorrectness/incorrectness.conf
ssc.exe -T -Z -o ../out/nitsnits.tst -f ../toast/other/nits/nits.conf
ssc.exe -T -Z -o ../out/parsingparsing.tst -f ../toast/other/parsing/parsing.conf
ssc.exe -T -Z -o ../out/RDFrdf.tst -f ../toast/other/pattern/pattern.conf
ssc.exe -T -Z -o ../out/RDFrdf.tst -f ../toast/other/RDF/rdf.conf
ssc.exe -T -Z -o ../out/simplesimple.tst -f ../toast/other/simple/simple.conf
ssc.exe -T -Z -o ../out/ssissi.tst -f ../toast/other/ssi/ssi.conf
ssc.exe -T -Z -o ../out/commentcomment.tst -f ../toast/shadow/comment/comment.conf
ssc.exe -T -Z -o ../out/copycopy.tst -f ../toast/shadow/copy/copy.conf
ssc.exe -T -Z -o ../out/copyovercopyover.tst -f ../toast/shadow/copyover/copyover.conf
ssc.exe -T -Z -o ../out/dedudedu.tst -f ../toast/shadow/dedu/dedu.conf
ssc.exe -T -Z -o ../out/deduoverdeduover.tst -f ../toast/shadow/deduover/deduover.conf
ssc.exe -T -Z -o ../out/hardhard.tst -f ../toast/shadow/hard/hard.conf
ssc.exe -T -Z -o ../out/pagespages.tst -f ../toast/shadow/pages/pages.conf
ssc.exe -T -Z -o ../out/softsoft.tst -f ../toast/shadow/soft/soft.conf
ssc.exe -T -Z -o ../out/softoversoftover.tst -f ../toast/shadow/softover/softover.conf
ssc.exe -T -Z -o ../out/ssissi.tst -f ../toast/shadow/ssi/ssi.conf
ssc.exe -T -Z -o ../out/1.0svg.tst -f ../toast/SVG/1.0/svg.conf
ssc.exe -T -Z -o ../out/1.1svg.tst -f ../toast/SVG/1.1/svg.conf
ssc.exe -T -Z -o ../out/detailstats.tst -f ../toast/stats/detail/stats.conf
ssc.exe -T -Z -o ../out/singlestats.tst -f ../toast/stats/single/stats.conf
ssc.exe -T -Z -o ../out/summarystats.tst -f ../toast/stats/summary/stats.conf
ssc.exe -T -Z -o ../out/colourcolour.tst -f ../toast/type/colour/colour.conf
ssc.exe -T -Z -o ../out/httpequivhttpequiv.tst -f ../toast/type/httpequiv/httpequiv.conf
ssc.exe -T -Z -o ../out/langlang.tst -f ../toast/type/lang/lang.conf
ssc.exe -T -Z -o ../out/metanamemetaname.tst -f ../toast/type/metaname/metaname.conf
ssc.exe -T -Z -o ../out/mimetypemimetype.tst -f ../toast/type/mimetype/mimetype.conf
ssc.exe -T -Z -o ../out/sgmlsgml.tst -f ../toast/type/sgml/sgml.conf
ssc.exe -T -Z -o ../out/urlurl.tst -f ../toast/type/url/url.conf
ssc.exe -T -Z -o ../out/w3-3663.tst -f ../toast/w3/3663/w3.conf
ssc.exe -T -Z -o ../out/w3-12458.tst -f ../toast/w3/12458/w3.conf
ssc.exe -T -Z -o ../out/w3-acefh.tst -f ../toast/w3/acefh/w3.conf
ssc.exe -T -Z -o ../out/w3-bogus.tst -f ../toast/w3/bogus/w3.conf
ssc.exe -T -Z -o ../out/w3-charset.tst -f ../toast/w3/charset/w3.conf
ssc.exe -T -Z -o ../out/w3-html20.tst -f ../toast/w3/html20/w3.conf
ssc.exe -T -Z -o ../out/w3-html40.tst -f ../toast/w3/html40/w3.conf
ssc.exe -T -Z -o ../out/w3-html401.tst -f ../toast/w3/html401/w3.conf
ssc.exe -T -Z -o ../out/w3-html5.tst -f ../toast/w3/html5/w3.conf
ssc.exe -T -Z -o ../out/w3-imnop.tst -f ../toast/w3/imnop/w3.conf
ssc.exe -T -Z -o ../out/w3-mathml.tst -f ../toast/w3/mathml/w3.conf
ssc.exe -T -Z -o ../out/w3-rddl.tst -f ../toast/w3/rddl/w3.conf
ssc.exe -T -Z -o ../out/w3-rstuw.tst -f ../toast/w3/rstuw/w3.conf
ssc.exe -T -Z -o ../out/w3-sgml.tst -f ../toast/w3/sgml/w3.conf
ssc.exe -T -Z -o ../out/w3-smil.tst -f ../toast/w3/smil/w3.conf
ssc.exe -T -Z -o ../out/w3-svg.tst -f ../toast/w3/svg/w3.conf
ssc.exe -T -Z -o ../out/w3-text.tst -f ../toast/w3/text/w3.conf
ssc.exe -T -Z -o ../out/w3-xhtml.tst -f ../toast/w3/xhtml/w3.conf
ssc.exe -T -Z -o ../out/w3-xml.tst -f ../toast/w3/xml/w3.conf
ssc.exe -T -Z -o ../out/jan05webapps.tst -f ../toast/webapps/jan05/webapps.conf
ssc.exe -T -Z -o ../out/jul05webapps.tst -f ../toast/webapps/jul05/webapps.conf
ssc.exe -T -Z -o ../out/jan06webapps.tst -f ../toast/webapps/jan06/webapps.conf
ssc.exe -T -Z -o ../out/jul06webapps.tst -f ../toast/webapps/jul06/webapps.conf
ssc.exe -T -Z -o ../out/jan07webapps.tst -f ../toast/webapps/jan07/webapps.conf
ssc.exe -T -Z -o ../out/1.0xhtml1.tst -f ../toast/XHTML/1.0/xhtml1.conf
ssc.exe -T -Z -o ../out/1.1xhtml11.tst -f ../toast/XHTML/1.1/xhtml11.conf
ssc.exe -T -Z -o ../out/2.0xhtml2.tst -f ../toast/XHTML/2.0/xhtml2.conf

