[general]
verbose=5
output=../out/apr24.out
class=true

[html]
version=2024/04/01

[nits]
nids=

[link]
check=

[ontology]
schema=26.0

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/living/apr24

[validation]
element=labeled-checkbox
element=question-box
