[general]
verbose=info
output=../out/ads.out
class=
ads=

[html]
version=2025/09/01

[link]
check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/other/ads

[spell]
no-check=true
