[general]
verbose=5
output=../out/css3shader.out
class=

[css]
verify=
extension=css
version=2.1
shader=3

[html]
analysis=dec25
version=2026/04/01

[link]
no-check=

[nits]
nids=

[site]
domain=example.com
extension=html
index=index.html
root=../toast/css/3-shader

[spell]
no-check=
