[general]
verbose=5
output=../out/ruby.out
class=

[css]
verify=
extension=css
version=3
no-external=

[html]
version=2024/05/01
ruby=

[link]
check=

[nits]
nids=

[site]
domain=example.edu
extension=html
extension=xhtml
index=index.html
root=../toast/other/ruby

[spell]
no-check=true
