-N 1 -f ../toast/RDFa/gr/rdfa.conf

PASS ../toast/RDFa/gr/example-1.html
40 invalid_attribute_version wrong_version
72 invalid_attribute_version wrong_version
77 requires_itemscope
112 requires_itemscope bad_itemid
132 requires_itemscope bad_itemid
143 ontology_domain
158 invalid_attribute_version wrong_version
163 missing_close
164 use_quote_code
167 unknown_protocol no_itemscope
168 unknown_protocol no_itemscope
169 unknown_protocol no_itemscope
173 unrecognised_value unknown_rel
206 data_vocabulary data_vocabulary
221 use_quote_code
240 requires_itemscope bad_itemid
276 requires_itemscope bad_itemid
290 double_angular_open
295 requires_itemscope bad_itemid
301 double_angular_open
315 requires_itemscope
348 ontology_domain
352 ontology_domain
360 unknown_protocol no_itemscope
362 not_ontology_property bad_property
405 requires_itemscope
408 use_quote_code
411 url_not_found
413 invalid_attribute_version wrong_version
416 missing_close requires_itemscope bad_itemid
421 missing_close
444 missing_close
455 missing_close
467 missing_close
481 missing_close
492 missing_close
494 inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure

itemids
#offer
#product
#product_data
