-f ../toast/living/jul13/living.conf

PASS ../toast/living/jul13/a.html
9 url_not_found
10 chocolate_teapot
11 url_not_found
15 unrecognised_value

PASS ../toast/living/jul13/abbr.html
17 id_exists
35 naughty_grave

PASS ../toast/living/jul13/address.html
0 charset_mismatch charset_used charset_invalid
11 attempted_escape no_such_folder url_not_found
12 attempted_escape no_such_folder url_not_found
13 url_not_found

PASS ../toast/living/jul13/aside.html
0 charset_mismatch charset_used charset_invalid
19 use_quote_code
22 use_quote_code
25 use_quote_code

PASS ../toast/living/jul13/aside-2.html
0 charset_mismatch charset_used charset_invalid
16 missing_close
17 inserted_missing_closure
22 url_not_found
23 inserted_missing_closure missing_close url_not_found
24 inserted_missing_closure
32 use_quote_code
35 use_quote_code
43 missing_close url_not_found
44 inserted_missing_closure
57 use_quote_code
60 missing_close url_not_found
61 inserted_missing_closure
65 url_not_found
66 url_not_found
67 url_not_found

PASS ../toast/living/jul13/b.html
0 charset_mismatch charset_used charset_invalid
12 use_quote_code

PASS ../toast/living/jul13/blockquote.html
0 charset_mismatch charset_used charset_invalid
7 missing_close
8 use_quote_code
12 inserted_missing_closure
21 use_quote_code
27 use_quote_code
30 use_quote_code
44 use_quote_code
50 use_double_quote_code
60 inserted_missing_closure
69 use_quote_code
71 use_double_quote_code
72 use_double_quote_code
87 inserted_missing_closure

PASS ../toast/living/jul13/canvas3.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close

PASS ../toast/living/jul13/caption.html
9 inserted_missing_closure missing_close
13 inserted_missing_closure

PASS ../toast/living/jul13/data.html
10 unrecognised_value
11 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
12 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul13/datalist.html
11 inserted_missing_closure missing_close
12 inserted_missing_closure
19 id_exists
24 inserted_missing_closure
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jul13/dd.html
0 charset_mismatch charset_used charset_invalid
8 unrecognised_value use_quote_code
9 unrecognised_value
13 unrecognised_value use_quote_code
14 unrecognised_value
16 unrecognised_value

PASS ../toast/living/jul13/del.html
9 use_quote_code

PASS ../toast/living/jul13/details.html
0 charset_mismatch charset_used charset_invalid
6 unrecognised_value unrecognised_value
7 use_double_quote_code
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jul13/dfn.html
9 use_quote_code
15 use_quote_code

PASS ../toast/living/jul13/div.html
10 use_quote_code
18 use_quote_code use_double_quote_code
20 use_double_quote_code

PASS ../toast/living/jul13/dl.html
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
54 use_quote_code

PASS ../toast/living/jul13/el.html
9 use_quote_code
13 use_quote_code
27 missing_close
28 inserted_missing_closure

PASS ../toast/living/jul13/embed.html
6 reputation url_not_found
8 wild_attribute reputation wild_attribute url_not_found
10 reputation url_not_found

PASS ../toast/living/jul13/et.html
8 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
10 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure
17 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
18 no_such_folder url_not_found
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
20 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
21 no_such_folder url_not_found
22 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
23 no_such_folder url_not_found
24 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
25 no_such_folder url_not_found
26 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul13/example.html
6 missing_close inserted_missing_closure missing_open
10 url_not_found
28 url_not_found
29 inserted_missing_closure url_not_found
30 inserted_missing_closure missing_close url_not_found
31 inserted_missing_closure
33 url_not_found
44 url_not_found
53 inserted_missing_closure inserted_missing_closure
54 inserted_missing_closure inserted_missing_closure
55 inserted_missing_closure inserted_missing_closure
66 inserted_missing_closure inserted_missing_closure missing_open
68 inserted_missing_closure unrecognised_value
70 input_bad_aria
72 inserted_missing_closure
78 attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute
88 unrecognised_value no_such_folder url_not_found
98 attribute_unrecognised unrecognised_attribute unrecognised_value
100 unrecognised_value
103 unrecognised_namespace unknown_element
106 unknown_element
110 newline_in_string newline_in_string
112 unrecognised_value
113 use_double_quote_code use_quote_code
114 unrecognised_value
115 inserted_missing_closure unrecognised_value
116 unrecognised_value
117 use_quote_code use_double_quote_code inserted_missing_closure unrecognised_value use_double_quote_code
118 unrecognised_value use_double_quote_code
121 newline_in_string newline_in_string
122 newline_in_string newline_in_string
127 only_elements
131 unrecognised_value
133 unrecognised_value
138 data_type attribute_required attribute_required attribute_required
156 url_not_found
162 use_quote_code
165 url_not_found
166 url_not_found
167 missing_close url_not_found
172 use_double_quote_code inserted_missing_closure
177 url_not_found
180 url_not_found
181 inserted_missing_closure missing_close
182 inserted_missing_closure
186 use_quote_code
191 url_not_found
194 url_not_found
195 inserted_missing_closure missing_close
196 inserted_missing_closure
199 use_quote_code
209 use_quote_code naughty_grave naughty_grave naughty_grave naughty_grave naughty_grave naughty_grave
211 use_double_quote_code
213 use_double_quote_code

PASS ../toast/living/jul13/example-2.html
4 url_not_found style_not_css
5 url_not_found
6 url_not_found
9 url_not_found
11 url_not_found
13 url_not_found
15 url_not_found
16 url_not_found
17 url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 no_such_folder url_not_found
22 no_such_folder url_not_found
23 no_such_folder url_not_found
24 no_such_folder url_not_found
33 url_not_found
34 mime
48 use_quote_code
62 use_quote_code
107 unrecognised_value
122 use_quote_code
132 use_quote_code

PASS ../toast/living/jul13/fieldset.html
12 pattern
27 pattern
34 pattern
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure missing_close
47 inserted_missing_closure missing_close
48 inserted_missing_closure
49 inserted_missing_closure

PASS ../toast/living/jul13/figure.html
21 newline_in_string newline_in_string url_not_found
25 use_quote_code
29 use_double_quote_code inserted_missing_closure
30 url_not_found
35 inserted_missing_closure
36 url_not_found
40 url_not_found
45 inserted_missing_closure
46 use_quote_code
55 url_not_found
57 url_not_found
60 newline_in_string newline_in_string url_not_found
67 url_not_found
69 url_not_found
71 url_not_found

PASS ../toast/living/jul13/footer.html
2 naughty_lang
9 attempted_escape
18 attempted_escape

PASS ../toast/living/jul13/footer-2.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang
4 inserted_missing_closure
8 no_such_folder url_not_found
9 no_such_folder url_not_found
26 url_not_found
27 url_not_found

PASS ../toast/living/jul13/footer-3.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang
13 no_such_folder url_not_found naughty_alt
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 attribute_required no_such_folder url_not_found naughty_alt
19 no_such_folder url_not_found
21 attribute_required no_such_folder url_not_found naughty_alt
23 use_quote_code no_such_folder url_not_found
26 url_not_found
27 inserted_missing_closure url_not_found
28 inserted_missing_closure missing_close url_not_found
29 inserted_missing_closure
32 url_not_found

PASS ../toast/living/jul13/formex.html
15 url_not_found
21 url_not_found
23 missing_close inserted_missing_closure
35 inserted_missing_closure
36 inserted_missing_closure missing_close
37 inserted_missing_closure
41 inserted_missing_closure
42 inserted_missing_closure missing_close
43 inserted_missing_closure
50 invalid_attribute_version wrong_version
52 inserted_missing_closure
54 inserted_missing_closure
55 inserted_missing_closure missing_close
57 inserted_missing_closure
79 url_not_found
85 url_not_found

PASS ../toast/living/jul13/forms.html
119 inserted_missing_closure missing_close
120 inserted_missing_closure
144 inserted_missing_closure missing_close
145 inserted_missing_closure
169 inserted_missing_closure missing_close
170 inserted_missing_closure
195 inserted_missing_closure missing_close
196 inserted_missing_closure
249 unrecognised_value
254 inserted_missing_closure use_quote_code
255 inserted_missing_closure
257 use_double_quote_code inserted_missing_closure
259 inserted_missing_closure use_quote_code unrecognised_value
260 inserted_missing_closure
262 use_double_quote_code inserted_missing_closure missing_close
267 inserted_missing_closure

PASS ../toast/living/jul13/h-1.html
6 use_quote_code

PASS ../toast/living/jul13/h-2.html
6 use_quote_code

PASS ../toast/living/jul13/header.html
2 naughty_lang
31 url_id_unfound
33 unrecognised_value

PASS ../toast/living/jul13/header-2.html
2 naughty_lang
14 url_not_found
15 inserted_missing_closure url_not_found
16 inserted_missing_closure missing_close url_not_found
17 inserted_missing_closure
21 use_quote_code

PASS ../toast/living/jul13/hr.html
17 use_quote_code
47 use_quote_code
49 use_quote_code
58 use_quote_code

PASS ../toast/living/jul13/hs-7.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
18 inserted_missing_closure
19 use_quote_code

PASS ../toast/living/jul13/hs-8.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
31 inserted_missing_closure
33 use_quote_code

PASS ../toast/living/jul13/hs-9.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close

PASS ../toast/living/jul13/hs-10.html
0 title_required
5 use_double_quote_code inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close

PASS ../toast/living/jul13/hs-11.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close long_title
3 inserted_missing_parent inserted_missing_closure missing_close
5 use_quote_code

PASS ../toast/living/jul13/hs-12.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close long_title use_quote_code
3 inserted_missing_parent inserted_missing_closure missing_close use_quote_code
11 use_quote_code
13 wrong_parent
16 use_quote_code

PASS ../toast/living/jul13/hs-13.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
16 use_quote_code

PASS ../toast/living/jul13/i.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jul13/iframe.html
9 missing_close
14 use_quote_code
16 missing_close no_such_folder url_not_found
17 inserted_missing_closure
19 no_such_folder url_not_found
20 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
23 no_such_folder url_not_found
24 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1 mixed_mess missing_open
27 no_such_folder url_not_found
28 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
31 use_quote_code
32 url_not_found
35 overallowed
37 url_not_found
39 url_not_found
41 url_not_found
43 url_not_found
48 inserted_missing_closure

PASS ../toast/living/jul13/iframe-2.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
7 url_not_found

PASS ../toast/living/jul13/im.html
8 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found

PASS ../toast/living/jul13/img.html
6 url_not_found naughty_alt
8 url_not_found
11 url_not_found
15 url_not_found naughty_alt
18 inserted_missing_closure
21 newline_in_string url_not_found
25 use_quote_code
31 url_not_found
32 use_quote_code
43 newline_in_string newline_in_string url_not_found
45 use_quote_code
51 use_quote_code
52 url_not_found
61 url_not_found naughty_alt
67 url_not_found url_not_found
68 url_not_found url_not_found
69 url_not_found url_not_found
72 interactive url_not_found url_not_found naughty_alt url_not_found naughty_alt
73 interactive url_not_found url_not_found naughty_alt url_not_found naughty_alt
74 url_not_found naughty_alt
76 interactive url_not_found url_not_found
77 url_not_found
78 interactive url_not_found
79 url_not_found url_not_found url_not_found
81 interactive url_not_found
82 url_not_found naughty_alt url_not_found naughty_alt
83 interactive url_not_found
84 url_not_found naughty_alt url_not_found naughty_alt url_not_found naughty_alt
92 newline_in_string no_such_folder url_not_found
98 newline_in_string newline_in_string url_not_found
105 url_not_found
111 no_such_folder url_not_found no_such_folder url_not_found naughty_alt
112 no_such_folder url_not_found no_such_folder url_not_found naughty_alt
119 url_not_found
127 url_not_found
132 use_quote_code
135 url_not_found
140 url_not_found naughty_alt
143 url_not_found naughty_alt
151 newline_in_string no_such_folder url_not_found
157 use_quote_code
159 url_not_found
166 no_such_folder url_not_found naughty_alt
175 no_such_folder url_not_found naughty_alt
189 newline_in_string newline_in_string no_such_folder url_not_found
201 no_such_folder url_not_found
208 url_not_found naughty_alt
211 url_not_found naughty_alt
216 use_quote_code
222 url_not_found url_not_found naughty_alt
225 url_not_found url_not_found naughty_alt
225 url_not_found naughty_alt
226 url_not_found naughty_alt url_not_found naughty_alt
231 url_not_found
233 url_not_found naughty_alt url_not_found
245 newline_in_string newline_in_string url_not_found
252 newline_in_string newline_in_string url_not_found
260 newline_in_string newline_in_string no_such_folder url_not_found
268 newline_in_string newline_in_string no_such_folder url_not_found
277 newline_in_string newline_in_string url_not_found
280 attribute_required url_not_found
286 attribute_required url_not_found naughty_alt
293 attribute_required url_not_found
308 newline_in_string newline_in_string url_not_found
314 attribute_required url_not_found naughty_alt
321 wrong_parent inserted_missing_closure
322 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
324 attribute_required url_not_found naughty_alt
325 wrong_parent inserted_missing_closure
326 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
327 attribute_required url_not_found naughty_alt
328 wrong_parent inserted_missing_closure missing_close
329 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul13/index.html
3 attribute_unrecognised_here unrecognised_attribute

PASS ../toast/living/jul13/input.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure missing_close
14 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure
29 inserted_missing_closure
30 inserted_missing_closure
31 inserted_missing_closure
32 inserted_missing_closure missing_close
33 inserted_missing_closure
38 inserted_missing_closure
39 inserted_missing_closure
40 inserted_missing_closure missing_close
41 inserted_missing_closure
60 inserted_missing_closure missing_close
61 inserted_missing_closure
69 inserted_missing_closure missing_close
71 inserted_missing_closure
80 id_exists
85 inserted_missing_closure
86 inserted_missing_closure missing_close
88 inserted_missing_closure
93 url_not_found
95 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
96 inserted_missing_closure wrong_parent inserted_missing_closure
98 wrong_parent inserted_missing_closure
99 wrong_parent inserted_missing_closure
100 wrong_parent inserted_missing_closure bad_form
101 inserted_missing_closure wrong_parent inserted_missing_closure
103 wrong_parent inserted_missing_closure
104 wrong_parent inserted_missing_closure
105 wrong_parent inserted_missing_closure bad_form
106 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
107 pattern
108 wrong_parent inserted_missing_closure
109 wrong_parent inserted_missing_closure
110 wrong_parent inserted_missing_closure missing_close bad_form
111 inserted_missing_closure inserted_missing_closure
112 bad_form
117 url_not_found
121 inserted_missing_closure
124 inserted_missing_closure
127 inserted_missing_closure missing_close
129 inserted_missing_closure
137 inserted_missing_closure
138 inserted_missing_closure
139 inserted_missing_closure missing_close
140 inserted_missing_closure
166 url_not_found
177 inserted_missing_closure missing_close
178 inserted_missing_closure
182 url_not_found
183 url_not_found naughty_alt
188 placeholder
189 placeholder
191 placeholder
192 placeholder

PASS ../toast/living/jul13/keygen.html
6 url_not_found

PASS ../toast/living/jul13/li.html
7 inserted_missing_parent missing_close
10 lingo
11 use_quote_code
20 inserted_missing_closure
23 inserted_missing_parent missing_close
26 lingo
27 use_quote_code
36 inserted_missing_closure

PASS ../toast/living/jul13/links-alternate.html
5 url_not_found
6 url_not_found
15 url_not_found
16 url_not_found
19 url_not_found

PASS ../toast/living/jul13/links-bookmark.html
13 use_quote_code
20 url_not_found

PASS ../toast/living/jul13/links-help.html
10 no_such_folder url_not_found

PASS ../toast/living/jul13/links-icon.html
5 url_not_found
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found

PASS ../toast/living/jul13/links-licence.html
0 charset_mismatch charset_used charset_invalid
5 no_such_folder url_not_found
10 attempted_escape
13 attribute_required no_such_folder url_not_found
19 attempted_escape

PASS ../toast/living/jul13/links-tag2.html
19 unrecognised_value

PASS ../toast/living/jul13/ls1.html
2 naughty_lang

PASS ../toast/living/jul13/ls2.html
2 naughty_lang

PASS ../toast/living/jul13/ls3.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jul13/ls4.html
0 charset_mismatch charset_used charset_invalid
6 missing_open

PASS ../toast/living/jul13/ls5.html
2 naughty_lang

PASS ../toast/living/jul13/ls6.html
3 contradictory_namespace naughty_lang
5 use_quote_code
6 unknown_element
8 unrecognised_namespace unknown_element attribute_unrecognised
9 unknown_element unknown_element
10 unknown_element attribute_unrecognised
11 unknown_element unknown_element
12 unknown_element
13 unknown_element
19 missing_open
20 missing_open
21 missing_open

PASS ../toast/living/jul13/ls8.html
2 naughty_lang

PASS ../toast/living/jul13/ls9.html
2 naughty_lang
5 element_offsite_base

PASS ../toast/living/jul13/ls10.html
4 long_title
5 element_offsite_base

PASS ../toast/living/jul13/ls11.html
2 naughty_lang

PASS ../toast/living/jul13/ls12.html
12 use_quote_code

PASS ../toast/living/jul13/ls14.html
3 naughty_lang

PASS ../toast/living/jul13/ls15.html
0 charset_mismatch charset_used charset_invalid
9 url_not_found
10 url_not_found
11 url_not_found
16 url_not_found
17 url_not_found
18 url_not_found
23 not_schema_property unrecognised_value bad_itemprop
42 url_not_found
43 url_not_found
44 url_not_found

PASS ../toast/living/jul13/ls16.html
0 charset_mismatch charset_used charset_invalid
11 url_not_found
13 only_elements
25 only_elements

PASS ../toast/living/jul13/main.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
13 inserted_missing_parent inserted_missing_closure missing_close
17 attempted_escape no_such_folder url_not_found
18 attempted_escape no_such_folder url_not_found
21 missing_close
22 use_quote_code inserted_missing_closure
32 missing_close
33 inserted_missing_closure

PASS ../toast/living/jul13/map.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
7 no_such_folder url_not_found
12 missing_close
13 no_such_folder url_not_found
14 no_such_folder url_not_found
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 no_such_folder url_not_found
18 no_such_folder url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 inserted_missing_closure

PASS ../toast/living/jul13/mark.html
9 use_quote_code
16 use_quote_code
25 unrecognised_value unrecognised_value
27 unrecognised_value
28 unrecognised_value unrecognised_value
29 unrecognised_value
46 use_quote_code
48 use_quote_code
51 use_quote_code

PASS ../toast/living/jul13/math.html
2 naughty_lang

PASS ../toast/living/jul13/me.html
7 url_not_found
65 url_not_found autoplay
66 url_not_found autoplay
89 url_not_found autoplay
91 url_not_found

PASS ../toast/living/jul13/menu.html
8 unrecognised_value
9 inserted_missing_closure id_exists
17 unrecognised_value
18 inserted_missing_closure id_exists
21 only_elements
27 unrecognised_value
28 inserted_missing_closure id_exists

PASS ../toast/living/jul13/meter.html
7 url_not_found
10 bad_meter
11 bad_meter
16 inserted_missing_closure
17 inserted_missing_closure inserted_missing_closure missing_close
18 inserted_missing_closure
21 inserted_missing_closure
22 inserted_missing_closure inserted_missing_closure missing_close
23 inserted_missing_closure
26 menu_child
27 inserted_missing_closure
28 missing_open
31 no_such_folder url_not_found
32 no_such_folder url_not_found
37 no_such_folder url_not_found
38 no_such_folder url_not_found
43 no_such_folder url_not_found
44 no_such_folder url_not_found

PASS ../toast/living/jul13/noscript.html
6 url_not_found
27 url_not_found
30 id_exists

PASS ../toast/living/jul13/object.html
15 url_not_found
20 reputation

PASS ../toast/living/jul13/ol.html
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure missing_close
13 inserted_missing_closure
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure

PASS ../toast/living/jul13/optgroup.html
6 url_not_found
8 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure
16 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure inserted_missing_closure missing_close
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure

PASS ../toast/living/jul13/p.html
48 inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure
56 inserted_missing_closure
57 inserted_missing_closure missing_close
58 inserted_missing_closure

PASS ../toast/living/jul13/param.html
9 mime
16 newline_in_string newline_in_string url_not_found
21 url_not_found

PASS ../toast/living/jul13/q.html
7 use_double_quote_code
10 use_quote_code
12 use_double_quote_code
16 use_double_quote_code use_quote_code
17 use_double_quote_code
23 use_double_quote_code use_quote_code

PASS ../toast/living/jul13/ruby.html
10 missing_close inserted_missing_closure
12 missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close
13 inserted_missing_closure
15 missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure
18 missing_close inserted_missing_closure
26 missing_close inserted_missing_closure
28 missing_close inserted_missing_closure
30 missing_close inserted_missing_closure
32 missing_close inserted_missing_closure
34 inserted_missing_closure missing_close inserted_missing_closure
35 inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
36 inserted_missing_closure missing_close inserted_missing_closure
39 inserted_missing_closure
40 inserted_missing_closure inserted_missing_closure
41 inserted_missing_closure inserted_missing_closure missing_close
42 inserted_missing_closure
44 missing_close inserted_missing_closure
59 missing_close
60 inserted_missing_closure

PASS ../toast/living/jul13/samp.html
7 use_quote_code
9 unrecognised_value
13 unrecognised_value unrecognised_value

PASS ../toast/living/jul13/script.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 mime
37 use_double_quote_code

PASS ../toast/living/jul13/select.html
17 bad_select
40 inserted_missing_closure
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure
44 inserted_missing_closure
45 inserted_missing_closure
46 inserted_missing_closure
47 inserted_missing_closure
48 use_quote_code inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure

PASS ../toast/living/jul13/small.html
0 charset_mismatch charset_used charset_invalid
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure missing_close
11 inserted_missing_closure
23 use_double_quote_code

PASS ../toast/living/jul13/source.html
6 inserted_missing_parent missing_close media_descendants url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found
15 url_not_found mime
16 url_not_found mime
17 url_not_found mime
18 url_not_found
19 mime url_not_found
33 autoplay
34 url_not_found
35 url_not_found
39 inserted_missing_closure

PASS ../toast/living/jul13/span.html
6 unrecognised_value unrecognised_value unrecognised_value
7 unrecognised_value unrecognised_value
8 unrecognised_value unrecognised_value lonely_ampersand
9 unrecognised_value
10 unrecognised_value unrecognised_value
11 unrecognised_value unrecognised_value
12 unrecognised_value lonely_ampersand
13 unrecognised_value unrecognised_value
14 unrecognised_value
15 unrecognised_value

PASS ../toast/living/jul13/table.html
14 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
23 inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure inserted_missing_closure inserted_missing_closure
36 id_exists
37 wrong_parent inserted_missing_closure
38 wrong_parent inserted_missing_closure
39 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
41 bad_header_id bad_header_id
42 inserted_missing_closure id_exists
43 inserted_missing_closure
44 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
45 id_exists
46 inserted_missing_closure missing_close
47 inserted_missing_closure inserted_missing_closure inserted_missing_closure
61 id_exists
62 wrong_parent inserted_missing_closure
63 wrong_parent inserted_missing_closure
64 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
66 bad_header_id bad_header_id
67 inserted_missing_closure id_exists
68 inserted_missing_closure
69 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
70 bad_header_id bad_header_id
71 inserted_missing_closure id_exists
72 inserted_missing_closure missing_close
73 inserted_missing_closure inserted_missing_closure inserted_missing_closure
83 id_exists
84 wrong_parent inserted_missing_closure
85 wrong_parent inserted_missing_closure
86 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
88 bad_header_id bad_header_id
89 inserted_missing_closure id_exists
90 inserted_missing_closure
91 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
92 bad_header_id bad_header_id
93 inserted_missing_closure id_exists
94 inserted_missing_closure missing_close
95 inserted_missing_closure inserted_missing_closure inserted_missing_closure
107 inserted_missing_parent id_exists
108 wrong_parent inserted_missing_closure
109 wrong_parent inserted_missing_closure
110 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
112 bad_header_id bad_header_id
113 inserted_missing_closure id_exists
114 inserted_missing_closure
115 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
116 bad_header_id bad_header_id
117 inserted_missing_closure id_exists
118 inserted_missing_closure missing_close
119 inserted_missing_closure inserted_missing_closure inserted_missing_closure
127 wrong_parent inserted_missing_closure
128 wrong_parent inserted_missing_closure
129 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
132 inserted_missing_closure
133 wrong_parent inserted_missing_closure
134 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
136 inserted_missing_closure
137 wrong_parent inserted_missing_closure missing_close
138 inserted_missing_closure inserted_missing_closure inserted_missing_closure
147 use_quote_code
150 inserted_missing_closure
151 inserted_missing_closure
152 inserted_missing_closure
153 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
154 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
155 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
156 inserted_missing_closure inserted_missing_closure inserted_missing_closure
157 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
158 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
159 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
160 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
161 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
162 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
163 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
164 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul13/te.html
54 wrong_parent inserted_missing_closure
55 wrong_parent inserted_missing_closure
56 wrong_parent inserted_missing_closure
57 inserted_missing_closure inserted_missing_closure inserted_missing_closure
60 inserted_missing_closure
61 wrong_parent inserted_missing_closure
62 wrong_parent inserted_missing_closure
63 inserted_missing_closure wrong_parent inserted_missing_closure
65 inserted_missing_closure
66 wrong_parent inserted_missing_closure
67 wrong_parent inserted_missing_closure
68 inserted_missing_closure inserted_missing_closure inserted_missing_closure
71 inserted_missing_closure
72 wrong_parent inserted_missing_closure
73 wrong_parent inserted_missing_closure
74 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
75 missing_close
77 inserted_missing_closure
78 wrong_parent inserted_missing_closure
79 wrong_parent inserted_missing_closure missing_close
80 inserted_missing_closure inserted_missing_closure inserted_missing_closure
84 inserted_missing_closure
85 inserted_missing_closure
86 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
87 inserted_missing_closure inserted_missing_closure inserted_missing_closure
89 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
90 inserted_missing_closure wrong_parent inserted_missing_closure
91 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
92 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
94 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
95 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
96 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
97 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul13/template.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
10 inserted_missing_parent inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
16 missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure
18 inserted_missing_closure

PASS ../toast/living/jul13/textarea.html
12 use_quote_code use_double_quote_code

PASS ../toast/living/jul13/th.html
8 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure
10 inserted_missing_closure inserted_missing_closure wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
14 inserted_missing_closure inserted_missing_closure wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
16 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul13/thead.html
11 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
17 wrong_parent inserted_missing_closure
18 wrong_parent inserted_missing_closure
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
22 wrong_parent inserted_missing_closure
23 wrong_parent inserted_missing_closure attribute_required naughty_alt
24 wrong_parent inserted_missing_closure
25 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
27 wrong_parent inserted_missing_closure
28 wrong_parent inserted_missing_closure
29 wrong_parent inserted_missing_closure missing_close
30 inserted_missing_closure inserted_missing_closure inserted_missing_closure
31 url_not_found

PASS ../toast/living/jul13/time.html
75 schema_domain

PASS ../toast/living/jul13/tls.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
15 inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
26 unrecognised_value
29 use_double_quote_code
30 use_double_quote_code

PASS ../toast/living/jul13/track.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found

PASS ../toast/living/jul13/ul.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure

PASS ../toast/living/jul13/us-1.html
2 naughty_lang
3 use_quote_code

PASS ../toast/living/jul13/us-2.html
11 url_not_found
16 url_not_found naughty_alt

PASS ../toast/living/jul13/us-4.html
12 inserted_missing_closure url_not_found
13 inserted_missing_closure missing_close url_not_found
14 inserted_missing_closure

PASS ../toast/living/jul13/us-5.html
12 url_not_found

PASS ../toast/living/jul13/var.html
21 use_quote_code
27 use_quote_code

PASS ../toast/living/jul13/video.html
30 url_not_found autoplay
31 url_not_found

PASS ../toast/living/jul13/wbr.html
7 use_double_quote_code use_double_quote_code
