[general]
verbose=5
output=../out/jul25.out
class=true

[html]
version=2025/07/01

[nits]
nids=

[link]
check=

[ontology]
schema=29.2

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/living/jul25

[validation]
element=labeled-checkbox
element=question-box
