[general]
verbose=5
output=../out/m4core.out
class=

[css]
version=2024++

[html]
version=2025/07/01

[link]
check=

[math]
version=core

[nits]
nids=

[site]
domain=example.edu
extension=html
extension=xhtml
index=index.html
root=../toast/math/4-core

[svg]
version=2
