[general]
verbose=info
output=../out/ukarim.out
class=

[css]
verify=
extension=css
version=3
no-external=

[html]
version=2025/10/01

[link]
check=

[nits]
nids=

[site]
domain=example.org
extension=html
index=index.html
root=../toast/external/ukarim.com

[spell]
no-check=true
