[general]
verbose=info
output=../out/required.out
class=

[html]
version=2025/01/01

[link]
check=
required=index.html,,ALL
required=other.html,,INDEX
required=sub/other.html,,FRONT,MAIN

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/other/required

[spell]
no-check=true
