-f ../toast/HTML/2.0/html2.conf

PASS ../toast/HTML/2.0/html2-good.html
5 attribute_required
7 attribute_required
8 attribute_required
9 attribute_required
10 attribute_required
11 attribute_required
14 deprecated_element
31 urn_undefined methods_undefined

PASS ../toast/HTML/2.0/html2-bad.html
0 title_required
5 element_offsite_base
6 attribute_required
7 unrecognised_value empty
8 refresh_zero url_empty
9 deprecated_element
12 inserted_missing_parent
16 inserted_missing_closure
28 file_requires_enctype use_post
30 mime mime_list file_requires_enctype
33 missing_open

PASS ../toast/HTML/2.0/html2-badl1.html
11 unknown_element
12 unknown_element
16 unknown_element
17 unknown_element

PASS ../toast/HTML/2.0/html2-example.html
8 bad_datetime
9 use_metaname
10 use_metaname
11 double_gin_and_tonic use_metaname
35 inserted_missing_closure inserted_missing_closure
37 inserted_missing_closure
44 inserted_missing_closure
51 url_not_found
52 url_not_found
64 missing_close
66 inserted_missing_closure
71 inserted_missing_closure
73 inserted_missing_closure inserted_missing_closure missing_close
74 inserted_missing_closure
78 inserted_missing_closure
82 inserted_missing_closure missing_close
83 inserted_missing_closure
84 inserted_missing_closure missing_close
85 inserted_missing_closure
88 inserted_missing_closure
89 inserted_missing_closure inserted_missing_closure missing_close
90 inserted_missing_closure
93 inserted_missing_closure
94 inserted_missing_closure inserted_missing_closure missing_close
95 inserted_missing_closure
98 inserted_missing_closure
99 inserted_missing_closure inserted_missing_closure missing_close
100 inserted_missing_closure
130 no_such_folder url_not_found url_not_found
133 inserted_missing_closure
136 inserted_missing_closure
138 inserted_missing_closure
142 inserted_missing_closure
146 inserted_missing_closure url_not_found
157 inserted_missing_closure
158 inserted_missing_closure
159 inserted_missing_closure missing_close
160 inserted_missing_closure
168 inserted_missing_closure
170 inserted_missing_closure
171 inserted_missing_closure
172 inserted_missing_closure
173 inserted_missing_closure
175 inserted_missing_closure inserted_missing_closure inserted_missing_closure
176 inserted_missing_parent
177 inserted_missing_closure inserted_missing_closure inserted_missing_parent
178 inserted_missing_closure inserted_missing_closure missing_close inserted_missing_parent missing_close
179 inserted_missing_closure inserted_missing_closure
180 inserted_missing_parent
182 inserted_missing_closure inserted_missing_closure

PASS ../toast/HTML/2.0/html2-sample.html
13 inserted_missing_closure
16 inserted_missing_closure missing_close
18 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure
26 inserted_missing_closure missing_close
27 url_not_found
29 inserted_missing_closure

PASS ../toast/HTML/2.0/rfc1867.html
15 invalid_attribute_version wrong_version

PASS ../toast/HTML/2.0/rfc1942.html
12 inserted_missing_parent missing_close missing_close missing_close missing_close wrong_parent
13 missing_close wrong_parent missing_close wrong_parent
14 missing_close missing_close missing_close wrong_parent
15 missing_close missing_close missing_close missing_close wrong_parent
16 missing_close missing_close missing_close missing_close wrong_parent
17 inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure
22 inserted_missing_closure
23 inserted_missing_closure
24 inserted_missing_closure
25 inserted_missing_closure missing_close
26 missing_close
27 missing_close
28 missing_close wrong_parent
29 missing_close wrong_parent
30 missing_close wrong_parent
31 missing_close wrong_parent
32 missing_close wrong_parent
33 missing_close wrong_parent
34 missing_close
35 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
36 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
37 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
38 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
39 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
40 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
41 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
42 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
43 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
44 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
45 missing_close
46 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
47 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
48 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
49 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
50 missing_close missing_close missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent missing_close wrong_parent
51 inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/HTML/2.0/rfc1980-bad.html
10 url_not_found url_id_unfound
13 bad_coords unrecognised_value
14 url_not_found
15 url_not_found
16 url_not_found
17 bad_coords url_not_found
18 bad_coords url_not_found
19 bad_coords url_not_found
20 bad_coords url_not_found

PASS ../toast/HTML/2.0/rfc2070-bad.html
10 lingo unrecognised_value
14 lingo unrecognised_value
