-f ../toast/HTML/Plus/plus.conf

PASS ../toast/HTML/Plus/index.html
15 inserted_missing_closure missing_close
18 inserted_missing_closure

PASS ../toast/HTML/Plus/plus-bad.html
0 title_required
3 inserted_missing_parent missing_close inserted_missing_parent missing_close render

PASS ../toast/HTML/Plus/plus-bad2.html
2 inserted_missing_parent missing_close inserted_missing_parent missing_close missing_close inserted_missing_parent inserted_missing_closure inserted_missing_closure missing_close missing_close missing_open
4 ignoring_unknown
8 ignoring_unknown

PASS ../toast/HTML/Plus/plus-simple.html
1 public_missing
2 inserted_missing_parent missing_close inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
6 inserted_missing_closure missing_close

PASS ../toast/HTML/Plus/plus-example.html
20 inserted_missing_closure
24 inserted_missing_closure
27 inserted_missing_closure
28 inserted_missing_closure
33 url_id_unfound
36 inserted_missing_closure
56 inserted_missing_closure
69 inserted_missing_closure
80 inserted_missing_closure
85 inserted_missing_closure
88 inserted_missing_closure
103 inserted_missing_closure
104 inserted_missing_closure
105 inserted_missing_closure missing_close
106 inserted_missing_closure
110 inserted_missing_closure
111 inserted_missing_closure
112 inserted_missing_closure missing_close
113 inserted_missing_closure
117 inserted_missing_closure
118 inserted_missing_closure
119 inserted_missing_closure
120 inserted_missing_closure
121 inserted_missing_closure missing_close
122 inserted_missing_closure
126 inserted_missing_closure
127 inserted_missing_closure
128 inserted_missing_closure
130 inserted_missing_closure
131 inserted_missing_closure
132 inserted_missing_closure
133 inserted_missing_closure missing_close
138 inserted_missing_closure
141 inserted_missing_closure missing_close
143 inserted_missing_closure
148 inserted_missing_closure
177 inserted_missing_closure
179 inserted_missing_closure
180 inserted_missing_closure
182 inserted_missing_closure
183 inserted_missing_closure missing_close
184 inserted_missing_closure
188 inserted_missing_closure
201 inserted_missing_closure
202 inserted_missing_closure
203 inserted_missing_closure missing_close
204 inserted_missing_closure
206 missing_close
207 inserted_missing_closure
228 inserted_missing_closure
231 ignoring_unknown missing_open
243 missing_open
245 inserted_missing_closure
247 bizarre_character_code invalid_character_code
252 bizarre_character_code invalid_character_code
