-N 1 -f ../toast/HTML/5.2/html5.conf

PASS ../toast/HTML/5.2/example-1.html
2 naughty_lang
6 unrecognised_value
8 missing_close inserted_missing_closure

PASS ../toast/HTML/5.2/example-2.html
2 naughty_lang
6 unrecognised_value

PASS ../toast/HTML/5.2/example-3.html
0 title_required
2 inserted_missing_parent missing_close naughty_lang excluded_attribute excluded_attribute
5 url_not_found
6 url_not_found
7 url_not_found
8 excluded_attribute
12 url_not_found
13 url_not_found
14 url_not_found
19 excluded_attribute excluded_attribute excluded_attribute
21 excluded_attribute
23 excluded_attribute
28 excluded_attribute
35 excluded_attribute
36 excluded_attribute
38 url_not_found
39 url_not_found
40 url_not_found

PASS ../toast/HTML/5.2/example-4.html
0 title_required
2 inserted_missing_parent missing_close naughty_lang
7 url_not_found
9 only_elements
21 only_elements

PASS ../toast/HTML/5.2/example-5.html
0 title_required
2 inserted_missing_parent missing_close naughty_lang
14 missing_close
15 inserted_missing_closure
20 url_not_found
21 inserted_missing_closure missing_close url_not_found
22 inserted_missing_closure
31 use_quote_code
34 use_quote_code
41 missing_close url_not_found
42 inserted_missing_closure
55 use_quote_code
58 missing_close url_not_found
59 inserted_missing_closure
63 url_not_found
64 url_not_found
65 url_not_found

PASS ../toast/HTML/5.2/html5-bad.html
2 naughty_lang
5 bespoke_obsolete mime
7 only_once
10 default_role
16 attribute_unrecognised_here missing_close unrecognised_attribute
18 lonely_ampersand inserted_missing_parent inserted_missing_closure inserted_missing_parent
19 inserted_missing_closure inserted_missing_closure missing_close
21 missing_open
23 unrecognised_value invalid_attribute_version wrong_version
28 nuts invalid_attribute_version wrong_version
31 mixed_mess
33 special_name
48 missing_open
49 missing_open
51 attribute_unrecognised unrecognised_attribute unrecognised_value
53 inserted_missing_closure
55 unrecognised_value
56 attributes_on_closure
57 unrecognised_value
58 attribute_required url_not_found naughty_alt
59 attribute_required url_not_found naughty_alt
60 attribute_required url_not_found naughty_alt
61 attribute_required url_not_found naughty_alt
62 attribute_required url_not_found naughty_alt
63 attribute_required url_not_found naughty_alt
65 missing_close inserted_missing_closure missing_open
77 url_not_found
80 url_not_found
81 inserted_missing_closure missing_close
82 inserted_missing_closure
85 use_quote_code
89 dl_div
92 dt_dd
95 dl_div dl_div dl_div dl_div
96 dt_dd
101 url_not_found saucy_source autoplay
102 mime url_not_found saucy_source
103 url_not_found
107 url_not_found saucy_source out_of_order out_of_order
108 url_not_found
110 mime url_not_found saucy_source source_track source_track
113 url_not_found out_of_order saucy_source out_of_order
115 url_not_found source_track
116 mime url_not_found saucy_source source_track source_track
120 label_parentage
121 label_parentage
124 bad_id
127 bad_for label_parentage label_parentage
130 mime mime
131 bad_datetime
133 bad_datetime
134 bad_datetime
136 bad_datetime
138 bad_datetime
141 sunk minmax
142 minmax minmax minmax
143 sunk minmax
144 minmax minmax minmax
145 unrecognised_value bad_colour
147 unrecognised_value bad_colour
149 unrecognised_value bad_colour
150 minmax minmax minmax
152 minmax
153 minmax
155 minmax minmax minmax
156 input_bad_mix input_bad_mix
157 pattern
159 placeholder
160 bad_datalist_id
161 bad_datalist_id
178 bad_option
180 bad_option
185 url_not_found
186 bad_script bad_script
187 invalid_attribute_version wrong_version
188 script
189 script
190 script bad_script
191 script bad_script
192 script bad_script
193 script
194 unrecognised_value script
195 script bad_script
196 invalid_attribute_version wrong_version script bad_script bad_script
197 script

PASS ../toast/HTML/5.2/html5-bad-2.html
0 charset_mismatch charset_used charset_invalid
4 unrecognised_value
6 lingo lingo
7 no_xmllang
9 lang_xmllang double_gin_and_tonic

PASS ../toast/HTML/5.2/html5-example.html
2 naughty_lang
8 url_not_found url_not_found
9 url_not_found url_not_found
10 url_not_found
85 unrecognised_value
88 data_type attribute_required attribute_required attribute_required
98 url_not_found
104 use_quote_code
108 url_not_found
109 url_not_found
110 url_not_found
111 use_quote_code
117 url_not_found
120 url_not_found
121 inserted_missing_closure missing_close
122 inserted_missing_closure
125 use_quote_code
135 unrecognised_value
137 unrecognised_value
149 use_quote_code naughty_grave naughty_grave naughty_grave naughty_grave naughty_grave
151 use_double_quote_code
153 use_double_quote_code
156 schema_domain excluded_attribute excluded_attribute
158 excluded_attribute
159 excluded_attribute
163 use_quote_code
166 excluded_attribute
170 schema_domain excluded_attribute excluded_attribute
172 excluded_attribute
173 excluded_attribute
177 use_quote_code
181 schema_domain excluded_attribute excluded_attribute excluded_attribute
184 schema_domain excluded_attribute excluded_attribute excluded_attribute
185 excluded_attribute
187 excluded_attribute
191 schema_domain excluded_attribute excluded_attribute excluded_attribute
194 schema_domain excluded_attribute excluded_attribute excluded_attribute
195 excluded_attribute
197 excluded_attribute
241 url_not_found
244 url_not_found
246 no_such_folder url_not_found
248 use_double_quote_code
251 url_not_found
268 use_quote_code
271 use_quote_code
274 use_quote_code
276 use_quote_code
283 use_quote_code
320 url_id_unfound
322 missing_close unrecognised_value missing_close
323 inserted_missing_closure inserted_missing_closure
329 url_not_found
330 inserted_missing_closure url_not_found
331 inserted_missing_closure missing_close url_not_found
332 inserted_missing_closure
337 use_quote_code
343 attempted_escape
355 attempted_escape
360 no_such_folder url_not_found
361 no_such_folder url_not_found
378 url_not_found
379 url_not_found
389 no_such_folder url_not_found naughty_alt
391 no_such_folder url_not_found
392 no_such_folder url_not_found
393 attribute_required no_such_folder url_not_found naughty_alt
395 no_such_folder url_not_found
397 attribute_required no_such_folder url_not_found naughty_alt
399 use_quote_code no_such_folder url_not_found
402 url_not_found
403 inserted_missing_closure url_not_found
404 inserted_missing_closure missing_close url_not_found
405 inserted_missing_closure
408 url_not_found
412 attempted_escape no_such_folder url_not_found
413 attempted_escape no_such_folder url_not_found
414 url_not_found
467 inserted_missing_closure
468 use_quote_code
500 inserted_missing_closure
501 inserted_missing_closure missing_close
502 inserted_missing_closure
516 use_quote_code
544 use_quote_code
546 use_quote_code
555 use_quote_code
581 use_double_quote_code use_quote_code
588 use_double_quote_code
597 missing_close use_quote_code
600 inserted_missing_closure
602 use_double_quote_code
616 inserted_missing_closure
617 inserted_missing_closure
618 inserted_missing_closure missing_close
619 inserted_missing_closure
624 inserted_missing_closure
625 inserted_missing_closure
626 inserted_missing_closure missing_close
627 inserted_missing_closure
632 inserted_missing_closure
633 inserted_missing_closure
634 inserted_missing_closure missing_close
635 inserted_missing_closure
641 lingo
642 use_quote_code
670 use_quote_code
675 unrecognised_value use_quote_code
676 unrecognised_value
678 unrecognised_value use_quote_code
679 unrecognised_value
680 unrecognised_value
698 newline_in_string newline_in_string url_not_found
701 url_not_found url_not_found
703 use_quote_code
709 use_double_quote_code inserted_missing_closure
710 url_not_found
717 inserted_missing_closure
718 url_not_found
725 url_not_found
732 use_quote_code
743 use_quote_code
751 use_quote_code use_double_quote_code
753 use_double_quote_code
756 only_once
776 unrecognised_value
804 inserted_missing_parent missing_close
806 use_quote_code
822 inserted_missing_closure
823 inserted_missing_closure
824 inserted_missing_closure missing_close
825 inserted_missing_closure
836 use_double_quote_code
851 unrecognised_value
865 use_quote_code
868 use_quote_code
887 use_quote_code
900 use_double_quote_code use_quote_code
905 use_quote_code
911 use_quote_code
921 id_exists
939 naughty_grave
1010 schema_domain excluded_attribute excluded_attribute
1011 excluded_attribute
1012 excluded_attribute
1013 excluded_attribute
1016 excluded_attribute excluded_attribute
1017 excluded_attribute
1018 excluded_attribute
1019 excluded_attribute
1041 unrecognised_value
1061 use_quote_code
1067 use_quote_code
1071 use_quote_code
1073 unrecognised_value
1077 unrecognised_value unrecognised_value
1098 unrecognised_value
1115 missing_close
1116 use_quote_code
1117 unrecognised_value
1125 use_quote_code
1132 use_quote_code
1141 unrecognised_value unrecognised_value
1142 unrecognised_value
1143 unrecognised_value unrecognised_value
1144 unrecognised_value
1152 no_rp missing_close inserted_missing_closure
1154 no_rp inserted_missing_closure missing_close inserted_missing_closure
1156 no_rp no_rp
1157 no_rp no_rp
1158 no_rp no_rp
1160 no_rp no_rp no_rp
1161 no_rp
1162 no_rp no_rp
1164 no_rp missing_close inserted_missing_closure
1166 no_rp no_rp no_rp inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
1168 no_rp no_rp inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
1170 no_rp inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
1172 no_rp no_rp no_rp no_rp inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
1174 no_rp no_rp no_rp inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure
1176 no_rp no_rp no_rp no_rp no_rp no_rp
1177 inserted_missing_closure
1178 inserted_missing_closure
1179 inserted_missing_closure missing_close
1180 inserted_missing_closure
1182 no_rp no_rp no_rp no_rp no_rp no_rp
1188 no_rp
1197 no_rp no_rp no_rp no_rp no_rp
1205 inserted_missing_closure
1206 inserted_missing_closure missing_close
1207 inserted_missing_closure
1209 unrecognised_value unrecognised_value unrecognised_value unrecognised_value unrecognised_value
1210 unrecognised_value unrecognised_value lonely_ampersand unrecognised_value
1211 unrecognised_value unrecognised_value unrecognised_value unrecognised_value unrecognised_value
1212 lonely_ampersand unrecognised_value unrecognised_value unrecognised_value
1213 unrecognised_value
1220 chocolate_teapot
1221 chocolate_teapot
1227 use_double_quote_code use_double_quote_code
1265 use_quote_code
1291 use_quote_code
1295 use_quote_code
1313 no_such_folder url_not_found
1316 url_not_found
1317 no_such_folder url_not_found
1320 url_not_found
1332 url_not_found
1335 url_not_found
1337 url_not_found
1344 newline_in_string newline_in_string url_not_found
1355 overallowed
1357 url_not_found
1360 mime
1367 newline_in_string newline_in_string url_not_found
1372 url_not_found
1376 url_not_found mime
1377 url_not_found mime
1378 url_not_found mime
1379 url_not_found mime
1380 url_not_found mime
1381 url_not_found mime
1382 url_not_found mime
1383 url_not_found mime
1384 url_not_found mime
1385 url_not_found
1386 url_not_found
1387 url_not_found
1388 url_not_found mime
1391 url_not_found
1392 url_not_found
1393 url_not_found
1394 url_not_found
1395 url_not_found
1401 url_not_found
1404 url_not_found
1405 url_not_found
1406 url_not_found
1408 url_not_found
1418 use_quote_code
1421 inserted_missing_closure
1422 inserted_missing_closure
1423 inserted_missing_closure
1424 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1425 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1426 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1427 inserted_missing_closure inserted_missing_closure inserted_missing_closure
1428 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1429 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1430 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1431 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
1432 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1433 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1434 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
1435 inserted_missing_closure inserted_missing_closure inserted_missing_closure
1479 use_quote_code
1481 use_double_quote_code
1482 use_double_quote_code
1488 missing_close use_quote_code
1490 inserted_missing_closure
1500 use_quote_code
1506 use_quote_code
1508 use_quote_code
1522 use_quote_code
1528 use_double_quote_code
1538 inserted_missing_closure inserted_missing_closure

PASS ../toast/HTML/5.2/html5-good.html
2 naughty_lang
11 unrecognised_value unknown_rel link_rel_off
34 requires_href
38 url_not_found
58 lonely_radio
63 url_not_found naughty_alt

PASS ../toast/HTML/5.2/html5-legacy.html
2 deprecated_attribute naughty_lang avoid_manifest

PASS ../toast/HTML/5.2/template-1.html
2 naughty_lang

PASS ../toast/HTML/5.2/template-2.html
2 naughty_lang

PASS ../toast/HTML/5.2/template-3.html
1 presume_html_1 attribute_unrecognised_here unrecognised_attribute

PASS ../toast/HTML/5.2/template-4.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
4 inserted_missing_parent inserted_missing_closure missing_close

PASS ../toast/HTML/5.2/math-example-1.html
3 naughty_lang

CLASS
info 1
warning 1
error 1
