-f ../toast/living/jul20/living.conf

PASS ../toast/living/jul20/a.html
9 url_not_found
10 chocolate_teapot
11 url_not_found
15 unrecognised_value
36 wrong_parent inserted_missing_closure
37 wrong_parent inserted_missing_closure
38 inserted_missing_closure wrong_parent inserted_missing_closure
39 no_such_folder url_not_found
40 wrong_parent inserted_missing_closure
41 wrong_parent inserted_missing_closure
42 inserted_missing_closure wrong_parent inserted_missing_closure
43 no_such_folder url_not_found
44 wrong_parent inserted_missing_closure
45 wrong_parent inserted_missing_closure
46 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
47 no_such_folder url_not_found
48 wrong_parent inserted_missing_closure
49 wrong_parent inserted_missing_closure missing_close
50 inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/abbr.html
17 id_exists
35 naughty_grave

PASS ../toast/living/jul20/address.html
0 charset_mismatch charset_used charset_invalid
11 attempted_escape no_such_folder url_not_found
12 attempted_escape no_such_folder url_not_found
13 url_not_found

PASS ../toast/living/jul20/aside-2.html
0 charset_mismatch charset_used charset_invalid
16 missing_close
17 inserted_missing_closure
22 url_not_found
23 inserted_missing_closure missing_close
23 url_not_found
24 inserted_missing_closure
32 use_quote_code
35 use_quote_code
43 missing_close
43 url_not_found
44 inserted_missing_closure
57 use_quote_code
60 missing_close
60 url_not_found
61 inserted_missing_closure
65 url_not_found
66 url_not_found
67 url_not_found

PASS ../toast/living/jul20/aside.html
0 charset_mismatch charset_used charset_invalid
19 use_quote_code
22 use_quote_code
25 use_quote_code

PASS ../toast/living/jul20/b.html
0 charset_mismatch charset_used charset_invalid
12 use_quote_code

PASS ../toast/living/jul20/blockquote.html
0 charset_mismatch charset_used charset_invalid
7 missing_close
8 use_quote_code
10 inserted_missing_closure
19 use_quote_code
25 use_quote_code
28 use_quote_code
42 use_quote_code
48 use_double_quote_code
57 inserted_missing_closure
66 use_quote_code
68 use_double_quote_code
69 use_double_quote_code
84 inserted_missing_closure

PASS ../toast/living/jul20/canvas3.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
3 element_offsite_base
9 inserted_missing_parent inserted_missing_closure missing_close
158 inserted_missing_closure

PASS ../toast/living/jul20/caption.html
9 inserted_missing_closure missing_close
13 inserted_missing_closure

PASS ../toast/living/jul20/data.html
10 unrecognised_value
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
12 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure
14 wrong_parent inserted_missing_closure
14 wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
15 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure missing_close
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/datalist.html
11 inserted_missing_closure missing_close
12 inserted_missing_closure
19 id_exists
24 inserted_missing_closure
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jul20/dd.html
0 charset_mismatch charset_used charset_invalid
8 unrecognised_value
8 use_quote_code
9 unrecognised_value
13 unrecognised_value
13 use_quote_code
14 unrecognised_value
15 unrecognised_value

PASS ../toast/living/jul20/del.html
9 use_quote_code

PASS ../toast/living/jul20/details.html
0 charset_mismatch charset_used charset_invalid
6 unrecognised_value unrecognised_value
7 use_double_quote_code
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jul20/dfn.html
9 use_quote_code
15 use_quote_code

PASS ../toast/living/jul20/div.html
10 use_quote_code
18 use_quote_code use_double_quote_code
20 use_double_quote_code

PASS ../toast/living/jul20/dl.html
0 charset_mismatch charset_used charset_invalid
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
59 use_quote_code
65 inserted_missing_closure
68 inserted_missing_closure missing_close
70 inserted_missing_closure
73 inserted_missing_closure
76 inserted_missing_closure missing_close
78 inserted_missing_closure
84 inserted_missing_closure missing_itemtype
87 inserted_missing_closure
89 inserted_missing_closure
91 inserted_missing_closure missing_itemtype
94 inserted_missing_closure missing_close
96 inserted_missing_closure

PASS ../toast/living/jul20/el.html
9 use_quote_code
13 use_quote_code
27 missing_close
28 inserted_missing_closure

PASS ../toast/living/jul20/embed.html
6 reputation url_not_found
8 wild_attribute reputation wild_attribute url_not_found
10 reputation url_not_found

PASS ../toast/living/jul20/et.html
8 wrong_parent inserted_missing_closure
8 wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
10 wrong_parent inserted_missing_closure
10 wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
12 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure missing_close
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure
17 wrong_parent inserted_missing_closure
17 wrong_parent inserted_missing_closure
18 no_such_folder url_not_found
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
20 wrong_parent inserted_missing_closure
20 wrong_parent inserted_missing_closure
21 no_such_folder url_not_found
22 inserted_missing_closure wrong_parent inserted_missing_closure
22 wrong_parent inserted_missing_closure
22 wrong_parent inserted_missing_closure
23 no_such_folder url_not_found
24 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
24 wrong_parent inserted_missing_closure
24 wrong_parent inserted_missing_closure missing_close
25 no_such_folder url_not_found
26 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/example-2.html
4 url_not_found style_not_css
5 url_not_found
6 url_not_found
10 url_not_found
14 sizes sizes
23 no_such_folder url_not_found
35 url_not_found
41 url_not_found
44 url_not_found
45 mime
59 use_quote_code
73 use_quote_code
77 unrecognised_schema unrecognised_schema
87 unrecognised_schema unrecognised_schema
118 unrecognised_value
133 use_quote_code
143 use_quote_code

PASS ../toast/living/jul20/example.html
6 missing_close
6 inserted_missing_closure
6 missing_open
10 url_not_found
28 url_not_found
29 inserted_missing_closure
29 url_not_found
30 inserted_missing_closure missing_close
30 url_not_found
31 inserted_missing_closure
33 url_not_found
44 url_not_found
53 inserted_missing_closure inserted_missing_closure
54 inserted_missing_closure inserted_missing_closure
55 inserted_missing_closure inserted_missing_closure
65 inserted_missing_closure inserted_missing_closure unrecognised_value
66 input_bad_aria
68 inserted_missing_closure
93 attribute_unrecognised unrecognised_attribute unrecognised_value
95 unrecognised_value
99 url_not_found
107 newline_in_string
107 newline_in_string url_not_found
111 data_type
111 attribute_required attribute_required
111 attribute_required
129 url_not_found
135 use_quote_code
138 url_not_found
139 url_not_found
140 url_not_found
142 use_quote_code
148 url_not_found
151 url_not_found
152 inserted_missing_closure missing_close
153 inserted_missing_closure
157 use_quote_code
162 url_not_found
165 url_not_found
166 inserted_missing_closure missing_close
167 inserted_missing_closure
170 use_quote_code
174 unrecognised_namespace unknown_element
177 unknown_element
181 newline_in_string
181 newline_in_string
183 unrecognised_value
183 use_double_quote_code use_quote_code
184 unrecognised_value
185 inserted_missing_closure unrecognised_value
186 unrecognised_value
187 use_quote_code use_double_quote_code
187 inserted_missing_closure unrecognised_value
187 use_double_quote_code
188 unrecognised_value
188 use_double_quote_code
191 newline_in_string
191 newline_in_string
192 newline_in_string
192 newline_in_string
197 only_elements
210 unrecognised_value
212 unrecognised_value
219 unrecognised_value no_such_folder url_not_found

PASS ../toast/living/jul20/fieldset.html
12 pattern
27 pattern
34 pattern
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure missing_close
47 inserted_missing_closure missing_close
48 inserted_missing_closure
49 inserted_missing_closure

PASS ../toast/living/jul20/figcaption.html
0 normalise
6 inserted_missing_parent missing_close too_many_figcaption
16 inserted_missing_closure

PASS ../toast/living/jul20/figure.html
21 newline_in_string
21 newline_in_string url_not_found
25 use_quote_code
29 use_double_quote_code
29 inserted_missing_closure
30 url_not_found
35 inserted_missing_closure
36 url_not_found
40 url_not_found
45 inserted_missing_closure
46 use_quote_code
55 url_not_found
57 url_not_found
60 newline_in_string
60 newline_in_string url_not_found
65 url_not_found
67 url_not_found
69 url_not_found
76 url_not_found
83 use_quote_code

PASS ../toast/living/jul20/footer-2.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang
4 inserted_missing_closure
8 no_such_folder url_not_found
9 no_such_folder url_not_found
26 url_not_found
27 url_not_found

PASS ../toast/living/jul20/footer-3.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang
13 no_such_folder url_not_found naughty_alt
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 attribute_required no_such_folder url_not_found naughty_alt
19 no_such_folder url_not_found
21 attribute_required no_such_folder url_not_found naughty_alt
23 use_quote_code
23 no_such_folder url_not_found
26 url_not_found
27 inserted_missing_closure
27 url_not_found
28 inserted_missing_closure missing_close
28 url_not_found
29 inserted_missing_closure
32 url_not_found

PASS ../toast/living/jul20/footer.html
2 naughty_lang
9 attempted_escape
18 attempted_escape

PASS ../toast/living/jul20/formex.html
15 url_not_found
21 no_such_folder url_not_found
32 url_not_found
37 url_not_found
61 url_not_found
63 missing_close
63 inserted_missing_closure
74 bad_autocomplete
75 inserted_missing_closure
76 inserted_missing_closure missing_close
77 inserted_missing_closure
80 bad_autocomplete
81 inserted_missing_closure
82 inserted_missing_closure missing_close
83 inserted_missing_closure
85 url_not_found
90 inserted_missing_closure
91 inserted_missing_closure missing_close
92 inserted_missing_closure
99 inserted_missing_closure
100 inserted_missing_closure
101 inserted_missing_closure
102 inserted_missing_closure
103 inserted_missing_closure
104 inserted_missing_closure
105 inserted_missing_closure
107 inserted_missing_closure
108 inserted_missing_closure
109 inserted_missing_closure missing_close
110 inserted_missing_closure
119 bad_autocomplete
123 inserted_missing_closure
125 inserted_missing_closure
126 inserted_missing_closure missing_close
128 inserted_missing_closure
157 url_not_found
163 url_not_found

PASS ../toast/living/jul20/forms.html
119 inserted_missing_closure missing_close
120 inserted_missing_closure
144 inserted_missing_closure missing_close
145 inserted_missing_closure
169 inserted_missing_closure missing_close
170 inserted_missing_closure
195 inserted_missing_closure missing_close
196 inserted_missing_closure
306 unrecognised_value
308 missing_close
324 inserted_missing_closure
327 inserted_missing_closure
327 use_quote_code
328 inserted_missing_closure
330 use_double_quote_code
330 inserted_missing_closure
331 inserted_missing_closure
331 use_quote_code
332 inserted_missing_closure
334 use_double_quote_code
334 inserted_missing_closure
337 inserted_missing_closure
338 pattern

PASS ../toast/living/jul20/h-1.html
6 use_quote_code

PASS ../toast/living/jul20/h-2.html
6 use_quote_code

PASS ../toast/living/jul20/h-3.html
6 use_quote_code

PASS ../toast/living/jul20/header-2.html
2 naughty_lang
14 url_not_found
15 inserted_missing_closure
15 url_not_found
16 inserted_missing_closure missing_close
16 url_not_found
17 inserted_missing_closure
21 use_quote_code

PASS ../toast/living/jul20/header.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang

PASS ../toast/living/jul20/hgroup-2.html
18 newline_in_string
18 newline_in_string illegal_value
19 inserted_missing_closure
21 inserted_missing_closure
22 input_bad_mix
23 inserted_missing_closure missing_close
25 inserted_missing_closure
30 inserted_missing_closure
31 inserted_missing_closure missing_close
32 inserted_missing_closure

PASS ../toast/living/jul20/hr.html
17 use_quote_code
47 use_quote_code
49 use_quote_code
58 use_quote_code

PASS ../toast/living/jul20/hs-10.html
0 title_required
5 use_double_quote_code
5 inserted_missing_parent missing_close naughty_lang
5 inserted_missing_parent missing_close

PASS ../toast/living/jul20/hs-11.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
2 long_title
3 inserted_missing_parent inserted_missing_closure missing_close
5 use_quote_code

PASS ../toast/living/jul20/hs-12.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
2 long_title
2 use_quote_code
3 inserted_missing_parent inserted_missing_closure missing_close
3 use_quote_code
11 use_quote_code
15 use_quote_code

PASS ../toast/living/jul20/hs-13.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
16 use_quote_code

PASS ../toast/living/jul20/hs-7.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
18 inserted_missing_closure
19 use_quote_code

PASS ../toast/living/jul20/hs-8.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
31 inserted_missing_closure
33 use_quote_code

PASS ../toast/living/jul20/hs-9.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close

PASS ../toast/living/jul20/i.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jul20/iframe.html
0 charset_mismatch charset_used charset_invalid
9 missing_close
14 use_quote_code
16 missing_close
16 no_such_folder url_not_found
17 inserted_missing_closure
19 no_such_folder url_not_found
20 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
23 no_such_folder url_not_found
24 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1 mixed_mess missing_open
27 no_such_folder url_not_found
28 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
31 use_quote_code
32 url_not_found
35 overallowed
37 url_not_found
39 url_not_found
41 url_not_found
45 attribute_required no_such_folder url_not_found naughty_alt
46 no_such_folder url_not_found
46 url_id_unfound
55 inserted_missing_closure

PASS ../toast/living/jul20/im.html
8 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found

PASS ../toast/living/jul20/img.html
6 url_not_found naughty_alt
8 url_not_found
11 url_not_found
15 url_not_found naughty_alt
18 inserted_missing_closure
21 newline_in_string url_not_found
25 use_quote_code
31 url_not_found
32 use_quote_code
43 newline_in_string
43 newline_in_string url_not_found
45 use_quote_code
51 use_quote_code
52 url_not_found
61 url_not_found naughty_alt
67 url_not_found
67 url_not_found
68 url_not_found
68 url_not_found
69 url_not_found
69 url_not_found
72 interactive
72 url_not_found
72 url_not_found naughty_alt
72 url_not_found naughty_alt
73 interactive
73 url_not_found
73 url_not_found naughty_alt
73 url_not_found naughty_alt
74 url_not_found naughty_alt
76 interactive
76 url_not_found
76 url_not_found
77 url_not_found
78 interactive
78 url_not_found
79 url_not_found
79 url_not_found
79 url_not_found
81 interactive
81 url_not_found
82 url_not_found naughty_alt
82 url_not_found naughty_alt
83 interactive
83 url_not_found
84 url_not_found naughty_alt
84 url_not_found naughty_alt
84 url_not_found naughty_alt
92 newline_in_string no_such_folder url_not_found
98 newline_in_string
98 newline_in_string url_not_found
105 url_not_found
111 no_such_folder url_not_found
111 no_such_folder url_not_found
112 no_such_folder url_not_found
112 no_such_folder url_not_found
119 url_not_found
127 url_not_found
132 use_quote_code
135 url_not_found
140 url_not_found naughty_alt
143 url_not_found naughty_alt
151 newline_in_string no_such_folder url_not_found
157 use_quote_code
159 url_not_found
166 no_such_folder url_not_found naughty_alt
175 no_such_folder url_not_found naughty_alt
189 newline_in_string
189 newline_in_string no_such_folder url_not_found
201 no_such_folder url_not_found
208 url_not_found naughty_alt
211 url_not_found naughty_alt
216 use_quote_code
222 url_not_found
222 url_not_found naughty_alt
225 url_not_found
225 url_not_found naughty_alt
225 url_not_found naughty_alt
226 url_not_found naughty_alt
226 url_not_found naughty_alt
231 url_not_found
233 url_not_found naughty_alt
233 url_not_found
245 newline_in_string
245 newline_in_string url_not_found
252 newline_in_string
252 newline_in_string url_not_found
260 newline_in_string
260 newline_in_string no_such_folder url_not_found
268 newline_in_string
268 newline_in_string no_such_folder url_not_found
277 newline_in_string
277 newline_in_string url_not_found
280 attribute_required url_not_found
286 attribute_required url_not_found naughty_alt
293 attribute_required url_not_found
308 newline_in_string
308 newline_in_string url_not_found
314 attribute_required url_not_found naughty_alt
321 wrong_parent inserted_missing_closure
322 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
324 attribute_required url_not_found naughty_alt
325 wrong_parent inserted_missing_closure
326 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
327 attribute_required url_not_found naughty_alt
328 wrong_parent inserted_missing_closure missing_close
329 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/index.html
3 attribute_unrecognised_here unrecognised_attribute

PASS ../toast/living/jul20/input.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure missing_close
14 inserted_missing_closure
18 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure
29 inserted_missing_closure
30 inserted_missing_closure
31 inserted_missing_closure
32 inserted_missing_closure missing_close
33 inserted_missing_closure
38 inserted_missing_closure
39 inserted_missing_closure
40 inserted_missing_closure missing_close
41 inserted_missing_closure
60 inserted_missing_closure missing_close
61 inserted_missing_closure
69 inserted_missing_closure missing_close
71 inserted_missing_closure
80 id_exists
85 inserted_missing_closure
86 inserted_missing_closure missing_close
88 inserted_missing_closure
93 url_not_found
95 wrong_parent inserted_missing_closure
95 wrong_parent inserted_missing_closure
95 wrong_parent inserted_missing_closure
96 inserted_missing_closure wrong_parent inserted_missing_closure
98 wrong_parent inserted_missing_closure
99 wrong_parent inserted_missing_closure
100 wrong_parent inserted_missing_closure
100 bad_form
101 inserted_missing_closure wrong_parent inserted_missing_closure
103 wrong_parent inserted_missing_closure
104 wrong_parent inserted_missing_closure
105 wrong_parent inserted_missing_closure
105 bad_form
106 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
107 pattern
108 wrong_parent inserted_missing_closure
109 wrong_parent inserted_missing_closure
110 wrong_parent inserted_missing_closure missing_close
110 bad_form
111 inserted_missing_closure inserted_missing_closure
112 bad_form
117 url_not_found
121 inserted_missing_closure
124 inserted_missing_closure
127 inserted_missing_closure missing_close
129 inserted_missing_closure
137 inserted_missing_closure
138 inserted_missing_closure
139 inserted_missing_closure missing_close
140 inserted_missing_closure
166 url_not_found
177 inserted_missing_closure missing_close
178 inserted_missing_closure
182 url_not_found
183 url_not_found naughty_alt
188 placeholder
189 placeholder
191 placeholder
192 placeholder
195 inserted_missing_closure
199 minmax minmax
201 inserted_missing_closure
204 inserted_missing_closure
205 inserted_missing_closure
205 use_quote_code
206 inserted_missing_closure
207 inserted_missing_closure missing_close
207 use_quote_code
208 inserted_missing_closure
210 url_not_found
211 url_not_found
215 inserted_missing_closure missing_close
219 id_exists
221 inserted_missing_closure
222 inserted_missing_closure
223 inserted_missing_closure missing_close
224 inserted_missing_closure
236 minmax
238 inserted_missing_closure

PASS ../toast/living/jul20/label.html
8 unknown_element
8 unknown_element

PASS ../toast/living/jul20/li.html
7 inserted_missing_parent missing_close
10 lingo
11 use_quote_code
20 inserted_missing_closure
23 inserted_missing_parent missing_close
26 lingo
27 use_quote_code
36 inserted_missing_closure
40 inserted_missing_closure
41 inserted_missing_closure missing_close
42 inserted_missing_closure

PASS ../toast/living/jul20/links-alternate.html
7 url_not_found
9 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
15 url_not_found
16 url_not_found
17 url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 no_such_folder url_not_found
22 no_such_folder url_not_found
23 no_such_folder url_not_found
24 no_such_folder url_not_found
33 url_not_found
34 url_not_found
35 url_not_found

PASS ../toast/living/jul20/links-bookmark.html
13 use_quote_code
20 url_not_found

PASS ../toast/living/jul20/links-help.html
10 no_such_folder url_not_found

PASS ../toast/living/jul20/links-icon.html
5 url_not_found
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found

PASS ../toast/living/jul20/links-licence.html
0 charset_mismatch charset_used charset_invalid
5 no_such_folder url_not_found
10 attempted_escape
13 attribute_required no_such_folder url_not_found
19 attempted_escape

PASS ../toast/living/jul20/links-modulepreload.html
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found

PASS ../toast/living/jul20/links-noopener.html
10 url_not_found
12 url_not_found

PASS ../toast/living/jul20/links-noreferrer.html
10 missing_close url_not_found
10 missing_close wrong_parent wrong_parent url_not_found interactive
10 wrong_parent wrong_parent interactive
12 inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/links-tag2.html
19 unrecognised_value

PASS ../toast/living/jul20/ls1.html
8 url_not_found

PASS ../toast/living/jul20/ls10.html
5 element_offsite_base

PASS ../toast/living/jul20/ls11.html
4 long_title
5 element_offsite_base

PASS ../toast/living/jul20/ls13.html
12 use_quote_code

PASS ../toast/living/jul20/ls15.html
3 naughty_lang

PASS ../toast/living/jul20/ls16.html
0 charset_mismatch charset_used charset_invalid
9 url_not_found
10 url_not_found
11 url_not_found
16 url_not_found
17 url_not_found
18 url_not_found
23 bad_property
42 url_not_found
43 url_not_found
44 url_not_found

PASS ../toast/living/jul20/ls17.html
0 charset_mismatch charset_used charset_invalid
11 url_not_found
13 only_elements
25 only_elements

PASS ../toast/living/jul20/ls4.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jul20/ls5.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jul20/ls6.html
3 contradictory_namespace no_xmllang
5 use_quote_code
8 unrecognised_namespace unknown_element
9 unknown_element
9 unknown_element
10 unknown_element
11 unknown_element
11 unknown_element
12 unknown_element

PASS ../toast/living/jul20/main1.html
3 inserted_missing_parent missing_close
14 inserted_missing_parent inserted_missing_closure missing_close
18 attempted_escape no_such_folder url_not_found
19 attempted_escape no_such_folder url_not_found
22 missing_close
23 use_quote_code
23 inserted_missing_closure
32 missing_close
33 inserted_missing_closure
34 inserted_missing_closure

PASS ../toast/living/jul20/main2.html
0 normalise
2 missing_close
3 inserted_missing_parent missing_close
5 url_not_found
6 url_not_found
7 inserted_missing_parent inserted_missing_closure missing_close
8 chocolate_teapot
8 missing_open
9 url_not_found
10 url_not_found
24 missing_open

PASS ../toast/living/jul20/map.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
7 no_such_folder url_not_found
12 missing_close
13 no_such_folder url_not_found
14 no_such_folder url_not_found
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 no_such_folder url_not_found
18 no_such_folder url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 inserted_missing_closure

PASS ../toast/living/jul20/mark.html
9 use_quote_code
16 use_quote_code
25 unrecognised_value
25 unrecognised_value
27 unrecognised_value
28 unrecognised_value
28 unrecognised_value
29 unrecognised_value
46 use_quote_code
48 use_quote_code
51 use_quote_code

PASS ../toast/living/jul20/me.html
7 url_not_found
31 url_not_found
60 url_not_found autoplay

PASS ../toast/living/jul20/menu.html
7 interactive
7 url_not_found
8 interactive
8 url_not_found
9 interactive
9 url_not_found

PASS ../toast/living/jul20/meter.html
7 url_not_found
10 bad_meter
11 bad_meter
16 inserted_missing_closure
17 inserted_missing_closure
17 inserted_missing_closure missing_close
18 inserted_missing_closure
21 inserted_missing_closure
22 inserted_missing_closure
22 inserted_missing_closure missing_close
23 inserted_missing_closure
27 inserted_missing_closure
28 missing_open
31 no_such_folder url_not_found
32 no_such_folder url_not_found
37 no_such_folder url_not_found
38 no_such_folder url_not_found
43 no_such_folder url_not_found
44 no_such_folder url_not_found

PASS ../toast/living/jul20/noscript.html
6 url_not_found
27 url_not_found
30 id_exists

PASS ../toast/living/jul20/object.html
7 url_not_found
12 reputation

PASS ../toast/living/jul20/ol.html
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure missing_close
13 inserted_missing_closure
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure

PASS ../toast/living/jul20/optgroup.html
6 url_not_found
8 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure
16 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure inserted_missing_closure missing_close
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure

PASS ../toast/living/jul20/p.html
48 inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure
56 inserted_missing_closure
57 inserted_missing_closure missing_close
58 inserted_missing_closure

PASS ../toast/living/jul20/param.html
9 mime
16 newline_in_string
16 newline_in_string url_not_found
21 url_not_found

PASS ../toast/living/jul20/q.html
7 use_double_quote_code
10 use_quote_code
12 use_double_quote_code
16 use_double_quote_code
16 use_quote_code
17 use_double_quote_code
23 use_double_quote_code use_quote_code

PASS ../toast/living/jul20/ruby.html
10 missing_close
10 inserted_missing_closure
12 missing_close
12 inserted_missing_closure
12 missing_close
12 inserted_missing_closure
12 missing_close
12 inserted_missing_closure
12 missing_close
13 inserted_missing_closure
15 missing_close
15 inserted_missing_closure
15 missing_close
15 inserted_missing_closure
15 missing_close
15 inserted_missing_closure
18 missing_close
18 inserted_missing_closure
26 missing_close
26 inserted_missing_closure
28 missing_close
28 inserted_missing_closure
30 missing_close
30 inserted_missing_closure
32 missing_close
32 inserted_missing_closure
34 inserted_missing_closure missing_close
34 inserted_missing_closure
35 inserted_missing_closure missing_close
35 inserted_missing_closure
35 inserted_missing_closure missing_close
35 inserted_missing_closure
35 inserted_missing_closure missing_close
35 inserted_missing_closure
36 inserted_missing_closure missing_close
36 inserted_missing_closure
39 inserted_missing_closure
40 inserted_missing_closure
40 inserted_missing_closure
41 inserted_missing_closure
41 inserted_missing_closure missing_close
42 inserted_missing_closure
44 missing_close
44 inserted_missing_closure
59 missing_close
60 inserted_missing_closure

PASS ../toast/living/jul20/samp.html
7 use_quote_code
9 unrecognised_value
13 unrecognised_value
13 unrecognised_value
16 unrecognised_value

PASS ../toast/living/jul20/script.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 mime
37 use_double_quote_code
46 url_not_found
51 use_quote_code
77 bad_script
82 bad_script
100 url_not_found
101 url_not_found
103 url_not_found script

PASS ../toast/living/jul20/select.html
17 bad_select
40 inserted_missing_closure
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure
44 inserted_missing_closure
45 inserted_missing_closure
46 inserted_missing_closure
47 inserted_missing_closure
48 use_quote_code
48 inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure

PASS ../toast/living/jul20/small.html
0 charset_mismatch charset_used charset_invalid
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure missing_close
11 inserted_missing_closure
23 use_double_quote_code

PASS ../toast/living/jul20/source.html
6 inserted_missing_parent missing_close media_descendants
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found
15 url_not_found mime
16 url_not_found mime
17 url_not_found mime
18 url_not_found
19 mime url_not_found
33 autoplay
34 url_not_found
35 url_not_found
39 inserted_missing_closure

PASS ../toast/living/jul20/span.html
6 unrecognised_value
6 unrecognised_value
6 unrecognised_value
7 unrecognised_value
7 unrecognised_value
8 unrecognised_value
8 unrecognised_value
9 lonely_ampersand
9 unrecognised_value
10 unrecognised_value
10 unrecognised_value
11 unrecognised_value
11 unrecognised_value
12 unrecognised_value
13 lonely_ampersand
13 unrecognised_value
13 unrecognised_value
14 unrecognised_value
15 unrecognised_value

PASS ../toast/living/jul20/strong.html
8 inserted_missing_parent missing_close
11 use_quote_code
27 inserted_missing_closure

PASS ../toast/living/jul20/table.html
14 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
23 inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure inserted_missing_closure inserted_missing_closure
36 id_exists
37 wrong_parent inserted_missing_closure
38 wrong_parent inserted_missing_closure
39 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
41 bad_header_id bad_header_id
42 inserted_missing_closure id_exists
43 inserted_missing_closure
44 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
45 id_exists
46 inserted_missing_closure missing_close
47 inserted_missing_closure inserted_missing_closure inserted_missing_closure
61 id_exists
62 wrong_parent inserted_missing_closure
63 wrong_parent inserted_missing_closure
64 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
66 bad_header_id bad_header_id
67 inserted_missing_closure id_exists
68 inserted_missing_closure
69 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
70 bad_header_id bad_header_id
71 inserted_missing_closure id_exists
72 inserted_missing_closure missing_close
73 inserted_missing_closure inserted_missing_closure inserted_missing_closure
83 id_exists
84 wrong_parent inserted_missing_closure
85 wrong_parent inserted_missing_closure
86 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
88 bad_header_id bad_header_id
89 inserted_missing_closure id_exists
90 inserted_missing_closure
91 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
92 bad_header_id bad_header_id
93 inserted_missing_closure id_exists
94 inserted_missing_closure missing_close
95 inserted_missing_closure inserted_missing_closure inserted_missing_closure
107 inserted_missing_parent
107 id_exists
108 wrong_parent inserted_missing_closure
109 wrong_parent inserted_missing_closure
110 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
112 bad_header_id bad_header_id
113 inserted_missing_closure id_exists
114 inserted_missing_closure
115 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
116 bad_header_id bad_header_id
117 inserted_missing_closure id_exists
118 inserted_missing_closure missing_close
119 inserted_missing_closure inserted_missing_closure inserted_missing_closure
127 wrong_parent inserted_missing_closure
128 wrong_parent inserted_missing_closure
129 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
132 inserted_missing_closure
133 wrong_parent inserted_missing_closure
134 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
136 inserted_missing_closure
137 wrong_parent inserted_missing_closure missing_close
138 inserted_missing_closure inserted_missing_closure inserted_missing_closure
147 use_quote_code
150 inserted_missing_closure
151 inserted_missing_closure
152 inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
154 inserted_missing_closure wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
155 inserted_missing_closure wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
156 inserted_missing_closure inserted_missing_closure inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
158 inserted_missing_closure wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
159 inserted_missing_closure wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
160 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
162 inserted_missing_closure wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
163 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure missing_close
164 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/td.html
9 wrong_parent inserted_missing_closure
10 inserted_missing_closure wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 inserted_missing_closure wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure wrong_parent inserted_missing_closure
18 wrong_parent inserted_missing_closure
19 inserted_missing_closure wrong_parent inserted_missing_closure
21 wrong_parent inserted_missing_closure
22 inserted_missing_closure wrong_parent inserted_missing_closure
24 wrong_parent inserted_missing_closure
25 inserted_missing_closure wrong_parent inserted_missing_closure
27 wrong_parent inserted_missing_closure
28 inserted_missing_closure wrong_parent inserted_missing_closure
30 wrong_parent inserted_missing_closure
31 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
33 inserted_missing_closure missing_close
33 missing_close attribute_barred
34 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/te.html
54 wrong_parent inserted_missing_closure
55 wrong_parent inserted_missing_closure
56 wrong_parent inserted_missing_closure
57 inserted_missing_closure inserted_missing_closure inserted_missing_closure
60 inserted_missing_closure
61 wrong_parent inserted_missing_closure
62 wrong_parent inserted_missing_closure
63 inserted_missing_closure wrong_parent inserted_missing_closure
65 inserted_missing_closure
66 wrong_parent inserted_missing_closure
67 wrong_parent inserted_missing_closure
68 inserted_missing_closure inserted_missing_closure inserted_missing_closure
71 inserted_missing_closure
72 wrong_parent inserted_missing_closure
73 wrong_parent inserted_missing_closure
74 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
75 missing_close
77 inserted_missing_closure
78 wrong_parent inserted_missing_closure
79 wrong_parent inserted_missing_closure missing_close
80 inserted_missing_closure inserted_missing_closure inserted_missing_closure
84 inserted_missing_closure
85 inserted_missing_closure
86 wrong_parent inserted_missing_closure
86 wrong_parent inserted_missing_closure
86 wrong_parent inserted_missing_closure
87 inserted_missing_closure inserted_missing_closure inserted_missing_closure
89 inserted_missing_closure
89 wrong_parent inserted_missing_closure
89 wrong_parent inserted_missing_closure
90 inserted_missing_closure wrong_parent inserted_missing_closure
91 inserted_missing_closure
91 wrong_parent inserted_missing_closure
91 wrong_parent inserted_missing_closure
92 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
94 inserted_missing_closure
94 wrong_parent inserted_missing_closure
94 wrong_parent inserted_missing_closure
95 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
96 inserted_missing_closure
96 wrong_parent inserted_missing_closure
96 wrong_parent inserted_missing_closure missing_close
97 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/template1.html
5 inserted_missing_closure missing_close
16 inserted_missing_closure

PASS ../toast/living/jul20/template2.html
2 inserted_missing_parent missing_close naughty_lang
2 inserted_missing_parent missing_close
10 inserted_missing_parent inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
16 missing_close
16 wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure
18 inserted_missing_closure

PASS ../toast/living/jul20/textarea.html
12 use_quote_code use_double_quote_code
21 bad_textarea
31 newline_in_string
31 newline_in_string

PASS ../toast/living/jul20/th.html
8 wrong_parent inserted_missing_closure
8 wrong_parent inserted_missing_closure
8 wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure
10 inserted_missing_closure
10 inserted_missing_closure
10 wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
14 inserted_missing_closure
14 inserted_missing_closure
14 wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
16 wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jul20/thead.html
11 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
17 wrong_parent inserted_missing_closure
18 wrong_parent inserted_missing_closure
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
22 wrong_parent inserted_missing_closure
23 wrong_parent inserted_missing_closure
23 attribute_required naughty_alt
24 wrong_parent inserted_missing_closure
25 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
27 wrong_parent inserted_missing_closure
28 wrong_parent inserted_missing_closure
29 wrong_parent inserted_missing_closure missing_close
30 inserted_missing_closure inserted_missing_closure inserted_missing_closure
31 url_not_found

PASS ../toast/living/jul20/time.html
75 schema_domain

PASS ../toast/living/jul20/tls.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
15 inserted_missing_closure
15 inserted_missing_closure missing_close
15 inserted_missing_closure
25 unrecognised_value
28 use_double_quote_code
29 use_double_quote_code

PASS ../toast/living/jul20/track.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found

PASS ../toast/living/jul20/ul.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure

PASS ../toast/living/jul20/us-1.html
2 naughty_lang
3 use_quote_code

PASS ../toast/living/jul20/us-2.html
11 url_not_found
16 url_not_found naughty_alt

PASS ../toast/living/jul20/us-4.html
12 inserted_missing_closure
12 url_not_found
13 inserted_missing_closure missing_close
13 url_not_found
14 inserted_missing_closure

PASS ../toast/living/jul20/us-5.html
12 url_not_found

PASS ../toast/living/jul20/var.html
21 use_quote_code
27 use_quote_code

PASS ../toast/living/jul20/video.html
30 url_not_found autoplay
31 url_not_found

PASS ../toast/living/jul20/wbr.html
7 use_double_quote_code
7 use_double_quote_code

update
0 normalise normalise
