[general]
verbose=5
output=../out/css4filter.out
class=

[css]
verify=
extension=css
version=3
filter=4

[html]
version=2026/07/01

[nits]
nids=

[site]
domain=example.edu
extension=html
extension=svg
index=index.html
root=../toast/css/4-filter

[spell]
no-check=
