-f tests/HTML/4.00/html4.conf

PASS tests/HTML/4.00/html4-simple.html
11 missing_close
12 inserted_missing_closure

PASS tests/HTML/4.00/svg1-example.html
79 attribute_required
90 id_exists
118 url_not_found
237 id_exists
253 missing_close
255 inserted_missing_closure
265 id_exists
304 attribute_unrecognised_here attribute_unrecognised_here unrecognised_attribute
313 id_exists
321 attribute_unrecognised_here attribute_unrecognised_here unrecognised_attribute
331 id_exists
427 url_not_found
436 attribute_unrecognised unrecognised_attribute url_not_found
451 inserted_missing_parent missing_close
454 attribute_barred
470 unrecognised_value bad_colour
475 id_exists
479 attribute_unrecognised_here attribute_unrecognised_here unrecognised_attribute id_exists
488 inserted_missing_closure
500 attribute_unrecognised unrecognised_attribute
510 attribute_required
551 attribute_unrecognised unrecognised_attribute
552 ignoring_unknown ignoring_unknown
553 ignoring_unknown
554 ignoring_unknown ignoring_unknown ignoring_unknown
