[general]
verbose=5
output=../out/microlink.out
thread=1

[html]
version=2024/01/01

[link]
check=
xlink=

[nits]
nids=

[ontology]
schema=26

[site]
domain=example.edu
extension=shtml
index=index.shtml
root=../toast/microdata/link

[stats]
summary=
