-N 1 -f ../toast/living/jan12/living.conf

PASS ../toast/living/jan12/a.html
9 url_not_found
10 chocolate_teapot
11 url_not_found
15 unrecognised_value

PASS ../toast/living/jan12/abbr.html
17 id_exists
35 naughty_grave

PASS ../toast/living/jan12/address.html
0 charset_mismatch charset_used charset_invalid
11 attempted_escape no_such_folder url_not_found
12 attempted_escape no_such_folder url_not_found
13 url_not_found

PASS ../toast/living/jan12/aside-2.html
0 charset_mismatch charset_used charset_invalid
16 missing_close
17 inserted_missing_closure
22 url_not_found
23 inserted_missing_closure missing_close
23 url_not_found
24 inserted_missing_closure
32 use_quote_code
35 use_quote_code
43 missing_close
43 url_not_found
44 inserted_missing_closure
57 use_quote_code
60 missing_close
60 url_not_found
61 inserted_missing_closure
65 url_not_found
66 url_not_found
67 url_not_found

PASS ../toast/living/jan12/aside.html
0 charset_mismatch charset_used charset_invalid
19 use_quote_code
22 use_quote_code
25 use_quote_code

PASS ../toast/living/jan12/b.html
0 charset_mismatch charset_used charset_invalid
12 use_quote_code

PASS ../toast/living/jan12/blockquote.html
0 charset_mismatch charset_used charset_invalid
7 missing_close
8 use_quote_code
10 inserted_missing_closure
19 use_quote_code
25 use_quote_code
28 use_quote_code
42 use_quote_code
48 use_double_quote_code
57 inserted_missing_closure
66 use_quote_code
68 use_double_quote_code
69 use_double_quote_code
73 inserted_missing_closure

PASS ../toast/living/jan12/caption.html
9 inserted_missing_closure missing_close
13 inserted_missing_closure

PASS ../toast/living/jan12/command.html
7 no_such_folder url_not_found unknown
8 no_such_folder url_not_found unknown
9 no_such_folder url_not_found unknown
11 no_such_folder url_not_found

PASS ../toast/living/jan12/data.html
10 unrecognised_value
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
12 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure
14 wrong_parent inserted_missing_closure
14 wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
15 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure missing_close
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan12/dd.html
0 charset_mismatch charset_used charset_invalid
8 unrecognised_value
8 use_quote_code
9 unrecognised_value
13 unrecognised_value
13 use_quote_code
14 unrecognised_value
16 unrecognised_value

PASS ../toast/living/jan12/del.html
9 use_quote_code

PASS ../toast/living/jan12/details.html
0 charset_mismatch charset_used charset_invalid
6 unrecognised_value unrecognised_value
7 use_double_quote_code
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jan12/dfn.html
9 use_quote_code
15 use_quote_code

PASS ../toast/living/jan12/div.html
10 use_quote_code
18 use_quote_code use_double_quote_code
20 use_double_quote_code

PASS ../toast/living/jan12/dl.html
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
54 use_quote_code

PASS ../toast/living/jan12/el.html
9 use_quote_code
13 use_quote_code
27 missing_close
28 inserted_missing_closure

PASS ../toast/living/jan12/embed.html
6 reputation url_not_found
8 wild_attribute reputation wild_attribute url_not_found
10 reputation url_not_found

PASS ../toast/living/jan12/et.html
8 wrong_parent inserted_missing_closure
8 wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
10 wrong_parent inserted_missing_closure
10 wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
12 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure missing_close
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure
17 wrong_parent inserted_missing_closure
17 wrong_parent inserted_missing_closure
18 no_such_folder url_not_found
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
20 wrong_parent inserted_missing_closure
20 wrong_parent inserted_missing_closure
21 no_such_folder url_not_found
22 inserted_missing_closure wrong_parent inserted_missing_closure
22 wrong_parent inserted_missing_closure
22 wrong_parent inserted_missing_closure
23 no_such_folder url_not_found
24 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
24 wrong_parent inserted_missing_closure
24 wrong_parent inserted_missing_closure missing_close
25 no_such_folder url_not_found
26 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan12/example-2.html
4 url_not_found style_not_css
5 url_not_found
6 url_not_found
11 url_not_found
13 url_not_found
15 url_not_found
16 url_not_found
17 url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
22 no_such_folder url_not_found
24 no_such_folder url_not_found
25 no_such_folder url_not_found
26 no_such_folder url_not_found
35 url_not_found
36 mime
50 use_quote_code
64 use_quote_code
68 bad_property bad_property bad_property bad_property bad_property
78 bad_property bad_property bad_property bad_property bad_property
109 unrecognised_value
124 use_quote_code
134 use_quote_code

PASS ../toast/living/jan12/example.html
6 missing_close
6 inserted_missing_closure
6 missing_open
10 url_not_found
28 url_not_found
29 inserted_missing_closure
29 url_not_found
30 inserted_missing_closure missing_close
30 url_not_found
31 inserted_missing_closure
33 url_not_found
44 url_not_found
53 inserted_missing_closure inserted_missing_closure
54 inserted_missing_closure inserted_missing_closure
55 inserted_missing_closure inserted_missing_closure
57 character_code
59 character_code
61 character_code
66 inserted_missing_closure inserted_missing_closure
66 missing_open
68 inserted_missing_closure unrecognised_value
69 input_bad_aria
71 inserted_missing_closure
75 attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute
85 unrecognised_value no_such_folder url_not_found
87 attribute_unrecognised unrecognised_attribute unrecognised_value
89 unrecognised_value
92 unrecognised_namespace unknown_element
95 unknown_element
99 newline_in_string
99 newline_in_string
101 unrecognised_value
102 use_double_quote_code use_quote_code
103 unrecognised_value
104 inserted_missing_closure unrecognised_value
105 unrecognised_value
106 use_quote_code use_double_quote_code
106 inserted_missing_closure unrecognised_value
106 use_double_quote_code
107 unrecognised_value
107 use_double_quote_code
110 newline_in_string
110 newline_in_string
111 newline_in_string
111 newline_in_string
116 only_elements
120 unrecognised_value
122 unrecognised_value
127 data_type
127 attribute_required attribute_required
127 attribute_required
145 url_not_found
151 use_quote_code
154 url_not_found
155 url_not_found
156 url_not_found
158 use_quote_code
164 url_not_found
167 url_not_found
168 inserted_missing_closure missing_close
169 inserted_missing_closure
173 use_quote_code
183 use_quote_code naughty_grave naughty_grave naughty_grave naughty_grave naughty_grave
185 use_double_quote_code
186 use_double_quote_code

PASS ../toast/living/jan12/fieldset.html
12 pattern
27 pattern
34 pattern
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure missing_close
47 inserted_missing_closure missing_close
48 inserted_missing_closure
49 inserted_missing_closure

PASS ../toast/living/jan12/figure.html
21 newline_in_string
21 newline_in_string url_not_found
25 use_quote_code
29 use_double_quote_code
29 inserted_missing_closure
30 url_not_found
35 inserted_missing_closure
36 url_not_found
40 url_not_found
45 inserted_missing_closure
46 use_quote_code
55 url_not_found
57 url_not_found
60 newline_in_string
60 newline_in_string url_not_found
65 url_not_found
67 url_not_found
69 url_not_found

PASS ../toast/living/jan12/footer-2.html
0 charset_mismatch charset_used charset_invalid
4 inserted_missing_closure
8 attribute_unrecognised unrecognised_attribute no_such_folder url_not_found
9 no_such_folder url_not_found
26 url_not_found
27 url_not_found

PASS ../toast/living/jan12/footer-3.html
0 charset_mismatch charset_used charset_invalid
13 no_such_folder url_not_found naughty_alt
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 attribute_required no_such_folder url_not_found naughty_alt
19 no_such_folder url_not_found
21 attribute_required no_such_folder url_not_found naughty_alt
23 use_quote_code
23 no_such_folder url_not_found
26 url_not_found
27 inserted_missing_closure
27 url_not_found
28 inserted_missing_closure missing_close
28 url_not_found
29 inserted_missing_closure
32 url_not_found

PASS ../toast/living/jan12/footer.html
9 attempted_escape
18 attempted_escape

PASS ../toast/living/jan12/formex.html
18 url_not_found
20 missing_close
20 inserted_missing_closure
40 url_not_found
46 url_not_found

PASS ../toast/living/jan12/forms.html
119 inserted_missing_closure missing_close
120 inserted_missing_closure
144 inserted_missing_closure missing_close
145 inserted_missing_closure
169 inserted_missing_closure missing_close
170 inserted_missing_closure
195 inserted_missing_closure missing_close
196 inserted_missing_closure

PASS ../toast/living/jan12/h-1.html
6 use_quote_code

PASS ../toast/living/jan12/h-2.html
6 use_quote_code

PASS ../toast/living/jan12/header-2.html
14 url_not_found
15 inserted_missing_closure
15 url_not_found
16 inserted_missing_closure missing_close
16 url_not_found
17 inserted_missing_closure
21 use_quote_code

PASS ../toast/living/jan12/header.html
31 url_id_unfound
33 unrecognised_value

PASS ../toast/living/jan12/hr.html
17 use_quote_code
47 use_quote_code
49 use_quote_code
58 use_quote_code

PASS ../toast/living/jan12/i.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan12/iframe.html
9 missing_close
14 use_quote_code
16 no_such_folder url_not_found
20 no_such_folder url_not_found
22 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
25 no_such_folder url_not_found
27 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1 mixed_mess missing_open
30 no_such_folder url_not_found
32 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
35 use_quote_code
36 url_not_found
39 overallowed
41 url_not_found
43 url_not_found
45 url_not_found
47 url_not_found
52 inserted_missing_closure

PASS ../toast/living/jan12/im.html
8 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found

PASS ../toast/living/jan12/img.html
6 url_not_found naughty_alt
8 url_not_found
11 url_not_found
15 url_not_found naughty_alt
18 inserted_missing_closure
21 newline_in_string url_not_found
25 use_quote_code
31 url_not_found
32 use_quote_code
43 newline_in_string
43 newline_in_string url_not_found
45 use_quote_code
51 use_quote_code
52 url_not_found
61 url_not_found naughty_alt
67 url_not_found
67 url_not_found
68 url_not_found
68 url_not_found
69 url_not_found
69 url_not_found
72 interactive
72 url_not_found
72 url_not_found naughty_alt
72 url_not_found naughty_alt
73 interactive
73 url_not_found
73 url_not_found naughty_alt
73 url_not_found naughty_alt
74 url_not_found naughty_alt
76 interactive
76 url_not_found
76 url_not_found
77 url_not_found
78 interactive
78 url_not_found
79 url_not_found
79 url_not_found
79 url_not_found
81 interactive
81 url_not_found
82 url_not_found naughty_alt
82 url_not_found naughty_alt
83 interactive
83 url_not_found
84 url_not_found naughty_alt
84 url_not_found naughty_alt
84 url_not_found naughty_alt
92 newline_in_string no_such_folder url_not_found
98 newline_in_string
98 newline_in_string url_not_found
105 url_not_found
111 no_such_folder url_not_found
111 no_such_folder url_not_found naughty_alt
112 no_such_folder url_not_found
112 no_such_folder url_not_found naughty_alt
119 url_not_found
127 url_not_found
132 use_quote_code
135 url_not_found
140 url_not_found naughty_alt
143 url_not_found naughty_alt
151 newline_in_string no_such_folder url_not_found
157 use_quote_code
159 url_not_found
166 no_such_folder url_not_found naughty_alt
175 no_such_folder url_not_found naughty_alt
189 newline_in_string
189 newline_in_string no_such_folder url_not_found
201 no_such_folder url_not_found
208 url_not_found naughty_alt
211 url_not_found naughty_alt
216 use_quote_code
222 url_not_found
222 url_not_found naughty_alt
225 url_not_found
225 url_not_found naughty_alt
225 url_not_found naughty_alt
226 url_not_found naughty_alt
226 url_not_found naughty_alt
231 url_not_found
233 url_not_found naughty_alt
233 url_not_found
245 newline_in_string
245 newline_in_string url_not_found
252 newline_in_string
252 newline_in_string url_not_found
260 newline_in_string
260 newline_in_string no_such_folder url_not_found
268 newline_in_string
268 newline_in_string no_such_folder url_not_found
277 newline_in_string
277 newline_in_string url_not_found
280 attribute_required url_not_found
286 attribute_required url_not_found naughty_alt
293 attribute_required url_not_found
308 newline_in_string
308 newline_in_string url_not_found
314 attribute_required url_not_found naughty_alt
321 wrong_parent inserted_missing_closure
322 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
324 attribute_required url_not_found naughty_alt
325 wrong_parent inserted_missing_closure
326 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
327 attribute_required url_not_found naughty_alt
328 wrong_parent inserted_missing_closure missing_close
329 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan12/index.html
3 attribute_unrecognised_here unrecognised_attribute

PASS ../toast/living/jan12/input.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure missing_close
14 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure
29 inserted_missing_closure
30 inserted_missing_closure
31 inserted_missing_closure
32 inserted_missing_closure missing_close
33 inserted_missing_closure
38 inserted_missing_closure
39 inserted_missing_closure
40 inserted_missing_closure missing_close
41 inserted_missing_closure
60 inserted_missing_closure missing_close
61 inserted_missing_closure
69 inserted_missing_closure missing_close
71 inserted_missing_closure
80 id_exists
85 inserted_missing_closure
86 inserted_missing_closure missing_close
88 inserted_missing_closure
93 url_not_found
95 wrong_parent inserted_missing_closure
95 wrong_parent inserted_missing_closure
95 wrong_parent inserted_missing_closure
96 inserted_missing_closure wrong_parent inserted_missing_closure
98 wrong_parent inserted_missing_closure
99 wrong_parent inserted_missing_closure
100 wrong_parent inserted_missing_closure
100 bad_form
101 inserted_missing_closure wrong_parent inserted_missing_closure
103 wrong_parent inserted_missing_closure
104 wrong_parent inserted_missing_closure
105 wrong_parent inserted_missing_closure
105 bad_form
106 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
107 pattern
108 wrong_parent inserted_missing_closure
109 wrong_parent inserted_missing_closure
110 wrong_parent inserted_missing_closure missing_close
110 bad_form
111 inserted_missing_closure inserted_missing_closure
112 bad_form
117 url_not_found
121 inserted_missing_closure
124 inserted_missing_closure
127 inserted_missing_closure missing_close
129 inserted_missing_closure
137 inserted_missing_closure
138 inserted_missing_closure
139 inserted_missing_closure missing_close
140 inserted_missing_closure
166 url_not_found

PASS ../toast/living/jan12/keygen.html
6 url_not_found

PASS ../toast/living/jan12/li.html
7 inserted_missing_parent missing_close
10 lingo
11 use_quote_code
20 inserted_missing_closure
23 inserted_missing_parent missing_close
26 lingo
27 use_quote_code
36 inserted_missing_closure

PASS ../toast/living/jan12/links-alternate.html
5 url_not_found
6 url_not_found
15 url_not_found
16 url_not_found
19 url_not_found

PASS ../toast/living/jan12/links-bookmark.html
13 use_quote_code
20 url_not_found

PASS ../toast/living/jan12/links-help.html
10 no_such_folder url_not_found

PASS ../toast/living/jan12/links-icon.html
5 url_not_found
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found

PASS ../toast/living/jan12/links-licence.html
0 charset_mismatch charset_used charset_invalid
5 no_such_folder url_not_found
10 attempted_escape
13 attribute_required no_such_folder url_not_found
19 attempted_escape

PASS ../toast/living/jan12/ls1.html
8 url_not_found

PASS ../toast/living/jan12/ls11.html
12 use_quote_code

PASS ../toast/living/jan12/ls14.html
0 charset_mismatch charset_used charset_invalid
9 url_not_found
10 url_not_found
11 url_not_found
16 url_not_found
17 url_not_found
18 url_not_found
39 url_not_found
40 url_not_found
41 url_not_found

PASS ../toast/living/jan12/ls15.html
0 charset_mismatch charset_used charset_invalid
11 url_not_found
13 only_elements
25 only_elements

PASS ../toast/living/jan12/ls3.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan12/ls4.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan12/ls5.html
3 contradictory_namespace
5 use_quote_code
8 unrecognised_namespace unknown_element
9 unknown_element
9 unknown_element
10 unknown_element
11 unknown_element
11 unknown_element
12 unknown_element

PASS ../toast/living/jan12/ls8.html
5 element_offsite_base

PASS ../toast/living/jan12/ls9.html
4 long_title
5 element_offsite_base

PASS ../toast/living/jan12/map.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close
2 inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
7 no_such_folder url_not_found
12 missing_close
13 no_such_folder url_not_found
14 no_such_folder url_not_found
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 no_such_folder url_not_found
18 no_such_folder url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 inserted_missing_closure

PASS ../toast/living/jan12/mark.html
9 use_quote_code
16 use_quote_code
25 unrecognised_value
25 unrecognised_value
27 unrecognised_value
28 unrecognised_value
28 unrecognised_value
29 unrecognised_value
46 use_quote_code
48 use_quote_code
51 use_quote_code

PASS ../toast/living/jan12/me.html
7 url_not_found
57 css_syntax property
57 css_syntax property
65 url_not_found autoplay
66 url_not_found autoplay
88 url_not_found autoplay

PASS ../toast/living/jan12/menu.html
8 no_such_folder url_not_found unknown
10 no_such_folder url_not_found unknown
12 no_such_folder url_not_found unknown
15 no_such_folder url_not_found
36 url_not_found
37 url_not_found
42 url_not_found
48 newline_in_string
48 newline_in_string
63 newline_in_string
63 newline_in_string

PASS ../toast/living/jan12/meter.html
7 url_not_found
10 bad_meter
11 bad_meter
16 inserted_missing_closure
17 inserted_missing_closure
17 inserted_missing_closure missing_close
18 inserted_missing_closure
21 inserted_missing_closure
22 inserted_missing_closure
22 inserted_missing_closure missing_close
23 inserted_missing_closure
31 no_such_folder url_not_found
32 no_such_folder url_not_found
37 no_such_folder url_not_found
38 no_such_folder url_not_found
43 no_such_folder url_not_found
44 no_such_folder url_not_found

PASS ../toast/living/jan12/noscript.html
6 url_not_found
27 url_not_found
30 id_exists

PASS ../toast/living/jan12/object.html
15 url_not_found
20 reputation

PASS ../toast/living/jan12/ol.html
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure missing_close
13 inserted_missing_closure
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure

PASS ../toast/living/jan12/optgroup.html
6 url_not_found
8 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure
16 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure inserted_missing_closure missing_close
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure

PASS ../toast/living/jan12/p.html
48 inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure
56 inserted_missing_closure
57 inserted_missing_closure missing_close
58 inserted_missing_closure

PASS ../toast/living/jan12/param.html
9 mime
16 newline_in_string
16 newline_in_string url_not_found
21 url_not_found

PASS ../toast/living/jan12/q.html
7 use_double_quote_code
10 use_quote_code
12 use_double_quote_code
16 use_double_quote_code
16 use_quote_code
17 use_double_quote_code
23 use_double_quote_code use_quote_code

PASS ../toast/living/jan12/samp.html
7 use_quote_code
9 unrecognised_value
13 unrecognised_value
13 unrecognised_value

PASS ../toast/living/jan12/script.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 mime
37 use_double_quote_code

PASS ../toast/living/jan12/select.html
17 bad_select
40 inserted_missing_closure
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure
44 inserted_missing_closure
45 inserted_missing_closure
46 inserted_missing_closure
47 inserted_missing_closure
48 use_quote_code
48 inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure

PASS ../toast/living/jan12/small.html
0 charset_mismatch charset_used charset_invalid
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure missing_close
11 inserted_missing_closure
23 use_double_quote_code

PASS ../toast/living/jan12/source.html
6 inserted_missing_parent missing_close media_descendants
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found
15 url_not_found mime
16 url_not_found mime
17 url_not_found mime
18 url_not_found
19 mime url_not_found
33 autoplay
34 url_not_found
35 url_not_found
39 inserted_missing_closure

PASS ../toast/living/jan12/span.html
6 unrecognised_value
6 unrecognised_value
6 unrecognised_value
7 unrecognised_value
7 unrecognised_value
8 unrecognised_value
8 unrecognised_value
9 lonely_ampersand
9 unrecognised_value
10 unrecognised_value
10 unrecognised_value
11 unrecognised_value
11 unrecognised_value
12 unrecognised_value
13 lonely_ampersand
13 unrecognised_value
13 unrecognised_value
14 unrecognised_value
15 unrecognised_value

PASS ../toast/living/jan12/table.html
14 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
23 inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure inserted_missing_closure inserted_missing_closure
36 id_exists
37 wrong_parent inserted_missing_closure
38 wrong_parent inserted_missing_closure
39 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
41 bad_header_id bad_header_id
42 inserted_missing_closure id_exists
43 inserted_missing_closure
44 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
45 id_exists
46 inserted_missing_closure missing_close
47 inserted_missing_closure inserted_missing_closure inserted_missing_closure
61 id_exists
62 wrong_parent inserted_missing_closure
63 wrong_parent inserted_missing_closure
64 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
66 bad_header_id bad_header_id
67 inserted_missing_closure id_exists
68 inserted_missing_closure
69 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
70 bad_header_id bad_header_id
71 inserted_missing_closure id_exists
72 inserted_missing_closure missing_close
73 inserted_missing_closure inserted_missing_closure inserted_missing_closure
83 id_exists
84 wrong_parent inserted_missing_closure
85 wrong_parent inserted_missing_closure
86 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
88 bad_header_id bad_header_id
89 inserted_missing_closure id_exists
90 inserted_missing_closure
91 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
92 bad_header_id bad_header_id
93 inserted_missing_closure id_exists
94 inserted_missing_closure missing_close
95 inserted_missing_closure inserted_missing_closure inserted_missing_closure
107 inserted_missing_parent
107 id_exists
108 wrong_parent inserted_missing_closure
109 wrong_parent inserted_missing_closure
110 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
112 bad_header_id bad_header_id
113 inserted_missing_closure id_exists
114 inserted_missing_closure
115 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
116 bad_header_id bad_header_id
117 inserted_missing_closure id_exists
118 inserted_missing_closure missing_close
119 inserted_missing_closure inserted_missing_closure inserted_missing_closure
127 wrong_parent inserted_missing_closure
128 wrong_parent inserted_missing_closure
129 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
132 inserted_missing_closure
133 wrong_parent inserted_missing_closure
134 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
136 inserted_missing_closure
137 wrong_parent inserted_missing_closure missing_close
138 inserted_missing_closure inserted_missing_closure inserted_missing_closure
147 use_quote_code
150 inserted_missing_closure
151 inserted_missing_closure
152 inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
153 wrong_parent inserted_missing_closure
154 inserted_missing_closure wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
154 wrong_parent inserted_missing_closure
155 inserted_missing_closure wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
155 wrong_parent inserted_missing_closure
156 inserted_missing_closure inserted_missing_closure inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
157 wrong_parent inserted_missing_closure
158 inserted_missing_closure wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
158 wrong_parent inserted_missing_closure
159 inserted_missing_closure wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
159 wrong_parent inserted_missing_closure
160 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
161 wrong_parent inserted_missing_closure
162 inserted_missing_closure wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
162 wrong_parent inserted_missing_closure
163 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure
163 wrong_parent inserted_missing_closure missing_close
164 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan12/te.html
54 wrong_parent inserted_missing_closure
55 wrong_parent inserted_missing_closure
56 wrong_parent inserted_missing_closure
57 inserted_missing_closure inserted_missing_closure inserted_missing_closure
60 inserted_missing_closure
61 wrong_parent inserted_missing_closure
62 wrong_parent inserted_missing_closure
63 inserted_missing_closure wrong_parent inserted_missing_closure
65 inserted_missing_closure
66 wrong_parent inserted_missing_closure
67 wrong_parent inserted_missing_closure
68 inserted_missing_closure inserted_missing_closure inserted_missing_closure
71 inserted_missing_closure
72 wrong_parent inserted_missing_closure
73 wrong_parent inserted_missing_closure
74 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
75 missing_close
77 inserted_missing_closure
78 wrong_parent inserted_missing_closure
79 wrong_parent inserted_missing_closure missing_close
80 inserted_missing_closure inserted_missing_closure inserted_missing_closure
84 inserted_missing_closure
85 inserted_missing_closure
86 wrong_parent inserted_missing_closure
86 wrong_parent inserted_missing_closure
86 wrong_parent inserted_missing_closure
87 inserted_missing_closure inserted_missing_closure inserted_missing_closure
89 inserted_missing_closure
89 wrong_parent inserted_missing_closure
89 wrong_parent inserted_missing_closure
90 inserted_missing_closure wrong_parent inserted_missing_closure
91 inserted_missing_closure
91 wrong_parent inserted_missing_closure
91 wrong_parent inserted_missing_closure
92 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
94 inserted_missing_closure
94 wrong_parent inserted_missing_closure
94 wrong_parent inserted_missing_closure
95 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
96 inserted_missing_closure
96 wrong_parent inserted_missing_closure
96 wrong_parent inserted_missing_closure missing_close
97 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan12/th.html
8 wrong_parent inserted_missing_closure
8 wrong_parent inserted_missing_closure
8 wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure
10 inserted_missing_closure
10 inserted_missing_closure
10 wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
11 wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
14 inserted_missing_closure
14 inserted_missing_closure
14 wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
16 wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan12/thead.html
11 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
17 wrong_parent inserted_missing_closure
18 wrong_parent inserted_missing_closure
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
22 wrong_parent inserted_missing_closure
23 wrong_parent inserted_missing_closure
23 attribute_required naughty_alt
24 wrong_parent inserted_missing_closure
25 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
27 wrong_parent inserted_missing_closure
28 wrong_parent inserted_missing_closure
29 wrong_parent inserted_missing_closure missing_close
30 inserted_missing_closure inserted_missing_closure inserted_missing_closure
31 url_not_found

PASS ../toast/living/jan12/time.html
75 ontology_domain

PASS ../toast/living/jan12/tls.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
15 inserted_missing_closure
15 inserted_missing_closure missing_close
15 inserted_missing_closure
25 unrecognised_value
28 use_double_quote_code
29 use_double_quote_code

PASS ../toast/living/jan12/track.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found

PASS ../toast/living/jan12/ul.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure

PASS ../toast/living/jan12/var.html
21 use_quote_code
27 use_quote_code

PASS ../toast/living/jan12/video.html
30 url_not_found autoplay
31 url_not_found

PASS ../toast/living/jan12/wbr.html
7 use_double_quote_code
7 use_double_quote_code
