[general]
verbose=info
output=e:\www\live.out
ignore=pre
rpt=
vcs=
progress=
class=
classic=
no-rel=

[css]
verify=
extension=css
version=3

[html]
version=2024/01/01
title=80
rfc1942=
rfc2070=
ie=
safari=

[link]
no-external=
xlink=
pretend=cgi-bin
local=

[microformat]
verify=

[nits]
silence=use_double_quote_code
silence=use_quote_code
silence=missing_itemtype
nids=

[shadow]
copy=dedu
root=E:\www\live
file=e:\www\live.ndx
ignore=.inc
ignore=.DS_Store
info=
update=
msg=arts & ego, the identity site of dylan harris, is (c) 1978-2024 dylan harris

[site]
domain=dylanharris.org
extension=shtml
extension=html
extension=htm
extension=asp
index=index.shtml
root=E:\project\web\live

[spell]
check=

[ssi]
verify=

[stats]
summary=

[validation]
lang=ma
fontname=Advent
fontname=ArialMT
fontname=Arial-BoldMT
fontname=droid-sans-mono
fontname=Lucida Bright
fontname=Lucida Fax
fontname=Marain
fontname=Times-Italic
fontname=Times-Roman
fontname=TimesNewRomanPSMT
fontname=TrebuchetMS
fontname=TrebuchetMS-Italic
