-f ../toast/living/jan11/living.conf

PASS ../toast/living/jan11/example.html
6 inserted_missing_closure missing_open
8 inserted_missing_closure missing_open
18 attribute_required
19 ignoring_unknown attribute_barred ignoring_unknown
20 inserted_missing_closure
23 missing_open
26 inserted_missing_closure inserted_missing_closure
27 inserted_missing_closure inserted_missing_closure
28 inserted_missing_closure inserted_missing_closure
30 inserted_missing_closure
39 inserted_missing_closure missing_close missing_open
41 inserted_missing_parent inserted_missing_closure inserted_missing_parent invalid_attribute_version wrong_version
42 inserted_missing_closure inserted_missing_closure inserted_missing_closure invalid_attribute_version wrong_version input_bad_aria
44 inserted_missing_closure attribute_required inserted_missing_closure missing_open
46 attribute_required inserted_missing_closure missing_open
50 attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute
52 inserted_missing_closure missing_open
54 inserted_missing_closure
55 missing_open
57 inserted_missing_closure missing_open
61 attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised unrecognised_value unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute invalid_attribute_version wrong_version no_such_folder url_not_found
64 unrecognised_value unrecognised_value
65 unrecognised_value unrecognised_value
66 unrecognised_value unrecognised_value
69 inserted_missing_closure attribute_unrecognised unrecognised_attribute unrecognised_value missing_open
72 newline_in_string inserted_missing_closure newline_in_string attribute_unrecognised unrecognised_value unrecognised_attribute missing_open
75 newline_in_string newline_in_string
77 unrecognised_value unrecognised_value ignoring_unknown ignoring_unknown
78 use_double_quote_code use_quote_code
79 unrecognised_value unrecognised_value ignoring_unknown ignoring_unknown
80 inserted_missing_closure unrecognised_value unrecognised_value ignoring_unknown ignoring_unknown
81 unrecognised_value unrecognised_value ignoring_unknown ignoring_unknown
82 use_quote_code use_double_quote_code inserted_missing_closure unrecognised_value unrecognised_value ignoring_unknown ignoring_unknown
83 use_double_quote_code
84 unrecognised_value unrecognised_value ignoring_unknown ignoring_unknown use_double_quote_code
87 newline_in_string newline_in_string
88 newline_in_string newline_in_string
91 attribute_unrecognised unrecognised_attribute
93 only_elements
97 attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised attribute_unrecognised unrecognised_value unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute unrecognised_attribute
99 unrecognised_value
120 url_not_found
126 use_quote_code
129 url_not_found
130 url_not_found
131 url_not_found
133 use_quote_code
139 url_not_found
142 inserted_missing_closure inserted_missing_closure url_not_found
143 inserted_missing_parent inserted_missing_closure inserted_missing_closure
144 missing_open
148 use_quote_code
150 ignoring_unknown attribute_barred attribute_barred
156 use_quote_code double_angular_open
159 ignoring_unknown attribute_barred
160 use_double_quote_code
162 use_double_quote_code ignoring_unknown
163 ignoring_unknown

PASS ../toast/living/jan11/example-2.html
4 url_not_found style_not_css
5 url_not_found
6 url_not_found
11 url_not_found
13 url_not_found
15 url_not_found
16 url_not_found
17 url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
22 no_such_folder url_not_found
24 no_such_folder url_not_found
25 no_such_folder url_not_found
26 no_such_folder url_not_found

PASS ../toast/living/jan11/index.html
3 attribute_unrecognised_here unrecognised_attribute

PASS ../toast/living/jan11/ls1.html
8 url_not_found

PASS ../toast/living/jan11/ls3.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan11/ls4.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan11/ls5.html
3 xmlns_namespace
5 use_quote_code
8 ignoring_unknown xmlns_namespace attribute_barred attribute_barred
9 ignoring_unknown ignoring_unknown
10 ignoring_unknown xmlns_namespace attribute_barred
11 ignoring_unknown ignoring_unknown
12 ignoring_unknown

PASS ../toast/living/jan11/ls8.html
5 element_offsite_base
7 url_not_found
8 url_not_found
9 url_not_found

PASS ../toast/living/jan11/ls9.html
4 long_title
5 element_offsite_base
8 url_not_found
