/*
ssc (static site checker)
Copyright (c) 2020-2026 Dylan Harris
https://dylanharris.org/

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public Licence for more details.

You should have received a copy of the GNU General Public
Licence along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
*/

#include "main/standard.h"
#include "type/type.h"
#include "webpage/directory.h"
#include "webpage/page.h"
#include "element/element.h"

struct enum_name_t {
    e_type t_;
    const char* name_; };

enum_name_t enum_name [] =
{   { t_0_more, "0 more" },
    { t_0_to_1, "0 to 1" },
    { t_0_to_2, "0 to 2" },
    { t_0_to_3, "0 to 3" },
    { t_0_to_4, "0 to 4" },
    { t_0_to_6, "0 to 6" },
    { t_0_to_7, "0 to 7" },
    { t_0_to_8, "0 to 8" },
    { t_0_to_9, "0 to 9" },
    { t_0_to_100, "0 to 100" },
    { t_0_to_150, "0 to 150" },
    { t_0_to_255, "0 to 255" },
    { t_0_to_1000, "0 to 1000" },
    { t_10, "10" },
    { t_1_more, "1 more" },
    { t_1_more_i, "1 more i" },
    { t_1_to_2, "1 to 2"},
    { t_1_to_20, "1 to 20" },
    { t_1_or_6, "1 or 6" },
    { t_1_to_7, "1 to 7" },
    { t_1_to_8, "1 to 8" },
    { t_1_to_99, "1 to 99" },
    { t_1_to_10000, "1 to 10000" },
    { t_10_int, "10 int" },
    { t_2_to_3, "2 to 3" },
    { t_2_to_4, "2 to 4" },
    { t_2_or_6, "2 or 6" },
    { t_2000_to_50000, "2k to 50k" },
    { t_2pt, "2pt" },
    { t_2string, "2 string" },
    { t_2x_integer, "2x integer" },
    { t_2x_unsigned, "2x unsigned" },
    { t_3x_integer, "3x integers" },
    { t_3x_real, "3x real" },
    { t_3x_unsigned, "3x unsigned" },
    { t_3x_urational, "3x urational" },
    { t_4string, "4 string" },
    { t_4string_ni, "4 string ni" },
    { t_4x_0_to_6, "4x 0 to 6" },
    { t_4x_unsigned, "4x unsigned" },
    { t_4x_urational, "4x urational" },
    { t_5x_unsigned, "5x unsigned" },
    { t_a_b_c_d, "a.b.c.d" },
    { t_a_v, "a v" },
    { t_aabn, "aabn" },
    { t_abcfl, "abcfl" },
    { t_abfmt, "abfmt" },
    { t_ablr, "ablr" },
    { t_abn, "abn" },
    { t_about, "about" },
    { t_absolute_url, "absolute url" },
    { t_accept, "accept" },
    { t_accrual_method, "accrual method" },
    { t_accrual_periodicity, "accrual periodicity" },
    { t_accrual_policy, "accrual policy" },
    { t_accumulate, "accumulate" },
    { t_accumulate0, "accumulate 0" },
    { t_accumulate1, "accumulate 1" },
    { t_accumulate2, "accumulate 2" },
    { t_aces, "aces" },
    { t_acm, "acm" },
    { t_acn, "acn" },
    { t_acn_2, "acn 2" },
    { t_action, "action" },
    { t_actiontype, "action type" },
    { t_actiontype2, "action type 2" },
    { t_additive, "additive" },
    { t_advar, "advar" },
    { t_aesf, "aesf" },
    { t_aesfs, "aesfs" },
    { t_aftw, "aftw" },
    { t_aftws, "aftws" },
    { t_align, "align" },
    { t_align2070, "align 2070" },
    { t_align3, "align 3" },
    { t_aligndec, "align dec" },
    { t_alignfig, "align fig" },
    { t_alignment_baseline, "alignment baseline" },
    { t_alignplus, "align plus" },
    { t_aria_current, "aria current" },
    { t_allow_deny, "allow deny" },
    { t_allow_force, "allow force" },
    { t_allow_numeric, "allow numeric" },
    { t_all_none, "all none" },
    { t_all_auto_none, "all auto none" },
    { t_allow_ad_n, "allow ad n" },
    { t_allow_list, "allow list" },
    { t_alp, "alp" },
    { t_always_auto_never, "always auto never" },
    { t_always_normal, "always normal" },
    { t_analysis, "analysis" },
    { t_anchor_centre, "anchor centre" },
    { t_angle, "angle" },
    { t_angle_0, "angle 0" },
    { t_angle_a, "angle a" },
    { t_angle_ar, "angle ar" },
    { t_angle_ars, "angle ars" },
    { t_angle_ai, "angle ai" },
    { t_angle_i, "angle i" },
    { t_angle_n, "angle n" },
    { t_angle_p, "angle pn" },
    { t_angular_colour_more, "angular colour more" },
    { t_angular_colour_stop, "angular colour stop" },
    { t_anw, "anw" },
    { t_anywhere_break_normal, "anywhere break normal" },
    { t_arabic_form, "arabic form" },
    { t_arabicenum, "arabi enum" },
    { t_aria_autocomplete, "aria autocomplete" },
    { t_aria_current, "aria_current" },
    { t_aria_invalidity, "aria invalidity" },
    { t_aria_live, "aria live" },
    { t_aria_popup, "aria popup" },
    { t_aria_relevant, "aria relevant" },
    { t_aria_relevants, "aria relevants" },
    { t_aria_sort, "aria sort" },
    { t_arxiv, "arXiv" },
    { t_as, "as" },
    { t_ass, "ass" },
    { t_as_units, "as units" },
    { t_at_pos, "at pos" },
    { t_atom_mime, "atom mime" },
    { t_atom_type, "atom type" },
    { t_attr, "attr" },
    { t_attributename, "attribute name" },
    { t_attributetype, "attribute type" },
    { t_attr_unit, "attr unit" },
    { t_audio_level, "audio level" },
    { t_auto, "autok" },
    { t_auto_break, "auto break" },
    { t_autocapitalise, "autocapitalise" },
    { t_autocomplete, "autocomplete" },
    { t_autocompletes, "autocompletes" },
    { t_autocompletevaried, "autocomplete varied" },
    { t_auto_contain, "auto contain" },
    { t_auto_contain_cover, "auto contain cover" },
    { t_auto_first_last, "auto first last" },
    { t_auto_focus_scroll, "auto focus_scroll" },
    { t_auto_hidden_visible, "auto hidden visible" },
    { t_auto_inert, "auto inert" },
    { t_auto_manual, "auto manual" },
    { t_auto_manual_none, "auto manual none" },
    { t_auto_merge_separate, "auto merge separate" },
    { t_auto_none, "auto none" },
    { t_auto_none_oblique, "auto none oblique" },
    { t_auto_none_thin, "auto none thin" },
    { t_auto_smooth, "auto smooth" },
    { t_auto_stable, "auto stable" },
    { t_b64, "b64" },
    { t_background, "background" },
    { t_bandwidth, "bandwidth" },
    { t_base, "base" },
    { t_baseline, "baseline" },
    { t_baselineshift, "baseline shift" },
    { t_baseline_contain_none, "baseline contain none" },
    { t_bb, "bb" },
    { t_bcess, "bcess" },
    { t_bcs, "bcs" },
    { t_bdn, "bdn" },
    { t_bdns, "bdns" },
    { t_beginvalue, "begin value" },
    { t_beginvaluelist, "begin value list" },
    { t_beginvalues, "begin values" },
    { t_behaviour, "behaviour" },
    { t_bens, "bens" },
    { t_benrs, "benrs" },
    { t_bgfg, "bgfg" },
    { t_bihv, "bihv" },
    { t_bixies, "bixies" },
    { t_bixy, "bixy" },
    { t_bixys, "bixys" },
    { t_blink_none, "blink none" },
    { t_block, "block" },
    { t_blocking, "blocking" },
    { t_block_inline, "block inside" },
    { t_block_inline_2, "block inside 2" },
    { t_blrt, "blrt" },
    { t_bns, "bns" },
    { t_bool, "bool" },
    { t_bools, "bools" },
    { t_border, "border" },
    { t_braille, "braille" },
    { t_braille_or_not, "braille or not" },
    { t_brs, "brs" },
    { t_btyy, "btyy" },
    { t_buffered_rendering, "buffered rendering" },
    { t_button, "button" },
    { t_byto, "byto" },
    { t_cache, "cache" },
    { t_cachekey, "cachekey" },
    { t_calcmode, "calcmode" },
    { t_capture, "capture" },
    { t_cc_permits, "cc permits" },
    { t_cc_prohibits, "cc prohibits" },
    { t_cc_requires, "cc requires" },
    { t_ccee, "ccee" },
    { t_celnrs, "celnrs" },
    { t_celrs, "celrs" },
    { t_cens, "cens" },
    { t_centre_space, "centre space" },
    { t_ces, "ces"},
    { t_channelselector, "channel selector" },
    { t_char, "char" },
    { t_charset, "charset" },
    { t_charsets, "charsets" },
    { t_charspacing, "char spacing" },
    { t_cio, "cio" },
    { t_circle_ellipse, "circle ellipse" },
    { t_cipr, "cipr" },
    { t_citype, "citype" },
    { t_class, "class" },
    { t_clear, "clear" },
    { t_clear30, "clear 30" },
    { t_clip, "clip" },
    { t_clip_path_rule, "clip path rule" },
    { t_clllr, "clllr" },
    { t_closedby, "closed by" },
    { t_closed_open, "closed open" },
    { t_closure, "closure" },
    { t_cmx_1, "cmx 1" },
    { t_cmx_2, "cmx 2" },
    { t_cmx_12, "cmx 12" },
    { t_cnn, "cnn" },
    { t_cntype, "cntype" },
    { t_coden, "coden" },
    { t_colour, "colour" },
    { t_colour_a, "colour a" },
    { t_colour_ci, "colour ci" },
    { t_colour_cii, "colour cii" },
    { t_colour_i, "colour i" },
    { t_colour_ii, "colour ii" },
    { t_colour_interpolation, "colour interpolation" },
    { t_colour_ni, "colour ni" },
    { t_colour_profile, "colour profile" },
    { t_colour_profile_name, "colour profile name" },
    { t_colour_profile_name_or_uri, "colour profile name or uri" },
    { t_colour_rendering, "colour rendering" },
    { t_colour_scheme, "colour scheme" },
    { t_colour_scheme_o, "colour scheme o" },
    { t_colour_schemes, "colour schemes" },
    { t_colour_schemes_n, "colour schemes n" },
    { t_colour_schemes_o, "colour schemes o" },
    { t_colour_space, "colour space" },
    { t_colour_trans, "colour trans" },
    { t_colour_trans_i, "colour trans i" },
    { t_colour_v, "colour v" },
    { t_command, "command" },
    { t_command2, "command2" },
    { t_command3, "command3" },
    { t_comp_op, "comp op" },
    { t_compact, "compact" },
    { t_compact_normal, "compact normal" },
    { t_composite_operator, "composite operator" },
    { t_compositing, "compositing" },
    { t_conic_1, "conic 1" },
    { t_conic_2, "conic 2" },
    { t_conic_12, "conic 12" },
    { t_conlit, "conlit" },
    { t_contain_cover, "contain cover" },
    { t_contain_cover_sd, "contain cover sd" },
    { t_connect, "connect" },
    { t_contain, "contain" },
    { t_container_condition, "container_condition" },
    { t_content_encoding, "content encoding" },
    { t_content_encodings, "content encodings" },
    { t_content_type, "content type" },
    { t_context_menu, "context menu" },
    { t_contents, "contents" },
    { t_controlslist, "controls list" },
    { t_corners_sides, "corners sides" },
    { t_cookie, "cookie" },
    { t_cookieid, "cookie id" },
    { t_cookies, "cookies" },
    { t_coordinatesystem, "coordinate system" },
    { t_coords, "coords" },
    { t_copy, "copy" },
    { t_corp, "corp" },
    { t_cors, "cors" },
    { t_countries, "countries" },
    { t_country, "country" },
    { t_cpp, "cpp" },
    { t_create_parent, "create parent" },
    { t_crossout, "crossout" },
    { t_cr_fileproperty, "cr fileproperty" },
    { t_crs_tonecurvename, "crs tonecurvename" },
    { t_crs_whitebalance, "crs whitebalance" },
    { t_cs, "cs" },
    { t_csp, "csp" },
    { t_csp_ancestor, "csp ancestor" },
    { t_csp_directive, "csp directive" },
    { t_csp_keyword, "csp keyword" },
    { t_csp_sauce, "csp sauce" },
    { t_csp_source, "csp source" },
    { t_css, "CSS" },
    { t_css_aaalri, "CSS aaal ri" },
    { t_css_aai, "CSS aai" },
    { t_css_absolute_size, "CSS absolute size" },
    { t_css_act_nav, "CSS act nav" },
    { t_css_act_navs, "CSS act navs" },
    { t_css_add_fn, "CSS add fn" },
    { t_css_addsym, "CSS add sym" },
    { t_css_addsyms, "CSS add syms" },
    { t_css_align_content, "CSS align content" },
    { t_css_align_items, "CSS align items" },
    { t_css_align_items_a, "CSS align items a" },
    { t_css_all, "CSS all" },
    { t_css_all_2, "CSS all 2" },
    { t_css_alpha, "CSS alpha" },
    { t_css_alpha_n, "CSS alpha n" },
    { t_css_anchor, "CSS anchor" },
    { t_css_anchored, "CSS anchored" },
    { t_css_anchor_id, "CSS anchor id" },
    { t_css_anchor_idref, "CSS anchor idref" },
    { t_css_anchor_idref_na, "CSS anchor idref na" },
    { t_css_anchor_none, "CSS anchor none" },
    { t_css_anchor_side, "CSS anchor side" },
    { t_css_anchor_side_e, "CSS anchor side e" },
    { t_css_anchor_size, "CSS anchor size" },
    { t_css_anchor_size_e, "CSS anchor size e" },
    { t_css_angle, "CSS angle" },
    { t_css_angular_colour_stop, " CSS angular conic stop" },
    { t_css_angular_colour_stop_list, " CSS angular conic stop list" },
    { t_css_animation, "CSS animation" },
    { t_css_animations, "CSS animations" },
    { t_css_anim_act, "CSS anim act" },
    { t_css_anim_base, "CSS anim base" },
    { t_css_anim_comp, "CSS anim comp" },
    { t_css_anim_comps, "CSS anim comps" },
    { t_css_anim_dir, "CSS anim dir" },
    { t_css_anim_dirs, "CSS anim dirs" },
    { t_css_anim_fill_mode, "CSS anim fill mode" },
    { t_css_anim_fill_modes, "CSS anim fill modes" },
    { t_css_anim_iter_count, "CSS anim iter count" },
    { t_css_anim_name, "CSS anim name" },
    { t_css_anim_play_state, "CSS anim play state" },
    { t_css_anim_play_states, "CSS anim play states" },
    { t_css_anim_range, "CSS anim range" },
    { t_css_anim_range_2, "CSS anim range 2" },
    { t_css_anim_range_2s, "CSS anim range 2s" },
    { t_css_anim_range_centre, "CSS anim range centre" },
    { t_css_anim_range_centres, "CSS anim range centres" },
    { t_css_anim_ranges, "CSS anim ranges" },
    { t_css_anim_range_source, "CSS anim range source" },
    { t_css_anim_rt, "CSS anim rt" },
    { t_css_anim_timeline, "CSS anim timeline" },
    { t_css_anw_nr, "CSS anw nr" },
    { t_css_anw_nr_wr, "CSS anw nr wr" },
    { t_css_appearance, "CSS appearance" },
    { t_css_atf, "CSS atf" },
    { t_css_atf_ky, "CSS atf ky" },
    { t_css_atfs, "CSS atfs" },
    { t_css_at, "CSS at" },
    { t_css_ats, "CSS ats" },
    { t_css_atsn, "CSS atsn" },
    { t_css_atsns, "CSS atsns" },
    { t_css_attr, "CSS attr" },
    { t_css_attr_type, "CSS attr type" },
    { t_css_attr_unit, "CSS attr unit" },
    { t_css_azimuth, "CSS azimuth" },
    { t_css_azimuth_be, "CSS azimuth be" },
    { t_css_azimuth_e, "CSS azimuth e" },
    { t_css_azimuth_eb, "CSS azimuth eb" },
    { t_css_azimuth_es, "CSS azimuth es" },
    { t_css_azimuth_lri, "CSS azimuth lri" },
    { t_css_background, "CSS background" },
    { t_css_background_0, "CSS background 0" },
    { t_css_background_1, "CSS background 1" },
    { t_css_background_2, "CSS background 2" },
    { t_css_background_3, "CSS background 3" },
    { t_css_background_attachment, "CSS background attachment" },
    { t_css_background_attachment_3, "CSS background attachment 3" },
    { t_css_background_attachments, "CSS background attachments" },
    { t_css_background_boxes, "CSS background boxes" },
    { t_css_background_clip, "CSS background clip" },
    { t_css_background_clips, "CSS background clips" },
    { t_css_background_position, "CSS background position" },
    { t_css_background_position_1, "CSS background position_1" },
    { t_css_background_position_2, "CSS background position_2" },
    { t_css_background_position_3, "CSS background position 3" },
    { t_css_background_position_3s, "CSS background position 3s" },
    { t_css_background_position_rel, "CSS background position rel" },
    { t_css_background_position_rels, "CSS background position rels" },
    { t_css_background_positions, "CSS background positions" },
    { t_css_background_repeat, "CSS background repeat" },
    { t_css_background_repeat_2, "CSS background repeat 2" },
    { t_css_background_repeat_3, "CSS background repeat 3" },
    { t_css_background_repeats, "CSS background repeats" },
    { t_css_background_size, "CSS background size" },
    { t_css_background_sizes, "CSS background sizes" },
    { t_css_background_tbd, "CSS background tbd" },
    { t_css_backval, "CSS backval" },
    { t_css_base_palette, "CSS base palette" },
    { t_css_baseline_position, "CSS baseline position" },
    { t_css_base_url, "CSS base url" },
    { t_css_bespoke, "CSS bespoke" },
    { t_css_bespoker, "CSS bespoker" },
    { t_css_blend_colour, "CSS blend colour" },
    { t_css_blend_mode, "CSS blend mode" },
    { t_css_blend_modes, "CSS blend modes" },
    { t_css_block_step, "CSS block stop" },
    { t_css_border_collapse, "CSS border collapse" },
    { t_css_border_clip, "CSS border clip" },
    { t_css_border_clips, "CSS border clips" },
    { t_css_border_image, "CSS border image" },
    { t_css_border_image_repeat, "CSS border image repeat" },
    { t_css_border_images_repeat, "CSS border images repeat" },
    { t_css_border_image_slice, "CSS border image slice" },
    { t_css_border_image_width, "CSS border image width" },
    { t_css_border_image_src, "CSS border image src" },
    { t_css_border_juice, "CSS border juice" },
    { t_css_border_juice_2, "CSS border juice 2" },
    { t_css_border_juice_4, "CSS border juice 4" },
    { t_css_border_limit, "CSS border limit" },
    { t_css_border_limit_part, "CSS border limit part" },
    { t_css_border_limit_side, "CSS border limit side" },
    { t_css_border_measure, "CSS border measure" },
    { t_css_border_radius, "CSS border radius" },
    { t_css_border_shape, "CSS border shape" },
    { t_css_border_shapes, "CSS border shapes" },
    { t_css_border_spacing, "CSS border spacing" },
    { t_css_border_spacing_2, "CSS border spacing 2" },
    { t_css_border_style, "CSS border style" },
    { t_css_border_style_i, "CSS border style i" },
    { t_css_border_styles, "CSS border styles" },
    { t_css_border_styles_2, "CSS border styles 2" },
    { t_css_border_styles_l, "CSS border styles l" },
    { t_css_border_width, "CSS border width" },
    { t_css_border_width_col, "CSS border width col" },
    { t_css_border_width_i, "CSS border width i" },
    { t_css_border_wsc, "CSS border wsc" },
    { t_css_borders_measure, "CSS borders measure" },
    { t_css_borders_measure_2, "CSS borders measure 2" },
    { t_css_borders_measure_i, "CSS borders measure i" },
    { t_css_borders_measure_l, "CSS borders measure l" },
    { t_css_box_alignitems, "CSS box alignitems" },
    { t_css_box_alignitems_ns, "CSS box alignitems ns" },
    { t_css_box_alignself, "CSS box alignself" },
    { t_css_box_alignself_acs, "CSS box alignself acs" },
    { t_css_box_alignself_mess, "CSS box alignself mess" },
    { t_css_box_content, "CSS box content" },
    { t_css_box_content_n, "CSS box content n" },
    { t_css_box_direction, "CSS box direction" },
    { t_css_box_justitems, "CSS box justitems" },
    { t_css_box_justitems_ns, "CSS box justitems ns" },
    { t_css_box_justself, "CSS box justself" },
    { t_css_box_justify, "CSS box justify" },
    { t_css_box_justify_n, "CSS box justify n" },
    { t_css_box_legacy, "CSS box legacy" },
    { t_css_box_orient, "CSS box orient" },
    { t_css_box_overflow, "CSS box overflow" },
    { t_css_box_pack, "CSS box pack" },
    { t_css_box_reflect, "CSS box reflect" },
    { t_css_box_reflect_img, "CSS box reflect img" },
    { t_css_box_shadow, "CSS box shadow" },
    { t_css_box_shadows, "CSS box shadows" },
    { t_css_box_shadows_n, "CSS box shadows n" },
    { t_css_box_sizing, "CSS box sizing" },
    { t_css_box_snap, "CSS box snap" },
    { t_css_break, "CSS break" },
    { t_css_break_box, "CSS break box" },
    { t_css_break_inside, "CSS break inside" },
    { t_css_calc_size, "CSS calc size" },
    { t_css_calc_size_fn, "CSS calc size fn" },
    { t_css_calc_value, "CSS calc value" },
    { t_css_caret, "CSS caret" },
    { t_css_caret_shape, "CSS caret shape" },
    { t_css_clear, "CSS clear" },
    { t_css_clip_coord_box, "CSS clip coord box" },
    { t_css_clip_coord_boxen, "CSS clip coord boxen" },
    { t_css_clip_path, "clip path" },
    { t_css_clip_path_box, "clip path box" },
    { t_css_clip_path_shape, "clip path shape" },
    { t_css_coin1, "CSS coin 1" },
    { t_css_coin2, "CSS coin 2" },
    { t_css_coin3, "CSS coin 3" },
    { t_css_col, "CSS col" },
    { t_css_col_img, "CSS col img" },
    { t_css_col_img_per, "CSS col img per" },
    { t_css_col_img_str_url, "CSS col img str" },
    { t_css_colour, "CSS colour" },
    { t_css_colour_3, "CSS colour 3" },
    { t_css_colour_4, "CSS colour 4" },
    { t_css_colour_5, "CSS colour 5" },
    { t_css_colour_a, "CSS colour auto" },
    { t_css_colour_interpolation, "CSS colour interpolation" },
    { t_css_colour_ld, "CSS colour ld" },
    { t_css_colour_percent, "CSS colour percent" },
    { t_css_colour_percent_n, "CSS colour percent n" },
    { t_css_colour_stop_list, "CSS colour stop list" },
    { t_css_col_r, "CSS col r" },
    { t_css_col_rs, "CSS col rs" },
    { t_css_cols, "CSS cols" },
    { t_css_cols_2, "CSS cols 2" },
    { t_css_cols_2_a, "CSS cols 2 a" },
    { t_css_cols_comma, "CSS cols comma" },
    { t_css_cols_l, "CSS cols l" },
    { t_css_col_s_url, "t_css_col_s_url" },
    { t_css_column_fill, "CSS column fill" },
    { t_css_column_rule, "CSS column rule" },
    { t_css_column_rules, "CSS column rules" },
    { t_css_column_width, "CSS column width" },
    { t_css_columns, "CSS columns" },
    { t_css_composite, "CSS composite" },
    { t_css_composite_mode, "CSS composite mode" },
    { t_css_composites, "CSS composites" },
    { t_css_contain, "CSS contain" },
    { t_css_contain_e, "CSS contain e" },
    { t_css_contain_slp, "CSS contain slp" },
    { t_css_container, "CSS container" },
    { t_css_container_feature, "CSS container feature" },
    { t_css_container_name, "CSS container name" },
    { t_css_container_query, "CSS container query" },
    { t_css_container_state, "CSS container state" },
    { t_css_container_type, "CSS container type" },
    { t_css_content, "CSS content" },
    { t_css_content_3, "CSS content 3" },
    { t_css_content_3nn, "CSS content 3nn" },
    { t_css_content_base, "CSS content base" },
    { t_css_content_cm_box, "CSS content cm box" },
    { t_css_content_enum, "CSS content enum" },
    { t_css_content_fixed, "CSS content fixed" },
    { t_css_content_fn, "CSS content fn" },
    { t_css_content_list, "CSS content list" },
    { t_css_content_name, "CSS content name" },
    { t_css_content_position, "CSS content position" },
    { t_css_content_twice, "CSS content twice" },
    { t_css_content_x, "CSS content x" },
    { t_css_continue, "CSS continue" },
    { t_css_control_break, "CSS control break" },
    { t_css_context_properties, " CSS context properties" },
    { t_css_contrast_colour, "CSS contrast colour" },
    { t_css_coord_box, "CSS coord box" },
    { t_css_coord_boxen, "CSS coord boxen" },
    { t_css_copy_into, "CSS copy into" },
    { t_css_copy_intos, "CSS copy intos" },
    { t_css_copy_intos_n, "CSS copy intos none" },
    { t_css_corner_shape, "CSS corner shape" },
    { t_css_corner_shape_name, "CSS corner shape name" },
    { t_css_corner_shapes, "CSS corner shapes" },
    { t_css_corner_shapes4, "CSS corner shapes4" },
    { t_css_counter, "CSS counter" },
    { t_css_counter_ii, "CSS counter ii" },
    { t_css_counter_iin, "CSS counter iin" },
    { t_css_counter_set, "CSS counter set" },
    { t_css_counter_ss, "CSS counter ss" },
    { t_css_counter_style, "CSS counter style" },
    { t_css_counter_style_name, "CSS counter style name" },
    { t_css_counters, "CSS counters" },
    { t_css_cross_fade, "CSS cross fade" },
    { t_css_cross_fade_colour, "CSS cross fade colour" },
    { t_css_cue, "CSS cue" },
    { t_css_cues, "CSS cues" },
    { t_css_cursor, "CSS cursor" },
    { t_css_cursor_e, "CSS cursor e" },
    { t_css_cursor_url, "CSS cursor url" },
    { t_css_custom_content_level, "CSS custom content level" },
    { t_css_descriptor, "CSS descriptor" },
    { t_css_dimension, "CSS dimension" },
    { t_css_djs, "CSS djs" },
    { t_css_djs_n, "CSS djs n" },
    { t_css_djss, "CSS djss" },
    { t_css_display, "CSS display" },
    { t_css_display_1, "CSS display 1" },
    { t_css_display_3, "CSS display 3" },
    { t_css_display_box, "CSS display box" },
    { t_css_display_flow, "CSS display flow" },
    { t_css_display_inside, "CSS display inside" },
    { t_css_display_internal, "CSS display internal" },
    { t_css_display_legacy, "CSS display legacy" },
    { t_css_display_listitem, "CSS display listitem" },
    { t_css_display_outside, "CSS display outside" },
    { t_css_double_rainbow, "CSS double rainbow" },
    { t_css_duration_n, "CSS duration n" },
    { t_css_durations, "CSS durations" },
    { t_css_dynamic_range_limit, "CSS dynamic range limit" },
    { t_css_dynamic_range_limit_e, "CSS dynamic range limit e" },
    { t_css_dynamic_range_limit_p, "CSS dynamic range limit p" },
    { t_css_dynamic_range_limit_pe, "CSS dynamic range limit pe" },
    { t_css_dynamic_range_limit_ps, "CSS dynamic range limit ps" },
    { t_css_earnest, "CSS earnest" },
    { t_css_easing_fn, "CSS easing fn" },
    { t_css_easing_fns, "CSS easing fns" },
    { t_css_elevation, "CSS elevation" },
    { t_css_elevation_e, "CSS elevation e" },
    { t_css_ellipse_pos, "CSS ellipse pos" },
    { t_css_ellipse_pos_1, "CSS ellipse pos 1" },
    { t_css_ellipse_pos_2, "CSS ellipse pos 2" },
    { t_css_ellipse_pos_2a, "CSS ellipse pos 2a" },
    { t_css_ellipse_pos_2b, "CSS ellipse pos 2b" },
    { t_css_ellipse_pos_2c, "CSS ellipse pos 2c" },
    { t_css_ellipse_pos_2c_block, "CSS ellipse pos 2c block" },
    { t_css_ellipse_pos_2c_inline, "CSS ellipse pos 2c inline" },
    { t_css_ellipse_pos_4, "CSS ellipse pos 4" },
    { t_css_ellipse_pos_4a, "CSS ellipse pos 4a" },
    { t_css_ellipse_pos_4b, "CSS ellipse pos 4b" },
    { t_css_ellipse_pos_4bx, "CSS ellipse pos 4bx" },
    { t_css_ellipse_pos_4by, "CSS ellipse pos 4by" },
    { t_css_ellipse_pos_4c, "CSS ellipse pos 4c" },
    { t_css_ellipse_pos_4cs, "CSS ellipse pos 4cs" },
    { t_css_ellipse_pos_e, "CSS ellipse pos e" },
    { t_css_ellipse_pos_x_2_e, "CSS ellipse pos x 2 e" },
    { t_css_ellipse_pos_y_2_e, "CSS ellipse pos y 2 e" },
    { t_css_ellipse_pos_xl, "CSS ellipse pos xl" },
    { t_css_ellipse_pos_yl, "CSS ellipse pos yl" },
    { t_css_empty_cells, "CSS empty cells" },
    { t_css_env_var, "CSS env var"},
    { t_css_env_var_name, "CSS env var name" },
    { t_css_env_var_predef, "CSS env var predef" },
    { t_css_etee, "CSS etee" },
    { t_css_eteek, "CSS eteek" },
    { t_css_eteeks, "CSS eteeks" },
    { t_css_eteeks2, "CSS eteeks2" },
    { t_css_eteeks2n, "CSS eteeks2n" },
    { t_css_eteeks2ns, "CSS eteeks2ns" },
    { t_css_etns, "CSS etns" },
    { t_css_etnss, "CSS etnss" },
    { t_css_etnssn, "CSS etnssn" },
    { t_css_fca, "CSS fca" },
    { t_css_feature_annotation, "CSS feature annotation" },
    { t_css_feature_character_variant, "CSS feature character variant" },
    { t_css_feature_historical_forms, "CSS feature historical forms" },
    { t_css_feature_ornaments, "CSS feature ornaments" },
    { t_css_feature_swash, "CSS feature swash" },
    { t_css_feature_styleset, "CSS feature styleset" },
    { t_css_feature_stylistic, "CSS feature stylistic" },
    { t_css_filter, "CSS filter" },
    { t_css_filters, "CSS filters" },
    { t_css_filters_n, "CSS filters n" },
    { t_css_fit, "CSS fit" },
    { t_css_fit_position, "CSS fit position" },
    { t_css_flex, "CSS flex" },
    { t_css_flexes, "CSS flexes" },
    { t_css_flex_basis, "CSS flex basis" },
    { t_css_flex_content, "CSS flex content"},
    { t_css_flex_direction, "CSS flex direction" },
    { t_css_flex_direction_a, "CSS flex direction a" },
    { t_css_flex_flow, "CSS flex flow" },
    { t_css_flex_n, "CSS flex n" },
    { t_css_flex_wrap, "CSS flex wrap" },
    { t_css_float, "CSS float" },
    { t_css_float_fn, "CSS float fn" },
    { t_css_fn, "CSS fn" },
    { t_css_ffv, "CSS ffv" },
    { t_css_fn_anchor, "CSS fn anchor" },
    { t_css_fn_anchor_size, "CSS fn anchor size" },
    { t_css_fn_anchored, "CSS fn anchored" },
    { t_css_fn_annotation, "CSS fn annotation" },
    { t_css_fn_attr, "CSS fn attr" },
    { t_css_fn_calc, "CSS fn calc" },
    { t_css_fn_calc_args, "CSS fn calc args" },
    { t_css_fn_calc_size, "CSS fn calc size" },
    { t_css_fn_character_variant, "CSS fn character variant" },
    { t_css_fn_conic_gradient, "CSS fn conic gradient" },
    { t_css_fn_counter, "CSS fn counter" },
    { t_css_fn_counters, "CSS fn counters" },
    { t_css_fn_cross_fade, "CSS fn cross fade" },
    { t_css_fn_cubic_bezier, "CSS fn cubic bezier" },
    { t_css_fn_custom, "CSS fn custom" },
    { t_css_fn_dylm, "CSS fn dylm" },
    { t_css_fn_element, "CSS fn element" },
    { t_css_fn_fit_content, "CSS fn fit content" },
    { t_css_fn_if, "CSS fn if" },
    { t_css_fn_if_media, "CSS fn if media" },
    { t_css_fn_if_supports, "CSS fn if supports" },
    { t_css_fn_if_style, "CSS fn if style" },
    { t_css_fn_image, "CSS fn image" },
    { t_css_fn_image_set, "CSS fn image set" },
    { t_css_fn_inset, "CSS fn inset" },
    { t_css_fn_keypress, "CSS fn keypress" },
    { t_css_fn_linear, "CSS fn linear" },
    { t_css_fn_linear_gradient, "CSS fn linear gradient" },
    { t_css_fn_minmax, "CSS fn minmax" },
    { t_css_fn_mix, "CSS fn mix" },
    { t_css_fn_moz_image_rect, "CSS fn moz image rect" },
    { t_css_fn_ornaments, "CSS fn ornaments" },
    { t_css_fn_param, "CSS fn param" },
    { t_css_fn_path_args, "CSS fn path args"},
    { t_css_fn_progress, "CSS fn progress" },
    { t_css_fn_radial_gradient, "CSS fn radial gradient" },
    { t_css_fn_ray, "CSS fn ray" },
    { t_css_fn_rect, "CSS fn rect" },
    { t_css_fn_repeat, "CSS fn repeat" },
    { t_css_fn_repeating_conic_gradient, "CSS fn repeating conic gradient" },
    { t_css_fn_repeating_linear_gradient, "CSS fn repeating linear gradient" },
    { t_css_fn_repeating_radial_gradient, "CSS fn repeating radial gradient" },
    { t_css_fn_round_t, "CSS fn round type" },
    { t_css_fn_shape, "CSS fn shape" },
    { t_css_fn_snap_block, "CSS fn snap block" },
    { t_css_fn_snap_inline, "CSS fn snap inline" },
    { t_css_fn_steps, "CSS fn steps" },
    { t_css_fn_styleset, "CSS fn styleset" },
    { t_css_fn_stylistic, "CSS fn stylistic" },
    { t_css_fn_superellipse, "CSS fn superellipse" },
    { t_css_fn_swash, "CSS fn swash" },
    { t_css_fn_type, "CSS fn type" },
    { t_css_fn_type_args, "CSS fn type args" },
    { t_css_fn_url_pattern, "CSS fn url pattern" },
    { t_css_fn_var, "CSS fn var" },
    { t_css_fn_wcag2, "CSS fn wcag2" },
    { t_css_fn_xywh, "CSS fn xywh" },
    { t_css_fns_calc_size, "CSS fns calc size" },
    { t_css_font, "CSS font" },
    { t_css_font_display, "CSS font display" },
    { t_css_font_families, "CSS font families" },
    { t_css_font_feature, "CSS font feature" },
    { t_css_font_feature_settings, "CSS font feature settings" },
    { t_css_font_feature_tag, "CSS font feature tag" },
    { t_css_font_feature_tags, "CSS font feature tags" },
    { t_css_font_format, "CSS font format" },
    { t_css_font_kerning, "CSS font kerning" },
    { t_css_font_named_instance, "CSS named instance" },
    { t_css_font_size, "CSS font size" },
    { t_css_font_size_4, "CSS font size 4" },
    { t_css_font_size_adjust, "CSS font size adjust" },
    { t_css_font_size_adjust_e, "CSS font size adjust e" },
    { t_css_font_smooth, " CSS font smooth" },
    { t_css_font_stretch, " CSS font stretch" },
    { t_css_font_style, "CSS font style" },
    { t_css_font_style_2, "CSS font style 2" },
    { t_css_font_style_a, "CSS font style a" },
    { t_css_font_style_e, "CSS font style e" },
    { t_css_font_synthesis, "CSS font synthesis" },
    { t_css_font_synthesis_n, "CSS font synthesis n" },
    { t_css_font_tech, "CSS font tech" },
    { t_css_font_techs, "CSS font techs" },
    { t_css_font_variation, "CSS font variation" },
    { t_css_font_variation_settings, "CSS font variation settings" },
    { t_css_font_variation_tag, "CSS font variation tag" },
    { t_css_font_variation_tags, "CSS font variation tags" },
    { t_css_font_variant, "CSS font variant" },
    { t_css_font_variant_i, "CSS font variant i" },
    { t_css_font_variant_4, "CSS font variant 4" },
    { t_css_font_weight, "CSS font weight" },
    { t_css_font_weight_4, "CSS font weight 4" },
    { t_css_font_weights, "CSS font weights" },
    { t_css_font_width, "CSS font width" },
    { t_css_format, "CSS format" },
    { t_css_frame, "CSS frame" },
    { t_css_gap, "CSS gap" },
    { t_css_gap_2, "CSS gap 2" },
    { t_css_gap_3, "CSS gap 3" },
    { t_css_gap_rule, "CSS gap rule" },
    { t_css_gaps, "CSS gaps" },
    { t_css_generic_family, "CSS generic family" },
    { t_css_gradient, "CSS gradient" },
    { t_css_gradient_image, "CSS gradient image" },
    { t_css_gradient_image_n, "CSS gradient image n" },
    { t_css_grid, "CSS grid" },
    { t_css_grid_line, "CSS grid line" },
    { t_css_grid_lines, "CSS grid lines" },
    { t_css_grid_auto_flow, "CSS grid auto flow" },
    { t_css_grid_template, "CSS grid template" },
    { t_css_grid_templates, "CSS grid templates" },
    { t_css_grid_track_size, "CSS grid track size" },
    { t_css_grid_track_sizes, "CSS grid track sizes" },
    { t_css_hang_punct, "CSS hang punct" },
    { t_css_hang_punct_n, "CSS hang punct n" },
    { t_css_hangs_punct, "CSS hangs punct" },
    { t_css_hll, "CSS hll" },
    { t_css_hue, "CSS hue" },
    { t_css_hue_interpolation, "CSS hue interpolation" },
    { t_css_hue_n, "CSS hue n" },
    { t_css_id, "CSS id" },
    { t_css_ids, "CSS ids" },
    { t_css_ids_an, "CSS ids an" },
    { t_css_ids_n, "CSS ids n" },
    { t_css_if, "CSS if" },
    { t_css_if_bool, "CSS bool" },
    { t_css_if_bool_test, "CSS bool test" },
    { t_css_if_cond, "CSS if cond" },
    { t_css_if_decl, "CSS if decl" },
    { t_css_if_test, "CSS if test" },
    { t_css_image, "CSS image" },
    { t_css_images, "CSS images" },
    { t_css_image_animation, "CSS image animation" },
    { t_css_image_background, "CSS image background" },
    { t_css_image_resolution, "CSS image resolution" },
    { t_css_image_resolution_from, "CSS image resolution from" },
    { t_css_image_set, "CSS image set" },
    { t_css_image_set_rhs, "CSS image set rhs" },
    { t_css_image_proc_e, "CSS image proc e" },
    { t_css_image_processing, "CSS image processing" },
    { t_css_initial_letter, "CSS initial letter" },
    { t_css_initial_letter_align, "CSS initial letter align" },
    { t_css_initial_letter_align_bb, "CSS initial letter align bb" },
    { t_css_initial_letter_n, "CSS initial letter n" },
    { t_css_initial_letter_wrap, "CSS initial letter wrap" },
    { t_css_initial_letter_wrap_e, "CSS initial letter wrap e" },
    { t_css_inline_bem, "CSS inline bem" },
    { t_css_inline_bem_1, "CSS inline bem 1" },
    { t_css_inline_bem_2, "CSS inline bem 2" },
    { t_css_inline_bem_l, "CSS inline bem l" },
    { t_css_inherit, "CSS inherit" },
    { t_css_intrinsic, "CSS intrinsic" },
    { t_css_intrinsic_2, "CSS intrinsic 2" },
    { t_css_isolation, "CSS isolation" },
    { t_css_item_flow, "CSS item flow" },
    { t_css_justify_content, "CSS justify content" },
    { t_css_kbd_lhs, "CSS kbd lhs" },
    { t_css_kdb_nav, "CSS kdb nav" },
    { t_css_kbd_rhs, "CSS kbd rhs" },
    { t_css_lang, "CSS lang" },
    { t_css_langs, "CSS langs" },
    { t_css_layout_box, "CSS background box" },
    { t_css_length, "CSS length" },
    { t_css_length_2, "CSS length 2" },
    { t_css_length_2_a, "CSS length 2 a" },
    { t_css_length_3, "CSS length 3" },
    { t_css_length_a, "CSS length a" },
    { t_css_length_aa, "CSS length aa" },
    { t_css_length_a2, "CSS length a2" },
    { t_css_length_aa2, "CSS length aa2" },
    { t_css_length_abs, "CSS lengths abs" },
    { t_css_length_abs_r, "CSS length abs r" },
    { t_css_length_ai, "CSS length ai" },
    { t_css_length_aia, "CSS length aia" },
    { t_css_length_amm, "CSS length amm" },
    { t_css_length_an, "CSS length an" },
    { t_css_length_base, "CSS length base" },
    { t_css_length_f, "CSS length f" },
    { t_css_length_reals, "CSS length reals" },
    { t_css_length_w, "CSS length w" },
    { t_css_length_inf, "CSS length inf" },
    { t_css_length_infs, "CSS length infs" },
    { t_css_length_inf_mtt, "CSS length inf mtt" },
    { t_css_length_inf_n, "CSS length inf n" },
    { t_css_length_inf_no, "CSS length inf no" },
    { t_css_length_math, "CSS length math" },
    { t_css_length_minmax, "CSS length minmax" },
    { t_css_length_n, "CSS length n" },
    { t_css_length_norm, "CSS length norm" },
    { t_css_length_percent, "CSS length percent" },
    { t_css_length_percent_2, "CSS length percent 2" },
    { t_css_length_percent_inf, "CSS length percent inf" },
    { t_css_length_percent_inf_a, "CSS length percent inf a" },
    { t_css_length_percent_inf_2, "CSS length percent inf 2" },
    { t_css_length_pos, "CSS length pos" },
    { t_css_length_real, "CSS length real" },
    { t_css_length_size, "CSS length size" },
    { t_css_length_twice, "CSS length twice" },
    { t_css_length_xtz, "CSS length xtz" },
    { t_css_length_4, "CSS lengths 4" },
    { t_css_lengths, "CSS lengths" },
    { t_css_lengths_a, "CSS lengths a" },
    { t_css_lengths_aa, "CSS lengths aa" },
    { t_css_lengths_a_l, "CSS lengths a l" },
    { t_css_lengths_aa_l, "CSS lengths aa l" },
    { t_css_lengths_comma, "CSS lengths comma" },
    { t_css_lengths_l, "CSS lengths l" },
    { t_css_lengths_n, "CSS lengths n" },
    { t_css_lengths_n_comma, "CSS lengths n comma" },
    { t_css_line_break, "CSS line break" },
    { t_css_line_clamp, "CSS line clamp" },
    { t_css_line_clamp_n, "CSS line clamp n" },
    { t_css_line_colour, "CSS line colour" },
    { t_css_line_colours, "CSS line colours" },
    { t_css_line_height, "CSS line height" },
    { t_css_line_rule, "CSS line rule" },
    { t_css_line_rules, "CSS line rules" },
    { t_css_line_style, "CSS line style" },
    { t_css_line_styles, "CSS line styles" },
    { t_css_line_width, "CSS line width" },
    { t_css_line_width_border, "CSS line width border" },
    { t_css_line_width_border_2, "CSS line width border 2" },
    { t_css_line_width_border_4, "CSS line width border 4" },
    { t_css_line_width_e, "CSS line width e" },
    { t_css_line_widths, "CSS line width" },
    { t_css_link_params, "CSS link params" },
    { t_css_link_params_n, "CSS link params n" },
    { t_css_link_to, "CSS link to" },
    { t_css_link_to_h, "CSS link to h" },
    { t_css_list_style, "CSS list style" },
    { t_css_list_style_position, "CSS list style position" },
    { t_css_list_style_type, "CSS list style type" },
    { t_css_list_style_type_cs, "CSS list style type cs" },
    { t_css_local_url, "CSS local url" },
    { t_css_ls_val, "CSS ls val" },
    { t_css_margin_break, "CSS margin break" },
    { t_css_margin_trim, "CSS margin trim" },
    { t_css_margin_trim_inner, "CSS margin trim inner" },
    { t_css_margins_trim_inner, "CSS margins trim inner" },
    { t_css_margins, "CSS margins" },
    { t_css_margins_l, "CSS margins l" },
    { t_css_mark, "CSS mark" },
    { t_css_marks, "CSS marks" },
    { t_css_marx, "CSS marx" },
    { t_css_mask, "CSS mask" },
    { t_css_mask_border, "CSS mask border" },
    { t_css_mask_border_mode, "CSS mask border mode" },
    { t_css_mask_border_outsets, "CSS mask border outsets" },
    { t_css_mask_border_repeat, "CSS mask border repeat" },
    { t_css_mask_border_repeats, "CSS mask border repeats" },
    { t_css_mask_border_slice, "CSS mask border slice" },
    { t_css_mask_border_width, "CSS mask border width" },
    { t_css_mask_border_widths, "CSS mask border widths" },
    { t_css_mask_composite, "CSS mask composite" },
    { t_css_mask_composites, "CSS mask composites" },
    { t_css_masking_mode, "CSS masking mode" },
    { t_css_masking_modes, "CSS masking modes" },
    { t_css_mask_ref, "CSS mask ref" },
    { t_css_mask_refs, "CSS mask refs" },
    { t_css_mask_repeat, "CSS mask repeat" },
    { t_css_mask_repeats, "CSS mask repeats" },
    { t_css_masks, "CSS masks" },
    { t_css_math_depth, "CSS math depth" },
    { t_css_mix_blend_mode, "CSS mix blend mode" },
    { t_css_module, "CSS module" },
    { t_css_navigation_keyword, "CSS navigation keyword" },
    { t_css_nth, "CSS nth" },
    { t_css_nth_oe, "CSS nth odd/even" },
    { t_css_object_fit, "CSS object fit" },
    { t_css_object_view_box, "CSS object view box" },
    { t_css_object_view_box_n, "CSS object view box n" },
    { t_css_offset, "CSS offset" },
    { t_css_offset_path, "CSS offset path" },
    { t_css_offset_path_basic, "CSS offset path basic" },
    { t_css_offset_path_n, "CSS offset path n" },
    { t_css_opacity, "CSS opacity"},
    { t_css_orientation, "CSS orientation" },
    { t_css_outline, "CSS outline" },
    { t_css_outline_i, "CSS outline i" },
    { t_css_outline_style, "CSS outline style" },
    { t_css_outlines, "CSS outlines" },
    { t_css_overflow, "CSS overflow" },
    { t_css_overflow_style, "CSS overflow style" },
    { t_css_overflows, "CSS overflows" },
    { t_css_override_colour, "CSS override colour" },
    { t_css_override_colours, "CSS override colours" },
    { t_css_pa_block, "CSS pa block" },
    { t_css_pa_block_inline, "CSS pa block inline" },
    { t_css_pa_inline, "CSS pa inline" },
    { t_css_pa_left, "CSS pa left" },
    { t_css_pa_left_top, "CSS pa left top" },
    { t_css_pa_self, "CSS pa self" },
    { t_css_pa_self_block, "CSS pa self_= block" },
    { t_css_pa_self_block_inline, "CSS pa self block inline" },
    { t_css_pa_self_inline, "CSS pa self inline" },
    { t_css_pa_top, "CSS pa top" },
    { t_css_pa_start, "CSS pa start" },
    { t_css_palette, "CSS palette" },
    { t_css_palette_nld, "CSS palette nld" },
    { t_css_paint_box, "CSS paint box" },
    { t_css_pause, "CSS pause" },
    { t_css_pause_2, "CSS pause 2" },
    { t_css_pause_3, "CSS pause 3" },
    { t_css_pause_3_e, "CSS pause 3 e" },
    { t_css_pause_i, "CSS pause i" },
    { t_css_pauses, "CSS pauses" },
    { t_css_pitch, "CSS pitch" },
    { t_css_pitch_e, "CSS pitch e" },
    { t_css_place_content, "CSS place content" },
    { t_css_place_items, "CSS place items" },
    { t_css_place_self, "CSS place self" },
    { t_css_play_during, "CSS play during" },
    { t_css_play_during_mr, "CSS play during mr" },
    { t_css_polar, "CSS polar" },
    { t_css_pointer_args, "CSS pointer args" },
    { t_css_pointer_source, "CSS pointer source" },
    { t_css_pointer_timeline, "CSS pointer timeline" },
    { t_css_pointer_timelines, "CSS pointer timelines" },
    { t_css_position, "CSS position" },
    { t_css_position_a, "CSS position a" },
    { t_css_position_area, "CSS position area" },
    { t_css_position_area_n, "CSS position area n" },
    { t_css_position_na, "CSS position na" },
    { t_css_position_try, "CSS position try" },
    { t_css_position_visibility, "CSS position visibility" },
    { t_css_position_vvo, "CSS position vvo" },
    { t_css_position_vvos, "CSS position vvos" },
    { t_css_print_status, "CSS print status" },
    { t_css_property, "CSS property" },
    { t_css_pto, "CSS pto" },
    { t_css_quotes, "CSS quotes" },
    { t_css_quotes_3, "CSS quote 3" },
    { t_css_radial_size, "CSS radial size" },
    { t_css_range, "CSS range" },
    { t_css_range_a, "CSS range a" },
    { t_css_ranges, "CSS ranges" },
    { t_css_ray, "CSS ray" },
    { t_css_ray_size, "CSS ray size" },
    { t_css_reading_flow, "CSS reading flow" },
    { t_css_rect, "CSS rect" },
    { t_css_rect_ai, "CSS rect ai" },
    { t_css_rect_fn, "CSS rect fn" },
    { t_css_ref_annotation, "CSS ref annotation" },
    { t_css_ref_character_variant, "CSS ref character variant" },
    { t_css_ref_historical_forms, "CSS ref historical forms" },
    { t_css_ref_ornaments, "CSS ref ornaments" },
    { t_css_ref_swash, "CSS ref swash" },
    { t_css_ref_styleset, "CSS ref styleset" },
    { t_css_ref_stylistic, "CSS ref stylistic" },
    { t_css_region_flow_into, "CSS region flow into" },
    { t_css_region_flow_into_n, "CSS region flow into n" },
    { t_css_region_id, "CSS region id" },
    { t_css_region_id_ni, "CSS region id ni" },
    { t_css_repeat_bixy, "CSS repeat bixy" },
    { t_css_repeat_style, "CSS repeat style" },
    { t_css_repeat_style_xr, "CSS repeat style xr" },
    { t_css_repeat_styles, "CSS repeat styles" },
    { t_css_required_region, "CSS required region" },
    { t_css_relative_size, "CSS relative size" },
    { t_css_resize, "CSS resize" },
    { t_css_rgb_xyz, "CSS rgb xyz" },
    { t_css_rotate, "CSS rotate" },
    { t_css_rotate_angle, "CSS rotate angle" },
    { t_css_rotate_x, "CSS rotate x" },
    { t_css_rotate_y, "CSS rotate y" },
    { t_css_rotate_z, "CSS rotate z" },
    { t_css_route_name, "CSS route name" },
    { t_css_ruby_pos, "CSS ruby pos" },
    { t_css_ruby_pos_in, "CSS ruby pos in" },
    { t_css_rule_colour, "CSS rule colour" },
    { t_css_rule_inset, "CSS rule inset" },
    { t_css_rule_insets, "CSS rule insets" },
    { t_css_rule_insets_sl, "CSS rule insets sl" },
    { t_css_scale, "CSS scale" },
    { t_css_scale_3, "CSS scale 3" },
    { t_css_scope, "CSS scope" },
    { t_css_scroll_button, "CSS scroll button" },
    { t_css_scrollbar_gutter, "CSS scrollbar gutter" },
    { t_css_scroll_state, "CSS scroll state" },
    { t_css_ss_scroll, "CSS ss scroll" },
    { t_css_ss_stuck, "CSS ss stuck" },
    { t_css_ss_snapped, "CSS ss snapped" },
    { t_css_self_position, "CSS self position" },
    { t_css_shadow_spread, "CSS shadow spread" },
    { t_css_shape_box, "CSS shape box" },
    { t_css_shape_ellipse, "CSS shape ellipse" },
    { t_css_shape_fillrule, "CSS shape fillrule" },
    { t_css_shape_inside, "CSS shape inside" },
    { t_css_shape_inside_box, "CSS shape inside box" },
    { t_css_shape_inside_boxen, "CSS shape inside boxen" },
    { t_css_shape_inside_e, "CSS shape inside e" },
    { t_css_shape_outside, "CSS shape outside" },
    { t_css_shape_position, "CSS shape position" },
    { t_css_size, "CSS size" },
    { t_css_size_3, "CSS size 3" },
    { t_css_size_e, "CSS size e" },
    { t_css_size_es, "CSS size es" },
    { t_css_sizing, "CSS sizing" },
    { t_css_skip_line, "CSS skip line" },
    { t_css_skip_lines, "CSS skip lines" },
    { t_css_skip_self, "CSS skip self" },
    { t_css_slider_orientation, "CSS slider orientation" },
    { t_css_speak, "CSS speak" },
    { t_css_speak_2, "CSS speak 2" },
    { t_css_speak_as, "CSS speak as" },
    { t_css_speak_as_2, "CSS speak as 2" },
    { t_css_speak_as_3, "CSS speak as 3" },
    { t_css_speak_as_e, "CSS speak as e" },
    { t_css_speak_header, "CSS speak header" },
    { t_css_speak_numeral, "CSS speak numeral" },
    { t_css_speak_punctuation, "CSS speak punctuation" },
    { t_css_speech_rate, "CSS speech rate" },
    { t_css_speech_rate_e, "CSS speech rate e" },
    { t_css_speech_rate_p, "CSS speech rate p" },
    { t_css_speech_rate_t, "CSS speech rate t" },
    { t_css_spread_shadow, "CSS spread shadow" },
    { t_css_spread_shadows, "CSS spread shadows" },
    { t_css_src, "CSS src" },
    { t_css_src_2, "CSS src 2" },
    { t_css_src_3, "CSS src 3" },
    { t_css_src_4, "CSS src 4" },
    { t_css_srcs, "CSS srcs" },
    { t_css_ss_align, "CSS ss align" },
    { t_css_ss_type, "CSS ss type" },
    { t_css_ss_type_e, "CSS ss type e" },
    { t_css_ss_type_n, "CSS ss type n" },
    { t_css_statement, "CSS statement" },
    { t_css_stn, "CSS stn" },
    { t_css_stn_n, "CSS stn n" },
    { t_css_stn_na, "CSS stn na" },
    { t_css_stroke_linejoin, "CSS stroke linejoin" },
    { t_css_str_set, "CSS str set" },
    { t_css_str_sets, "CSS str sets" },
    { t_css_str_sets_n, "CSS str sets n" },
    { t_css_sts, "CSS sts" },
    { t_css_stss, "CSS stss" },
    { t_css_stss_n, "CSS stss n" },
    { t_css_sym, "CSS sym" },
    { t_css_system, "CSS system" },
    { t_css_system_e, "CSS system e" },
    { t_css_system_ext, "CSS system ext" },
    { t_css_system_fix, "CSS system fix" },
    { t_css_synthesis, "CSS synthesis" },
    { t_css_table_layout, "CSS table layout" },
    { t_css_target_contrast, "CSS target contrast" },
    { t_css_tech, "CSS tech" },
    { t_css_template_set, "CSS template set" },
    { t_css_text_align, "CSS text align" },
    { t_css_text_align_4, "CSS text align 4" },
    { t_css_text_align_all, "CSS text align all" },
    { t_css_text_align_last, "CSS text align last" },
    { t_css_text_autospace, "CSS text autospace" },
    { t_css_text_autospaces, "CSS text autospaces" },
    { t_css_text_autospaces_na, "CSS text autospaces na" },
    { t_css_text_combine_upright, "CSS text combine upright" },
    { t_css_text_combine_upright_d, "CSS text combine upright d" },
    { t_css_text_decoration, "CSS text decoration" },
    { t_css_text_decorations, "CSS text decorations" },
    { t_css_text_fade, "CSS text fade" },
    { t_css_text_indent, "CSS text indent" },
    { t_css_text_justify, "CSS text justify" },
    { t_css_text_justify_nc, "CSS text justify nc" },
    { t_css_text_orientation, "CSS text orientation" },
    { t_css_text_resize, "CSS text resize" },
    { t_css_text_resize_4, "CSS text resize 4" },
    { t_css_text_resizes, "CSS text resizes" },
    { t_css_text_resizes_4, "CSS text resizes 4" },
    { t_css_text_shadow, "CSS text shadow" },
    { t_css_text_spacing, "CSS text spacing" },
    { t_css_text_spacing_nan, "CSS text spacing nan" },
    { t_css_text_spacing_trim, "CSS text spacing trim" },
    { t_css_text_transform, "CSS text transform" },
    { t_css_text_transform_3, "CSS text transform 3" },
    { t_css_text_transform_n, "CSS text transform n" },
    { t_css_textdec_line, "CSS textdec line" },
    { t_css_textdec_line_e, "CSS textdec line e" },
    { t_css_textdec_short, "CSS textdec short" },
    { t_css_textdec_style, "CSS textdec style" },
    { t_css_textdec_skip, "CSS textdec skip" },
    { t_css_textdec_skips, "CSS textdec skips" },
    { t_css_textdec_skip_space, "CSS textdec skip space" },
    { t_css_textdec_thickness, "CSS textdec thickness" },
    { t_css_textdec_underline, "CSS textdec underline" },
    { t_css_textdec_underline_lru, "CSS textdec underline lru" },
    { t_css_textdec_underline_offset, "CSS textdec underline offset" },
    { t_css_text_emphases, "CSS text emphases" },
    { t_css_text_emphasis, "CSS text emphasis" },
    { t_css_textemph_skip, "CSS textemph skip" },
    { t_css_textemph_pos, "CSS textemph pos" },
    { t_css_textemph_shape, "CSS textemph shape" },
    { t_css_textemph_string, "CSS textemph string" },
    { t_css_textemph_style, "CSS textemph style" },
    { t_css_textemph_substyle, "CSS textemph substyle" },
    { t_css_text_fit, "CSS text fit" },
    { t_css_texts_indent, "CSS texts indent" },
    { t_css_text_wrap, "CSS text wrap" },
    { t_css_text_wrap_mode, "CSS text wrap mode" },
    { t_css_text_wrap_style, "CSS text wrap style" },
    { t_css_tmbl, "CSS tmbl" },
    { t_css_touch_action, "CSS touch action" },
    { t_css_track_list, "CSS track list" },
    { t_css_track_name, "CSS track name" },
    { t_css_track_part, "CSS track part" },
    { t_css_track_part_x, "CSS track part x" },
    { t_css_trans_prop, "CSS trans prop" },
    { t_css_trans_prop_a, "CSS trans prop a" },
    { t_css_trans_prop_n, "CSS trans prop n" },
    { t_css_trans_props, "CSS transi props" },
    { t_css_trans_props_n, "CSS trans props n" },
    { t_css_transform, "CSS transform" },
    { t_css_transform_box, "CSS transform box" },
    { t_css_transform_origin, "CSS transform origin" },
    { t_css_transform_origins, "CSS transform origins" },
    { t_css_transform_n, "CSS transform n" },
    { t_css_transforms, "CSS transforms" },
    { t_css_transform_style, "CSS transform style" },
    { t_css_translate, "CSS translate" },
    { t_css_translate_n, "CSS translate n" },
    { t_css_transition, "CSS transition" },
    { t_css_transitions, "CSS transitions" },
    { t_css_trn, "CSS trn" },
    { t_css_try_fallback, "CSS try fallback" },
    { t_css_try_fallbacks, "CSS try fallbacks" },
    { t_css_try_size, "CSS try size" },
    { t_css_try_tactic, "CSS try tactic" },
    { t_css_try_tactics, "CSS try tactics" },
    { t_css_tst, "CSS tst" },
    { t_css_ttaran, "CSS ttar" },
    { t_css_ttarans, "CSS ttarans" },
    { t_css_ttaran2, "CSS ttaran2" },
    { t_css_ttaran2s, "CSS ttaran2s" },
    { t_css_ttarn, "CSS ttarn" },
    { t_css_ttarns, "CSS ttarns" },
    { t_css_ttarn2, "CSS ttarn2" },
    { t_css_ttarn2s, "CSS ttar2s" },
    { t_css_tt, "CSS tt" },
    { t_css_ttrnl, "CSS ttrnl" },
    { t_css_tts, "CSS tts" },
    { t_css_ttsn, "CSS ttsn" },
    { t_css_type, "CSS type" },
    { t_css_unicode_from_to, "CSS unicode from to" },
    { t_css_unicode_range, "CSS unicode range" },
    { t_css_unicode_ranges, "CSS unicode ranges" },
    { t_css_unicode_wildcard, "CSS unicode wildcard" },
    { t_css_url, "CSS url" },
    { t_css_url_or_s, "CSS url or s" },
    { t_css_user_select, "CSS user select" },
    { t_css_val_con, "CSS val con" },
    { t_css_val_fn, "CSS val fn" },
    { t_css_val_fn_n, "CSS val fn n" },
    { t_css_var, "CSS var" },
    { t_css_vbl_len, "CSS vbl len" },
    { t_css_vector_effect, "CSS vector effect" },
    { t_css_version, "CSS version" },
    { t_css_vertal, "CSS vertal" },
    { t_css_vertal_2, "CSS vertal 2" },
    { t_css_vertal_inline, "CSS vertal inline" },
    { t_css_vertical_align, "CSS vertical align" },
    { t_css_view_timeline, "CSS view timeline" },
    { t_css_view_timelines, "CSS view timelines" },
    { t_css_visual_box, "CSS visual box" },
    { t_css_voice, "CSS voice" },
    { t_css_voice_age, "CSS voice age" },
    { t_css_voice_balance, "CSS voice balance" },
    { t_css_voice_balance_e, "CSS voice balance e" },
    { t_css_voice_families, "CSS voice families" },
    { t_css_voice_families_p, "CSS voice families p" },
    { t_css_voice_family, "CSS voice family" },
    { t_css_voice_family_desc, "CSS voice family desc" },
    { t_css_voice_gender, "CSS voice gender" },
    { t_css_voice_pitch, "CSS voice pitch" },
    { t_css_voice_volume, "CSS voice volume" },
    { t_css_volume, "CSS volume" },
    { t_css_volume_e, "CSS volume e" },
    { t_css_vtg, "CSS vtg" },
    { t_css_vtn, "CSS vtn" },
    { t_css_vtn_n, "CSS vtn n" },
    { t_css_vtn_splat, "CSS vtn splat" },
    { t_css_wbd, "CSS wbd" },
    { t_css_wbe, "CSS wbe" },
    { t_css_wc, "CSS WC" },
    { t_css_wc_e, "CSS WC e" },
    { t_css_wcs, "CSS WCs" },
    { t_css_wcs_a, "CSS WCs a" },
    { t_css_whitespace, "CSS whitespace" },
    { t_css_whitespace_2, "CSS whitespace 2" },
    { t_css_whitespace_4, "CSS whitespace 4" },
    { t_css_wide, "CSS wide" },
    { t_css_win_shad, "CSS win shad" },
    { t_css_word_break, "CSS word break" },
    { t_css_worklet, "CSS worklet"},
    { t_css_wrap_flow, "CSS wrap flow" },
    { t_css_ws_wsc, "CSS ws wsc val" },
    { t_css_wsc, "CSS wsc" },
    { t_css_wsc_val, "CSS wsc val" },
    { t_css_wst, "CSS wst" },
    { t_css_wsts, "CSS wsts" },
    { t_css_zoom, "CSS zoom" },
    { t_csvw_direction, "csvw direction" },
    { t_curie, "curie" },
    { t_curie_safe, "curie safe" },
    { t_curies, "curies" },
    { t_currency, "currency" },
    { t_current_colour_sz, "current colour sz" },
    { t_cursor, "cursor" },
    { t_cursor_f, "cursor f" },
    { t_cursor_i, "cursor i" },
    { t_custom_element, "custom element" },
    { t_custom_element_old, "custom element (old)" },
    { t_custom_element_new, "custom element (new)" },
    { t_custom_id, "custom id" },
    { t_custom_ids, "custom ids" },
    { t_custom_ids_n, "custom ids n" },
    { t_custom_property, "custom property" },
    { t_d, "d" },
    { t_dashes, "dashes" },
    { t_data, "data" },
    { t_dataformatas, "data format as" },
    { t_datetime, "datetime" },
    { t_datetime_4, "datetime 4" },
    { t_datetime_5, "datetime 5" },
    { t_datetime_absolute, "datetime absolute" },
    { t_datetime_auto, "datetime auto" },
    { t_datetime_autos, "datetime autos" },
    { t_datetime_http, "datetime http" },
    { t_datetime_local, "datetime local" },
    { t_day, "day" },
    { t_dcmitype, "dcmitype" },
    { t_ddny, "ddny" },
    { t_decalign, "dec align" },
    { t_decibel, "decibel" },
    { t_decoding, "decoding" },
    { t_defaultaction, "default action" },
    { t_default_none, "default none" },
    { t_depth, "depth" },
    { t_determiner, "determiner" },
    { t_device, "device" },
    { t_device_or_height, "device or height" },
    { t_device_or_width, "device or width" },
    { t_dg, "dg" },
    { t_digits, "digits" },
    { t_dingbat, "dingbat" },
    { t_dir, "dir" },
    { t_direction, "direction" },
    { t_directive, "directive" },
    { t_display, "display" },
    { t_display_align, "display align" },
    { t_display_none_parent, "display none parent" },
    { t_dnu, "dnu" },
    { t_dominantbaseline, "dominant baseline" },
    { t_dosh, "dosh" },
    { t_drag_nodrag, "drag nodrag" },
    { t_drop_raise, "drop raise" },
    { t_dsc, "dsc" },
    { t_dsc2, "dsc2" },
    { t_dss, "dss" },
    { t_dsss, "dsss" },
    { t_dur, "dur" },
    { t_dur_repeat, "dur repeat" },
    { t_duration, "duration" },
    { t_duration_a, "duration a" },
    { t_duration_media, "duration media" },
    { t_dynamic_range, "dynamic range" },
    { t_e_w, "e w" },
    { t_economy_exact, "economy exact" },
    { t_edgemode, "edge mode" },
    { t_edi, "edi" },
    { t_edit, "edit" },
    { t_editable, "editable" },
    { t_effect, "effect" },
    { t_email, "email" },
    { t_emails, "emails" },
    { t_empty, "empty" },
    { t_ems, "ems" },
    { t_enable_background, "enable background" },
    { t_enctype, "enc type" },
    { t_end, "end" },
    { t_endvaluelist, "end value list" },
    { t_ens, "ens" },
    { t_enterkeyhint, "enter key hint" },
    { t_environment_blending, "environment blending" },
    { t_eso, "eso" },
    { t_evt_action, "evt action" },
    { t_exif_intind, "exif int ind" },
    { t_existential, "existential" },
    { t_expected, "expected" },
    { t_exportpart, "exportpart" },
    { t_fallback, "fallback" },
    { t_fediverse_id, "fediverse_id" },
    { t_ffls, "ffls" },
    { t_figalign, "fig align" },
    { t_filename, "filename" },
    { t_filesize, "file size" },
    { t_fill, "fill" },
    { t_fill_v, "fill v" },
    { t_fill_opacity, "fill opacity" },
    { t_fill_rule, "fill rule" },
    { t_fill_ve, "fill ve" },
    { t_fillanim, "fill anim" },
    { t_filled_open, "filled open" },
    { t_filter_in, "filter in" },
    { t_filterres, "filter res" },
    { t_first_last, "first last" },
    { t_fixedcolour, "fixed colour" },
    { t_fixedpoint, "fixed point" },
    { t_fixedpoint_inf, "fixedpoint inf" },
    { t_fixed_zoom, "fixed zoom" },
    { t_css_fn_trans_args, "fn" },
    { t_fnrs, "fnrs" },
    { t_fns, "fns" },
    { t_font, "font" },
    { t_font_enum, "font enum" },
    { t_font_families, "font families" },
    { t_font_family, "font family" },
    { t_font_synthesis, "font synthesis" },
    { t_font_synthesis_n, "font synthesis n" },
    { t_font_variant, "font variant" },
    { t_font_variant_2, "font variant 2" },
    { t_font_variant_2s, "font variant 2s" },
    { t_font_variant_4, "font variant 4" },
    { t_font_variant_alternatives, "font variant alternatives" },
    { t_font_variant_caps, "font variant caps" },
    { t_font_variant_east_asian, "font variant east asian" },
    { t_font_variant_east_asians, "font variant east asians" },
    { t_font_variant_emoji, "font variant emoji" },
    { t_font_variant_ligature, "font variant ligature" },
    { t_font_variant_ligatures, "font variant ligatures" },
    { t_font_variant_numeric, "font variant numeric" },
    { t_font_variant_numerics, "font variant numerics" },
    { t_font_variant_position, "font variant position" },
    { t_fontname, "fontname" },
    { t_fontnia, "font nia" },
    { t_fontnias, "font nias" },
    { t_fontsize, "font size" },
    { t_fontsizeadjust, "font size adjust" },
    { t_fontstretch, "font stretch" },
    { t_fontstretches, "font stretches" },
    { t_fontstyle, "font style" },
    { t_fontvariant, "font variant" },
    { t_fontvariants, "font variants" },
    { t_fontweight, "font weight" },
    { t_forced_colours, "forced colours" },
    { t_form, "form" },
    { t_format, "format" },
    { t_formaturi, "format uri" },
    { t_forrev, "forrev" },
    { t_fr, "fr" },
    { t_frp, "frp" },
    { t_frame, "frame" },
    { t_frame4, "frame 4" },
    { t_framespacing, "frame spacing" },
    { t_frequency, "frequency" },
    { t_frequency_abs, "frequency abs" },
    { t_from, "from" },
    { t_from_angle, "from angle" },
    { t_ftpte, "ftpte" },
    { t_gamut, "gamut" },
    { t_gender, "gender" },
    { t_generic, "generic" },
    { t_glyphname, "glyph name" },
    { t_glyphnames, "glyph names" },
    { t_gns, "gns" },
    { t_grid_normal, "grid normal" },
    { t_groupalign, "group align" },
    { t_gtin, "gtin" },
    { t_gtin8, "gtin8" },
    { t_gtin12, "gtin12" },
    { t_gtin13, "gtin13" },
    { t_gtin14, "gtin14" },
    { t_halign, "h align" },
    { t_hash_fn, "hash fn" },
    { t_hash_ref, "hash ref" },
    { t_height, "height" },
    { t_hex, "hex" },
    { t_hidden, "hidden" },
    { t_hidden_ex, "hidden ex" },
    { t_hline, "hline" },
    { t_hour, "hour" },
    { t_hslafn, "hsla fn" },
    { t_hslfn, "hsl fn" },
    { t_hslfn4, "hsl fn 4" },
    { t_html, "html" },
    { t_html_boolean, "html boolean" },
    { t_httpequiv, "http equiv" },
    { t_hue, "hue" },
    { t_hue_n, "hue n" },
    { t_hunit, "hunit" },
    { t_huv, "huv" },
    { t_hwbfn, "hwb fn" },
    { t_labfn, "lab fn" },
    { t_lchfn, "lch fn" },
    { t_oklabfn, "oklab fn" },
    { t_oklchfn, "oklch fn" },
    { t_colourfn, "colour fn" },
    { t_colourspace, "colourspace" },
    { t_icalfreq, "ical freq" },
    { t_icc, "icc" },
    { t_icccolour, "icc colour" },
    { t_id, "id" },
    { t_identifier_url, "identifier url" },
    { t_idref, "idref" },
    { t_idrefs, "idrefs" },
    { t_ign_stf, "ign stf" },
    { t_iiu, "iiu" },
    { t_illegal, "illegal" },
    { t_image_rendering, "image rendering" },
    { t_imcastr, "imcastr" },
    { t_imgsizes, "img sizes" },
    { t_imgsizes_a, "img sizes a" },
    { t_importance, "importance" },
    { t_in, "in" },
    { t_indentalign, "indent align" },
    { t_indentalign2, "indent align 2" },
    { t_indentshift2, "indent shift 2" },
    { t_index, INDEX },
    { t_infixlinebreakstyle, "infix line break style" },
    { t_initialvisibility, "initial visibility" },
    { t_inky, "inky" },
    { t_inline, "inline" },
    { t_inlist, "inlist" },
    { t_inn, "inn" },
    { t_inn2, "inn2" },
    { t_inputaccept, "input accept" },
    { t_inputmode, "input mode" },
    { t_inputplus, "input plus" },
    { t_inputtype, "input type" },
    { t_inputtype3, "input type 3" },
    { t_inputtype32, "input type 3/2" },
    { t_inputtype4, "input type4" },
    { t_inputtype5, "input type5" },
    { t_inset, "inset" },
    { t_integer, "integer" },
    { t_integer_1_up, "integer 1 up" },
    { t_integer_1_up_inf, "integer 1 up inf" },
    { t_integer_1_up_inf_a, "integer 1 up inf a" },
    { t_integer_1_up_inf_aa, "integer 1 up inf aa" },
    { t_integer_1_up_inf_aaa, "integer 1 up inf aaa" },
    { t_integer_1_up_inf_aan, "integer 1 up inf aan" },
    { t_integer_ai, "integer ai" },
    { t_integer_i, "integer i" },
    { t_integer_is, "integer is" },
    { t_integer_ln, "integer ln" },
    { t_integer_n, "integer n" },
    { t_integer_nl, "integer nl" },
    { t_integer_oo, "integer oo" },
    { t_integer_or_percent, "integer or percent" },
    { t_integers, "integers" },
    { t_integers_a, "integers a" },
    { t_intent, "intent" },
    { t_intent_app, "intent app" },
    { t_intent_args, "intent args" },
    { t_intent_conlit, "intent conlit" },
    { t_intent_hint, "intent hint" },
    { t_intent_ref, "intent ref" },
    { t_interactive_widget, "interactie widget" },
    { t_inverted_colours, "inverted colours" },
    { t_io, "io" },
    { t_ios, "ios" },
    { t_ip_address, "ip address" },
    { t_is, "is" },
    { t_isbn, "isbn" },
    { t_issn, "issn" },
    { t_itemid, "item id" },
    { t_itemprop, "item prop" },
    { t_itemref, "item ref" },
    { t_itemtype, "item type" },
    { t_js_lang, "JS lang" },
    { t_js_lang_map, "JS lang map" },
    { t_js_map, "JS map" },
    { t_js_term, "JS term" },
    { t_js_type, "JS type" },
    { t_js_value, "JS value" },
    { t_js_version, "JS version" },
    { t_json, "json" },
    { t_jtoken, "j token" },
    { t_just_date, "just date" },
    { t_just_time, "just time" },
    { t_k_m_n, "k m n" },
    { t_key, "key" },
    { t_keychar, "keychar" },
    { t_keycode, "keycode" },
    { t_keygentype, "key gen type" },
    { t_keyspline, "key spline" },
    { t_keysplines, "key splines" },
    { t_keytimes, "key times" },
    { t_keytype, "key type" },
    { t_kind, "kind" },
    { t_lang, "lang" },
    { t_lang_n, "lang n" },
    { t_langq, "lang q" },
    { t_langqs, "lang qs" },
    { t_langs, "langs" },
    { t_larnalign, "larn align" },
    { t_layout, "layout" },
    { t_lchfn, "lch fn" },
    { t_lcralign, "lcr align" },
    { t_lcraligns, "lcr aligns" },
    { t_lcrd, "lcrd" },
    { t_lcrds, "lcrds" },
    { t_lcrdss, "lcrdss" },
    { t_legacy_scale, "legacy scale" },
    { t_lcrnalign, "lcrn align" },
    { t_length, "length" },
    { t_length_absolute, "length absolute" },
    { t_length_relative, "length relative" },
    { t_lengthadjust, "length adjust" },
    { t_light_dark, "light dark" },
    { t_linear_1, "linear 1" },
    { t_linear_2, "linear 2" },
    { t_linear_12, "linear 12" },
    { t_linear_arg, "linear arg" },
    { t_linear_colour_more, "linear colour more" },
    { t_linear_colour_stop, "linear colour stop" },
    { t_linear_colour_stops, "linear colour stops" },
    { t_line_height, "line height" },
    { t_linebreak, "line break" },
    { t_linebreakstyle, "line break style" },
    { t_linecap, "line cap" },
    { t_linejoin, "line join" },
    { t_linethickness, "line thickness" },
    { t_link, "link" },
    { t_linkarg, "link arg" },
    { t_linkargs, "link args" },
    { t_linkitself, "link itself" },
    { t_linkparam, "lin kparam" },
    { t_links, "links" },
    { t_listtype, "list type" },
    { t_literal, "literal" },
    { t_literal_or_not, "literal or not" },
    { t_lnr, "lnr" },
    { t_loading, "loading" },
    { t_localfn, "local fn" },
    { t_local_url, "local url" },
    { t_locale, "locale" },
    { t_location, "location" },
    { t_longdivstyle, "long div style" },
    { t_loop, "loop" },
    { t_loopie, "loopie" },
    { t_lraalign, "lra align" },
    { t_lralign, "lr align" },
    { t_lrnalign, "lrn align" },
    { t_lrnialign, "lrni align" },
    { t_lrtb, "lrtb" },
    { t_lrxx, "lrxx" },
    { t_lspace, "l space" },
    { t_ltr_rtl, "ltr rtl" },
    { t_lzz, "lzz" },
    { t_m_t, "m t" },
    { t_m1_to_1, "-1 to 1"},
    { t_m1_to_5, "-1 to 5" },
    { t_m100_to_100, "-100 to 100" },
    { t_m100_to_100r, "-100.0 to 100.0" },
    { t_m128_to_127, "-128 to 127" },
    { t_m150_to_150, "-150 to 150" },
    { t_m4_to_4, "-4 to 4" },
    { t_m50_to_100, "-50 to 100" },
    { t_mah, "mah" },
    { t_mand_prox, "mand prox" },
    { t_manual_normal, "manual normal" },
    { t_margin_padding, "margin padding" },
    { t_margin_padding_new, "margin padding new" },
    { t_margin_padding_old, "margin padding old" },
    { t_marked_up, "marked up" },
    { t_marker, "marker" },
    { t_markerunits, "marker units" },
    { t_match_self_parent, "match self parent" },
    { t_mathalign, "math align" },
    { t_mathalign_n, "math align n" },
    { t_mathaligns, "math aligns" },
    { t_mathclosure, "math closure" },
    { t_math_constant, "math constant" },
    { t_mathfontstyle, "math font style" },
    { t_mathfontweight, "math font weight" },
    { t_mathform, "math form" },
    { t_mathframe, "math frame" },
    { t_mathlocation, "math location" },
    { t_mathmode, "math mode" },
    { t_mathnotation, "math notation" },
    { t_mathnotations, "math notations" },
    { t_mathoccurence, "math occurence" },
    { t_mathorder, "math order" },
    { t_mathoverflow, "math overflow" },
    { t_mathscope, "math scope" },
    { t_mathside, "math side" },
    { t_mathsize, "math size" },
    { t_mathspace, "math space" },
    { t_mathspaceauto, "math space auto" },
    { t_mathspacefit, "math space fit" },
    { t_mathspaceinfinity, "math space infinity" },
    { t_math_str, "math str" },
    { t_mathvariant, "math variant" },
    { t_math_version, "math version" },
    { t_mathvertauto, "math vertauto" },
    { t_matrix_values, "matrix values" },
    { t_matrixtype, "matrix type" },
    { t_maybe_filename, "maybe_filename" },
    { t_mb, "mb" },
    { t_measure, "measure" },
    { t_measure_2, "measure 2" },
    { t_measure_4, "measure 4" },
    { t_measure_a, "measure a" },
    { t_measure_ai, "measure ai" },
    { t_measure_ai_2, "measure ai 2" },
    { t_measure_i, "measure i" },
    { t_measure_in, "measure in" },
    { t_measure_ni, "measure ni" },
    { t_measure_or_more, "measure or more" },
    { t_measures, "measures" },
    { t_measures_a, "measures a" },
    { t_measures_all, "measures all" },
    { t_measures_i, "measures i" },
    { t_measures_l, "measures l" },
    { t_media, "media" },
    { t_media_display_mode, "media display mode" },
    { t_media_hover, "media hover" },
    { t_media_inline, "media inline" },
    { t_media_orientation, "media orientation" },
    { t_media_overflow, "media overflow" },
    { t_media_pointer, "media pointer" },
    { t_media_prefers, "media prefers" },
    { t_media_prefers_2, "media prefers 2" },
    { t_media_scripting, "media scripting" },
    { t_meetslice, "meet slice" },
    { t_menuitem, "menu item" },
    { t_menutype, "menu type" },
    { t_metaname, "metaname" },
    { t_method, "method" },
    { t_methodological, "methodological" },
    { t_mf_availability, "mf availability" },
    { t_mf_category, "mf category" },
    { t_mf_class, "mf class" },
    { t_mf_identifier, "mf identifier" },
    { t_mf_itemtype, "mf itemtype" },
    { t_mf_listing_action, "mf listing action" },
    { t_mf_listing_actions, "mf listing actions" },
    { t_mf_method, "mf method" },
    { t_mf_relationship, "mf_relationship" },
    { t_mf_reviewtype, "mf reviewtype" },
    { t_mf_status, "mf status" },
    { t_mf_tel, "mf_tel" },
    { t_mime, "mime" },
    { t_mimelist, "mime list" },
    { t_mimemodule, "mime module" },
    { t_mimeq, "mime q" },
    { t_mimeqs, "mime qs" },
    { t_mimestar, "mime star" },
    { t_minmax_content, "minmax content" },
    { t_minute, "minute" },
    { t_mode, "mode" },
    { t_month, "month" },
    { t_month_english_long, "month english long" },
    { t_month_english_short, "month english short" },
    { t_monthday, "month day" },
    { t_morphology_operator, "morphology operator" },
    { t_mql, "mql" },
    { t_mqls, "mqls" },
    { t_musickey, "musickey" },
    { t_mrss_expression, "mrss expression" },
    { t_mrss_info, "mrss info" },
    { t_mrss_medium, "mrss medium" },
    { t_mrss_ntp, "mrss ntp" },
    { t_mrss_price_type, "mrss price type" },
    { t_mrss_reltype, "mrss reltype" },
    { t_mrss_role, "mrss role" },
    { t_mrss_state, "mrss state" },
    { t_mrss_status, "mrss status" },
    { t_mrss_type, "mrss type" },
    { t_mtt, "mtt" },
    { t_multiple_single, "t_multiple_single" },
    { t_myersbriggs, "pseudopsychology" },
    { t_n_s, "n s" },
    { t_name, "name" },
    { t_namedspace, "named space" },
    { t_naughty, "naughty" },
    { t_nameref, "name ref" },
    { t_namespace, "name space" },
    { t_nav_controls, "nav controls" },
    { t_navigation, "navigation" },
    { t_nearest_none, "none nearest" },
    { t_negative, "negative" },
    { t_nit_macro, "nit macro" },
    { t_nit_section, "nit section" },
    { t_no_braille, "no_braille" },
    { t_none, "none" },
    { t_none_objects, "none objects" },
    { t_none_wrap, "none wrap" },
    { t_normal, "normal" },
    { t_normal_spell, "normal spell" },
    { t_normal_stretch, "normal stretch" },
    { t_not_0, "not 0" },
    { t_not_empty, "not empty" },
    { t_not_neg, "not neg" },
    { t_not_pos, "not pos" },
    { t_notation, "notation" },
    { t_notations, "notations" },
    { t_nsd, "nsd" },
    { t_nsds, "nsds" },
    { t_nss, "nss" },
    { t_nuf, "nuf" },
    { t_num, "num" },
    { t_occurence, "occurence" },
    { t_og, "og" },
    { t_ogdet, "og det" },
    { t_ogtype, "og type" },
    { t_onetwo, "onetwo" },
    { t_onetwothree, "onetwothree" },
    { t_onoff, "onoff" },
    { t_onoffempty, "onoffempty" },
    { t_opacity, "opacity" },
    { t_opacity_percent, "opacity percent" },
    { t_open, "open" },
    { t_operator, "operator" },
    { t_order, "order" },
    { t_orientation, "orientation" },
    { t_origin, "origin" },
    { t_output_template, "output template" },
    { t_overflow, "overflow" },
    { t_overlay, "overlay" },
    { t_over_under, "over under" },
    { t_p1_10, "p1 10" },
    { t_page_orientation, "page orientation" },
    { t_paint, "paint" },
    { t_paint_order, "paint order" },
    { t_paint_orders, "paint orders" },
    { t_paintkeyword, "paintkeyword" },
    { t_pam_ccv, "pam ccv" },
    { t_pam_status, "pam status" },
    { t_panose1, "panose1" },
    { t_part, "part" },
    { t_pcmm_status, "pcmm status" },
    { t_percent, "percent" },
    { t_percent_100, "percent 100" },
    { t_percent_b, "percent b" },
    { t_percent_flexible, "percent flexible" },
    { t_percent_int, "percent int" },
    { t_percent_l, "percent l" },
    { t_percent_n, "percent n" },
    { t_percent_s, "percent s" },
    { t_percent_or_neg, "t_percent_or_neg" },
    { t_percent_or_not, "t_percent_or_not" },
    { t_percent_w, "percent w" },
    { t_percentish, "percent positive" },
    { t_percents_flexible, "percent flexible" },
    { t_percents_n, "percent n" },
    { t_percents_nf, "percents nf" },
    { t_permpol, "permpol" },
    { t_phase, "phase" },
    { t_phase_x, "phase x" },
    { t_pics, "pics" },
    { t_plainhtml, "plain html" },
    { t_plus_1_7, "plus 1 7" },
    { t_plusstyle, "plus style" },
    { t_pointer_events, "pointer events" },
    { t_points, "points" },
    { t_popover, "popover" },
    { t_popovertargetaction, "popovertargetaction" },
    { t_port, "port" },
    { t_position, "position" },
    { t_position_lcrtcb, "position" },
    { t_position_lcrtcb_len, "position" },
    { t_position_lr_len, "position" },
    { t_position_lrtb_len, "position" },
    { t_position_tb_len, "position" },
    { t_position_tickleish, "position_tickleish" },
    { t_positions, "positions" },
    { t_positive, "positive" },
    { t_positive_1_2, "positive 1 2" },
    { t_positive_i, "positive i" },
    { t_positive_n, "positive n" },
    { t_pragma, "pragma" },
    { t_prefix, "prefix" },
    { t_preload, "preload" },
    { t_preload5, "preload 5" },
    { t_preserveaspectratio, "preserve aspect ratio" },
    { t_preserveaspectratio10, "preserve aspect ratio 10" },
    { t_preserveaspectratio12, "preserve aspect ratio 12" },
    { t_pri_img_colour, "pri img colour" },
    { t_pri_img_orientation, "pri img orientation" },
    { t_pri_img_season, "pri img season" },
    { t_pri_img_setting, "pri img setting" },
    { t_pri_img_technique, "pri img technique" },
    { t_pri_img_viewpoint, "pri img viewpoint" },
    { t_print, "print" },
    { t_prism_ad_pos, "prism ad pos" },
    { t_prism_ad_type, "prism ad type" },
    { t_prism_ag_type, "prism ag type" },
    { t_prism_audience_sector, "prism audience sector" },
    { t_prism_ccv, "prism ccv" },
    { t_prism_class, "prism class" },
    { t_prism_contenttype, "prism contenttype" },
    { t_prism_cvp, "prism cvp" },
    { t_prism_fccv, "prism fccv" },
    { t_prism_genre, "prism genre" },
    { t_prism_icv, "prism icv" },
    { t_prism_issue_type, "prism issue type" },
    { t_prism_pasv, "prism pasv" },
    { t_prism_pcv, "prism pcv" },
    { t_prism_pfv, "prism pfv" },
    { t_prism_ptv, "prism ptv" },
    { t_prism_rcv, "prism rcv" },
    { t_prism_rcv_opt, "prism rcv opt" },
    { t_prism_role, "prism role" },
    { t_prism_tablet_ad, "prism tablet ad" },
    { t_private_token, "private token" },
    { t_protocol, "protocol" },
    { t_prs_action, "prs action" },
    { t_prs_duty, "prs duty" },
    { t_propagate, "propagate" },
    { t_pseudo, "pseudo" },
    { t_pseudonamedspace, "pseudo named space" },
    { t_pt, "pt" },
    { t_purls, "purls" },
    { t_q, "q" },
    { t_quote_style, "quote style" },
    { t_r0_to_1, "r0 to 1" },
    { t_radial_3, "radial 3" },
    { t_radial_4, "radial 4" },
    { t_radial_34, "radial 34" },
    { t_radial_ending, "radial ending" },
    { t_radial_size, "radial size" },
    { t_radial_start, "radial start" },
    { t_rap, "rap" },
    { t_ratio, "ratio" },
    { t_ratio_a, "ratio a" },
    { t_rational, "rational" },
    { t_rationals, "rationals" },
    { t_rating, "rating" },
    { t_rdf_parsetype, "rdf parse type" },
    { t_rdfa_typeof, "rdfa type of" },
    { t_real, "real" },
    { t_real_1_2, "real 1 2" },
    { t_real_1_up, "real 1 up" },
    { t_real_1_up_inf, "real 1 up inf" },
    { t_real_04, "real 04" },
    { t_real_100, "real 100" },
    { t_real_125, "real 125" },
    { t_real_360, "real 360" },
    { t_real_ai, "real ai" },
    { t_real_angle_h, "real angle h" },
    { t_real_angle_n, "real angle n" },
    { t_real_i, "real i" },
    { t_real_infinity, "real infinity" },
    { t_real_int_1_up, "real int 1 up" },
    { t_real_n, "real n" },
    { t_real_ni, "real ni" },
    { t_real_infinity_pos, "real inf pos" },
    { t_real_percent, "real %" },
    { t_real_percent_04, "real % 04" },
    { t_real_percent_100, "real % 100" },
    { t_real_percent_125, "real % 125" },
    { t_real_percentish, "real %ish"},
    { t_real_percent_n, "real % n" },
    { t_real_percent_n_a, "real % n a" },
    { t_real_percent_n_a04, "real % n a04" },
    { t_real_percent_n_b, "real % n b" },
    { t_real_percent_n_bz, "real % n bz" },
    { t_real_percent_n_b04, "real % n b04" },
    { t_real_percent_n_b125, "real % n b125" },
    { t_real_percent_n_c, "real % n c" },
    { t_real_percent_n_g, "real % n g" },
    { t_real_percent_n_gy, "real % n gy" },
    { t_real_percent_n_h, "real % n h" },
    { t_real_percent_n_L, "real % n L" },
    { t_real_percent_n_l, "real % n l" },
    { t_real_percent_n_r, "real % n g" },
    { t_real_percent_n_rx, "real % n gx" },
    { t_real_percents, "real %s" },
    { t_real_perflex, "real % flex" },
    { t_reals, "reals" },
    { t_reals_1_up, "reals 1 up" },
    { t_recipe_content, "recipe content" },
    { t_recipe_course, "recipe course" },
    { t_recipe_cuisine, "recipe cuisine" },
    { t_recipe_dietary, "recipe dietary" },
    { t_recipe_dish, "recipe dish" },
    { t_recipe_exclusion, "recipe exclusion" },
    { t_recipe_kit, "recipe kit" },
    { t_recipe_meal, "recipe meal" },
    { t_recipe_method, "recipe method" },
    { t_recipe_source, "recipe source" },
    { t_recipe_skill, "recipe skill" },
    { t_recipe_special, "recipe special" },
    { t_recipe_time, "recipe time" },
    { t_rect_round, "rect round" },
    { t_referrer, "referrer" },
    { t_refresh, "refresh" },
    { t_refx, "refx" },
    { t_refxs, "refxs" },
    { t_refy, "refy" },
    { t_refys, "refys" },
    { t_regex, "regex" },
    { t_rel, "rel" },
    { t_rel_avoid, "rel avoid" },
    { t_rel_css, "rel css" },
    { t_rel_illegal, "rel illegal" },
    { t_rel_obsolete, "rel obsolete" },
    { t_rendering_colour_space, "rendering colour space" },
    { t_rendering_in_tents, "rendering in tents" },
    { t_repeatcount, "repeat count" },
    { t_report, "report" },
    { t_required_page, "required page" },
    { t_restart, "restart" },
    { t_resolution, "resolution" },
    { t_result, "result" },
    { t_reveal_trans, "reveal trans" },
    { t_rfc822, "rfc822" },
    { t_rfc822_zone, "rfc822 zone" },
    { t_rgbafn, "rgba fn" },
    { t_rgbfn, "rgb fn" },
    { t_role, "role" },
    { t_robotic, "robotic" },
    { t_roles, "roles" },
    { t_roman_dsc, "roman dsc" },
    { t_root_url, "root url" },
    { t_rotate, "rotate" },
    { t_rotate_anim, "rotate anim" },
    { t_rotate_upright, "rotate upright" },
    { t_round, "round" },
    { t_row_column, "row column" },
    { t_rowscols, "rows cols" },
    { t_rsl_copyright, "rsl copyright" },
    { t_rsl_disclaimer, "rsl disclaimer" },
    { t_rsl_legal, "rsl legal" },
    { t_rsl_payment, "rsl payment" },
    { t_rsl_permits, "rsl permits" },
    { t_rsl_type, "rsl type" },
    { t_rsl_usage, "rsl usage" },
    { t_rsl_usages, "rsl usages" },
    { t_rsl_user, "rsl user" },
    { t_rsl_users, "rsl users" },
    { t_rsl_warranty, "rsl warranty" },
    { t_rss_protocol, "rss protocol" },
    { t_rss_version, "rss version" },
    { t_rsvp, "rsvp" },
    { t_rule_over, "rule over" },
    { t_rules, "rules" },
    { t_safe_unsafe, "safe unsafe" },
    { t_sandbox, "sandbox" },
    { t_sandboxen, "sandboxen" },
    { t_scale_down, "scale down" },
    { t_scan, "scan" },
    { t_scei, "scei" },
    { t_ontology, "schema type" },
    { t_scope, "scope" },
    { t_script, "script" },
    { t_scrolling, "scrolling" },
    { t_second, "second" },
    { t_semitone, "semitone" },
    { t_security, "security" },
    { t_setback_offset, "setback offset" },
    { t_settype, "settype" },
    { t_severity, "severity" },
    { t_sex, "sex" },
    { t_sgml, "sgml" },
    { t_sha1, "sha1" },
    { t_sha256, "sha256" },
    { t_shadow, "shadow" },
    { t_shadowinherit, "shadow inherit" },
    { t_shape, "shape" },
    { t_shape_1, "shape 1" },
    { t_shape_12, "shape 12" },
    { t_shape_2, "shape 2" },
    { t_shape3, "shape 3" },
    { t_shape4, "shape 4" },
    { t_shape7, "shape 7" },
    { t_shape_cmd, "shape cmd" },
    { t_shape_fn, "shape fn" },
    { t_shape_fn_circle, "shape fn circle" },
    { t_shape_fn_ellipse, "shape fn ellipse" },
    { t_shape_fn_polygon, "shape fn polygon" },
    { t_shape_none_uri, "shape none uri" },
    { t_shape_rcp, "shape rcp" },
    { t_shape_rendering, "shape rendering" },
    { t_shape_uri, "shape uri" },
    { t_short, "short" },
    { t_side, "side" },
    { t_simple_neg, "simple neg" },
    { t_size, "size" },
    { t_size3, "size 3" },
    { t_size_inlinesize, "size inline-size" },
    { t_sizes, "sizes" },
    { t_sizex, "size x" },
    { t_slash, "slash" },
    { t_smei, "smei" },
    { t_snap, "snap" },
    { t_source_target, "source target" },
    { t_spacer, "spacer" },
    { t_spacing, "spacing" },
    { t_speculationrules, "speculationrules" },
    { t_spreadmethod, "spread method" },
    { t_srcset, "src set" },
    { t_ssi, "ssi" },
    { t_ssi_comparison, "ssi comparison" },
    { t_ssi_config, "ssi config" },
    { t_ssi_echo, "ssi echo" },
    { t_ssi_encoding, "ssi encoding" },
    { t_ssi_env, "ssi env" },
    { t_ssi_exec, "ssi exec" },
    { t_ssi_f, "ssi f" },
    { t_ssi_include, "ssi include" },
    { t_ssi_set, "ssi set" },
    { t_ssi_sizefmt, "ssi sizefmt" },
    { t_start, "start" },
    { t_startend, "startend" },
    { t_startends, "startends" },
    { t_step, "step" },
    { t_step_position, "step position" },
    { t_stitchtiles, "stitch tiles" },
    { t_stripe, "stripe" },
    { t_streamedcontents, "streamed contents" },
    { t_stress, "stress" },
    { t_stretch, "stretch" },
    { t_supports, "supports" },
    { t_style, "style" },
    { t_svg_align, "SVG align" },
    { t_svg_baselineshift, "SVG baseline shift" },
    { t_svg_baseprofile, "SVG base profile" },
    { t_svg_clip, "SVG clip" },
    { t_svg_colour_profile, "SVG colour profile" },
    { t_svg_content, "SVG content" },
    { t_svg_direction, "SVG direction" },
    { t_svg_display, "SVG display" },
    { t_svg_duration, "SVG duration" },
    { t_svg_feature, "SVG feature" },
    { t_svg_features, "SVG features" },
    { t_svg_fontstretch, "SVG font stretch" },
    { t_svg_fontstretch_ff, "SVG font stretch ff" },
    { t_svg_fontstyle, "SVG font style" },
    { t_svg_fontstyle_ff, "SVG font style ff" },
    { t_svg_fontvariant, "SVG font variant" },
    { t_svg_fontvariant_ff, "SVG font variant ff" },
    { t_svg_fontweight, "SVG font weight" },
    { t_svg_fontweight_ff, "SVG font weight ff" },
    { t_svg_fontweights, "SVG font weights" },
    { t_svg_host, "SVG host" },
    { t_svg_method, "SVG method" },
    { t_svg_mode, "SVG mode" },
    { t_svg_name_iri, "SVG name iri" },
    { t_svg_overflow, "SVG overflow" },
    { t_svg_phase, "SVG phase" },
    { t_svg_playbackorder, "SVG playback order" },
    { t_svg_profile_name, "SVG profile name" },
    { t_svg_rendering_intent, "SVG rendering intent" },
    { t_svg_shape, "SVG shape" },
    { t_svg_shapefn, "SVG shape fn" },
    { t_svg_side, "SVG side" },
    { t_svg_src, "SVG src" },
    { t_svg_svg, "SVG svg" },
    { t_svg_time, "SVG time" },
    { t_svg_time_default, "SVG time default" },
    { t_svg_time_inherit, "SVG time inherit" },
    { t_svg_time_none, "SVG time none" },
    { t_svg_timelinebegin, "SVG timeline begin" },
    { t_svg_transform, "SVG transform" },
    { t_svg_two_profile, "SVG 2 profile" },
    { t_svg_type, "SVG type" },
    { t_svg_units, "SVG units" },
    { t_svg_values, "SVG values" },
    { t_svg_version, "SVG version" },
    { t_svg_version_grand, "SVG version grand" },
    { t_svg_viewbox, "SVG view box" },
    { t_svg_viewboxrect, "SVG view box rect" },
    { t_sym, "sym" },
    { t_syncbehaviour, "sync behaviour" },
    { t_syncbehaviourdefault, "sync behaviour default" },
    { t_tableframe, "table frame" },
    { t_tablevalues, "table values" },
    { t_target, "target" },
    { t_tbalign, "tb align" },
    { t_tblri, "tbl ri" },
    { t_tcbalign, "tcbalign" },
    { t_tdscope, "td scope" },
    { t_tel, "tel" },
    { t_tendstotype, "tends to type" },
    { t_text, "text" },
    { t_text_2, "text 2" },
    { t_text_2n, "text 2n" },
    { t_text_a, "text a" },
    { t_text_decoration, "text decoration" },
    { t_text_na, "text na" },
    { t_text_rendering, "text rendering" },
    { t_textoverflow, "text overflow" },
    { t_texts, "texts" },
    { t_texts_n, "texts n" },
    { t_tfa, "tfa" },
    { t_tfi, "tfi" },
    { t_tfmu, "tfmu" },
    { t_tfn, "tfn" },
    { t_tfu, "tfu" },
    { t_tld, "tld" },
    { t_tokens, "tokens" },
    { t_to_lrtb, "to lrtb" },
    { t_transform, "transform" },
    { t_transform_anim, "transform anim" },
    { t_transform_fn, "transform fn" },
    { t_transformbehaviour, "transform behaviour" },
    { t_transition_subtype, "transition subtype" },
    { t_transition_type, "transition type" },
    { t_transp, "trans p" },
    { t_transparentsz, "transparent sz" },
    { t_truefalseempty, "true false empty" },
    { t_turbulence_type, "turbulence type" },
    { t_type, "type" },
    { t_type_fn, "type fn" },
    { t_typeof, "type of" },
    { t_tz, "tz" },
    { t_ugeo, "u geo" },
    { t_under_ff, "under ff" },
    { t_uid, "uid" },
    { t_un_ex, "un ex" },
    { t_unicode_bidi, "unicode bidi" },
    { t_unit, "unit" },
    { t_unit_any, "unit any" },
    { t_unit_abs_len, "unit_abs_len" },
    { t_unit_abs_per, "unit_abs_per" },
    { t_unit_angle, "unit_angle" },
    { t_unit_angle_per, "unit_angle_per" },
    { t_unit_freq, "unit_freq" },
    { t_unit_freq_per, "unit_freq_per" },
    { t_unit_rel_len, "unit_rel_len" },
    { t_unit_rel_per, "unit_rel_per" },
    { t_unit_res, "unit_res" },
    { t_unit_res_per, "unit_res_per" },
    { t_unit_time, "unit_time" },
    { t_unit_time_per, "unit_time_per" },
    { t_units, "units" },
    { t_unknown, "unknown" },
    { t_unsigned, "unsigned" },
    { t_unsigned_1_more, "unsigned 1 more" },
    { t_unsigned_1_more_a, "unsigned 1 more a" },
    { t_unsigned_1_or_2, "unsigned 1 or 2" },
    { t_unsigned_byte, "unsigned byte" },
    { t_unsigned_dosh, "unsigned dosh" },
    { t_unsigned_n, "unsigned n" },
    { t_unsigned_short, "unsigned short" },
    { t_unsigneds, "unsigneds" },
    { t_uplr, "uplr" },
    { t_urange, "u range" },
    { t_urational, "urational" },
    { t_urationals, "urationals" },
    { t_urifn, "uri fn" },
    { t_urifn_db, "uri fn db" },
    { t_urifn_ni, "uri fn ni" },
    { t_urifn_str, "uri str" },
    { t_urifn_xy, "uri fn xy" },
    { t_url, "url" },
    { t_url_9309, "url 9309" },
    { t_url_9309s, "url 9309s" },
    { t_url_n, "url n" },
    { t_urls, "urls" },
    { t_urltemplate, "url template" },
    { t_url_temp_exp, "url_temp_exp" },
    { t_user_modify, "user modify" },
    { t_user_scalable, "user scalable" },
    { t_valign, "v align" },
    { t_valign3, "v align 3" },
    { t_valign_tmb, "v align tmb" },
    { t_value, "value" },
    { t_values, "values" },
    { t_valuetype, "value type" },
    { t_valuetype2, "value type 2" },
    { t_vtt_token, "vtt token" },
    { t_vector_effect, "vector effect" },
    { t_vector_effect_12, "vector effect 12" },
    { t_vector_effect_2, "vector effect 2" },
    { t_vector_effect_20, "vector effect 20" },
    { t_vector_effect_2s, "vector effect 2s" },
    { t_version, "version" },
    { t_vertical_align, "vertical align" },
    { t_vertical_align_enum, "vertical align enum" },
    { t_vgender, "v gender" },
    { t_vid, "v id" },
    { t_viewport, "viewport" },
    { t_viewport_comma, "viewport comma" },
    { t_viewport_height, "viewport height" },
    { t_viewport_initial_scale, "viewport initial scale" },
    { t_viewport_interactive_widget, "viewport interactive widget" },
    { t_viewport_maximum_scale, "viewport maximum scale" },
    { t_viewport_minimum_scale, "viewport minimum scale" },
    { t_viewport_scale, "viewport scale" },
    { t_viewport_semi, "viewport semi" },
    { t_viewport_setting, "viewport setting" },
    { t_viewport_target_densitydpi, "viewport target density dpi" },
    { t_viewport_user_scalable, "viewport user scalable" },
    { t_viewport_width, "viewport width" },
    { t_viewportscreen, "viewport screen" },
    { t_visibility, "visibility" },
    { t_visibility10, "visibility 10" },
    { t_visibility11, "visibility 11" },
    { t_vkind, "v kind" },
    { t_vline, "vline" },
    { t_vocab, "vocab" },
    { t_vrel, "v rel" },
    { t_vctelecomms, "vctelecomms" },
    { t_vtype, "v type" },
    { t_vunit, "v unit" },
    { t_vunits, "v units" },
    { t_wallclock, "wall clock" },
    { t_wacky, "wacky" },
    { t_wanted, "wanted" },
    { t_week, "week" },
    { t_weekday_english_long, "weekday english long" },
    { t_weekday_english_short, "weekday english short" },
    { t_whitespace, "whitespace" },
    { t_width, "width" },
    { t_wildcard, "wildcard" },
    { t_workertype, "worker type" },
    { t_wrap, "wrap" },
    { t_wrap3, "wrap 3" },
    { t_writingmode, "writing mode" },
    { t_wxhs, "wxhs" },
    { t_wximgalign, "wximgalign" },
    { t_x_content_type_options, "x content type options" },
    { t_x_dot_y, "x.y" },
    { t_x_ua_compatible, "x ua compatible" },
    { t_xlinkactuate, "x link actuate" },
    { t_xlinkactuate_onload, "x link actuate on load" },
    { t_xlinkactuate_onrequest, "x link actuate on request" },
    { t_xlinkshow, "x link show" },
    { t_xlinkshow_a, "x link show a" },
    { t_xlinkshow_e, "x link show e" },
    { t_xlinkshow_o, "x link show o" },
    { t_xlinktype, "x link type" },
    { t_xmllink, "xml link" },
    { t_xmlliteral, "xml literal" },
    { t_xmlns, "xmlns" },
    { t_xmlspace, "xml space" },
    { t_xmlurl, "xml url" },
    { t_xmpdm_audio_channel, "xmpdm audionchannel" },
    { t_xmpdm_audio_sample, "xmpdm audio sample" },
    { t_xmpdm_camera_angle, "xmpdm camera angle" },
    { t_xmpdm_camera_move, "xmpdm camera move" },
    { t_xmpdm_pulldown, "xmpdm pulldown" },
    { t_xmpdm_quality, "xmpdm quality" },
    { t_xmpdm_scaletype, "xmpdm scaletype" },
    { t_xmpdm_shotsize, "xmpdm shotsize" },
    { t_xmpdm_stretchmode, "xmpdm stretchmode" },
    { t_xmpdm_time_format, "xmpdm time format" },
    { t_xmpdm_time_signature, "xmpdm time signature" },
    { t_xmpdm_type, "xmpdm type" },
    { t_xmpdm_video_alphamode, "xmpdm video alphamode" },
    { t_xmpdm_video_colourspace, "xmpdm video colourspace" },
    { t_xmpdm_video_fieldorder, "xmpdm ideo fieldorder" },
    { t_xmpdm_video_videoframerate, "xmpdm video videoframerate" },
    { t_xmpdm_video_pixeldepth, "xmpdm video pixeldepth" },
    { t_xmpg_type, "xmpg type" },
    { t_xorder, " xorder" },
    { t_xsdbool, "xsd bool" },
    { t_xywh, "xywh" },
    { t_year, "year" },
    { t_yearmonth, "year month" },
    { t_yesno, "yes no" },
    { t_yesnoempty, "yes no empty" },
    { t_zero_or_one, "zero or one" },
    { t_zero_to_one, "zero to one" },
    { t_zero_to_ones, "zero to ones" },
    { t_zoompan, "zoom pan" },

    { t_error, "error" } };

vstr_t vtn;
msid_t mty;

void type_name_init (nitpick& nits)
{   vtn.resize (t_error);
    for (int i = 0; GSL_AT (enum_name, i).t_ != t_error; ++i)
    {   vtn.at (GSL_AT (enum_name, i).t_) = GSL_AT (enum_name, i).name_;
        mty.insert (msid_t::value_type (GSL_AT (enum_name, i).name_, GSL_AT (enum_name, i).t_)); }
    for (int i = 1; i < t_error; ++i)
        if (vtn.at (i).empty ())
            nits.pick (nit_type_error, es_error, ec_program, "Missing type name at ", ::boost::lexical_cast < ::std::string > (i), " (after ", vtn.at (i-1), ")"); }

::std::string type_name (const e_type e)
{   PRESUME (e <= t_error, __FILE__, __LINE__);
    if (! vtn.at (e).empty ()) return vtn.at (e);
    ::std::string res ("Empty type name at ");
    res += ::boost::lexical_cast <::std::string > (static_cast < int > (e));
    return res; }

e_type type_jag (const ::std::string& s)
{   msid_t::const_iterator i = mty.find (s);
    if (i == mty.cend ()) return t_unknown;
    return static_cast < e_type > (i -> second); }

::std::string get_type_site_path (const element* const box)
{   if (box == nullptr) return ::std::string ();
    if (box -> get_page ().get_directory () == nullptr) return ::std::string ();
    return box -> get_page ().get_directory () -> get_site_path (); }
