[general]
verbose=5
output=../out/print.out
class=

[css]
verify=
extension=css
version=2.1
image=3
print=

[html]
analysis=dec25
version=2026/04/01

[link]
no-check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/print

[spell]
no-check=
