[general]
verbose=5
output=../out/css3egg.out
class=

[css]
verify=
extension=css
version=2026+++
egg=3

[html]
analysis=dec25
version=2026/04/01

[link]
no-check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/3-egg

[spell]
no-spell=
