/*
ssc (static site checker)
Copyright (c) 2020-2025 Dylan Harris
https://dylanharris.org/

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence,  or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public Licence for more details.

You should have received a copy of the GNU General Public
Licence along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
*/

#include "main/standard.h"

#ifdef WX
#include "gui/gui-app.h"
#include "gui/gui-html.h"
#include "utility/filesystem.h"

// edit this, edit enable () in the html panel
html_version selection_version [] = 
{	html_tags,
    html_1,
    html_plus,
    html_2,
    html_2_level_1,
    html_2_level_2,
    html_3_0,
    html_3_2,
    html_4_0,
    html_4_1,
    xhtml_1_0,
    xhtml_1_1,
    xhtml_2,
    html_5_0,
    html_5_1,
    html_5_2,
    html_5_3,
    html_jan05,
    html_jul05,
    html_jan06,
    html_jan07,
    html_jul07,
    html_jan08,
    html_jul08,
    html_jan09,
    html_jul09,
    html_jan10,
    html_jul10,
    html_jan11,
    html_jul11,
    html_jan12,
    html_jul12,
    html_jan13,
    html_may13,
    html_jul13,
    html_jan14,
    html_jan15,
    html_jun15,
    html_jan16,
    html_jul16,
    html_jan17,
    html_jul17,
    html_jan18,
    html_jul18,
    html_oct18,
    html_jan19,
    html_jul19,
    html_jan20,
    html_jul20,
    html_jan21,
    html_feb21,
    html_apr21,
    html_jul21,
    html_oct21,
    html_nov21,
    html_jan22,
    html_apr22,
    html_jul22,
    html_oct22,
    html_jan23,
    html_apr23,
    html_jul23,
    html_oct23,
    html_jan24,
    html_apr24,
    html_jul24,
    html_oct24,
    html_jan25,
    html_apr25 };

// https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes#3191729
const char* selection_lang [] = {
    "aa", "aa-DJ", "aa-ER", "aa-ET",
    "af", "af-ZA",
    "am", "am-ET",
    "an", "an-ES",
    "ar", "ar-AE", "ar-BH", "ar-DZ", "ar-EG", "ar-IN", "ar-IQ", "ar-JO", "ar-KW", "ar-LB", "ar-LY", "ar-MA", "ar-OM", "ar-QA", "ar-SA",
          "ar-SD", "ar-SY", "ar-TN", "ar-YE",
    "as", "as-IN",
    "ast", "ast-ES",
    "az", "az-AZ",
    "be", "be-BY",
    "bem", "bem-ZM",
    "ber", "ber-DZ", "ber-MA",
    "bg", "bg-BG",
    "bho", "bho-IN",
    "bn", "bn-BD", "bn-IN",
    "bo", "bo-CN", "bo-IN",
    "br", "br-FR",
    "brx", "brx-IN",
    "bs", "bs-BA",
    "byn", "byn-ER",
    "ca", "ca-AD", "ca-ES", "ca-FR", "ca-IT",
    "crh", "crh-UA",
    "cs", "cs-CZ",
    "csb", "csb-PL",
    "cv", "cv-RU",
    "cy", "cy-GB",
    "da", "da-DK",
    "de", "de-AT", "de-BE", "de-CH", "de-DE", "de-LU",
    "dv", "dv-MV",
    "dz", "dz-BT",
    "el", "el-CY", "el-GR",
    "en", "en-AG", "en-AU", "en-BW", "en-CA", "en-DK", "en-GB", "en-HK", "en-IE", "en-IN", "en-NG", "en-NZ", "en-PH", "en-SG", "en-US",
          "en-ZA", "en-ZM", "en-ZW",
    "es", "es-AR", "es-BO", "es-CL", "es-CO", "es-CR", "es-CU", "es-DO", "es-EC", "es-ES", "es-GT", "es-HN", "es-MX", "es-NI", "es-PA",
          "es-PE", "es-PR", "es-PY", "es-SV", "es-US", "es-UY", "es-VE",
    "et", "et-EE",
    "eu", "eu-ES",
    "fa", "fa-IR",
    "ff", "ff-SN",
    "fi", "fi-FI",
    "fil", "fil-PH",
    "fo", "fo-FO",
    "fr", "fr-BE", "fr-CA", "fr-CH", "fr-FR", "fr-LU",
    "fur", "fur-IT",
    "fy", "fy-DE", "fy-NL",
    "ga", "ga-IE",
    "gd", "gd-GB",
    "gez", "gez-ER", "gez-ET",
    "gl", "gl-ES",
    "gu", "gu-IN",
    "gv", "gv-GB",
    "ha", "ha-NG",
    "he", "he-IL",
    "hi", "hi-IN",
    "hne", "hne-IN",
    "hr", "hr-HR",
    "hsb", "hsb-DE",
    "ht", "ht-HT",
    "hu", "hu-HU",
    "hy", "hy-AM",
    "id", "id-ID",
    "ig", "ig-NG",
    "ik", "ik-CA",
    "is", "is-IS",
    "it", "it-CH", "it-IT",
    "iu", "iu-CA",
    "iw", "iw-IL",
    "ja", "ja-JP",
    "ka", "ka-GE",
    "kk", "kk-KZ",
    "kl", "kl-GL",
    "km", "km-KH",
    "kn", "kn-IN",
    "ko", "ko-KR",
    "kok", "kok-IN",
    "ks", "ks-IN",
    "ku", "ku-TR",
    "kw", "kw-GB",
    "ky", "ky-KG",
    "lb", "lb-LU",
    "lg", "lg-UG",
    "li", "li-BE", "li-NL",
    "lij", "lij-IT",
    "lo", "lo-LA",
    "lt", "lt-LT",
    "lv", "lv-LV",
    "mag", "mag-IN",
    "mai", "mai-IN",
    "mg", "mg-MG",
    "mhr", "mhr-RU",
    "mi", "mi-NZ",
    "mk", "mk-MK",
    "ml", "ml-IN",
    "mn", "mn-MN",
    "mr", "mr-IN",
    "ms", "ms-MY",
    "mt", "mt-MT",
    "my", "my-MM",
    "nan", "nan-TW",
    "nb", "nb-NO",
    "nds", "nds-DE", "nds-NL",
    "ne", "ne-NP",
    "nl", "nl-AW", "nl-BE", "nl-NL",
    "nn", "nn-NO",
    "nr", "nr-ZA",
    "nso", "nso-ZA",
    "oc", "oc-FR",
    "om", "om-ET", "om-KE",
    "or", "or-IN",
    "os", "os-RU",
    "pa", "pa-IN", "pa-PK",
    "pap", "pap-AN",
    "pl", "pl-PL",
    "ps", "ps-AF",
    "pt", "pt-BR", "pt-PT",
    "ro", "ro-RO",
    "ru", "ru-RU", "ru-UA",
    "rw", "rw-RW",
    "sa", "sa-IN",
    "sc", "sc-IT",
    "sd", "sd-IN",
    "se", "se-NO",
    "shs", "shs-CA",
    "si", "si-LK",
    "sid", "sid-ET",
    "sk", "sk-SK",
    "sl", "sl-SI",
    "so", "so-DJ", "so-ET", "so-KE", "so-SO",
    "sq", "sq-AL", "sq-MK",
    "sr", "sr-ME", "sr-RS",
    "ss", "ss-ZA",
    "st", "st-ZA",
    "sv", "sv-FI", "sv-SE",
    "sw", "sw-KE", "sw-TZ",
    "ta", "ta-IN", "ta-LK",
    "te", "te-IN",
    "tg", "tg-TJ",
    "th", "th-TH",
    "ti", "ti-ER", "ti-ET",
    "tig", "tig-ER",
    "tk", "tk-TM",
    "tl", "tl-PH",
    "tn", "tn-ZA",
    "tr", "tr-CY", "tr-TR",
    "ts", "ts-ZA",
    "tt", "tt-RU",
    "ug", "ug-CN",
    "uk", "uk-UA",
    "unm", "unm-US",
    "ur", "ur-IN", "ur-PK",
    "uz", "uz-UZ",
    "ve", "ve-ZA",
    "vi", "vi-VN",
    "wa", "wa-BE",
    "wae", "wae-CH",
    "wal", "wal-ET",
    "wo", "wo-SN",
    "xh", "xh-ZA",
    "yi", "yi-US",
    "yo", "yo-NG",
    "yue", "yue-HK",
    "zh", "zh-CN", "zh-HK", "zh-SG", "zh-TW",
    "zu", "zu-ZA",
    nullptr };

::std::size_t selection_count = 0;

void gui_init ()
{   selection_count = sizeof (selection_version) / sizeof (html_version); }

#endif // WX
