[general]
verbose=info
output=../out/lkb.out
class=

[css]
verify=
extension=css
version=2025+++
no-external=

[html]
version=2025/10/01

[link]
check=

[nits]
nids=

[site]
domain=example.org
extension=html
index=index.html
root=../toast/external/1kb.lejtzen.dev

[spell]
no-check=true
