[general]
verbose=5
output=../out/oct25.out
class=true
url-var=src:/index.html

[css]
verify=
extension=css
version=html5

[html]
analysis=aug25
version=2025/10/01
custom=flag-icon
custom=my-checkbox
custom=img-viewer
custom=example-element
custom=labeled-checkbox
custom=question-box
custom=x-foo

[nits]
nids=

[link]
check=

[ontology]
schema=29.3

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/living/oct25

[spell]
no-check=

[validation]
element=labeled-checkbox
element=question-box
