[general]
verbose=5
output=../out/aria-graph.out
class=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/aria/graphics

[html]
version=2018/10/01

[svg]
version=1.1
