[general]
output=../toast/tmp/sign-pw.out
copy=../out/sign-pw.out
class=

[css]
verify=
extension=css
version=3
no-external=

[html]
version=2025/02/01

[link]
check=

[nits]
verbose=info
nids=

[output]
private=../toast/signing/sign-pw/privatekey-pw.pem
public=../toast/signing/sign-pw/publickey-pw.pem
sign=
signature=../toast/signing/sign-pw/test-pw.sig

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/signing/sign-pw

[spell]
no-check=true
