[atom]
extension=xml

[general]
verbose=5
output=../out/extatom.out

[html]
version=2025/10/01

[nits]
nids=

[link]
no-check=

[site]
domain=example.org
extension=html
extension=xml
index=ex1.xml
root=../toast/external/atom
