<li>Our details
<ol><li>This website is owned and operated by <a href="<!--#echo encoding="none" var="artsego" -->"><!--#echo encoding="none" var="editor" --></a>;</li>
<li><!--#echo encoding="none" var="editor" --> lives and works in the <!--#echo encoding="none" var="hostland" -->;</li>
<li>You can email <!--#echo encoding="none" var="sname" --> at <A href="mailto:<!--#echo encoding="none" var="email" -->"><!--#echo encoding="none" var="email" --></a>.</li>
</ol></li>
