[general]
verbose=info
output=../out/mrss.out
class=

[html]
version=2025/10/01

[link]
check=

[nits]
nids=

[site]
domain=example.edu
extension=html
extension=rss
index=1.rss
root=../toast/RSS/media

[spell]
no-check=true
