[general]
verbose=info
output=../out/mdnfunction.out
class=

[css]
verify=
extension=css
version=6

[html]
mozilla=
no-aria=
version=2026/07/01

[jsonld]
extension=jld
verify=
version=1.0

[link]
no-check=

[nits]
nids=
comment=slash_gt

[ontology]
schema=30.0

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/mdn/function

[spell]
no-check=
