[general]
verbose=info
output=../out/mdncombinator.out
class=

[css]
verify=
extension=css
version=6

[html]
analysis=dec25
mozilla=
no-aria=
version=2026/04/01

[jsonld]
extension=jld
verify=
version=1.0

[link]
no-check=

[nits]
nids=
comment=slash_gt

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/mdn/combinator

[spell]
no-check=
