[general]
verbose=5
output=../out/ssi.out
class=

[css]
verify=
extension=css
version=2.1

[ssi]
verify=
timefmt=%Y-%m-%dT%T

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/other/ssi
