[general]
verbose=info
output=../out/mdnplace.out
class=

[css]
verify=
extension=css
version=6

[html]
analysis=dec25
mozilla=
no-aria=
version=2026/01/01

[link]
no-check=

[nits]
nids=
comment=slash_gt

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/mdn/place

[spell]
no-check=
