[general]
output=../toast/tmp/sign-pw.out
copy=../out/sign-pw.out

[output]
public=../toast/signing/verify-pw/publickey-pw.pem
verify=
signature=../toast/signing/verify-pw/test-pw.sig

[nits]
verbose=info
nids=
