[general]
verbose=info
output=../out/inefficient.out
class=

[css]
no-verify=

[html]
no-aria=
no-efficient=
version=2025/08/01

[link]
no-check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/other/efficient

[spell]
no-check=true
