[general]
verbose=5
output=../out/css3shape.out
class=

[css]
verify=
extension=css
version=3
value=4
transform=4

[html]
version=2026/07/01

[nits]
nids=
comment=slash_gt

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/3-shape
