[general]
verbose=5
output=../out/css3shape.out
class=

[css]
verify=
extension=css
version=2.1
animation=3
background=3
custom=3
masking=3
selector=5
shape=3
transform=4

[html]
version=2023/07/01

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/3-shape
