[general]
verbose=5
output=../out/w3cag2.out
class=

[css]
verify=
extension=css
version=2.1

[html]
version=5.0

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/w3/cag-2

[spell]
no-check=
