[general]
verbose=info
output=../out/lists.out
class=

[html]
version=2025/08/01

[microformat]
verify=

[nits]
nids=

[site]
domain=example.edu
extension=html
extension=xhtml
index=index.html
root=../toast/other/lists

[shadow]
copy=all
root=../toast/tmp/lists
nice=element,h1,sausages
note=element,h1,hello
naughty=attribute,h1,id,fred
note=attribute,h1,id,fiddlesticks
naughty=ontology,schema,Question,name,Ruby
note=ontology,schema,Question,name,Doris
naughty=microformat,h-card,dt-bday,1911-11-11
note=microformat,h-card,dt-bday,1901-04-01

[spell]
no-check=true
