[general]
verbose=info
output=../out/robotic.out
class=
robots=

[html]
version=2025/09/01

[link]
check=

[nits]
nids=

[site]
domain=ssc.lu
extension=html
index=index.html
root=../toast/other/robotic
