-N 1 -f ../toast/RDFa/lrdw/rdfa.conf

PASS ../toast/RDFa/lrdw/lrdw.html
6 css_version
7 reputation
8 reputation
9 reputation
12 rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_confusion rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_confusion rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine
20 not_ontology_property bad_property not_ontology_property bad_property bad_property
102 ontology_domain
156 not_ontology_property bad_property ontology_domain not_ontology_property bad_property
255 ontology_domain
318 ontology_domain
320 not_ontology_property bad_property
454 empty_link
587 not_ontology_property bad_property
826 not_ontology_property bad_property
840 not_ontology_property bad_property not_ontology_property bad_property
858 contradictory_expansion
942 not_ontology_property bad_property
1003 not_ontology_property bad_property
1118 not_ontology_property bad_property
1201 ontology_domain
1202 ontology_domain
1206 ontology_domain
1382 not_ontology_property bad_property
1386 not_ontology_property bad_property
1436 not_ontology_property bad_property
1451 not_ontology_property bad_property
1553 not_ontology_property bad_property
1601 not_ontology_property bad_property
1848 invalid_ipv4 rel_requires_href chocolate_teapot
1851 invalid_ipv4
1924 no_such_folder url_not_found
2017 not_ontology_property bad_property not_ontology_property bad_property
2200 contradictory_expansion
2314 no_such_folder url_not_found
3572 invalid_ipv4 rel_requires_href chocolate_teapot
3611 ontology_domain
3779 no_such_folder url_not_found
3803 no_such_folder url_not_found
4632 no_such_folder url_not_found
4680 ontology_domain not_ontology_property bad_property
4682 ontology_domain not_ontology_property bad_property
4684 ontology_domain not_ontology_property bad_property
4686 ontology_domain not_ontology_property bad_property
4688 ontology_domain not_ontology_property bad_property
4686 ontology_domain not_ontology_property bad_property
4695 ontology_domain not_ontology_property bad_property
4697 ontology_domain not_ontology_property bad_property
4717 ontology_domain not_ontology_property bad_property
4719 ontology_domain not_ontology_property bad_property
4721 ontology_domain not_ontology_property bad_property
4723 ontology_domain not_ontology_property bad_property
4725 ontology_domain not_ontology_property bad_property
4727 ontology_domain not_ontology_property bad_property
4729 ontology_domain not_ontology_property bad_property
4731 ontology_domain not_ontology_property bad_property
5132 rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine
5138 invalid_attribute_version wrong_version
5182 not_ontology_property bad_property
5363 contradictory_expansion
5373 not_ontology_property bad_property
5380 rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine rdfa_redefine invalid_attribute_version wrong_version svg_version
5396 immeasurable
5397 immeasurable
5870 invalid_ipv4 rel_requires_href chocolate_teapot
5985 not_ontology_property bad_property
6068 invalid_ipv4 rel_requires_href chocolate_teapot
6085 ontology_domain
6087 ontology_domain
6089 ontology_domain
6091 ontology_domain
6093 ontology_domain
6096 ontology_domain
6236 ontology_domain
