-f ../toast/living/jan21/living.conf

PASS ../toast/living/jan21/404.html
50 link_rel_off
64 unrecognised_value
71 unrecognised_value unrecognised_value
74 unrecognised_value
75 unrecognised_value unrecognised_value missing_close unrecognised_value
76 inserted_missing_closure
119 unrecognised_value unrecognised_value unrecognised_value
122 unrecognised_value unrecognised_value
123 unrecognised_value
127 link_rel_off
128 link_rel_off

PASS ../toast/living/jan21/a.html
9 url_not_found
10 chocolate_teapot
11 url_not_found
15 unrecognised_value
36 wrong_parent inserted_missing_closure
37 wrong_parent inserted_missing_closure
38 inserted_missing_closure wrong_parent inserted_missing_closure
39 no_such_folder url_not_found
40 wrong_parent inserted_missing_closure
41 wrong_parent inserted_missing_closure
42 inserted_missing_closure wrong_parent inserted_missing_closure
43 no_such_folder url_not_found
44 wrong_parent inserted_missing_closure
45 wrong_parent inserted_missing_closure
46 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
47 no_such_folder url_not_found
48 wrong_parent inserted_missing_closure
49 wrong_parent inserted_missing_closure missing_close
50 inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/abbr.html
17 id_exists
35 naughty_grave

PASS ../toast/living/jan21/address.html
0 charset_mismatch charset_used charset_invalid
11 attempted_escape no_such_folder url_not_found
12 attempted_escape no_such_folder url_not_found
13 url_not_found

PASS ../toast/living/jan21/aside.html
0 charset_mismatch charset_used charset_invalid
19 use_quote_code
22 use_quote_code
25 use_quote_code

PASS ../toast/living/jan21/aside-2.html
0 charset_mismatch charset_used charset_invalid
16 missing_close
17 inserted_missing_closure
22 url_not_found
23 inserted_missing_closure missing_close url_not_found
24 inserted_missing_closure
32 use_quote_code
35 use_quote_code
43 missing_close url_not_found
44 inserted_missing_closure
57 use_quote_code
60 missing_close url_not_found
61 inserted_missing_closure
65 url_not_found
66 url_not_found
67 url_not_found

PASS ../toast/living/jan21/b.html
0 charset_mismatch charset_used charset_invalid
12 use_quote_code

PASS ../toast/living/jan21/blockquote.html
0 charset_mismatch charset_used charset_invalid
7 missing_close
8 use_quote_code
12 inserted_missing_closure
21 use_quote_code
27 use_quote_code
30 use_quote_code
44 use_quote_code
50 use_double_quote_code
60 inserted_missing_closure
69 use_quote_code
71 use_double_quote_code
72 use_double_quote_code
87 inserted_missing_closure

PASS ../toast/living/jan21/canvas3.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 element_offsite_base
9 inserted_missing_parent inserted_missing_closure missing_close
160 inserted_missing_closure

PASS ../toast/living/jan21/caption.html
9 inserted_missing_closure missing_close
13 inserted_missing_closure

PASS ../toast/living/jan21/data.html
10 unrecognised_value
11 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
12 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/datalist.html
11 inserted_missing_closure missing_close
12 inserted_missing_closure
19 id_exists
24 inserted_missing_closure
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jan21/del.html
9 use_quote_code

PASS ../toast/living/jan21/details.html
0 charset_mismatch charset_used charset_invalid
6 unrecognised_value unrecognised_value
7 use_double_quote_code
25 inserted_missing_closure missing_close
26 inserted_missing_closure

PASS ../toast/living/jan21/dfn.html
9 use_quote_code
15 use_quote_code

PASS ../toast/living/jan21/div.html
10 use_quote_code
18 use_quote_code use_double_quote_code
20 use_double_quote_code

PASS ../toast/living/jan21/dl.html
0 charset_mismatch charset_used charset_invalid
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
59 use_quote_code
65 inserted_missing_closure
68 inserted_missing_closure missing_close
70 inserted_missing_closure
73 inserted_missing_closure
76 inserted_missing_closure missing_close
78 inserted_missing_closure
84 inserted_missing_closure
87 inserted_missing_closure
89 inserted_missing_closure
91 inserted_missing_closure
94 inserted_missing_closure missing_close
96 inserted_missing_closure

PASS ../toast/living/jan21/dt.html
0 charset_mismatch charset_used charset_invalid
8 unrecognised_value use_quote_code
9 unrecognised_value
13 unrecognised_value use_quote_code
14 unrecognised_value
15 unrecognised_value

PASS ../toast/living/jan21/el.html
9 use_quote_code
13 use_quote_code
27 missing_close
28 inserted_missing_closure

PASS ../toast/living/jan21/embed.html
6 reputation url_not_found
8 wild_attribute reputation wild_attribute url_not_found
10 reputation url_not_found

PASS ../toast/living/jan21/et.html
8 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
10 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure
17 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
18 no_such_folder url_not_found
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
20 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
21 no_such_folder url_not_found
22 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
23 no_such_folder url_not_found
24 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
25 no_such_folder url_not_found
26 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/example.html
6  missing_close
6  inserted_missing_closure
6  missing_open
10  url_not_found
28  url_not_found
29  inserted_missing_closure
29  url_not_found
30  inserted_missing_closure missing_close
30  url_not_found
31  inserted_missing_closure
33  url_not_found
44  url_not_found
53  inserted_missing_closure inserted_missing_closure
54  inserted_missing_closure inserted_missing_closure
55  inserted_missing_closure inserted_missing_closure
65  inserted_missing_closure inserted_missing_closure unrecognised_value
66  input_bad_aria
68  inserted_missing_closure
93  attribute_unrecognised unrecognised_attribute unrecognised_value
95  unrecognised_value
99  url_not_found
107  newline_in_string
107  newline_in_string url_not_found
111  data_type
111  attribute_required attribute_required
111  attribute_required
129  url_not_found
135  use_quote_code
138  url_not_found
139  url_not_found
140  url_not_found
142  use_quote_code
148  url_not_found
151  url_not_found
152  inserted_missing_closure missing_close
153  inserted_missing_closure
157  use_quote_code
162  url_not_found
165  url_not_found
166  inserted_missing_closure missing_close
167  inserted_missing_closure
170  use_quote_code
174  ignoring_unknown attribute_barred attribute_barred
177  ignoring_unknown
181  newline_in_string
181  newline_in_string
183  unrecognised_value
183  use_double_quote_code use_quote_code
184  unrecognised_value
185  inserted_missing_closure unrecognised_value
186  unrecognised_value
187  use_quote_code use_double_quote_code
187  inserted_missing_closure unrecognised_value
187  use_double_quote_code
188  unrecognised_value
188  use_double_quote_code
191  newline_in_string
191  newline_in_string
192  newline_in_string
192  newline_in_string
197  only_elements
210  unrecognised_value
212  unrecognised_value
219  unrecognised_value no_such_folder url_not_found

PASS ../toast/living/jan21/example-2.html
4 url_not_found style_not_css
5 url_not_found
6 url_not_found
10 url_not_found
14 sizes sizes
23 no_such_folder url_not_found
36 url_not_found
43 url_not_found
46 url_not_found
47 mime
61 use_quote_code
75 use_quote_code
79 unrecognised_schema unrecognised_schema
89 unrecognised_schema unrecognised_schema
120 unrecognised_value
135 use_quote_code
145 use_quote_code

PASS ../toast/living/jan21/fieldset.html
12 pattern
27 pattern
34 pattern
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure missing_close
47 inserted_missing_closure missing_close
48 inserted_missing_closure
49 inserted_missing_closure

PASS ../toast/living/jan21/figcaption.html
6 inserted_missing_parent missing_close too_many_figcaption
16 inserted_missing_closure

PASS ../toast/living/jan21/figure.html
21 newline_in_string newline_in_string url_not_found
25 use_quote_code
29 use_double_quote_code inserted_missing_closure
30 url_not_found
35 inserted_missing_closure
36 url_not_found
40 url_not_found
45 inserted_missing_closure
46 use_quote_code
55 url_not_found
57 url_not_found
60 newline_in_string newline_in_string url_not_found
67 url_not_found
69 url_not_found
71 url_not_found
78 url_not_found
85 use_quote_code

PASS ../toast/living/jan21/footer.html
2 naughty_lang
9 attempted_escape
18 attempted_escape

PASS ../toast/living/jan21/footer-2.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang
4 inserted_missing_closure
8 no_such_folder url_not_found
9 no_such_folder url_not_found
26 url_not_found
27 url_not_found

PASS ../toast/living/jan21/footer-3.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang
13 no_such_folder url_not_found naughty_alt
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 attribute_required no_such_folder url_not_found naughty_alt
19 no_such_folder url_not_found
21 attribute_required no_such_folder url_not_found naughty_alt
23 use_quote_code no_such_folder url_not_found
26 url_not_found
27 inserted_missing_closure url_not_found
28 inserted_missing_closure missing_close url_not_found
29 inserted_missing_closure
32 url_not_found

PASS ../toast/living/jan21/formex.html
15 url_not_found
20 no_such_folder url_not_found
31 url_not_found
36 url_not_found
60 url_not_found
71 inserted_missing_closure
72 inserted_missing_closure missing_close
74 inserted_missing_closure
78 inserted_missing_closure
79 inserted_missing_closure missing_close
81 inserted_missing_closure
83 url_not_found
88 inserted_missing_closure
89 inserted_missing_closure missing_close
90 inserted_missing_closure
97 inserted_missing_closure
98 inserted_missing_closure
99 inserted_missing_closure
100 inserted_missing_closure
101 inserted_missing_closure
102 inserted_missing_closure
103 inserted_missing_closure
105 inserted_missing_closure
106 inserted_missing_closure
107 inserted_missing_closure missing_close
108 inserted_missing_closure
117 bad_autocomplete
121 inserted_missing_closure
123 inserted_missing_closure
124 inserted_missing_closure missing_close
126 inserted_missing_closure
155 url_not_found
161 url_not_found

PASS ../toast/living/jan21/forms.html
119 inserted_missing_closure missing_close
120 inserted_missing_closure
144 inserted_missing_closure missing_close
145 inserted_missing_closure
169 inserted_missing_closure missing_close
170 inserted_missing_closure
195 inserted_missing_closure missing_close
196 inserted_missing_closure
306 unrecognised_value
308 missing_close
324 inserted_missing_closure
327 inserted_missing_closure use_quote_code
328 inserted_missing_closure
330 use_double_quote_code inserted_missing_closure
331 inserted_missing_closure use_quote_code
332 inserted_missing_closure
334 use_double_quote_code inserted_missing_closure
337 inserted_missing_closure
338 pattern

PASS ../toast/living/jan21/h-1.html
6 use_quote_code

PASS ../toast/living/jan21/h-2.html
6 use_quote_code

PASS ../toast/living/jan21/h-3.html
6 use_quote_code

PASS ../toast/living/jan21/header.html
0 charset_mismatch charset_used charset_invalid
2 naughty_lang

PASS ../toast/living/jan21/header-2.html
2 naughty_lang
14 url_not_found
15 inserted_missing_closure url_not_found
16 inserted_missing_closure missing_close url_not_found
17 inserted_missing_closure
21 use_quote_code

PASS ../toast/living/jan21/hgroup-2.html
18 newline_in_string
18 newline_in_string illegal_value
19 inserted_missing_closure
21 inserted_missing_closure
22 input_bad_mix
23 inserted_missing_closure missing_close
25 inserted_missing_closure
30 inserted_missing_closure
31 inserted_missing_closure missing_close
32 inserted_missing_closure

PASS ../toast/living/jan21/hr.html
17 use_quote_code
47 use_quote_code
49 use_quote_code
58 use_quote_code

PASS ../toast/living/jan21/hs-7.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
18 inserted_missing_closure
19 use_quote_code

PASS ../toast/living/jan21/hs-8.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
31 inserted_missing_closure
33 use_quote_code

PASS ../toast/living/jan21/hs-9.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close

PASS ../toast/living/jan21/hs-10.html
0 title_required
5 use_double_quote_code inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close

PASS ../toast/living/jan21/hs-11.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close long_title
3 inserted_missing_parent inserted_missing_closure missing_close
5 use_quote_code

PASS ../toast/living/jan21/hs-12.html
0 charset_mismatch charset_used charset_invalid
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close long_title use_quote_code
3 inserted_missing_parent inserted_missing_closure missing_close use_quote_code
11 use_quote_code
15 use_quote_code

PASS ../toast/living/jan21/hs-13.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
3 inserted_missing_parent inserted_missing_closure missing_close
16 use_quote_code

PASS ../toast/living/jan21/i.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan21/iframe.html
0 charset_mismatch charset_used charset_invalid
9 missing_close
14 use_quote_code
16 missing_close no_such_folder url_not_found
17 inserted_missing_closure
19 no_such_folder url_not_found
20 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
23 no_such_folder url_not_found
24 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1 mixed_mess missing_open
27 no_such_folder url_not_found
28 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
31 use_quote_code
32 url_not_found
35 overallowed
37 url_not_found
39 url_not_found
41 url_not_found
45 attribute_required no_such_folder url_not_found naughty_alt
46 no_such_folder url_not_found url_id_unfound
55 inserted_missing_closure

PASS ../toast/living/jan21/im.html
8 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found

PASS ../toast/living/jan21/img.html
6 url_not_found
7 url_not_found
8 url_not_found
10 url_not_found
11 url_not_found
13 url_not_found naughty_alt
15 url_not_found
18 url_not_found
22 url_not_found naughty_alt
29 newline_in_string url_not_found
33 use_quote_code
36 attribute_required url_not_found naughty_alt
42 url_not_found
43 use_quote_code
54 newline_in_string newline_in_string url_not_found
57 use_quote_code
63 use_quote_code
64 url_not_found
72 url_not_found naughty_alt
76 use_quote_code
77 no_such_folder url_not_found naughty_alt
78 no_such_folder url_not_found
79 no_such_folder url_not_found
81 inserted_missing_closure use_quote_code
84 no_such_folder url_not_found naughty_alt
85 no_such_folder url_not_found
86 no_such_folder url_not_found
88 inserted_missing_closure
89 url_not_found
93 url_not_found
98 url_not_found
104 url_not_found
108 use_quote_code
111 mime
112 no_such_folder url_not_found naughty_alt
114 no_such_folder url_not_found
115 no_such_folder url_not_found
117 inserted_missing_closure
120 url_not_found
132 url_not_found
144 url_not_found id_exists
152 url_not_found
159 url_not_found
166 url_not_found
172 url_not_found
177 url_not_found url_not_found
178 url_not_found url_not_found
179 url_not_found url_not_found
182 interactive url_not_found url_not_found naughty_alt url_not_found naughty_alt
183 interactive url_not_found url_not_found naughty_alt url_not_found naughty_alt url_not_found naughty_alt
185 interactive url_not_found url_not_found url_not_found
186 interactive url_not_found url_not_found attribute_required url_not_found naughty_alt url_not_found
188 interactive url_not_found url_not_found naughty_alt url_not_found naughty_alt
189 interactive url_not_found url_not_found naughty_alt url_not_found naughty_alt url_not_found naughty_alt
198 newline_in_string no_such_folder url_not_found
203 url_not_found
210 url_not_found
215 no_such_folder url_not_found no_such_folder url_not_found
216 no_such_folder url_not_found no_such_folder url_not_found
223 url_not_found
231 url_not_found
236 use_quote_code
239 url_not_found
244 url_not_found naughty_alt
247 url_not_found naughty_alt
255 newline_in_string no_such_folder url_not_found
261 use_quote_code
263 url_not_found
265 no_such_folder url_not_found
269 inserted_missing_closure url_not_found
271 inserted_missing_closure
276 no_such_folder url_not_found naughty_alt
285 no_such_folder url_not_found naughty_alt
300 newline_in_string newline_in_string no_such_folder url_not_found
311 no_such_folder url_not_found
318 url_not_found naughty_alt
320 url_not_found naughty_alt
322 use_quote_code
324 url_not_found
327 use_quote_code
329 url_not_found
332 use_quote_code
336 use_quote_code
339 url_not_found
344 url_not_found naughty_alt
349 use_quote_code
355 url_not_found url_not_found naughty_alt
358 url_not_found url_not_found naughty_alt url_not_found naughty_alt
359 url_not_found naughty_alt url_not_found naughty_alt
364 url_not_found
366 url_not_found naughty_alt url_not_found
378 newline_in_string newline_in_string url_not_found
385 newline_in_string newline_in_string url_not_found
393 newline_in_string newline_in_string no_such_folder url_not_found
401 newline_in_string newline_in_string no_such_folder url_not_found
410 newline_in_string newline_in_string url_not_found
412 unrecognised_value
417 newline_in_string no_such_folder url_not_found
418 inserted_missing_closure
419 missing_close
420 inserted_missing_closure
423 attribute_required url_not_found
431 attribute_required url_not_found
445 newline_in_string newline_in_string url_not_found
451 attribute_required url_not_found naughty_alt
458 wrong_parent inserted_missing_closure
459 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
461 attribute_required url_not_found naughty_alt
462 wrong_parent inserted_missing_closure
463 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
464 attribute_required url_not_found naughty_alt
465 wrong_parent inserted_missing_closure missing_close
466 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/index.html
3 attribute_unrecognised_here unrecognised_attribute

PASS ../toast/living/jan21/input.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure missing_close
14 inserted_missing_closure
23 inserted_missing_closure
24 inserted_missing_closure
25 inserted_missing_closure
26 inserted_missing_closure missing_close
27 inserted_missing_closure
34 inserted_missing_closure
35 inserted_missing_closure
36 inserted_missing_closure missing_close
37 inserted_missing_closure
44 inserted_missing_closure missing_close
45 inserted_missing_closure
49 inserted_missing_closure
50 inserted_missing_closure missing_close
51 inserted_missing_closure
79 url_not_found
80 url_not_found
86 inserted_missing_closure
88 inserted_missing_closure url_not_found
90 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
91 inserted_missing_closure wrong_parent inserted_missing_closure
93 wrong_parent inserted_missing_closure
94 wrong_parent inserted_missing_closure
95 wrong_parent inserted_missing_closure bad_form
96 inserted_missing_closure wrong_parent inserted_missing_closure
98 wrong_parent inserted_missing_closure
99 wrong_parent inserted_missing_closure
100 wrong_parent inserted_missing_closure bad_form
101 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
102 pattern
103 wrong_parent inserted_missing_closure
104 wrong_parent inserted_missing_closure
105 wrong_parent inserted_missing_closure missing_close bad_form
106 inserted_missing_closure inserted_missing_closure
107 bad_form
112 url_not_found
116 inserted_missing_closure
119 inserted_missing_closure
122 inserted_missing_closure missing_close
124 inserted_missing_closure
129 inserted_missing_closure
130 inserted_missing_closure use_quote_code
131 inserted_missing_closure
132 inserted_missing_closure missing_close use_quote_code
133 inserted_missing_closure
141 inserted_missing_closure
142 inserted_missing_closure
143 inserted_missing_closure missing_close
144 inserted_missing_closure
157 minmax minmax
176 inserted_missing_closure missing_close
177 inserted_missing_closure
185 inserted_missing_closure missing_close
187 inserted_missing_closure
196 id_exists
201 inserted_missing_closure
202 inserted_missing_closure missing_close
204 inserted_missing_closure
217 placeholder
218 placeholder
220 placeholder
221 placeholder
223 minmax

PASS ../toast/living/jan21/label.html
8 ignoring_unknown attribute_barred ignoring_unknown

PASS ../toast/living/jan21/li.html
7 inserted_missing_parent missing_close
10 lingo
11 use_quote_code
20 inserted_missing_closure
23 inserted_missing_parent missing_close
26 lingo
27 use_quote_code
36 inserted_missing_closure
40 inserted_missing_closure
41 inserted_missing_closure missing_close
42 inserted_missing_closure

PASS ../toast/living/jan21/links-alternate.html
7 url_not_found
9 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
15 url_not_found
16 url_not_found
17 url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 no_such_folder url_not_found
22 no_such_folder url_not_found
23 no_such_folder url_not_found
24 no_such_folder url_not_found
33 url_not_found
34 url_not_found
35 url_not_found

PASS ../toast/living/jan21/links-bookmark.html
12 use_quote_code
19 url_not_found

PASS ../toast/living/jan21/links-help.html
10 no_such_folder url_not_found

PASS ../toast/living/jan21/links-icon.html
5 url_not_found
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found

PASS ../toast/living/jan21/links-licence.html
0 charset_mismatch charset_used charset_invalid
5 no_such_folder url_not_found
10 attempted_escape
13 attribute_required no_such_folder url_not_found
20 attempted_escape

PASS ../toast/living/jan21/links-modulepreload.html
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found

PASS ../toast/living/jan21/links-noopener.html
10 url_not_found
12 url_not_found

PASS ../toast/living/jan21/links-noreferrer.html
10 missing_close url_not_found missing_close wrong_parent url_not_found interactive
11 wrong_parent interactive
13 inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/links-tag2.html
19 unrecognised_value

PASS ../toast/living/jan21/ls1.html
8 url_not_found

PASS ../toast/living/jan21/ls4.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan21/ls5.html
0 charset_mismatch charset_used charset_invalid

PASS ../toast/living/jan21/ls6.html
3 xmlns_namespace no_xmllang
5 use_quote_code
8 ignoring_unknown custom attribute_barred
9 ignoring_unknown ignoring_unknown
10 ignoring_unknown custom
11 ignoring_unknown ignoring_unknown
12 ignoring_unknown

PASS ../toast/living/jan21/ls10.html
5 element_offsite_base

PASS ../toast/living/jan21/ls11.html
4 long_title
5 element_offsite_base

PASS ../toast/living/jan21/ls13.html
12 use_quote_code

PASS ../toast/living/jan21/ls15.html
3 naughty_lang

PASS ../toast/living/jan21/ls16.html
0 charset_mismatch charset_used charset_invalid
9 url_not_found
10 url_not_found
11 url_not_found
16 url_not_found
17 url_not_found
18 url_not_found
23 not_schema_property unrecognised_value bad_itemprop
42 url_not_found
43 url_not_found
44 url_not_found

PASS ../toast/living/jan21/ls17.html
0 charset_mismatch charset_used charset_invalid
11 url_not_found
13 only_elements
25 only_elements

PASS ../toast/living/jan21/main1.html
3 inserted_missing_parent missing_close
14 inserted_missing_parent inserted_missing_closure missing_close
18 attempted_escape no_such_folder url_not_found
19 attempted_escape no_such_folder url_not_found
22 missing_close
23 use_quote_code inserted_missing_closure
32 missing_close
33 inserted_missing_closure
34 inserted_missing_closure

PASS ../toast/living/jan21/main2.html
2 missing_close
3 inserted_missing_parent missing_close
5 url_not_found
6 url_not_found
7 inserted_missing_parent inserted_missing_closure missing_close
8 chocolate_teapot missing_open
9 url_not_found
10 url_not_found
24 missing_open

PASS ../toast/living/jan21/map.html
0 charset_mismatch charset_used charset_invalid
2 missing_close
3 inserted_missing_parent missing_close
4 inserted_missing_parent inserted_missing_closure missing_close
8 no_such_folder url_not_found
14 no_such_folder url_not_found
15 no_such_folder url_not_found
16 no_such_folder url_not_found
17 no_such_folder url_not_found
18 no_such_folder url_not_found
19 no_such_folder url_not_found
20 no_such_folder url_not_found
21 no_such_folder url_not_found

PASS ../toast/living/jan21/mark.html
9 use_quote_code
16 use_quote_code
25 unrecognised_value unrecognised_value
27 unrecognised_value
28 unrecognised_value unrecognised_value
29 unrecognised_value
46 use_quote_code
48 use_quote_code
51 use_quote_code

PASS ../toast/living/jan21/me.html
7 url_not_found
31 url_not_found
61 url_not_found autoplay

PASS ../toast/living/jan21/menu.html
7 interactive url_not_found
8 interactive url_not_found
9 interactive url_not_found

PASS ../toast/living/jan21/meter.html
7 url_not_found
10 bad_meter
11 bad_meter
16 inserted_missing_closure
17 inserted_missing_closure inserted_missing_closure missing_close
18 inserted_missing_closure
21 inserted_missing_closure
22 inserted_missing_closure inserted_missing_closure missing_close
23 inserted_missing_closure
27 inserted_missing_closure
28 missing_open
31 no_such_folder url_not_found
32 no_such_folder url_not_found
37 no_such_folder url_not_found
38 no_such_folder url_not_found
43 no_such_folder url_not_found
44 no_such_folder url_not_found

PASS ../toast/living/jan21/noscript.html
6 url_not_found
27 url_not_found
30 id_exists

PASS ../toast/living/jan21/object.html
7 url_not_found
12 reputation
22 url_not_found bad_usemap url_id_unfound

PASS ../toast/living/jan21/ol.html
10 inserted_missing_closure
11 inserted_missing_closure
12 inserted_missing_closure missing_close
13 inserted_missing_closure
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure

PASS ../toast/living/jan21/optgroup.html
6 url_not_found
8 inserted_missing_closure
12 inserted_missing_closure
13 inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure
16 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure inserted_missing_closure missing_close
20 inserted_missing_closure
21 inserted_missing_closure missing_close
22 inserted_missing_closure inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure

PASS ../toast/living/jan21/p.html
48 inserted_missing_closure
49 inserted_missing_closure missing_close
50 inserted_missing_closure
56 inserted_missing_closure
57 inserted_missing_closure missing_close
58 inserted_missing_closure

PASS ../toast/living/jan21/param.html
9 mime
16 newline_in_string newline_in_string url_not_found
21 url_not_found

PASS ../toast/living/jan21/q.html
7 use_double_quote_code
10 use_quote_code
12 use_double_quote_code
16 use_double_quote_code use_quote_code
17 use_double_quote_code
23 use_double_quote_code use_quote_code

PASS ../toast/living/jan21/ruby.html
10 missing_close inserted_missing_closure
12 missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure
14 missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure
16 missing_close inserted_missing_closure
24 missing_close inserted_missing_closure
26 missing_close inserted_missing_closure
28 missing_close inserted_missing_closure
30 missing_close inserted_missing_closure
32 inserted_missing_closure missing_close inserted_missing_closure
34 inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
37 inserted_missing_closure
38 inserted_missing_closure
39 inserted_missing_closure
42 missing_close inserted_missing_closure
56 missing_close
57 inserted_missing_closure

PASS ../toast/living/jan21/samp.html
7 use_quote_code
9 unrecognised_value
13 unrecognised_value unrecognised_value
16 unrecognised_value

PASS ../toast/living/jan21/script.html
0 charset_mismatch charset_used charset_invalid
6 bad_script
11 url_not_found
12 mime
42 use_double_quote_code
51 url_not_found
53 url_not_found
54 url_not_found
83 bad_script
88 bad_script
107 url_not_found script

PASS ../toast/living/jan21/select.html
17 bad_select
41 inserted_missing_closure
42 inserted_missing_closure
43 inserted_missing_closure
44 inserted_missing_closure
45 inserted_missing_closure
46 inserted_missing_closure
47 inserted_missing_closure
48 inserted_missing_closure
49 use_quote_code inserted_missing_closure
50 inserted_missing_closure missing_close
51 inserted_missing_closure

PASS ../toast/living/jan21/small.html
0 charset_mismatch charset_used charset_invalid
8 inserted_missing_closure
9 inserted_missing_closure
10 inserted_missing_closure missing_close
11 inserted_missing_closure
23 use_double_quote_code

PASS ../toast/living/jan21/source.html
6 inserted_missing_parent missing_close media_descendants url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found
11 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found
15 url_not_found mime
16 url_not_found mime
17 url_not_found mime
18 url_not_found
19 mime url_not_found
33 wrong_parent autoplay
34 url_not_found
35 url_not_found
39 inserted_missing_closure

PASS ../toast/living/jan21/span.html
6 unrecognised_value unrecognised_value unrecognised_value
7 unrecognised_value unrecognised_value
8 unrecognised_value unrecognised_value lonely_ampersand
9 unrecognised_value
10 unrecognised_value unrecognised_value
11 unrecognised_value unrecognised_value
12 unrecognised_value lonely_ampersand
13 unrecognised_value unrecognised_value
14 unrecognised_value
15 unrecognised_value

PASS ../toast/living/jan21/strong.html
8 inserted_missing_parent missing_close
11 use_quote_code
27 inserted_missing_closure

PASS ../toast/living/jan21/table.html
14 wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
19 inserted_missing_closure
20 inserted_missing_closure
21 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
23 inserted_missing_closure
24 inserted_missing_closure missing_close
25 inserted_missing_closure inserted_missing_closure inserted_missing_closure
36 id_exists
37 wrong_parent inserted_missing_closure
38 wrong_parent inserted_missing_closure
39 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
41 bad_header_id bad_header_id
42 inserted_missing_closure id_exists
43 inserted_missing_closure
44 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
45 bad_header_id bad_header_id
46 inserted_missing_closure id_exists
47 inserted_missing_closure missing_close
48 inserted_missing_closure inserted_missing_closure inserted_missing_closure
62 id_exists
63 wrong_parent inserted_missing_closure
64 wrong_parent inserted_missing_closure
65 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
67 bad_header_id bad_header_id
68 inserted_missing_closure id_exists
69 inserted_missing_closure
70 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
71 bad_header_id bad_header_id
72 inserted_missing_closure id_exists
73 inserted_missing_closure missing_close
74 inserted_missing_closure inserted_missing_closure inserted_missing_closure
84 id_exists
85 wrong_parent inserted_missing_closure
86 wrong_parent inserted_missing_closure
87 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
89 bad_header_id bad_header_id
90 inserted_missing_closure id_exists
91 inserted_missing_closure
92 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
93 bad_header_id bad_header_id
94 inserted_missing_closure id_exists
95 inserted_missing_closure missing_close
96 inserted_missing_closure inserted_missing_closure inserted_missing_closure
109 id_exists
110 wrong_parent inserted_missing_closure
111 wrong_parent inserted_missing_closure
112 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
114 bad_header_id bad_header_id
115 inserted_missing_closure id_exists
116 inserted_missing_closure
117 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
118 bad_header_id bad_header_id
119 inserted_missing_closure id_exists
120 inserted_missing_closure missing_close
121 inserted_missing_closure inserted_missing_closure inserted_missing_closure
129 wrong_parent inserted_missing_closure
130 wrong_parent inserted_missing_closure
131 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
134 inserted_missing_closure
135 wrong_parent inserted_missing_closure
136 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
138 inserted_missing_closure
139 wrong_parent inserted_missing_closure missing_close
140 inserted_missing_closure inserted_missing_closure inserted_missing_closure
147 use_quote_code
150 inserted_missing_closure
151 inserted_missing_closure
152 inserted_missing_closure
153 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
154 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
155 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
156 inserted_missing_closure inserted_missing_closure inserted_missing_closure
157 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
158 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
159 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
160 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
161 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
162 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
163 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
164 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/td.html
9 wrong_parent inserted_missing_closure
10 inserted_missing_closure wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 inserted_missing_closure wrong_parent inserted_missing_closure
15 wrong_parent inserted_missing_closure
16 inserted_missing_closure wrong_parent inserted_missing_closure
18 wrong_parent inserted_missing_closure
19 inserted_missing_closure wrong_parent inserted_missing_closure
21 wrong_parent inserted_missing_closure
22 inserted_missing_closure wrong_parent inserted_missing_closure
24 wrong_parent inserted_missing_closure
25 inserted_missing_closure wrong_parent inserted_missing_closure
27 wrong_parent inserted_missing_closure
28 inserted_missing_closure wrong_parent inserted_missing_closure
30 wrong_parent inserted_missing_closure
31 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
33 inserted_missing_closure missing_close missing_close attribute_barred
34 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/te.html
54 wrong_parent inserted_missing_closure
55 wrong_parent inserted_missing_closure
56 wrong_parent inserted_missing_closure
57 inserted_missing_closure inserted_missing_closure inserted_missing_closure
60 inserted_missing_closure
61 wrong_parent inserted_missing_closure
62 wrong_parent inserted_missing_closure
63 inserted_missing_closure wrong_parent inserted_missing_closure
65 inserted_missing_closure
66 wrong_parent inserted_missing_closure
67 wrong_parent inserted_missing_closure
68 inserted_missing_closure inserted_missing_closure inserted_missing_closure
71 inserted_missing_closure
72 wrong_parent inserted_missing_closure
73 wrong_parent inserted_missing_closure
74 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
75 missing_close
77 inserted_missing_closure
78 wrong_parent inserted_missing_closure
79 wrong_parent inserted_missing_closure missing_close
80 inserted_missing_closure inserted_missing_closure inserted_missing_closure
84 inserted_missing_closure
85 inserted_missing_closure
86 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
87 inserted_missing_closure inserted_missing_closure inserted_missing_closure
89 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
90 inserted_missing_closure wrong_parent inserted_missing_closure
91 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
92 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
94 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
95 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
96 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
97 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/template1.html
5 inserted_missing_closure missing_close
16 inserted_missing_closure

PASS ../toast/living/jan21/template2.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
10 inserted_missing_parent inserted_missing_closure missing_close
13 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
14 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
16 missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure
18 inserted_missing_closure

PASS ../toast/living/jan21/textarea.html
12 use_quote_code use_double_quote_code
21 bad_textarea
31 newline_in_string newline_in_string

PASS ../toast/living/jan21/th.html
8 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
9 inserted_missing_closure inserted_missing_closure inserted_missing_closure
10 inserted_missing_closure inserted_missing_closure wrong_parent inserted_missing_closure
11 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
12 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
13 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
14 inserted_missing_closure inserted_missing_closure wrong_parent inserted_missing_closure
15 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
16 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
17 inserted_missing_closure inserted_missing_closure inserted_missing_closure

PASS ../toast/living/jan21/thead.html
11 wrong_parent inserted_missing_closure
12 wrong_parent inserted_missing_closure
13 wrong_parent inserted_missing_closure
14 inserted_missing_closure wrong_parent inserted_missing_closure
16 wrong_parent inserted_missing_closure
17 wrong_parent inserted_missing_closure
18 wrong_parent inserted_missing_closure
19 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
22 wrong_parent inserted_missing_closure
23 wrong_parent inserted_missing_closure attribute_required naughty_alt
24 wrong_parent inserted_missing_closure
25 inserted_missing_closure wrong_parent inserted_missing_closure missing_close
27 wrong_parent inserted_missing_closure
28 wrong_parent inserted_missing_closure
29 wrong_parent inserted_missing_closure missing_close
30 inserted_missing_closure inserted_missing_closure inserted_missing_closure
31 url_not_found

PASS ../toast/living/jan21/time.html
75 schema_domain

PASS ../toast/living/jan21/tls.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
15 inserted_missing_closure inserted_missing_closure missing_close inserted_missing_closure
26 unrecognised_value
29 use_double_quote_code
30 use_double_quote_code

PASS ../toast/living/jan21/track.html
0 charset_mismatch charset_used charset_invalid
6 url_not_found
7 url_not_found
8 url_not_found
9 url_not_found
10 url_not_found

PASS ../toast/living/jan21/ul.html
9 inserted_missing_closure
10 inserted_missing_closure
11 inserted_missing_closure missing_close
12 inserted_missing_closure
17 inserted_missing_closure
18 inserted_missing_closure
19 inserted_missing_closure missing_close
20 inserted_missing_closure

PASS ../toast/living/jan21/us-1.html
2 naughty_lang
3 use_quote_code

PASS ../toast/living/jan21/us-2.html
11 url_not_found
16 url_not_found naughty_alt

PASS ../toast/living/jan21/us-4.html
12 inserted_missing_closure url_not_found
13 inserted_missing_closure missing_close url_not_found
14 inserted_missing_closure

PASS ../toast/living/jan21/us-5.html
12 url_not_found

PASS ../toast/living/jan21/var.html
21 use_quote_code
27 use_quote_code

PASS ../toast/living/jan21/video.html
30 url_not_found autoplay
31 url_not_found

PASS ../toast/living/jan21/wbr.html
7 use_double_quote_code use_double_quote_code
