[general]
verbose=5
output=../out/rsl.out

[html]
version=2025/09/01

[link]
check=

[nits]
nids=

[rsl]
verify=

[rss]
verify=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/type/rsl
