[general]
verbose=info
output=../out/vtt.out
class=

[css]
verify=
extension=css
version=2018++
no-external=
selector=4

[html]
version=2019/04/01

[link]
check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/other/vtt

[spell]
no-check=true

[stats]
summary=
class=
error=