-f ../toast/HTML/3.0/html3.conf

PASS ../toast/HTML/3.0/html3-deprecated.html
1 sq_bra_ket

PASS ../toast/HTML/3.0/html3-recommended.html
1 sq_bra_ket

PASS ../toast/HTML/3.0/html3-math.html
60 inserted_missing_closure
61 inserted_missing_closure missing_close
62 inserted_missing_closure
66 inserted_missing_closure
67 inserted_missing_closure
68 inserted_missing_closure missing_close
69 inserted_missing_closure
73 inserted_missing_closure
74 inserted_missing_closure
75 inserted_missing_closure missing_close
76 inserted_missing_closure

PASS ../toast/HTML/3.0/html3-sample.html
9 bad_datetime
10 use_metaname
11 use_metaname
12 deprecated_element deprecated_element
13 unrecognised_value
24 immeasurable
26 unrecognised_value
27 missing_close immeasurable
30 inserted_missing_closure
55 deprecated_element
58 inserted_missing_closure
59 inserted_missing_closure missing_close
60 inserted_missing_closure
62 deprecated_element
65 inserted_missing_closure
66 inserted_missing_closure missing_close
67 inserted_missing_closure
71 inserted_missing_closure
72 inserted_missing_closure inserted_missing_closure missing_close
73 inserted_missing_closure
76 inserted_missing_closure
77 inserted_missing_closure inserted_missing_closure missing_close
78 inserted_missing_closure
84 inserted_missing_closure
91 missing_close
92 deprecated_element
94 inserted_missing_closure
95 inserted_missing_closure
96 inserted_missing_closure
97 inserted_missing_closure missing_close
98 inserted_missing_closure
99 inserted_missing_closure
106 missing_close
107 inserted_missing_closure
111 wrong_parent inserted_missing_closure
112 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
113 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
114 inserted_missing_closure wrong_parent inserted_missing_closure inserted_missing_closure wrong_parent inserted_missing_closure
115 inserted_missing_closure wrong_parent inserted_missing_closure missing_close inserted_missing_closure wrong_parent inserted_missing_closure missing_close
116 inserted_missing_closure inserted_missing_closure
118 mixed_mess
119 inserted_missing_parent missing_close
125 wrong_parent inserted_missing_closure missing_close
126 inserted_missing_parent missing_close attribute_required
131 inserted_missing_closure inserted_missing_closure inserted_missing_closure
134 missing_close
135 missing_close
136 inserted_missing_parent missing_close attribute_required
141 inserted_missing_closure inserted_missing_closure inserted_missing_closure
144 unrecognised_value
145 wrong_parent inserted_missing_closure unrecognised_value
146 wrong_parent inserted_missing_closure missing_close unrecognised_value
147 inserted_missing_closure
