-f tests/HTML/5.4/html5.conf

PASS tests/HTML/5.4/example-1.html
2 naughty_lang
6 unrecognised_value
8 missing_close inserted_missing_closure

PASS tests/HTML/5.4/example-2.html
2 naughty_lang
6 unrecognised_value

PASS tests/HTML/5.4/example-3.html
0 title_required
2 inserted_missing_parent missing_close naughty_lang
5 url_not_found
6 url_not_found
7 url_not_found
12 url_not_found
13 url_not_found
14 url_not_found
38 url_not_found
39 url_not_found
40 url_not_found

PASS tests/HTML/5.4/example-4.html
0 title_required
2 inserted_missing_parent missing_close naughty_lang
7 url_not_found
9 only_elements
21 only_elements

PASS tests/HTML/5.4/example-5.html
0 title_required
2 inserted_missing_parent missing_close naughty_lang
14 missing_close
15 inserted_missing_closure
20 url_not_found
21 inserted_missing_closure missing_close url_not_found
22 inserted_missing_closure
31 use_quote_code
34 use_quote_code
41 missing_close url_not_found
42 inserted_missing_closure
55 use_quote_code
58 missing_close url_not_found
59 inserted_missing_closure
63 url_not_found
64 url_not_found
65 url_not_found

PASS tests/HTML/5.4/example-6.html
4 inserted_missing_closure
8 no_such_folder url_not_found
9 no_such_folder url_not_found
26 url_not_found
27 url_not_found

PASS tests/HTML/5.4/example-7.html
2 missing_close
3 inserted_missing_parent missing_close
4 inserted_missing_parent inserted_missing_closure missing_close
19 inserted_missing_closure
20 use_quote_code

PASS tests/HTML/5.4/example-8.html
3 inserted_missing_parent missing_close
4 inserted_missing_parent inserted_missing_closure missing_close
17 use_quote_code
29 inserted_missing_closure

PASS tests/HTML/5.4/html5-bad.html
2 naughty_lang
5 mime
7 only_once
10 default_role
14 attribute_required form_charset
16 correct_spelling attribute_unrecognised missing_close unrecognised_attribute
18 lonely_ampersand inserted_missing_parent inserted_missing_closure inserted_missing_parent
19 inserted_missing_closure inserted_missing_closure missing_close
21 missing_open
23 unrecognised_value unrecognised_value
31 mixed_mess
33 special_name
48 missing_open
49 missing_open
51 attribute_unrecognised unrecognised_attribute unrecognised_value
53 inserted_missing_closure
55 unrecognised_value
56 attributes_on_closure
57 unrecognised_value
58 attribute_required url_not_found naughty_alt
59 attribute_required url_not_found naughty_alt
60 attribute_required url_not_found
61 attribute_required url_not_found naughty_alt
62 attribute_required url_not_found
63 attribute_required url_not_found naughty_alt
65 missing_close inserted_missing_closure missing_open
67 nuts
77 url_not_found
80 url_not_found
81 inserted_missing_closure missing_close
82 inserted_missing_closure
85 use_quote_code
89 figcaption_first_last
90 use_quote_code
92 inserted_missing_closure
94 missing_open
97 saucy_source
99 mq_syntax
103 no_itemscope bad_object disordered_param
108 attribute_required
109 bad_datetime
110 bad_autocomplete
111 bad_autocomplete bad_datetime
112 bad_autocomplete bad_datetime
113 solo sunk minmax
114 minmax minmax
116 unrecognised_value bad_colour
119 solo
120 bad_autocomplete
121 relative_path
122 relative_path
123 bad_autocomplete relative_path
124 bad_autocomplete
125 bad_autocomplete
127 unrecognised_value
128 bad_autocomplete
130 bad_autocomplete
134 url_not_found
135 bad_script bad_script
136 bad_script
141 bad_script
142 bad_script
143 unrecognised_value invalid_attribute_version wrong_version
144 invalid_attribute_version wrong_version
145 bad_script
146 bad_script

PASS tests/HTML/5.4/html5-bad-2.html
5 link_rel_off
6 no_itemscope link_rel_off
7 sizes sizes sizes sizes sizes daft_rel_attr
8 daft_rel_attr
9 correct_spelling attribute_unrecognised unrecognised_attribute
10 sizes sizes sizes sizes sizes sizes
11 daft_rel_attr
12 as_not_image as_not_image daft_rel_attr
13 bad_srcset bad_srcset sizes sizes
14 bad_srcset bad_srcset
15 bad_srcset bad_srcset
17 unrecognised_value

PASS tests/HTML/5.4/html5-example.html
2 naughty_lang
6 element_offsite_base
8 url_not_found cannot_load_css
9 url_not_found
10 url_not_found
10 attribute_required
80 attribute_required
85 unrecognised_value
88 data_type attribute_required attribute_required attribute_required
98 url_not_found
104 use_quote_code
108 url_not_found
109 url_not_found
110 url_not_found
111 use_quote_code
117 url_not_found
120 url_not_found
121 inserted_missing_closure missing_close
122 inserted_missing_closure
125 use_quote_code
135 unrecognised_value
137 unrecognised_value
147 use_quote_code double_angular_open
151 use_double_quote_code
153 use_double_quote_code
156 schema_domain
163 use_quote_code
170 schema_domain
177 use_quote_code
181 schema_domain
184 schema_domain
191 schema_domain
194 schema_domain
241 url_not_found
244 url_not_found
246 no_such_folder url_not_found
248 use_double_quote_code
251 url_not_found
268 use_quote_code
271 use_quote_code
274 use_quote_code
276 use_quote_code
283 use_quote_code
292 bad_ancestor
320 url_id_unfound
322 missing_close unrecognised_value missing_close
323 inserted_missing_closure inserted_missing_closure
329 url_not_found
330 inserted_missing_closure url_not_found
331 inserted_missing_closure missing_close url_not_found
332 inserted_missing_closure
337 use_quote_code
343 attempted_escape
355 attempted_escape
360 no_such_folder url_not_found
361 no_such_folder url_not_found
378 url_not_found
379 url_not_found
389 no_such_folder url_not_found naughty_alt
391 no_such_folder url_not_found
391 no_such_folder url_not_found
392 no_such_folder url_not_found
393 attribute_required no_such_folder url_not_found naughty_alt
395 no_such_folder url_not_found
397 attribute_required no_such_folder url_not_found naughty_alt
399 use_quote_code no_such_folder url_not_found
402 url_not_found
403 inserted_missing_closure url_not_found
404 inserted_missing_closure missing_close url_not_found
405 inserted_missing_closure
408 url_not_found
412 attempted_escape no_such_folder url_not_found
413 attempted_escape no_such_folder url_not_found
414 url_not_found
442 bad_ancestor
467 inserted_missing_closure
468 use_quote_code
500 inserted_missing_closure
501 inserted_missing_closure missing_close
502 inserted_missing_closure
516 use_quote_code
544 use_quote_code
546 use_quote_code
555 use_quote_code
581 use_double_quote_code use_quote_code
588 use_double_quote_code
597 missing_close use_quote_code
600 inserted_missing_closure
602 use_double_quote_code
616 inserted_missing_closure
617 inserted_missing_closure
618 inserted_missing_closure missing_close
619 inserted_missing_closure
624 inserted_missing_closure
625 inserted_missing_closure
626 inserted_missing_closure missing_close
627 inserted_missing_closure
632 inserted_missing_closure
633 inserted_missing_closure
634 inserted_missing_closure missing_close
635 inserted_missing_closure
641 lingo
642 use_quote_code
670 use_quote_code
675 unrecognised_value use_quote_code
676 unrecognised_value
678 unrecognised_value use_quote_code
679 unrecognised_value
680 unrecognised_value
698 newline_in_string newline_in_string url_not_found
701 url_not_found url_not_found
703 use_quote_code
709 use_double_quote_code inserted_missing_closure
710 url_not_found
717 inserted_missing_closure
718 url_not_found
725 url_not_found
732 use_quote_code
743 use_quote_code
751 use_quote_code use_double_quote_code
753 use_double_quote_code
756 only_once
776 unrecognised_value
804 inserted_missing_parent missing_close
806 use_quote_code
822 inserted_missing_closure
823 inserted_missing_closure
824 inserted_missing_closure missing_close
825 inserted_missing_closure
836 use_double_quote_code
851 unrecognised_value
865 use_quote_code
868 use_quote_code
887 use_quote_code
900 use_double_quote_code use_quote_code
905 use_quote_code
911 use_quote_code
921 id_exists
1010 schema_domain
1041 unrecognised_value
1061 use_quote_code
1067 use_quote_code
1071 use_quote_code
1073 unrecognised_value
1077 unrecognised_value unrecognised_value
1098 unrecognised_value
1116 use_quote_code
1117 unrecognised_value
1125 use_quote_code
1132 use_quote_code
1141 unrecognised_value unrecognised_value
1142 unrecognised_value
1143 unrecognised_value unrecognised_value
1144 unrecognised_value
1152 missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure
1156 missing_close inserted_missing_closure missing_close inserted_missing_closure missing_close inserted_missing_closure
1158 missing_close inserted_missing_closure
1163 missing_close inserted_missing_closure
1165 missing_close inserted_missing_closure
1169 missing_close inserted_missing_closure
1171 inserted_missing_closure missing_close inserted_missing_closure
1177 inserted_missing_closure
1178 inserted_missing_closure
1179 inserted_missing_closure missing_close
1180 inserted_missing_closure
1182 missing_close inserted_missing_closure
1198 missing_close
1199 inserted_missing_closure
1201 no_rp
1202 no_rp no_rp
1209 unrecognised_value unrecognised_value unrecognised_value unrecognised_value unrecognised_value
1210 unrecognised_value unrecognised_value lonely_ampersand unrecognised_value
1211 unrecognised_value unrecognised_value unrecognised_value unrecognised_value unrecognised_value lonely_ampersand
1212 unrecognised_value unrecognised_value unrecognised_value
1213 unrecognised_value
1220 chocolate_teapot
1221 chocolate_teapot
1227 use_double_quote_code inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close use_double_quote_code inserted_missing_closure
1230 inserted_missing_closure
1231 inserted_missing_closure
1232 inserted_missing_closure
1233 inserted_missing_closure missing_close inserted_missing_closure
1265 use_quote_code
1291 use_quote_code
1295 use_quote_code
1313 no_such_folder url_not_found
1316 url_not_found
1317 no_such_folder url_not_found
1320 url_not_found
1332 url_not_found
1335 url_not_found
1337 url_not_found
1344 newline_in_string newline_in_string url_not_found
1355 overallowed
1357 url_not_found
1360 mime
1367 newline_in_string newline_in_string url_not_found
1372 url_not_found
1376 url_not_found
1377 url_not_found
1378 url_not_found
1379 url_not_found
1380 url_not_found
1381 url_not_found
1382 url_not_found
1383 url_not_found
1384 url_not_found
1385 url_not_found
1386 url_not_found
1387 url_not_found
1388 url_not_found
1391 url_not_found
1392 url_not_found
1393 url_not_found
1394 url_not_found
1395 url_not_found
1401 url_not_found
1404 url_not_found
1405 url_not_found
1406 url_not_found
1408 url_not_found
1418 use_quote_code
1421 inserted_missing_closure
1422 inserted_missing_closure
1423 inserted_missing_closure
1424 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1425 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1426 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1427 inserted_missing_closure inserted_missing_closure inserted_missing_closure
1428 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1429 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1430 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1431 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
1432 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1433 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
1434 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
1435 inserted_missing_closure inserted_missing_closure inserted_missing_closure
1512 unrecognised_value
1525 use_quote_code
1535 use_quote_code
1552 url_not_found
1554 only_elements
1566 only_elements
1592 url_not_found
1593 url_not_found
1594 url_not_found
1599 url_not_found
1600 url_not_found
1601 url_not_found
1605 only_once bad_ancestor
1624 url_not_found
1625 url_not_found
1626 url_not_found
1631 url_not_found
1633 url_not_found
1635 no_such_folder url_not_found
1637 use_double_quote_code
1639 url_not_found
1648 url_not_found
1650 inserted_missing_closure
1651 url_not_found
1652 inserted_missing_closure
1653 url_not_found
1654 inserted_missing_closure
1655 url_not_found
1656 inserted_missing_closure missing_close
1657 url_not_found
1658 inserted_missing_closure
1689 attribute_required
1698 inserted_missing_closure
1700 inserted_missing_closure
1701 input_bad_mix
1702 inserted_missing_closure missing_close
1704 inserted_missing_closure
1712 inserted_missing_closure
1714 inserted_missing_closure missing_close
1716 inserted_missing_closure
1743 url_not_found
1744 inserted_missing_closure url_not_found
1745 inserted_missing_closure missing_close url_not_found
1746 inserted_missing_closure
1751 use_quote_code
1758 attempted_escape
1770 attempted_escape
1776 no_such_folder url_not_found
1779 no_such_folder url_not_found
1780 no_such_folder url_not_found
1781 attribute_required no_such_folder url_not_found
1783 no_such_folder url_not_found
1785 attribute_required no_such_folder url_not_found
1787 use_quote_code no_such_folder url_not_found
1790 url_not_found
1791 inserted_missing_closure url_not_found
1792 inserted_missing_closure missing_close url_not_found
1793 inserted_missing_closure
1796 url_not_found
1800 attempted_escape no_such_folder url_not_found
1801 attempted_escape no_such_folder url_not_found
1802 url_not_found
1842 bad_ancestor
1858 bad_ancestor
1873 only_elements
1885 missing_close
1890 use_quote_code
1892 missing_close no_such_folder url_not_found inserted_missing_closure
1894 no_such_folder url_not_found
1895 inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
1898 no_such_folder url_not_found
1900 newline_in_string newline_in_string inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1 mixed_mess missing_open
1903 no_such_folder url_not_found
1905 newline_in_string newline_in_string inserted_missing_parent missing_close inserted_missing_parent missing_close presume_html_1
1909 url_not_found
1924 no_itemscope bad_object
1927 inserted_missing_closure inserted_missing_closure

PASS tests/HTML/5.4/html5-good.html
2 naughty_lang
34 requires_href
58 lonely_radio
63 naughty_alt

PASS tests/HTML/5.4/html5-legacy.html
2 naughty_lang

PASS tests/HTML/5.4/template-1.html
2 naughty_lang

PASS tests/HTML/5.4/template-2.html
2 naughty_lang

PASS tests/HTML/5.4/template-3.html
1 presume_html_1 attribute_unrecognised_here attribute_unrecognised_here unrecognised_attribute

PASS tests/HTML/5.4/template-4.html
2 inserted_missing_parent missing_close naughty_lang inserted_missing_parent missing_close
4 inserted_missing_parent inserted_missing_closure missing_close

PASS tests/HTML/5.4/math-example-1.html
3 naughty_lang

CLASS
info 1
warning 1
error 1
