[general]
verbose=5
output=../out/css4display.out
class=

[css]
verify=
extension=css
version=2.1
display=4
fbl=3
grid=4
selector=3

[html]
analysis=dec25
version=2026/01/01

[link]
no-check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/4-display

[spell]
no-check=
