-N 1 -f ../toast/RDFa/cc/rdfa.conf

PASS ../toast/RDFa/cc/cc.html
14 invalid_attribute_version wrong_version
22 invalid_attribute_version wrong_version
56 unrecognised_namespace unrecognised_namespace unrecognised_value unrecognised_value unrecognised_value
59 missing_close
61 unrecognised_value
73 wrong_parent wrong_parent no_such_folder url_not_found interactive
75 unrecognised_value
78 missing_close not_ontology_property bad_property missing_open
80 unrecognised_value
84 unrecognised_value no_such_folder url_not_found alt_title
86 inserted_missing_closure inserted_missing_closure
112 unrecognised_namespace unrecognised_value
117 naughty_alt
146 not_ontology_property bad_property
151 no_such_folder url_not_found
152 no_such_folder url_not_found
160 unrecognised_namespace unrecognised_value
170 unrecognised_value dl_ancestor dl_ancestor
173 not_ontology_property bad_property
179 unrecognised_value
185 only_elements
193 unrecognised_value dl_ancestor
194 dl_ancestor
212 mixed_mess
227 missing_open
231 attribute_required
235 character_code
236 bad_border invalid_attribute_version wrong_version attribute_required
242 unrecognised_value
246 invalid_attribute_version wrong_version
248 invalid_attribute_version wrong_version
253 inserted_missing_closure
255 empty invalid_attribute_version wrong_version
258 unrecognised_value invalid_attribute_version wrong_version
259 missing_close
265 inserted_missing_closure
267 unrecognised_value
268 missing_close
271 inserted_missing_closure
274 invalid_attribute_version wrong_version
281 missing_open
