[general]
verbose=5
output=../out/css4anchpos.out
class=

[css]
verify=
extension=css
version=4
contain=5

[html]
version=2026/01/01

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/4-anchor-positioning
