-N 1 -f ../toast/HTML/4.01/html4.conf

PASS ../toast/HTML/4.01/css-good.css
4 whatwg_class whatwg_class

PASS ../toast/HTML/4.01/html4-bad.html
5 bespoke_obsolete mime
12 deprecated_element unrecognised_value unrecognised_value bad_colour deprecated_attribute
15 inserted_missing_closure
16 missing_open
19 inserted_missing_closure
23 inserted_missing_closure
25 id_exists
27 inserted_missing_closure
28 use_quote_code key

PASS ../toast/HTML/4.01/html4-bad2.html
6 base_b4_lynx

PASS ../toast/HTML/4.01/html4-deprecated.html
1 html_superseded
6 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
9 deprecated_element deprecated_attribute
10 deprecated_element deprecated_attribute
11 deprecated_element deprecated_attribute
12 deprecated_element deprecated_attribute
13 deprecated_element deprecated_attribute
14 deprecated_element deprecated_attribute
15 deprecated_element deprecated_attribute
19 deprecated_element deprecated_attribute deprecated_attribute
20 deprecated_element deprecated_attribute deprecated_attribute
21 deprecated_element deprecated_attribute deprecated_attribute
23 deprecated_element deprecated_attribute
24 deprecated_element deprecated_attribute
25 deprecated_element deprecated_attribute
26 deprecated_element deprecated_attribute
27 deprecated_element deprecated_attribute
28 deprecated_element deprecated_attribute
29 deprecated_element deprecated_attribute
30 deprecated_element deprecated_attribute
31 deprecated_element deprecated_attribute
32 deprecated_element deprecated_attribute
33 deprecated_element deprecated_attribute
34 deprecated_element deprecated_attribute
35 deprecated_element deprecated_attribute
36 deprecated_element deprecated_attribute
37 deprecated_element deprecated_attribute
38 deprecated_element deprecated_attribute
45 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
46 deprecated_attribute
47 deprecated_attribute
48 deprecated_attribute
49 deprecated_attribute
51 deprecated_attribute
52 deprecated_attribute
53 deprecated_attribute
56 deprecated_attribute
57 deprecated_attribute
58 deprecated_attribute
59 deprecated_attribute
63 deprecated_attribute deprecated_attribute deprecated_attribute
64 deprecated_attribute
65 deprecated_attribute
66 deprecated_attribute
67 deprecated_attribute deprecated_attribute
69 deprecated_attribute
70 deprecated_attribute deprecated_attribute
71 deprecated_attribute deprecated_attribute
77 inserted_missing_closure
78 deprecated_attribute
79 missing_close
80 inserted_missing_closure
81 inserted_missing_closure missing_close
82 inserted_missing_closure
83 inserted_missing_closure missing_close
84 inserted_missing_closure
86 reputation deprecated_element deprecated_attribute deprecated_attribute deprecated_attribute url_not_found
90 deprecated_element deprecated_attribute deprecated_attribute deprecated_attribute url_not_found
95 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
96 deprecated_attribute
97 deprecated_attribute
101 inserted_missing_closure
102 inserted_missing_closure missing_close
103 inserted_missing_closure
105 deprecated_attribute
108 deprecated_element deprecated_attribute
109 deprecated_element deprecated_attribute
110 deprecated_element deprecated_attribute
111 deprecated_element deprecated_attribute
112 deprecated_element deprecated_attribute
113 deprecated_element deprecated_attribute
114 deprecated_element deprecated_attribute
117 deprecated_attribute deprecated_attribute
118 deprecated_attribute deprecated_attribute deprecated_attribute
119 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
121 deprecated_element deprecated_attribute
123 deprecated_element
124 deprecated_element
125 deprecated_element
126 deprecated_element
128 deprecated_attribute deprecated_attribute
129 deprecated_attribute
130 inserted_missing_parent missing_close deprecated_attribute
131 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
132 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
134 inserted_missing_closure
136 deprecated_attribute deprecated_attribute
138 inserted_missing_parent missing_close deprecated_attribute
139 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
140 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
142 inserted_missing_closure
144 deprecated_attribute deprecated_attribute
145 deprecated_attribute
146 inserted_missing_parent missing_close deprecated_attribute
147 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
148 deprecated_attribute deprecated_attribute deprecated_attribute deprecated_attribute
150 inserted_missing_closure
152 deprecated_attribute deprecated_attribute deprecated_attribute
153 deprecated_attribute
154 deprecated_attribute
155 deprecated_attribute
156 deprecated_attribute deprecated_attribute
158 deprecated_attribute
159 deprecated_attribute deprecated_attribute
160 deprecated_attribute deprecated_attribute
163 deprecated_attribute
164 deprecated_attribute
165 deprecated_attribute
166 deprecated_attribute

PASS ../toast/HTML/4.01/html4-example.html
0 charset_mismatch charset_used
10 bespoke_obsolete
15 bad_datetime
62 unrecognised_value unrecognised_value missing_units unrecognised_value isnt unrecognised_value isnt unrecognised_value
96 inserted_missing_closure inserted_missing_closure missing_close missing_close
97 inserted_missing_closure inserted_missing_closure
107 missing_close
108 inserted_missing_closure
119 inserted_missing_closure
120 inserted_missing_closure
122 inserted_missing_closure
124 use_double_quote_code
131 inserted_missing_closure
132 inserted_missing_parent missing_close inserted_missing_closure missing_close inserted_missing_closure
133 inserted_missing_closure missing_close inserted_missing_closure
134 inserted_missing_closure missing_close inserted_missing_closure
135 inserted_missing_closure missing_close inserted_missing_closure
136 inserted_missing_closure
141 inserted_missing_closure
142 inserted_missing_parent missing_close inserted_missing_closure missing_close inserted_missing_closure
143 inserted_missing_closure missing_close inserted_missing_closure
144 inserted_missing_closure missing_close inserted_missing_closure
145 inserted_missing_closure missing_close inserted_missing_closure
146 inserted_missing_closure
149 inserted_missing_closure missing_close inserted_missing_closure
155 inserted_missing_closure
157 missing_close
159 inserted_missing_closure
228 inserted_missing_closure
229 missing_open
245 inserted_missing_closure
246 inserted_missing_closure missing_close
247 inserted_missing_closure
251 inserted_missing_closure
252 inserted_missing_closure
253 inserted_missing_closure
254 inserted_missing_closure
255 inserted_missing_closure missing_close
256 inserted_missing_closure
260 inserted_missing_closure missing_close
262 inserted_missing_closure
265 deprecated_attribute
266 inserted_missing_closure deprecated_attribute
267 inserted_missing_closure missing_close
268 inserted_missing_closure
272 inserted_missing_closure
275 inserted_missing_closure
276 inserted_missing_closure
278 inserted_missing_closure
279 inserted_missing_closure missing_close
281 inserted_missing_closure
285 inserted_missing_closure
286 inserted_missing_closure
288 inserted_missing_closure missing_close
291 inserted_missing_closure
295 inserted_missing_closure missing_close
296 inserted_missing_closure
301 newline_in_string newline_in_string deprecated_attribute
303 inserted_missing_parent missing_close wrong_parent inserted_missing_closure
304 wrong_parent inserted_missing_closure
305 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
306 inserted_missing_closure wrong_parent inserted_missing_closure inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
307 inserted_missing_closure wrong_parent inserted_missing_closure missing_close inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
308 inserted_missing_closure inserted_missing_closure inserted_missing_closure
312 missing_close
313 inserted_missing_closure
315 missing_close
316 inserted_missing_closure
319 wrong_parent inserted_missing_closure missing_close
320 inserted_missing_closure
323 wrong_parent inserted_missing_closure
324 wrong_parent inserted_missing_closure missing_close
325 inserted_missing_closure
328 inserted_missing_parent
342 inserted_missing_closure
344 inserted_missing_closure
345 inserted_missing_closure missing_close
346 missing_close missing_close
347 inserted_missing_closure inserted_missing_closure inserted_missing_closure
349 inserted_missing_parent missing_close missing_close missing_close inserted_missing_closure inserted_missing_closure inserted_missing_closure
350 inserted_missing_parent missing_close missing_close missing_close inserted_missing_closure inserted_missing_closure inserted_missing_closure
351 missing_close inserted_missing_parent inserted_missing_closure missing_close missing_close missing_close inserted_missing_closure inserted_missing_closure inserted_missing_closure
352 inserted_missing_parent missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close inserted_missing_closure inserted_missing_closure
357 inserted_missing_closure
361 inserted_missing_closure deprecated_attribute
363 deprecated_attribute
364 inserted_missing_closure missing_close
365 missing_close missing_close
367 inserted_missing_closure inserted_missing_closure inserted_missing_closure
371 inserted_missing_closure
374 inserted_missing_closure missing_close
375 missing_close missing_close
377 inserted_missing_closure inserted_missing_closure inserted_missing_closure
382 newline_in_string newline_in_string
384 inserted_missing_parent missing_close
385 wrong_parent inserted_missing_closure
386 wrong_parent inserted_missing_closure missing_close
388 inserted_missing_closure inserted_missing_closure
393 newline_in_string newline_in_string
395 inserted_missing_parent missing_close
400 wrong_parent inserted_missing_closure
405 wrong_parent inserted_missing_closure missing_close
410 inserted_missing_closure inserted_missing_closure
412 deprecated_attribute
414 inserted_missing_parent missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
415 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
416 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
417 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure missing_close
418 inserted_missing_closure inserted_missing_closure inserted_missing_closure
420 deprecated_attribute
421 inserted_missing_parent missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
422 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
423 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
424 inserted_missing_closure inserted_missing_closure inserted_missing_closure
426 deprecated_attribute
427 inserted_missing_parent missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
428 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
429 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
430 inserted_missing_closure inserted_missing_closure inserted_missing_closure
432 deprecated_attribute
433 inserted_missing_parent missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
434 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
435 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure missing_close
436 inserted_missing_closure inserted_missing_closure inserted_missing_closure
442 newline_in_string newline_in_string deprecated_attribute
444 inserted_missing_parent missing_close
449 wrong_parent inserted_missing_closure
454 wrong_parent inserted_missing_closure missing_close
459 inserted_missing_closure inserted_missing_closure
464 newline_in_string newline_in_string deprecated_attribute
465 inserted_missing_parent missing_close
508 inserted_missing_closure
513 newline_in_string newline_in_string deprecated_attribute
516 inserted_missing_parent missing_close
567 inserted_missing_closure
571 newline_in_string newline_in_string deprecated_attribute
573 deprecated_attribute inserted_missing_closure deprecated_attribute
574 inserted_missing_closure deprecated_attribute inserted_missing_closure deprecated_attribute
575 inserted_missing_closure
577 wrong_parent inserted_missing_closure
578 wrong_parent inserted_missing_closure
579 wrong_parent inserted_missing_closure
580 wrong_parent inserted_missing_closure
581 wrong_parent inserted_missing_closure
582 wrong_parent inserted_missing_closure
583 inserted_missing_closure inserted_missing_closure inserted_missing_closure
584 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
585 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
586 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
587 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
588 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
589 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
590 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
591 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
592 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
593 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
594 inserted_missing_closure inserted_missing_closure inserted_missing_closure missing_close
595 wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
596 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
597 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
598 inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure
599 inserted_missing_closure wrong_parent inserted_missing_closure missing_close wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure wrong_parent inserted_missing_closure missing_close
600 inserted_missing_closure inserted_missing_closure inserted_missing_closure
608 inserted_missing_closure id_exists
620 id_exists
631 url_not_found
633 url_not_found
646 inserted_missing_closure
650 url_not_found incompatible_mime
653 inserted_missing_closure
655 url_not_found
657 missing_close
658 inserted_missing_closure
662 url_not_found
667 inserted_missing_closure url_not_found
669 missing_close
670 url_not_found
671 url_not_found
672 url_not_found
673 url_not_found
674 inserted_missing_closure
678 url_not_found
679 missing_close
680 inserted_missing_closure
681 id_exists
685 url_not_found
689 url_not_found
693 url_not_found
697 url_not_found
700 inserted_missing_closure
703 inserted_missing_closure unrecognised_value
711 inserted_missing_closure missing_close
713 inserted_missing_closure
720 use_quote_code
752 no_such_folder url_not_found
754 no_such_folder url_not_found
759 missing_close
763 inserted_missing_closure
764 inserted_missing_closure missing_close
765 inserted_missing_closure
768 inserted_missing_closure missing_close
769 inserted_missing_closure
772 inserted_missing_closure missing_close
773 inserted_missing_closure
775 inserted_missing_closure
787 url_not_found attribute_required
792 url_not_found attribute_required
805 url_not_found attribute_required
807 inserted_missing_closure
854 inserted_missing_closure url_not_found attribute_required
882 inserted_missing_closure
883 missing_close
884 inserted_missing_closure

PASS ../toast/HTML/4.01/html4-frameset.html
14 inserted_missing_closure
16 inserted_missing_closure
17 inserted_missing_closure missing_close
18 inserted_missing_closure

PASS ../toast/HTML/4.01/html4-frameset-bad.html
0 frameset_body

PASS ../toast/HTML/4.01/html4-good.html
86 inserted_missing_closure
87 inserted_missing_closure
89 inserted_missing_closure

PASS ../toast/HTML/4.01/html4-lang.html
11 inserted_missing_closure
12 inserted_missing_closure missing_close
15 inserted_missing_closure

PASS ../toast/HTML/4.01/html4-simple.html
7 missing_close
8 inserted_missing_closure
