<!--#config timefmt="%Y-%m-%dT%H:%M:%S" -->

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Security-Policy" content="<!--#echo encoding="none" var="csp" -->">

<meta name="theme-color" content="#000000">
<meta name="color-scheme" content="dark">

<meta name="author" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="creator" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="dc.creator" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="dcterms.creator" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="designer" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="web_author" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="contact" content="<!--#echo encoding="none" var="email" --> '<!--#echo encoding="none" var="uhostland" -->'">
<meta name="copyright" content="<!--#echo encoding="none" var="scopyright" -->">
<meta name="dcterms.rightsholder" content="<!--#echo encoding="none" var="swebmeister" -->">
<meta name="dc.language" content="<!--#echo encoding="none" var="lang" -->">
<meta name="og:locale" content="<!--#echo encoding="none" var="lang" -->">
<meta name="dcterms.license" content="<!--#echo encoding="none" var="licence" -->">
<meta name="dc.title" content="<!--#echo encoding="none" var="title" -->">
<meta name="dcterms.title" content="<!--#echo encoding="none" var="title" -->">
<meta name="og:title" content="<!--#echo encoding="none" var="title" -->">
<meta name="twitter:title" content="<!--#echo encoding="none" var="title" -->">
<meta name="dcterms.datecopyrighted" content="<!--#echo encoding="none" var="year" -->">
<meta name="dcterms.license" content="<!--#echo encoding="none" var="licence" -->">
<meta name="dcterms.rights" content="<!--#echo encoding="none" var="scopyright" -->">
<meta name="description" content="<!--#echo encoding="none" var="description" -->">
<meta name="dc.description" content="<!--#echo encoding="none" var="description" -->">
<meta name="dcterms.description" content="<!--#echo encoding="none" var="description" -->">
<meta name="og:description" content="<!--#echo encoding="none" var="description" -->">
<meta name="twitter:description" content="<!--#echo encoding="none" var="description" -->">
<meta name="keywords" content="<!--#echo encoding="none" var="sname" -->,poetry,publisher,luxembourg,esch-sur-alzette,english,buy,for sale,book,print">
<meta name="geo.country" content="<!--#echo encoding="none" var="country" -->">
<meta name="og:image" content="<!--#echo encoding="none" var="icon" -->">
<meta name="og:site_name" content="<!--#echo encoding="none" var="swebsite" -->">
<meta name="og:url" content="<!--#echo encoding="none" var="address" --><!--#echo encoding="none" var="DOCUMENT_URI" -->" >
<meta name="revision" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta name="revised" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta name="dcterms.modified" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta name="rights-standard" content=";<!--#echo encoding="none" var="cc" -->">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#000000"> <!--#comment see dylanharris.org/blog/2015/sn41.shtml -->
<meta name="viewport" content="width=device-width">
<link rel="author" href="<!--#echo encoding="none" var="artsego" -->">
<link rel="home" href="<!--#echo encoding="none" var="address" -->">
<link rel="canonical" href="<!--#echo encoding="none" var="address" --><!--#echo encoding="none" var="DOCUMENT_URI" -->" >
<link rel="icon" href="<!--#echo encoding="none" var="icon" -->">
<link rel="license" href="<!--#echo encoding="none" var="licence" -->">
<link rel="toc" href="/index.shtml">
<link rel="sitemap" href="/sitemap.xml">
<link rel="stylesheet" href="/plumbing/songshade.css" type="text/css">
</head>

<body>

<div itemprop="author copyrightHolder" itemscope itemtype="https://schema.org/Person" id="dh">
  <meta itemprop="name" content="<!--#echo encoding="none" var="swebmeister" -->">
  <link itemprop="sameAs url" href="<!--#echo encoding="none" var="artsego" -->">
</div>

<div itemprop="publisher" itemscope itemtype="https://schema.org/Organization" id="self">
  <div itemprop="address" itemscope itemtype="https://schema.org/PostalAddress">
    <meta itemprop="addressCountry" content="<!--#echo encoding="none" var="uhostland" -->">
    <meta itemprop="addressLocality" content="<!--#echo encoding="none" var="utown" -->">
  </div>
  <meta itemprop="description" content="<!--#echo encoding="none" var="description" -->">
  <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject" itemref="dh">
    <link itemprop="url contentUrl" href="<!--#echo encoding="none" var="address" -->/logo.jpg">
  </div>
  <meta itemprop="name" content="<!--#echo encoding="none" var="name" -->">
  <link itemprop="sameAs" href="<!--#echo encoding="none" var="address" -->">
</div>

<div class="site h-entry" itemscope itemtype="https://schema.org/WebPage" itemref="dh self">
<meta itemprop="dateModified" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta itemprop="description" content="<!--#echo encoding="none" var="description" -->">
<meta itemprop="headline" content="<!--#echo encoding="none" var="title" -->">
<meta itemprop="inLanguage" content="en-GB">
<link itemprop="mainEntityOfPage" href="<!--#echo encoding="none" var="address" --><!--#echo encoding="none" var="DOCUMENT_URI" -->">
<meta itemprop="name" content="<!--#echo encoding="none" var="title" -->">
