<nav>
<!--htdig_noindex-->
<p class="menu-top">
<span class="separator">:&nbsp;:</span>&nbsp;<a href="/index.shtml">home</a>&nbsp;<span class="separator">:&nbsp;:</span>
<a href="/info/about.shtml">about</a>&nbsp;<span class="separator">&cir;</span>
<a href="/authors/index.shtml">authors</a>&nbsp;<span class="separator">&cir;</span>
<a href="/index.shtml">books</a>&nbsp;<span class="separator">&cir;</span>
<a href="/search.shtml">search</a>&nbsp;<span class="separator">&cir;</span>
<a href="/info/submissions.shtml">submissions</a>&nbsp;<span class="separator">&cir;</span>
<a href="/info/cart.shtml">view&nbsp;cart</a>&nbsp;<span class="separator">:&nbsp;:</span>
</p>
<!--/htdig_noindex-->
</nav>
