<div class="site">
<div class="prod">

<div itemscope itemtype="https://schema.org/webPage">

  <div itemprop="author copyrightHolder" itemscope itemtype="https://schema.org/Person">
    <meta itemprop="name" content="<!--#echo encoding="none" var="webmeister" -->">
    <link itemprop="sameAs url" href="<!--#echo encoding="none" var="artsego" -->">
  </div>

  <link itemprop="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">
</div>

<div itemprop="editor" itemscope itemtype="https://schema.org/Person" id="editor">
  <meta itemprop="name" content="<!--#echo encoding="none" var="webmeister" -->">
  <link itemprop="sameAs url" href="<!--#echo encoding="none" var="artsego" -->">
</div>
