<!--#set var="address" value="https://corruptpress.com" -->
<!--#set var="artsego" value="https://dylanharris.org/" -->
<!--#set var="cc" value="CC BY-NC-SA 4.0" -->
<!--#set var="copyright" value="&copy;&nbsp;2011&ndash;2022&nbsp;dylan&nbsp;harris" -->
<!--#set var="scopyright" value="(c) 2011-2022 dylan harris" -->
<!--#set var="country" value="LU" -->
<!--#set var="csp" value="default-src 'self' 'unsafe-inline' 'unsafe-eval'; form-action 'self' www.paypal.com; object-src 'none'; child-src 'none'; script-src 'none'; img-src 'self' https: dylanharris.org corruptpress.com corruptpress.net;" -->
<!--#set var="description" value="corrupt press is a small poetry press" -->
<!--#set var="editor" value="dylan&nbsp;harris" -->
<!--#set var="email" value="dh@corruptpress.com" -->
<!--#set var="hostland" value="luxembourg" -->
<!--#set var="uhostland" value="The Grand Duchy of Luxembourg" -->
<!--#set var="icon" value="https://corruptpress.com/favicon.ico" -->
<!--#set var="lang" value="en-GB" -->
<!--#set var="licence" value="https://creativecommons.org/licenses/by-nc-sa/4.0/" -->
<!--#set var="name" value="corrupt&nbsp;press" -->
<!--#set var="sname" value="corrupt press" -->
<!--#set var="town" value="esch&ndash;sur&ndash;alzette" -->
<!--#set var="utown" value="Esch-sur-Alzette" -->
<!--#set var="webmeister" value="dylan&nbsp;harris" -->
<!--#set var="year" value="2022" -->
<!--#set var="swebmeister" value="dylan harris" -->
<!--#set var="website" value="corrupt&nbsp;press" -->
<!--#set var="swebsite" value="corrupt press" -->
