[general]
verbose=5
output=../out/oct24.out
class=true

[html]
version=2024/10/01

[nits]
nids=

[link]
check=

[ontology]
schema=28

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/living/oct24

[validation]
element=labeled-checkbox
element=question-box
