<span class="smaller biggerscreen">
<a href="/args/corpus.shtml">corpus</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/css.shtml">CSS</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/environment.shtml">env</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/html.shtml">HTML</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/json-ld.shtml">JSON-LD</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/link.shtml">link</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/math.shtml">MathML</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/microformat.shtml">microformat</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/general.shtml">misc.</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/nits.shtml">nits</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/ontology.shtml">ontology</a><br>
<a href="/args/output.shtml">output</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/rdfa.shtml">RDFa</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/shadow.shtml">shadow</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/cmd.shtml">shell</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/site.shtml">site</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/spell.shtml">spell</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/ssi.shtml">SSI</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/stats.shtml">stats</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/svg.shtml">SVG</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/template.shtml">templates</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/validation.shtml">validate</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/vtt.shtml">VTT</a>
</span><br><br>