<span class="smaller biggerscreen">
<span class="separator" lang="en"><!--#echo encoding="none" var="menustart" --></span>&nbsp;arguments&nbsp;<span class="separator"><!--#echo encoding="none" var="menumid" --></span>
<a href="corpus.shtml">corpus</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="css.shtml">CSS</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="environment.shtml">env</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="html.shtml">HTML</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="link.shtml">link</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="math.shtml">MathML</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="microformat.shtml">microformat</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="general.shtml">misc</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="nits.shtml">nits</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span><br>
<span class="separator"><!--#echo encoding="none" var="menusep" --></span>&nbsp;<a href="ontology.shtml">ontology</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="template.shtml">output</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="rdfa.shtml">RDFa</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="shadow.shtml">shadow</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="cmd.shtml">shell</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="site.shtml">site</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="spell.shtml">spell</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="stats.shtml">stats</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="svg.shtml">SVG</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="validation.shtml">validate</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menuend" --></span>
<br></span>