<div itemprop="mainEntity" itemscope itemtype="https://schema.org/BlogPosting">
<div itemprop="author copyrightHolder" itemscope itemtype="https://schema.org/Person" itemref="dh"></div>
<meta itemprop="accessMode" content="textual,visual">
<meta itemprop="accessModeSufficient" content="textual">
<meta itemprop="accessibilitySummary" content="of course no descriptions are present the idea is to read the dratted thing">
<meta itemprop="description" content="<!--#echo encoding="none" var="description" -->">
<link itemprop="license" href="<!--#echo encoding="none" var="licence" -->">
<link itemprop="mainEntityOfPage" href="<!--#echo encoding="none" var="address" --><!--#echo encoding="none" var="DOCUMENT_URI" -->">
<meta itemprop="name headline" content="<!--#echo encoding="none" var="title" -->">

<article class="e-content">
