<!--#config timefmt="%Y-%m-%dT%H:%M:%S" -->

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Security-Policy" content="<!--#echo encoding="none" var="csp" -->">
<meta http-equiv="X-Clacks-Overhead" content="GNU Iain Banks">
<meta http-equiv="X-Clacks-Overhead" content="GNU Terry Pratchett">
<meta http-equiv="X-Content-Type-Options" content="nosniff">
<meta name="theme-color" content="#000000">
<meta name="author" content="<!--#echo encoding="none" var="name" -->">
<meta name="color-scheme" content="dark">
<meta name="contact" content="<!--#echo encoding="none" var="tel" --> <!--#echo encoding="none" var="email" --> '<!--#echo encoding="none" var="uhostland" -->'">
<meta name="copyright" content="<!--#echo encoding="none" var="copyright" -->">
<meta name="creator" content="<!--#echo encoding="none" var="creator" -->">
<meta name="dc.creator" content="<!--#echo encoding="none" var="creator" -->">
<meta name="dc.description" content="<!--#echo encoding="none" var="description" -->">
<meta name="dc.language" content="<!--#echo encoding="none" var="lang" -->">
<meta name="dc.title" content="<!--#echo encoding="none" var="title" -->">
<meta name="dcterms.creator" content="<!--#echo encoding="none" var="name" -->">
<meta name="dcterms.datecopyrighted" content="<!--#echo encoding="none" var="year" -->">
<meta name="dcterms.description" content="<!--#echo encoding="none" var="description" -->">
<meta name="dcterms.license" content="<!--#echo encoding="none" var="licence" -->">
<meta name="dcterms.modified" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta name="dcterms.rightsholder" content="<!--#echo encoding="none" var="creator" -->">
<meta name="dcterms.rights" content="<!--#echo encoding="none" var="scopyright" -->">
<meta name="dcterms.title" content="<!--#echo encoding="none" var="title" -->">
<meta name="designer" content="<!--#echo encoding="none" var="creator" -->">
<meta name="description" content="<!--#echo encoding="none" var="description" -->">
<meta name="geo.country" content="<!--#echo encoding="none" var="country" -->">
<meta name="keywords" content="<!--#echo encoding="none" var="name" -->">
<meta name="og:description" content="<!--#echo encoding="none" var="description" -->">
<meta name="og:locale" content="<!--#echo encoding="none" var="lang" -->">
<meta name="og:title" content="<!--#echo encoding="none" var="title" -->">
<meta name="og:site_name" content="<!--#echo encoding="none" var="swebsite" -->">
<meta name="revised" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta name="revision" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta name="rights-standard" content=";<!--#echo encoding="none" var="cc" -->">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#000000"> <!--#comment see https://dylanharris.org/blog/2015/sn41.shtml -->
<meta name="web_author" content="<!--#echo encoding="none" var="name" -->">
<link rel="author" href="<!--#echo encoding="none" var="home" -->">
<link rel="canonical" href="<!--#echo encoding="none" var="address" --><!--#echo encoding="none" var="DOCUMENT_URI" -->" >
<link rel="home" href="<!--#echo encoding="none" var="home" -->">
<link rel="icon" href="<!--#echo encoding="none" var="icon" -->">
<link rel="license" href="<!--#echo encoding="none" var="licence" -->">
<link rel="stylesheet" href="<!--#echo encoding="none" var="css" -->" type="text/css">
</head>

<body>

<div id="dh">
  <meta itemprop="name" content="<!--#echo encoding="none" var="name" -->">
  <link itemprop="sameAs url" href="<!--#echo encoding="none" var="slashaddress" -->">
</div>

<div id="self">
  <meta itemprop="name" content="<!--#echo encoding="none" var="name" -->">
</div>

<div class="site h-entry" itemscope itemtype="https://schema.org/WebPage">
<div itemprop="author copyrightHolder" itemscope itemtype="https://schema.org/Person" itemref="dh"></div>
<meta itemprop="dateModified" content="<!--#echo encoding="none" var="LAST_MODIFIED" -->">
<meta itemprop="description" content="<!--#echo encoding="none" var="description" -->">
<meta itemprop="headline name" content="<!--#echo encoding="none" var="title" -->">
<meta itemprop="inLanguage" content="<!--#echo encoding="none" var="lang" -->">
<link itemprop="license" href="<!--#echo encoding="none" var="licence" -->">
<link itemprop="mainEntityOfPage" href="<!--#echo encoding="none" var="address" --><!--#echo encoding="none" var="DOCUMENT_URI" -->">
