<span class="separator" lang="en"><span class="mediumscreen"><!--#echo encoding="none" var="menustart" -->&nbsp;browse&nbsp;</span><!--#echo encoding="none" var="menustart" --></span>&nbsp;
<a href="<!--#echo encoding="none" var="about" -->">about</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/index.shtml">args</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/build.shtml">build</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/config.shtml">config</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="<!--#echo encoding="none" var="home" -->">home</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/release-notes.shtml" title="source &amp; release notes">notes</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/advanced.shtml">try</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/usage.shtml">usage</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/why.shtml" title="why i wrote it">why</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menuend" --></span>

<span class="smaller biggerscreen"><br>
<span class="separator" lang="en"><!--#echo encoding="none" var="menustart" -->&nbsp;offsite&nbsp;<!--#echo encoding="none" var="menumid" --></span>
<a href="<!--#echo encoding="none" var="aesite" -->" title="webmeister&rsquo;s site"><!--#echo encoding="none" var="aename" --></a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="<!--#echo encoding="none" var="corruptsite" -->" title="corrupt press">corrupt&nbsp;press</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="<!--#echo encoding="none" var="github" -->" title="pro site">github&nbsp;repository</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menuend" --></span>
</span>

<div class="rights">
<a href="<!--#echo encoding="none" var="legal" -->" title="&copy; and licence info"><!--#echo encoding="none" var="copyright" --></a>
</div></div></footer></div></div>

</body>
</html>
