<nav>
<a href="/about.shtml">about</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/index.shtml">args</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/build.shtml">build</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/args/config.shtml">config</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="<!--#echo encoding="none" var="home" -->">home</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/release-notes.shtml" title="source &amp; release notes">notes</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/usage.shtml">usage</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="/why.shtml" title="why i wrote it">why</a>

<span class="smaller biggerscreen"><br>
<a href="<!--#echo encoding="none" var="aesite" -->" title="webmeister&rsquo;s site"><!--#echo encoding="none" var="aename" --></a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="<!--#echo encoding="none" var="corruptsite" -->" title="corrupt press">corrupt&nbsp;press</a>&nbsp;<span class="separator"><!--#echo encoding="none" var="menusep" --></span>
<a href="<!--#echo encoding="none" var="github" -->" title="pro site">github&nbsp;repository</a>
</span>
</nav>

<div class="rights" role=presentation>
<a href="/legal.shtml" title="&copy; and licence info"><!--#echo encoding="none" var="copyright" --></a>
</div></div></footer></div></div>

</body>
</html>
