<!--#set var="about" value="/about.shtml" -->
<!--#set var="address" value="https://ssc.lu" -->
<!--#set var="slashaddress" value="https://ssc.lu/" -->
<!--#set var="aename" value="arts&nbsp;&amp;&nbsp;ego" -->
<!--#set var="aesite" value="https://dylanharris.org/" -->
<!--#set var="cc" value="CC BY-NC-SA 4.0" -->
<!--#set var="cclong" value="Creative Commons Attribution-Commercial-Share Alike 4.0 International Public Licence" -->
<!--#set var="copyright" value="&copy;&nbsp;2020&ndash;2024&nbsp;Dylan&nbsp;Harris" -->
<!--#set var="scopyright" value="(c) 2020-2023 dylan harris" -->
<!--#set var="corruptsite" value="https://corruptpress.com" -->
<!--#set var="country" value="LU" -->
<!--#set var="creator" value="dylan harris" -->
<!--#set var="css" value="/plumbing/ignorance.css" -->
<!--#set var="csp" value="default-src 'self' 'unsafe-inline' 'unsafe-eval'; form-action 'self' www.paypal.com; object-src 'none'; child-src 'none'; script-src 'none'; img-src 'self' https: creativecommons.org dylanharris.org *.facebook.com upload.wikimedia.org web.archive.org www.paypalobjects.com xkcd.com;" -->
<!--#set var="date" value="January&nbsp;2024" -->
<!--#set var="description" value="the static site checker, https://ssc.lu/, is a static website nitpicker" -->
<!--#set var="domain" value="ssc.lu" -->
<!--#set var="email" value="mail@ssc.lu" -->
<!--#set var="semail" value="mail&commat;ssc&period;lu" -->
<!--#set var="front" value="/index.shtml" -->
<!--#set var="github" value="https://github.com/devongarde/ssc" -->
<!--#set var="home" value="/index.shtml" -->
<!--#set var="hostland" value="luxembourg" -->
<!--#set var="uhostland" value="The Grand Duchy of Luxembourg" -->
<!--#set var="icon" value="/image/favicon.ico" -->
<!--#set var="jurisdiction" value="https://luxcommons.lu/" -->
<!--#set var="latest-HTML" value="Oct 2023" -->
<!--#set var="latest-CSS" value="2023" -->
<!--#set var="legal" value="/legal.shtml" -->
<!--#set var="licence" value="https://creativecommons.org/licenses/by-nc-sa/4.0/" -->
<!--#set var="menustart" value=":&nbsp;:" -->
<!--#set var="menumid" value=":&nbsp;:" -->
<!--#set var="menuarrow" value="&rarr;" -->
<!--#set var="menusep" value="&cir;" -->
<!--#set var="menusection" value="&bull;" -->
<!--#set var="menuend" value=":&nbsp;:" -->
<!--#set var="name" value="static site checker" -->
<!--#set var="uname" value="Static Site Checker" -->
<!--#set var="owner" value="dylan harris" -->
<!--#set var="uowner" value="Dylan Harris" -->
<!--#set var="short" value="ssc" -->
<!--#set var="sitemap" value="/sitemap_index.xml" -->
<!--#set var="slogan" value="an opinionated HTML nitpicker" -->
<!--#set var="tel" value="+352 621 377 160" -->
<!--#set var="terms" value="/terms.shtml" -->
<!--#set var="test" value="ssc-test" -->
<!--#set var="stel" value="+352&nbsp;621&nbsp;377&nbsp;160" -->
<!--#set var="webmeister" value="dylan&nbsp;harris" -->
<!--#set var="swebmeister" value="dylan harris" -->
<!--#set var="website" value="static&nbsp;site&nbsp;checker" -->
<!--#set var="swebsite" value="static site checker" -->
<!--#set var="xeq" value="ssc" -->
<!--#set var="xeqtest" value="ssc-test" -->
<!--#set var="version" value="0.1.50" -->
<!--#set var="year" value="2024" -->
