[general]
verbose=info
output=../out/w3sheets.out
class=

[css]
verify=
extension=css
version=2.1

[html]
version=5.0

[link]
check=

[nits]
nids=

[site]
domain=example.org
extension=html
index=index.html
root=../toast/external/w3-sheets

[spell]
no-check=true
