[general]
verbose=5
output=../out/css4page.out
class=

[css]
verify=
extension=css
version=3
page=4

[html]
analysis=dec25
version=2026/01/01

[link]
no-check=

[nits]
nids=

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/css/4-page

[spell]
no-check=
