[general]
verbose=5
output=../out/jul26.out
class=true
url-var=src:/index.html

[css]
verify=
extension=css
version=html5

[html]
version=2026/07/01
custom=flag-icon
custom=my-checkbox
custom=img-viewer
custom=example-element
custom=labeled-checkbox
custom=question-box
custom=x-foo

[nits]
nids=

[link]
check=

[ontology]
schema=30.0

[site]
domain=example.edu
extension=html
index=index.html
root=../toast/living/jul26

[spell]
no-check=

[validation]
element=labeled-checkbox
element=question-box
